In [1]:
import pandas as pd
import numpy as np
import ast
import random
import numpy as np
from modules import DataFramePreprocessing, CreationDataset,CollateFunction,set_seed,seed_worker,EncodedHashedEmbeddings
import torch
from torch.nn import Embedding
import mmh3
from transformers import get_linear_schedule_with_warmup,AutoTokenizer,DistilBertModel
import itertools
import pyarrow.parquet as pq
from torch.utils.data import DataLoader

In [2]:
seed=42
set_seed(seed=seed)

## Creation of the processed dataframe

In [3]:
interactions_train_df=pd.read_csv("data/interactions_train.csv")
PP_recipes_df=pd.read_csv("data/PP_recipes.csv")
PP_users_df=pd.read_csv("data/PP_users.csv")
RAW_interactions_df=pd.read_csv("data/RAW_interactions.csv")
RAW_recipes_df=pd.read_csv("data/RAW_recipes.csv")

In [4]:
interactions_train_df_filtered=interactions_train_df.sample(n=50000,replace=False,random_state=42)

In [5]:
print(interactions_train_df_filtered.shape)

(50000, 6)

In [6]:
RAW_recipes_df.rename(columns={"id":"recipe_id"},inplace=True)
PP_recipes_df.rename(columns={"techniques":"techniques_recipes"},inplace=True)
PP_users_df.rename(columns={"techniques":"techniques_users"},inplace=True)

In [7]:
print("interactions_train_df_filtered columns:")
print(interactions_train_df_filtered.columns)
print("------------------------------------------------------------------")
print("PP_recipes_df columns:")
print(PP_recipes_df.columns)
print("-------------------------------------------------------------------")
print("PP_users_df columns:")
print(PP_users_df.columns)
print("----------------------------------------------------------------------")
print("RAW_interactions_df columns:")
print(RAW_interactions_df.columns)
print("------------------------------------------------------------------------")
print("RAW_recipes_df columns:")
print(RAW_recipes_df.columns)

interactions_train_df_filtered columns:
Index(['user_id', 'recipe_id', 'date', 'rating', 'u', 'i'], dtype='object')
------------------------------------------------------------------
PP_recipes_df columns:
Index(['id', 'i', 'name_tokens', 'ingredient_tokens', 'steps_tokens',
       'techniques_recipes', 'calorie_level', 'ingredient_ids'],
      dtype='object')
-------------------------------------------------------------------
PP_users_df columns:
Index(['u', 'techniques_users', 'items', 'n_items', 'ratings', 'n_ratings'], dtype='object')
----------------------------------------------------------------------
RAW_interactions_df columns:
Index(['user_id', 'recipe_id', 'date', 'rating', 'review'], dtype='object')
------------------------------------------------------------------------
RAW_recipes_df columns:
Index(['name', 'recipe_id', 'minutes', 'contributor_id', 'submitted', 'tags',
       'nutrition', 'n_steps', 'steps', 'description', 'ingredients',
       'n_ingredients'],
      dtype='object')

In [8]:
full_df=interactions_train_df_filtered.merge(PP_recipes_df,on="i",how="left",suffixes=(None,"_1")).merge(PP_users_df,on="u",how="left",suffixes=(None,"_2")).merge(RAW_interactions_df,on=["user_id","recipe_id"],how="left",suffixes=(None,"_3")).merge(RAW_recipes_df,on=["recipe_id"],how="left",suffixes=(None,"_3"))

In [9]:
full_df=full_df.drop(columns=["review",'rating_3',"id","ingredients","submitted","contributor_id","date_3","date","steps_tokens","ingredient_tokens","name_tokens","u"],axis=1)

In [10]:
print(f"Columns of the full dataframe:")
print(full_df.columns)
print("----------------------------------------")
print(f"Shape of the full dataframe:")
print(full_df.shape)
print("----------------------------------------")
print(f"Columns of the filtered interaction dataframe:")
print(interactions_train_df_filtered.shape)
print("----------------------------------------")
print(f"Head of the full  dataframe:")
display(full_df.head())
print("----------------------------------------")
for col in full_df.columns:
    print(f"Unique values of {col} :")
    print(full_df[col].unique())
    print("----------------------------------------")
for col in full_df.columns:
    print(f"The type of {col} is")
    print(full_df[col].apply(type).unique())
    print("---------------------------------")

Columns of the full dataframe:
Index(['user_id', 'recipe_id', 'rating', 'i', 'techniques_recipes',
       'calorie_level', 'ingredient_ids', 'techniques_users', 'items',
       'n_items', 'ratings', 'n_ratings', 'name', 'minutes', 'tags',
       'nutrition', 'n_steps', 'steps', 'description', 'n_ingredients'],
      dtype='object')
----------------------------------------
Shape of the full dataframe:
(50000, 20)
----------------------------------------
Columns of the filtered interaction dataframe:
(50000, 6)
----------------------------------------
Head of the full  dataframe:

,user_id,recipe_id,rating,i,techniques_recipes,calorie_level,ingredient_ids,techniques_users,items,n_items,ratings,n_ratings,name,minutes,tags,nutrition,n_steps,steps,description,n_ingredients
0,231160,124810,5.0,170682,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,"[4574, 1910, 6906, 2499, 63, 332, 6270, 7470, ...","[3, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, ...","[8911, 20238, 117521, 79316, 154563, 34302, 17...",7,"[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]",7,huckleberry or blueberry coffee cake,75,"['time-to-make', 'course', 'main-ingredient', ...","[174.1, 4.0, 92.0, 8.0, 7.0, 3.0, 11.0]",11,['beat margarine and cream cheese at medium sp...,"cooking light published this in their book, fi...",10
1,142629,31342,5.0,120865,"[1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",1,"[1168, 1284, 8021, 2499, 330, 6270, 3217, 2318...","[6, 0, 0, 3, 1, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, ...","[122019, 150060, 117906, 82202, 119046, 141911...",10,"[4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 3.0, 5.0, 4.0, ...",10,blender quiche or whatever you have in your ...,65,"['weeknight', 'time-to-make', 'course', 'main-...","[308.4, 37.0, 8.0, 20.0, 21.0, 41.0, 3.0]",10,"['preheat oven to 350f', 'generously grease a ...",the great part is you can use whatever leftove...,12
2,822358,441841,4.0,23142,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,"[1648, 1706, 3347, 5298, 3044, 4623, 2148, 6270]","[1, 1, 0, 2, 3, 0, 0, 0, 1, 5, 0, 1, 0, 0, 0, ...","[29761, 87944, 72370, 139097, 39470, 37755, 23...",17,"[4.0, 5.0, 5.0, 5.0, 4.0, 4.0, 4.0, 5.0, 5.0, ...",17,sweet orange coleslaw,10,"['15-minutes-or-less', 'time-to-make', 'course...","[290.1, 21.0, 71.0, 14.0, 7.0, 8.0, 13.0]",6,"['chop the apples', 'in a small bowl mix the o...",this recipe came from one of my mom's cookbook...,8
3,655579,211110,4.0,156541,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,"[7031, 5006, 339, 3203, 5975, 6270, 590]","[10, 0, 0, 5, 11, 0, 0, 0, 0, 7, 1, 3, 0, 0, 1...","[34492, 71279, 73805, 68721, 114795, 35164, 33...",28,"[2.0, 3.0, 4.0, 2.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...",28,wilted greens with garlic and balsamic vinegar,15,"['15-minutes-or-less', 'time-to-make', 'course...","[77.5, 10.0, 5.0, 5.0, 2.0, 4.0, 1.0]",5,"['cut the greens into strips 1 inch wide', 'in...",this simple but delicious side dish can be mad...,7
4,35140,114469,5.0,30839,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",2,"[1240, 6270, 5006, 1257, 2683, 5168, 800, 2461...","[176, 4, 2, 55, 72, 0, 1, 7, 4, 141, 13, 15, 0...","[121722, 36691, 151293, 154016, 1205, 12802, 1...",364,"[5.0, 5.0, 0.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...",364,chicken in the limelight,75,"['time-to-make', 'course', 'main-ingredient', ...","[645.9, 69.0, 11.0, 22.0, 80.0, 54.0, 4.0]",8,"['preheat oven to 350', 'grate lime peel and s...",very tender chicken soaked with flavor,9

----------------------------------------
Unique values of user_id :
[ 231160  142629  822358 ... 1086887 1364251  508459]
----------------------------------------
Unique values of recipe_id :
[124810  31342 441841 ...  13564 422436 398104]
----------------------------------------
Unique values of rating :
[5. 4. 3. 2. 0. 1.]
----------------------------------------
Unique values of i :
[170682 120865  23142 ... 110221  82789  70493]
----------------------------------------
Unique values of techniques_recipes :
['[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'
 '[1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'
 '[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]'
 ...
 '[1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]'
 '[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]'
 '[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]']
----------------------------------------
Unique values of calorie_level :
[0 1 2]
----------------------------------------
Unique values of ingredient_ids :
['[4574, 1910, 6906, 2499, 63, 332, 6270, 7470, 3819, 3497]'
 '[1168, 1284, 8021, 2499, 330, 6270, 3217, 2318, 2856, 4717, 5006, 5168]'
 '[1648, 1706, 3347, 5298, 3044, 4623, 2148, 6270]' ...
 '[5010, 1124, 3184, 840, 2683, 7562, 1938, 5753, 3668, 1118, 1795, 2809, 6273]'
 '[5058, 6082, 6696, 7193, 3723, 2809]'
 '[4814, 3597, 6654, 7258, 7233, 5362]']
----------------------------------------
Unique values of techniques_users :
['[3, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]'
 '[6, 0, 0, 3, 1, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 4, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 3, 0, 2]'
 '[1, 1, 0, 2, 3, 0, 0, 0, 1, 5, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 2, 1, 0, 1, 0, 0, 4, 1, 0, 0, 0, 0, 0, 4, 0, 1, 4, 1, 1, 0, 0, 1, 3, 3, 1, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 2, 1, 2]'
 ...
 '[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'
 '[2, 0, 0, 0, 2, 0, 0, 0, 0, 3, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0, 0, 0, 4, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0]'
 '[13, 0, 0, 2, 8, 0, 0, 1, 0, 12, 0, 2, 0, 0, 3, 0, 4, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 1, 9, 1, 0, 0, 0, 7, 0, 1, 2, 1, 3, 0, 0, 1, 7, 3, 0, 0, 5, 0, 0, 2, 0, 0, 0, 5, 1, 3, 1, 3]']
----------------------------------------
Unique values of items :
['[8911, 20238, 117521, 79316, 154563, 34302, 170682]'
 '[122019, 150060, 117906, 82202, 119046, 141911, 171519, 120865, 71287, 171522]'
 '[29761, 87944, 72370, 139097, 39470, 37755, 23142, 71578, 77036, 137338, 161477, 153736, 40366, 83647, 168229, 16010, 59580]'
 ... '[62900, 85346]'
 '[62117, 97415, 44202, 174552, 142634, 43965, 12072]'
 '[95699, 125846, 14970, 54631, 125833, 101819, 155236, 76934, 28422, 54149, 175495, 78609, 166987, 903, 49228, 137391, 98591, 137755, 171328, 67898, 80102, 146951, 150292, 37204, 113716, 114402, 170520, 50909]']
----------------------------------------
Unique values of n_items :
[   7   10   17   28  364  700 1125  423   13  174  394  443 1203 1263
   68  173  445    9  144  166  261  330 3465   56  188   22 2602  275
 1817  201  596   11   26   25  204   40 3656  322  416   36  637  283
    3  402  346   31 1112   50  211   20 1987  750  517   42  284    4
 4581 2024  813   66  153   32  218  351   67   14   16   48   47   71
   27  298  380  158   38   97 2232    5 1790 1302  171 2733  849  306
  910  635  232   57  125  269  398   65   84  292   79    8 6437 1667
   69   23  383   61  196   18   12  102  891   51  963    2 1138 2432
  580  547  907 2242   43  755  127   59 3338  122  980  167 1374  854
  428  296 1226  527  756  798  362  282  615  245   34  467 1697 1005
  785  236   63  395 1758  814   52  540  956  389 2798  277  117   44
  104 2011 1120 1679   33 1830  411 1477  896  529  522   19   81  746
   78   55  146  622  109  379  781  179 2457  195  657 1533   89  987
 1553  476   24 1212  592  293  256  181  308  118   30  231 1043  291
   41   15   80  684  752  161  189   29  365  252   35    6   58  357
  242  687  381  808  358 2046  121   90 1002  412  317 1592 1303  871
  914  128  151   37  709  185  738  305  278  607  216  399  274  328
  598  528  479 1253   85  234  107  129  338  968  112   21  734  142
  130  462 1386  132  869   73   99  662   76  224  766  260  180  281
  950  475  490   39 1308  564   86  749 1460  361   88  920  152  582
  229  302   72   93  183  698  647  255  427 1923  493  134  198   49
  431  336  663  106  140  149   74 2851  699  695  300  205  729 1265
  680  187  339  534   70  217   62   77  625  254  192  406  244  184
  199  633  488  378  793  250  376  515  168   96 1354  228   45   83
  212 1421  113  105  348  147 2377  110  550  100  141 1177  591 1319
  571  410  315 1363  900  156  583  384 1270  155  303  721  473   92
  353  354  454  557  177  116  424  111   60  324  226  239   54  541
 1839   82 1513  970  136  478  240   53  429  350  203  932  285  676
  138  979   46  143  289  131  491  120  455   94  552  163  148  145
  344  674 1118  235  135  457 1218  176  209   98  150  740  832  273
  495  200 1669  649  318  539  287  108  165  243  732  408  312  392
 1108  314  247  123  401  193  213  342  497  249   91  391 1594  265
   75 1147  352  329 1209  898  103  114  501  327  267  604  320  182
  507 1324  639   64  407  266  461  307  889  326  162  133  259  119
   95  701  206  169  405  271  279   87  263  386  251  191  486 1048
  304  418  115  126  686  373  223  690  340 1258  238  222  459  366
  888  918  237  137  241  286  221  413  175  426  297  164  280  301
  157  178  518  632  692  355  590  186  170  748  248  321  520  512
  290  310  257  335  268  368  101  893  219  566  693  124  367  214
  215  202  194  347  464  323  276  333  230  190  272  225  641  415
  393  313  483  396  258  299  139  159  154  471  207  294  220  227
  319  208]
----------------------------------------
Unique values of ratings :
['[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]'
 '[4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 3.0, 5.0, 4.0, 5.0]'
 '[4.0, 5.0, 5.0, 5.0, 4.0, 4.0, 4.0, 5.0, 5.0, 4.0, 4.0, 5.0, 4.0, 4.0, 4.0, 3.0, 4.0]'
 ...
 '[5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 3.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]'
 '[5.0, 5.0, 1.0, 3.0, 4.0, 4.0, 5.0, 5.0, 3.0, 3.0, 4.0, 5.0, 4.0, 4.0, 4.0, 5.0, 5.0]'
 '[5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 1.0, 5.0, 5.0, 5.0, 5.0, 0.0, 5.0, 5.0]']
----------------------------------------
Unique values of n_ratings :
[   7   10   17   28  364  700 1125  423   13  174  394  443 1203 1263
   68  173  445    9  144  166  261  330 3465   56  188   22 2602  275
 1817  201  596   11   26   25  204   40 3656  322  416   36  637  283
    3  402  346   31 1112   50  211   20 1987  750  517   42  284    4
 4581 2024  813   66  153   32  218  351   67   14   16   48   47   71
   27  298  380  158   38   97 2232    5 1790 1302  171 2733  849  306
  910  635  232   57  125  269  398   65   84  292   79    8 6437 1667
   69   23  383   61  196   18   12  102  891   51  963    2 1138 2432
  580  547  907 2242   43  755  127   59 3338  122  980  167 1374  854
  428  296 1226  527  756  798  362  282  615  245   34  467 1697 1005
  785  236   63  395 1758  814   52  540  956  389 2798  277  117   44
  104 2011 1120 1679   33 1830  411 1477  896  529  522   19   81  746
   78   55  146  622  109  379  781  179 2457  195  657 1533   89  987
 1553  476   24 1212  592  293  256  181  308  118   30  231 1043  291
   41   15   80  684  752  161  189   29  365  252   35    6   58  357
  242  687  381  808  358 2046  121   90 1002  412  317 1592 1303  871
  914  128  151   37  709  185  738  305  278  607  216  399  274  328
  598  528  479 1253   85  234  107  129  338  968  112   21  734  142
  130  462 1386  132  869   73   99  662   76  224  766  260  180  281
  950  475  490   39 1308  564   86  749 1460  361   88  920  152  582
  229  302   72   93  183  698  647  255  427 1923  493  134  198   49
  431  336  663  106  140  149   74 2851  699  695  300  205  729 1265
  680  187  339  534   70  217   62   77  625  254  192  406  244  184
  199  633  488  378  793  250  376  515  168   96 1354  228   45   83
  212 1421  113  105  348  147 2377  110  550  100  141 1177  591 1319
  571  410  315 1363  900  156  583  384 1270  155  303  721  473   92
  353  354  454  557  177  116  424  111   60  324  226  239   54  541
 1839   82 1513  970  136  478  240   53  429  350  203  932  285  676
  138  979   46  143  289  131  491  120  455   94  552  163  148  145
  344  674 1118  235  135  457 1218  176  209   98  150  740  832  273
  495  200 1669  649  318  539  287  108  165  243  732  408  312  392
 1108  314  247  123  401  193  213  342  497  249   91  391 1594  265
   75 1147  352  329 1209  898  103  114  501  327  267  604  320  182
  507 1324  639   64  407  266  461  307  889  326  162  133  259  119
   95  701  206  169  405  271  279   87  263  386  251  191  486 1048
  304  418  115  126  686  373  223  690  340 1258  238  222  459  366
  888  918  237  137  241  286  221  413  175  426  297  164  280  301
  157  178  518  632  692  355  590  186  170  748  248  321  520  512
  290  310  257  335  268  368  101  893  219  566  693  124  367  214
  215  202  194  347  464  323  276  333  230  190  272  225  641  415
  393  313  483  396  258  299  139  159  154  471  207  294  220  227
  319  208]
----------------------------------------
Unique values of name :
['huckleberry   or blueberry  coffee cake'
 'blender quiche   or whatever you have in your kitchen leftover'
 'sweet orange coleslaw' ... 'pumpkin peanut soup'
 'sesame tamari vinaigrette' 'turnover tortillas']
----------------------------------------
Unique values of minutes :
[        75         65         10         15          4         31
         35         25         33        250         55         17
         18         40         22         20          0         30
         19          5         90         45         23         89
         79         50         80         60        190         70
        385        490         13          2       1920         38
        150        380        300        485        105         81
        135         44         85         32        160        140
        610         95         28        310         27          8
        195        130       1680        280        155        330
        505         16          3        120        370         51
         52        245         42        125         49        560
        110        165        495        200          6        375
         21         57         12          7        500        615
         53        430         68        205        285       1500
        805         39        325        510       1490         24
        180         54          9       1475        365        305
        100      10095        435        175        315        270
        243          1         34        260       2895         26
         36        240        750        187         46        745
        210         62         43         76        420        405
        360        555       1480        390        185         29
         11        145       1440       1455       5760         97
        545        232        440        147         47         74
         58        550       2900         48        230       1620
        480         41       1470        182       1460       1380
         14        680         37        675        520       1445
        605        115        252        132       1800       1443
        248        218        400        255        235        425
         72        530        602        620       2190        265
        492       1442        275       1080        770         88
        486        107        225         83        184        487
        138        124       1450        112       1456      10090
        320        170         67        740        126        103
        215        790       1200       2925       1485        167
       2910       1580        780         77        525        730
        640        314        900        915         63        144
         71         56       4350        735        223        153
        765        246        515      21615        570        308
        214       1452        395         93        630       7210
        106        372        381        220        335       1090
        301         64        104        128        600       2760
        143        660         59         78        249        725
        188        840       1540       5820         66        608
       1465        482         84        720        645        800
        616       2905        307        481      15860         99
        588       1515        109        158        625         94
      10320       9740        290        410         87       2885
        825        795       1530        363        760       1020
         73       4330        445      10080        970        540
         98         61       1520        164        102       1510
        196        122      60510         96       4335       1448
        121         82       1250      28820       1590       5775
        450        133        488       2970        960      18720
        364        427        930        428         91       5780
       6000       5790        604        565        151       4545
       1560        855        724        284        127        382
       1740       1454        162        345       2890       3000
        137      10082        183        142        295       1085
        129        415        213        624       1446       4340
        186 2147483647        845       1970      86400        470
         92        197       1447        192        585      14430
      14460       1230      10085        945      10110]
----------------------------------------
Unique values of tags :
["['time-to-make', 'course', 'main-ingredient', 'preparation', 'occasion', 'breads', 'breakfast', 'fruit', 'oven', 'easy', 'coffee-cakes', 'dietary', 'berries', 'blueberries', 'brunch', 'equipment', '4-hours-or-less']"
 "['weeknight', 'time-to-make', 'course', 'main-ingredient', 'cuisine', 'preparation', 'occasion', 'north-american', 'lunch', 'main-dish', 'eggs-dairy', 'pork', 'poultry', 'vegetables', 'american', 'oven', 'cheese', 'eggs', 'chicken', 'food-processor-blender', 'dietary', 'oamc-freezer-make-ahead', 'meat', 'equipment', 'small-appliance', 'number-of-servings', '4-hours-or-less']"
 "['15-minutes-or-less', 'time-to-make', 'course', 'main-ingredient', 'preparation', 'low-protein', 'salads', 'fruit', 'vegetables', 'easy', 'dietary', 'low-cholesterol', 'low-saturated-fat', 'healthy-2', 'low-in-something', 'apples', 'greens']"
 ...
 "['60-minutes-or-less', 'time-to-make', 'course', 'main-ingredient', 'cuisine', 'preparation', 'occasion', 'soups-stews', 'eggs-dairy', 'fruit', 'vegetables', 'african', 'potluck', 'dinner-party', 'fall', 'holiday-event', 'kosher', 'vegetarian', 'winter', 'nuts', 'stove-top', 'dietary', 'christmas', 'hanukkah', 'new-years', 'thanksgiving', 'seasonal', 'rosh-hashana', 'kwanzaa', 'to-go', 'equipment']"
 "['15-minutes-or-less', 'time-to-make', 'course', 'cuisine', 'preparation', 'low-protein', 'salads', 'asian', 'diabetic', 'salad-dressings', 'dietary', 'gluten-free', 'low-cholesterol', 'free-of-something', 'low-in-something']"
 "['ham', '30-minutes-or-less', 'time-to-make', 'course', 'main-ingredient', 'preparation', 'lunch', 'eggs-dairy', 'pork', 'cheese', 'meat']"]
----------------------------------------
Unique values of nutrition :
['[174.1, 4.0, 92.0, 8.0, 7.0, 3.0, 11.0]'
 '[308.4, 37.0, 8.0, 20.0, 21.0, 41.0, 3.0]'
 '[290.1, 21.0, 71.0, 14.0, 7.0, 8.0, 13.0]' ...
 '[288.4, 35.0, 20.0, 7.0, 19.0, 37.0, 5.0]'
 '[19.2, 1.0, 7.0, 3.0, 0.0, 0.0, 0.0]'
 '[351.3, 30.0, 17.0, 34.0, 35.0, 59.0, 9.0]']
----------------------------------------
Unique values of n_steps :
[11 10  6  5  8  7  9  4 13  3 20 12 14 16 15 19 18 17 21 22 26 24 28 30
 23 27 29 25 31 33]
----------------------------------------
Unique values of steps :
["['beat margarine and cream cheese at medium speed of an electric mixer until creamy', 'gradually 1 cup sugar , beating well', 'add egg , and beat well', 'combine flour , baking powder , and salt', 'stir into margarine mixture', 'stir in vanilla , then fold in berries', 'pour batter into a 9-inch round cake pan coated with cooking spray', 'combine 2 tablespoons sugar and cinnamon', 'sprinkle over batter', 'bake at 350f for 1 hour', 'cool on a wire rack']"
 "['preheat oven to 350f', 'generously grease a 9 inch pie pan', 'spread shredded cheese across bottom of pie pan', 'cover cheese with meat and vegetables', 'in a blender , combine eggs , baking mix , salt , garlic powder , onions , parsley , and milk', 'blend until smooth , then add olive oil', 'blend until combined , then pour mixture over meat and vegetable layer', 'sprinkle with paprika', 'bake in preheated oven for 40 minutes', 'cool 10 minutes before serving']"
 "['chop the apples', 'in a small bowl mix the orange juice concentate , mayo , dijon , and salt', 'in a large serving bowl toss the coleslaw mix , rice , and apples', 'mix the dressing with the slaw until well coated', 'stir in the pecans', 'chill before serving']"
 ...
 '[\'finely mince the onion and celery\', \'either use a garlic press for the garlic or mince extremely fine\', \'melt the butter in your stock pot and saut the onion , celery and garlic in the butter for about five minutes or until soft\', "add flour and stir for a minute or two until it\'s disolved", \'add the stock , followed by the remaining indgredients , whisking the mixture so it remains smooth\', \'simmer for about fifteen minutes and serve\']'
 "['whisk orange juice , vinegar , tamari , oil , honey and ginger in a small bowl until the honey is incorporated', 'transfer to a jar and refrigerate', 'make ahead', 'dietary exchanges: 1 / 2 fat']"
 '[\'cut each slice of ham into four pieces\', \'place 1 slice of cheese , 2 squares of ham , and 1 teaspoon of sour cream on 1 of the tortillas\', \'fold in half , then in half again\', \'repeat with remaining cheese , ham , sour cream , and tortillas\', \'arrange "turnovers" in a shallow greased baking dish\', \'in a small bowl combine tomato sauce and picante sauce\', \'pour over tortillas\', \'bake at 350 degrees for about 20 minutes\']']
----------------------------------------
Unique values of description :
['cooking light published this in their book, five star recipes--the best of 10 years, and their staff voted this as one of their top five recipes from the first 10 years. it is very, very good, either for breakfast, brunch, or as dessert, warm out of the oven with a scoop of vanilla ice cream.'

In [11]:
PP_users_df["len_items"]=PP_users_df["items"].str.count(r",")+1
PP_recipes_df["len_ingredients"]=PP_recipes_df["ingredient_ids"].str.count(r",")+1
max_len_ingredients=PP_recipes_df["len_ingredients"].max()
max_len_items=PP_users_df["len_items"].max()
PP_users_df.drop(columns=["len_items"],inplace=True)
PP_recipes_df.drop(columns=["len_ingredients"],inplace=True)

In [12]:
full_df_processed=DataFramePreprocessing(full_df,max_len_ingredients,max_len_items)
full_df_processed=full_df_processed.preprocessing()

In [4]:
PP_recipes_df["ingredient_ids_transformed"]=PP_recipes_df["ingredient_ids"].apply(lambda x: list(map(int,ast.literal_eval(x))))
all_ingredient_ids=np.unique(list(itertools.chain.from_iterable(list(PP_recipes_df["ingredient_ids_transformed"]))))
ingredient_continuous_ids=pd.Series([i for i in range(1,len(all_ingredient_ids)+1)],index=list(np.sort(all_ingredient_ids)))

In [14]:
def mapping_list(x:list,mapping_serie:pd.Series):
    return [mapping_serie.loc[i] if i in mapping_serie.index else 0 for i in x]

In [15]:
full_df_processed["ingredient_ids_continuous"]=full_df_processed["ingredient_ids"].apply(lambda x : mapping_list(x,ingredient_continuous_ids))

In [16]:
full_df_processed.to_parquet(path="./modules/dataframe/full_df_processed.parquet")

## Load of the dataframe

In [5]:
parquet_file = pq.ParquetFile("./modules/dataframe/full_df_processed.parquet")

chunks = []
for batch in parquet_file.iter_batches(batch_size=10000):
    chunks.append(batch.to_pandas())

full_df_processed = pd.concat(chunks, ignore_index=True)

In [6]:
print(f"Columns of the full processed dataframe:")
print(full_df_processed.columns)
print("----------------------------------------")
print(f"Shape of the full processed dataframe:")
print(full_df_processed.shape)
print("----------------------------------------")
print(f"Head of the full  processed dataframe:")
display(full_df_processed.head())
print("----------------------------------------")
for col in full_df_processed.columns:
    print(f"Exemple of {col} :")
    print(full_df_processed.iloc[0][col])
    print("----------------------------------------")
for col in full_df_processed.columns:
    print(f"The type of {col} is")
    print(full_df_processed[col].apply(type).unique())
    print("---------------------------------")

Columns of the full processed dataframe:
Index(['user_id', 'recipe_id', 'rating', 'i', 'techniques_recipes',
       'calorie_level', 'ingredient_ids', 'techniques_users', 'items',
       'n_items', 'ratings', 'n_ratings', 'name', 'minutes', 'tags',
       'nutrition', 'n_steps', 'steps', 'description', 'n_ingredients',
       'ingredient_ids_continuous'],
      dtype='object')
----------------------------------------
Shape of the full processed dataframe:
(50000, 21)
----------------------------------------
Head of the full  processed dataframe:

,user_id,recipe_id,rating,i,techniques_recipes,calorie_level,ingredient_ids,techniques_users,items,n_items,...,n_ratings,name,minutes,tags,nutrition,n_steps,steps,description,n_ingredients,ingredient_ids_continuous
0,231160,124810,5.0,170683,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,"[4574, 1910, 6906, 2499, 63, 332, 6270, 7470, ...","[3, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, ...","[8912, 20239, 117522, 79317, 154564, 34303, 17...",7,...,7,huckleberry or blueberry coffee cake,75,time to make [SEP] course [SEP] main ingredien...,"[174.1, 4.0, 92.0, 8.0, 7.0, 3.0, 11.0]",11,beat margarine and cream cheese at medium spee...,"cooking light published this in their book, fi...",10,"[4560, 1904, 6880, 2493, 63, 331, 6248, 7443, ..."
1,142629,31342,5.0,120866,"[1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",1,"[1168, 1284, 8021, 2499, 330, 6270, 3217, 2318...","[6, 0, 0, 3, 1, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, ...","[122020, 150061, 117907, 82203, 119047, 141912...",10,...,10,blender quiche or whatever you have in your ...,65,weeknight [SEP] time to make [SEP] course [SEP...,"[308.4, 37.0, 8.0, 20.0, 21.0, 41.0, 3.0]",10,preheat oven to 350f [SEP] generously grease a...,the great part is you can use whatever leftove...,12,"[1163, 1278, 7992, 2493, 329, 6248, 3209, 2312..."
2,822358,441841,4.0,23143,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,"[1648, 1706, 3347, 5298, 3044, 4623, 2148, 627...","[1, 1, 0, 2, 3, 0, 0, 0, 1, 5, 0, 1, 0, 0, 0, ...","[29762, 87945, 72371, 139098, 39471, 37756, 23...",17,...,17,sweet orange coleslaw,10,15 minutes or less [SEP] time to make [SEP] co...,"[290.1, 21.0, 71.0, 14.0, 7.0, 8.0, 13.0]",6,chop the apples [SEP] in a small bowl mix the ...,this recipe came from one of my mom's cookbook...,8,"[1642, 1700, 3339, 5281, 3036, 4609, 2142, 624..."
3,655579,211110,4.0,156542,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,"[7031, 5006, 339, 3203, 5975, 6270, 590, 0, 0,...","[10, 0, 0, 5, 11, 0, 0, 0, 0, 7, 1, 3, 0, 0, 1...","[34493, 71280, 73806, 68722, 114796, 35165, 33...",28,...,28,wilted greens with garlic and balsamic vinegar,15,15 minutes or less [SEP] time to make [SEP] co...,"[77.5, 10.0, 5.0, 5.0, 2.0, 4.0, 1.0]",5,cut the greens into strips 1 inch wide [SEP] i...,this simple but delicious side dish can be mad...,7,"[7005, 4990, 338, 3195, 5953, 6248, 588, 1, 1,..."
4,35140,114469,5.0,30840,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",2,"[1240, 6270, 5006, 1257, 2683, 5168, 800, 2461...","[176, 4, 2, 55, 72, 0, 1, 7, 4, 141, 13, 15, 0...","[121723, 36692, 151294, 154017, 1206, 12803, 1...",364,...,364,chicken in the limelight,75,time to make [SEP] course [SEP] main ingredien...,"[645.9, 69.0, 11.0, 22.0, 80.0, 54.0, 4.0]",8,preheat oven to 350 [SEP] grate lime peel and ...,very tender chicken soaked with flavor,9,"[1235, 6248, 4990, 1252, 2677, 5151, 798, 2455..."

----------------------------------------
Exemple of user_id :
231160
----------------------------------------
Exemple of recipe_id :
124810
----------------------------------------
Exemple of rating :
5.0
----------------------------------------
Exemple of i :
170683
----------------------------------------
Exemple of techniques_recipes :
[1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
----------------------------------------
Exemple of calorie_level :
0
----------------------------------------
Exemple of ingredient_ids :
[4574 1910 6906 2499   63  332 6270 7470 3819 3497    0    0    0    0
    0    0    0    0    0    0]
----------------------------------------
Exemple of techniques_users :
[3 0 0 0 1 0 0 0 0 2 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 2 1 0 0 0 2 0 0 1
 0 0 0 0 0 1 2 0 0 0 1 0 0 0 0 0 0 1 0 0 1]
----------------------------------------
Exemple of items :
[  8912  20239 117522 ...      0      0      0]
----------------------------------------
Exemple of n_items :
7
----------------------------------------
Exemple of ratings :
[5 5 5 ... 0 0 0]
----------------------------------------
Exemple of n_ratings :
7
----------------------------------------
Exemple of name :
huckleberry   or blueberry  coffee cake
----------------------------------------
Exemple of minutes :
75
----------------------------------------
Exemple of tags :
time to make [SEP] course [SEP] main ingredient [SEP] preparation [SEP] occasion [SEP] breads [SEP] breakfast [SEP] fruit [SEP] oven [SEP] easy [SEP] coffee cakes [SEP] dietary [SEP] berries [SEP] blueberries [SEP] brunch [SEP] equipment [SEP] 4 hours or less
----------------------------------------
Exemple of nutrition :
[174.1   4.   92.    8.    7.    3.   11. ]
----------------------------------------
Exemple of n_steps :
11
----------------------------------------
Exemple of steps :
beat margarine and cream cheese at medium speed of an electric mixer until creamy [SEP] gradually 1 cup sugar , beating well [SEP] add egg , and beat well [SEP] combine flour , baking powder , and salt [SEP] stir into margarine mixture [SEP] stir in vanilla , then fold in berries [SEP] pour batter into a 9-inch round cake pan coated with cooking spray [SEP] combine 2 tablespoons sugar and cinnamon [SEP] sprinkle over batter [SEP] bake at 350f for 1 hour [SEP] cool on a wire rack
----------------------------------------
Exemple of description :
cooking light published this in their book, five star recipes--the best of 10 years, and their staff voted this as one of their top five recipes from the first 10 years. it is very, very good, either for breakfast, brunch, or as dessert, warm out of the oven with a scoop of vanilla ice cream.
----------------------------------------
Exemple of n_ingredients :
10
----------------------------------------
Exemple of ingredient_ids_continuous :
[4560 1904 6880 2493   63  331 6248 7443 3810 3489    1    1    1    1
    1    1    1    1    1    1]
----------------------------------------
The type of user_id is
[<class 'int'>]
---------------------------------
The type of recipe_id is
[<class 'int'>]
---------------------------------
The type of rating is
[<class 'float'>]
---------------------------------
The type of i is
[<class 'int'>]
---------------------------------
The type of techniques_recipes is
[<class 'numpy.ndarray'>]
---------------------------------
The type of calorie_level is
[<class 'int'>]
---------------------------------
The type of ingredient_ids is
[<class 'numpy.ndarray'>]
---------------------------------
The type of techniques_users is
[<class 'numpy.ndarray'>]
---------------------------------
The type of items is
[<class 'numpy.ndarray'>]
---------------------------------
The type of n_items is
[<class 'int'>]
---------------------------------
The type of ratings is
[<class 'numpy.ndarray'>]
---------------------------------
The type of n_ratings is
[<class 'int'>]
---------------------------------
The type of name is
[<class 'str'>]
---------------------------------
The type of minutes is
[<class 'int'>]
---------------------------------
The type of tags is
[<class 'str'>]
---------------------------------
The type of nutrition is
[<class 'numpy.ndarray'>]
---------------------------------
The type of n_steps is
[<class 'int'>]
---------------------------------
The type of steps is
[<class 'str'>]
---------------------------------
The type of description is
[<class 'str'>]
---------------------------------
The type of n_ingredients is
[<class 'int'>]
---------------------------------
The type of ingredient_ids_continuous is
[<class 'numpy.ndarray'>]
---------------------------------

## Model

In [7]:
dataset=CreationDataset(full_df_processed)

In [8]:
dataset.__getitem__(10)

{'user_id': 186070,
 'recipe_id': 11107,
 'rating': 4.0,
 'i': 3815,
 'techniques_recipes': array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 'calorie_level': 1,
 'ingredient_ids': array([7655, 5901, 2503,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0]),
 'techniques_users': array([86,  3,  1, 28, 24,  0,  0,  7,  0, 58,  7,  3,  0,  0,  2,  0, 23,
         0,  0,  7, 14,  3,  0, 11,  3,  0,  2,  5, 28,  9,  0,  0,  1, 37,
         0,  0, 20, 15,  8,  1,  0,  4,  8, 21,  1,  2, 17,  2,  0,  5,  0,
         0,  0,  6,  6, 18,  2, 20], dtype=int64),
 'items': array([ 80000, 111111,  61367, ...,      0,      0,      0]),
 'n_items': 174,
 'ratings': array([5, 5, 5, ..., 0, 0, 0]),
 'n_ratings': 174,
 'name': 'buttered egg noodles  best ever',
 'minutes': 10,
 'tags': '15 minutes or less [SEP] time to make [SEP] course [SEP] main ingredient [SEP] cuisine [SEP] preparation [SEP] occasion [SEP] north american [SEP] 5 ingredients or less [SEP] main dish [SEP] side dishes [SEP] pasta [SEP] american [SEP] easy [SEP] heirloom historical [SEP] holiday event [SEP] stove top [SEP] dietary [SEP] pasta rice and grains [SEP] equipment',
 'nutrition': array([424.8,  39. ,   4. ,  15. ,  17. ,  76. ,  13. ]),
 'n_steps': 4,
 'steps': 'bring water , 2 boullion cubes and 1 / 2 stick of butter to boil using med to high heat [SEP] add egg noodles [SEP] cook until noodles are desired texture [SEP] during last minute of cooking add remaining 1 / 2 stick of butter',
 'description': 'the creamiest buttered egg noodles you will ever taste. always a hit and easy to prepare.',
 'n_ingredients': 4,
 'ingredient_ids_continuous': array([7628, 5879, 2497,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1], dtype=int64)}

In [9]:
tokenizer=AutoTokenizer.from_pretrained("distilbert-base-uncased")

In [10]:
generator=torch.Generator()
generator.manual_seed(seed)
collate_function_object=CollateFunction(tokenizer=tokenizer)
collate_fn=collate_function_object.collate_fn
dataloader=DataLoader(dataset,batch_size=32,collate_fn=collate_fn,generator=generator,worker_init_fn=seed_worker,shuffle=True,drop_last=True)

In [12]:
batch=next(iter(dataloader))
for key in list(batch.keys()):
    print(key)
    print(f"The shape of batch {key} is :")
    print(batch[key].shape)
    print("-------------------")

user_id
The shape of batch user_id is :
torch.Size([32, 1])
-------------------
recipe_id
The shape of batch recipe_id is :
torch.Size([32, 1])
-------------------
rating
The shape of batch rating is :
torch.Size([32, 1])
-------------------
i
The shape of batch i is :
torch.Size([32, 1])
-------------------
technique_recipes
The shape of batch technique_recipes is :
torch.Size([32, 58])
-------------------
calorie_level
The shape of batch calorie_level is :
torch.Size([32, 1])
-------------------
ingredient_ids
The shape of batch ingredient_ids is :
torch.Size([32, 20])
-------------------
techniques_users
The shape of batch techniques_users is :
torch.Size([32, 58])
-------------------
items
The shape of batch items is :
torch.Size([32, 6437])
-------------------
n_items
The shape of batch n_items is :
torch.Size([32, 1])
-------------------
ratings
The shape of batch ratings is :
torch.Size([32, 6437])
-------------------
n_ratings
The shape of batch n_ratings is :
torch.Size([32, 1])
-------------------
minutes
The shape of batch minutes is :
torch.Size([32, 1])
-------------------
nutrition
The shape of batch nutrition is :
torch.Size([32, 7])
-------------------
n_ingredients
The shape of batch n_ingredients is :
torch.Size([32, 1])
-------------------
ingredient_ids_continuous
The shape of batch ingredient_ids_continuous is :
torch.Size([32, 20])
-------------------
input_ids_steps
The shape of batch input_ids_steps is :
torch.Size([32, 210])
-------------------
attention_mask_steps
The shape of batch attention_mask_steps is :
torch.Size([32, 210])
-------------------
input_ids_names
The shape of batch input_ids_names is :
torch.Size([32, 14])
-------------------
attention_mask_names
The shape of batch attention_mask_names is :
torch.Size([32, 14])
-------------------
input_ids_descriptions
The shape of batch input_ids_descriptions is :
torch.Size([32, 122])
-------------------
attention_mask_descriptions
The shape of batch attention_mask_descriptions is :
torch.Size([32, 122])
-------------------
input_ids_tags
The shape of batch input_ids_tags is :
torch.Size([32, 92])
-------------------
attention_mask_tags
The shape of batch attention_mask_tags is :
torch.Size([32, 92])
-------------------

In [24]:
n_recipes_ids=len(np.unique(PP_recipes_df["i"]))
n_ingredients_ids=len(all_ingredient_ids)

print(f"There are {n_recipes_ids} recipe ids")
print(f"There are {n_ingredients_ids} ingredient ids")

There are 178265 recipe ids
There are 7993 ingredient ids

In [25]:
hash_encoder=EncodedHashedEmbeddings(n_recipes_ids,1024,n_ingredients_ids,1024)
hashed_recipes_ids_encoded_embeddings,hashed_ingredients_ids_encoded_embeddings=hash_encoder.get_encoded_hashed_embeddings("./modules/hashed_encoded_tables")

In [18]:
hashed_ingredients_ids_encoded_embeddings=torch.load("./modules/hashed_encoded_tables/hashed_embeddings_ingredients.pt")
hashed_recipes_ids_encoded_embeddings=torch.load("./modules/hashed_encoded_tables/hashed_embeddings_recipes.pt")

In [27]:
print(hashed_ingredients_ids_encoded_embeddings.shape)
print(hashed_recipes_ids_encoded_embeddings.shape)

torch.Size([7994, 1024])
torch.Size([178266, 1024])

In [33]:
print(hashed_recipes_ids_encoded_embeddings)

tensor([[ 0.7909, -0.9181,  0.4172,  ..., -0.1900,  0.4413,  0.9525],
        [-0.6644,  0.3263,  0.5654,  ...,  0.5458, -0.7577, -0.6355],
        [ 0.1152,  0.0698,  0.0535,  ..., -0.4404,  0.5246,  0.4121],
        ...,
        [ 0.9130, -0.5091, -0.2525,  ..., -0.9953, -0.0469, -0.3890],
        [ 0.0600, -0.6166, -0.7683,  ...,  0.6400, -0.9979,  0.9455],
        [ 0.0768, -0.9113,  0.0535,  ...,  0.2832, -0.0500,  0.4495]])

In [29]:
filter=[1,1,2,2]

In [30]:
print(hashed_recipes_ids_encoded_embeddings[batch["items"],:].shape)

torch.Size([32, 6437, 1024])

In [31]:
print(hashed_recipes_ids_encoded_embeddings[filter,:])

tensor([[-0.6644,  0.3263,  0.5654,  ...,  0.5458, -0.7577, -0.6355],
        [-0.6644,  0.3263,  0.5654,  ...,  0.5458, -0.7577, -0.6355],
        [ 0.1152,  0.0698,  0.0535,  ..., -0.4404,  0.5246,  0.4121],
        [ 0.1152,  0.0698,  0.0535,  ..., -0.4404,  0.5246,  0.4121]])

In [32]:
PP_users_df["items"]=PP_users_df["items"].apply(lambda x : list(map(int,ast.literal_eval(x))))
print(np.unique(list(itertools.chain.from_iterable(list(PP_users_df["items"])))))

[     0      1      2 ... 178257 178261 178262]

In [25]:
print(batch["items"].shape)
print(batch["items"])

torch.Size([32, 6437])
tensor([[125929, 135695, 147187,  ...,      0,      0,      0],
        [ 44203,   7481, 165528,  ...,      0,      0,      0],
        [134305, 169902, 109856,  ...,      0,      0,      0],
        ...,
        [ 49370,  84047, 114955,  ...,      0,      0,      0],
        [112382,  76064, 159609,  ...,      0,      0,      0],
        [ 28553,  34760, 151713,  ...,      0,      0,      0]],
       dtype=torch.int32)

In [29]:
print(hashed_recipes_ids_encoded_embeddings.shape)
print(hashed_recipes_ids_encoded_embeddings[batch["items"]].shape)

torch.Size([178266, 1024])
torch.Size([32, 6437, 1024])

In [30]:
print(batch["items"].shape)

torch.Size([32, 6437])

In [54]:
mask=(batch["items"]!=0).int()

In [55]:
print(mask)
print(mask.shape)

tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]], dtype=torch.int32)
torch.Size([32, 6437])

In [56]:
encoded=hashed_recipes_ids_encoded_embeddings[batch["items"]]
print(encoded.shape)

torch.Size([32, 6437, 1024])

In [57]:
mask=mask.unsqueeze(1)
print(mask.shape)
torch.mul(mask,encoded)

torch.Size([32, 1, 6437])

RuntimeError: The size of tensor a (6437) must match the size of tensor b (1024) at non-singleton dimension 2