In [1]:
from google.colab import drive
drive.mount('/content/drive')

import os
project_path = "/content/drive/MyDrive/Recipe recommendation system"
os.chdir(project_path)
print(os.getcwd())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/Recipe recommendation system

In [2]:
!pip install mlflow
!pip install loguru

Requirement already satisfied: mlflow in /usr/local/lib/python3.12/dist-packages (3.10.1)
Requirement already satisfied: mlflow-skinny==3.10.1 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.1)
Requirement already satisfied: mlflow-tracing==3.10.1 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.1)
Requirement already satisfied: Flask-CORS<7 in /usr/local/lib/python3.12/dist-packages (from mlflow) (6.0.2)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.18.4)
Requirement already satisfied: cryptography<47,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (43.0.3)
Requirement already satisfied: docker<8,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (7.1.0)
Requirement already satisfied: graphene<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.4.3)
Requirement already satisfied: gunicorn<26 in /usr/local/lib/python3.12/dist-packages (from mlflow) (25.3.0)
Requirement already satisfied: huey<3,>=2.5.4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.6.0)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.2.2)
Requirement already satisfied: pyarrow<24,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (18.1.0)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)
Requirement already satisfied: skops<1 in /usr/local/lib/python3.12/dist-packages (from mlflow) (0.13.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.48)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (8.3.1)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (3.1.2)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (0.102.0)
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (0.135.2)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (3.1.46)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (1.38.0)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (26.0)
Requirement already satisfied: protobuf<7,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (2.12.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (1.2.2)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (0.5.5)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.10.1->mlflow) (0.42.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.3.10)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography<47,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.7)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (3.2.8)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.3.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography<47,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow) (2.47.0)
Requirement already satisfied: starlette>=0.46.0 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.10.1->mlflow) (0.52.1)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.10.1->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.10.1->mlflow) (0.0.4)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.10.1->mlflow) (4.0.12)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.10.1->mlflow) (3.23.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.59b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.10.1->mlflow) (0.59b0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.1->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.1->mlflow) (2.41.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.1->mlflow) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.1->mlflow) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.1->mlflow) (2026.2.25)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<1->mlflow-skinny==3.10.1->mlflow) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.10.1->mlflow) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow) (4.9.1)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from starlette>=0.46.0->fastapi<1->mlflow-skinny==3.10.1->mlflow) (4.13.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow) (0.6.3)
Requirement already satisfied: loguru in /usr/local/lib/python3.12/dist-packages (0.7.3)

In [28]:
import pandas as pd
import numpy as np
import ast
import numpy as np
import torch
import mmh3
from transformers import AutoTokenizer,DistilBertModel
import itertools
import pyarrow.parquet as pq
from torch.utils.data import DataLoader
from sklearn.preprocessing import StandardScaler
import mlflow
from modules import DataFramePreprocessing, CreationDataset,CollateFunction,set_seed,seed_worker,EncodedHashedEmbeddings,Scaler,split_df,RecommendationModel,Train,BERTCreationDataset,BERTCreationDataset,BERTEmbeddingsExtractor,BertCollateFunction,ContrastiveMSELoss

In [29]:
seed=42
set_seed(seed=seed)

In [ ]:
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Recommendation_model_training")

WARNING:urllib3.connectionpool:Retrying (Retry(total=6, connect=6, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7aed26ae6a20>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Recommendation_model_training
WARNING:urllib3.connectionpool:Retrying (Retry(total=5, connect=5, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7aed268a6150>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Recommendation_model_training
WARNING:urllib3.connectionpool:Retrying (Retry(total=4, connect=4, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7aed268a6450>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Recommendation_model_training
WARNING:urllib3.connectionpool:Retrying (Retry(total=3, connect=3, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7aed2697a270>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Recommendation_model_training
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=2, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7aed2697a900>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Recommendation_model_training
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=1, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7aed2697a000>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Recommendation_model_training

KeyboardInterrupt:

In [30]:
mlflow.set_tracking_uri("file:./modules/mlflow_runs/mlruns")
mlflow.set_experiment("Recommendation_model_training")

/usr/local/lib/python3.12/dist-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
2026/04/02 19:29:03 INFO mlflow.tracking.fluent: Experiment with name 'Recommendation_model_training' does not exist. Creating a new experiment.

<Experiment: artifact_location=('file:///content/drive/MyDrive/Recipe recommendation '
 'system/modules/mlflow_runs/mlruns/282575499087463590'), creation_time=1775158143443, experiment_id='282575499087463590', last_update_time=1775158143443, lifecycle_stage='active', name='Recommendation_model_training', tags={}, workspace='default'>

## Creation of the processed dataframe

In [4]:
interactions_train_df=pd.read_csv("data/interactions_train.csv")
PP_recipes_df=pd.read_csv("data/PP_recipes.csv")
PP_users_df=pd.read_csv("data/PP_users.csv")
RAW_interactions_df=pd.read_csv("data/RAW_interactions.csv")
RAW_recipes_df=pd.read_csv("data/RAW_recipes.csv")

In [4]:
interactions_train_df_filtered=interactions_train_df.sample(n=20000,replace=False,random_state=42)

In [5]:
print(interactions_train_df_filtered.shape)

(20000, 6)

In [6]:
RAW_recipes_df.rename(columns={"id":"recipe_id"},inplace=True)
PP_recipes_df.rename(columns={"techniques":"techniques_recipes"},inplace=True)
PP_users_df.rename(columns={"techniques":"techniques_users"},inplace=True)

In [7]:
print("interactions_train_df_filtered columns:")
print(interactions_train_df_filtered.columns)
print("------------------------------------------------------------------")
print("PP_recipes_df columns:")
print(PP_recipes_df.columns)
print("-------------------------------------------------------------------")
print("PP_users_df columns:")
print(PP_users_df.columns)
print("----------------------------------------------------------------------")
print("RAW_interactions_df columns:")
print(RAW_interactions_df.columns)
print("------------------------------------------------------------------------")
print("RAW_recipes_df columns:")
print(RAW_recipes_df.columns)

interactions_train_df_filtered columns:
Index(['user_id', 'recipe_id', 'date', 'rating', 'u', 'i'], dtype='object')
------------------------------------------------------------------
PP_recipes_df columns:
Index(['id', 'i', 'name_tokens', 'ingredient_tokens', 'steps_tokens',
       'techniques_recipes', 'calorie_level', 'ingredient_ids'],
      dtype='object')
-------------------------------------------------------------------
PP_users_df columns:
Index(['u', 'techniques_users', 'items', 'n_items', 'ratings', 'n_ratings'], dtype='object')
----------------------------------------------------------------------
RAW_interactions_df columns:
Index(['user_id', 'recipe_id', 'date', 'rating', 'review'], dtype='object')
------------------------------------------------------------------------
RAW_recipes_df columns:
Index(['name', 'recipe_id', 'minutes', 'contributor_id', 'submitted', 'tags',
       'nutrition', 'n_steps', 'steps', 'description', 'ingredients',
       'n_ingredients'],
      dtype='object')

In [8]:
full_df=interactions_train_df_filtered.merge(PP_recipes_df,on="i",how="left",suffixes=(None,"_1")).merge(PP_users_df,on="u",how="left",suffixes=(None,"_2")).merge(RAW_interactions_df,on=["user_id","recipe_id"],how="left",suffixes=(None,"_3")).merge(RAW_recipes_df,on=["recipe_id"],how="left",suffixes=(None,"_3"))

In [9]:
full_df=full_df.drop(columns=["review",'rating_3',"id","ingredients","submitted","contributor_id","date_3","date","steps_tokens","ingredient_tokens","name_tokens","u"],axis=1)

In [10]:
print(f"Columns of the full dataframe:")
print(full_df.columns)
print("----------------------------------------")
print(f"Shape of the full dataframe:")
print(full_df.shape)
print("----------------------------------------")
print(f"Columns of the filtered interaction dataframe:")
print(interactions_train_df_filtered.shape)
print("----------------------------------------")
print(f"Head of the full  dataframe:")
display(full_df.head())
print("----------------------------------------")
for col in full_df.columns:
    print(f"Unique values of {col} :")
    print(full_df[col].unique())
    print("----------------------------------------")
for col in full_df.columns:
    print(f"The type of {col} is")
    print(full_df[col].apply(type).unique())
    print("---------------------------------")

Columns of the full dataframe:
Index(['user_id', 'recipe_id', 'rating', 'i', 'techniques_recipes',
       'calorie_level', 'ingredient_ids', 'techniques_users', 'items',
       'n_items', 'ratings', 'n_ratings', 'name', 'minutes', 'tags',
       'nutrition', 'n_steps', 'steps', 'description', 'n_ingredients'],
      dtype='object')
----------------------------------------
Shape of the full dataframe:
(20000, 20)
----------------------------------------
Columns of the filtered interaction dataframe:
(20000, 6)
----------------------------------------
Head of the full  dataframe:

,user_id,recipe_id,rating,i,techniques_recipes,calorie_level,ingredient_ids,techniques_users,items,n_items,ratings,n_ratings,name,minutes,tags,nutrition,n_steps,steps,description,n_ingredients
0,231160,124810,5.0,170682,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,"[4574, 1910, 6906, 2499, 63, 332, 6270, 7470, ...","[3, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, ...","[8911, 20238, 117521, 79316, 154563, 34302, 17...",7,"[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]",7,huckleberry or blueberry coffee cake,75,"['time-to-make', 'course', 'main-ingredient', ...","[174.1, 4.0, 92.0, 8.0, 7.0, 3.0, 11.0]",11,['beat margarine and cream cheese at medium sp...,"cooking light published this in their book, fi...",10
1,142629,31342,5.0,120865,"[1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",1,"[1168, 1284, 8021, 2499, 330, 6270, 3217, 2318...","[6, 0, 0, 3, 1, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, ...","[122019, 150060, 117906, 82202, 119046, 141911...",10,"[4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 3.0, 5.0, 4.0, ...",10,blender quiche or whatever you have in your ...,65,"['weeknight', 'time-to-make', 'course', 'main-...","[308.4, 37.0, 8.0, 20.0, 21.0, 41.0, 3.0]",10,"['preheat oven to 350f', 'generously grease a ...",the great part is you can use whatever leftove...,12
2,822358,441841,4.0,23142,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,"[1648, 1706, 3347, 5298, 3044, 4623, 2148, 6270]","[1, 1, 0, 2, 3, 0, 0, 0, 1, 5, 0, 1, 0, 0, 0, ...","[29761, 87944, 72370, 139097, 39470, 37755, 23...",17,"[4.0, 5.0, 5.0, 5.0, 4.0, 4.0, 4.0, 5.0, 5.0, ...",17,sweet orange coleslaw,10,"['15-minutes-or-less', 'time-to-make', 'course...","[290.1, 21.0, 71.0, 14.0, 7.0, 8.0, 13.0]",6,"['chop the apples', 'in a small bowl mix the o...",this recipe came from one of my mom's cookbook...,8
3,655579,211110,4.0,156541,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,"[7031, 5006, 339, 3203, 5975, 6270, 590]","[10, 0, 0, 5, 11, 0, 0, 0, 0, 7, 1, 3, 0, 0, 1...","[34492, 71279, 73805, 68721, 114795, 35164, 33...",28,"[2.0, 3.0, 4.0, 2.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...",28,wilted greens with garlic and balsamic vinegar,15,"['15-minutes-or-less', 'time-to-make', 'course...","[77.5, 10.0, 5.0, 5.0, 2.0, 4.0, 1.0]",5,"['cut the greens into strips 1 inch wide', 'in...",this simple but delicious side dish can be mad...,7
4,35140,114469,5.0,30839,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",2,"[1240, 6270, 5006, 1257, 2683, 5168, 800, 2461...","[176, 4, 2, 55, 72, 0, 1, 7, 4, 141, 13, 15, 0...","[121722, 36691, 151293, 154016, 1205, 12802, 1...",364,"[5.0, 5.0, 0.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...",364,chicken in the limelight,75,"['time-to-make', 'course', 'main-ingredient', ...","[645.9, 69.0, 11.0, 22.0, 80.0, 54.0, 4.0]",8,"['preheat oven to 350', 'grate lime peel and s...",very tender chicken soaked with flavor,9

----------------------------------------
Unique values of user_id :
[231160 142629 822358 ... 241982 164867 137854]
----------------------------------------
Unique values of recipe_id :
[124810  31342 441841 ...  98278 274099 283283]
----------------------------------------
Unique values of rating :
[5. 4. 3. 2. 0. 1.]
----------------------------------------
Unique values of i :
[170682 120865  23142 ... 108495 128044  25867]
----------------------------------------
Unique values of techniques_recipes :
['[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'
 '[1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'
 '[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]'
 ...
 '[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]'
 '[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]'
 '[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]']
----------------------------------------
Unique values of calorie_level :
[0 1 2]
----------------------------------------
Unique values of ingredient_ids :
['[4574, 1910, 6906, 2499, 63, 332, 6270, 7470, 3819, 3497]'
 '[1168, 1284, 8021, 2499, 330, 6270, 3217, 2318, 2856, 4717, 5006, 5168]'
 '[1648, 1706, 3347, 5298, 3044, 4623, 2148, 6270]' ...
 '[1254, 1165, 2374, 3716, 222, 1168]'
 '[1786, 5319, 1252, 5006, 5010, 3203, 1257, 7233, 6212, 3399, 1511, 1563, 68, 5975, 553, 1706]'
 '[3244, 7821, 1527, 2010, 1119, 4884, 2809, 3406, 5058]']
----------------------------------------
Unique values of techniques_users :
['[3, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]'
 '[6, 0, 0, 3, 1, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 4, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 3, 0, 2]'
 '[1, 1, 0, 2, 3, 0, 0, 0, 1, 5, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 2, 1, 0, 1, 0, 0, 4, 1, 0, 0, 0, 0, 0, 4, 0, 1, 4, 1, 1, 0, 0, 1, 3, 3, 1, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 2, 1, 2]'
 ...
 '[6, 0, 0, 2, 3, 0, 0, 0, 0, 5, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 4, 0, 0, 2, 1, 0, 0, 0, 0, 1, 1, 0, 0, 3, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 1]'
 '[9, 0, 0, 3, 3, 0, 0, 1, 0, 5, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 2, 5, 1, 0, 0, 0, 6, 0, 1, 2, 0, 1, 0, 0, 0, 3, 2, 0, 0, 3, 1, 0, 1, 0, 0, 0, 3, 1, 2, 1, 3]'
 '[37, 3, 0, 16, 21, 0, 0, 1, 0, 20, 6, 2, 0, 0, 2, 0, 6, 0, 0, 4, 4, 4, 0, 2, 0, 0, 2, 4, 14, 3, 0, 0, 0, 28, 0, 4, 9, 4, 5, 0, 0, 3, 13, 5, 1, 1, 15, 1, 0, 1, 0, 1, 0, 3, 0, 2, 4, 4]']
----------------------------------------
Unique values of items :
['[8911, 20238, 117521, 79316, 154563, 34302, 170682]'
 '[122019, 150060, 117906, 82202, 119046, 141911, 171519, 120865, 71287, 171522]'
 '[29761, 87944, 72370, 139097, 39470, 37755, 23142, 71578, 77036, 137338, 161477, 153736, 40366, 83647, 168229, 16010, 59580]'
 ...
 '[156329, 47112, 9002, 48914, 82283, 44569, 12384, 107161, 81246, 37900]'
 '[164203, 21935, 116632, 93494, 93193, 34860, 2267, 121932, 23646, 97372, 3332, 99368, 158194, 18103, 92882, 162858, 89027, 89140]'
 '[162186, 151953, 91760, 83170, 51796, 39867, 151177, 168722, 95442, 46843, 173363, 61869, 1754, 15430, 85086, 71955, 126328, 139970, 22578, 170817, 40735, 78551, 82136, 155665, 50048, 112281, 4864, 139149, 94090, 44321, 19812, 21692, 52532, 74837, 24305, 17876, 51263, 93685, 11814, 47251, 72474, 1921, 178015, 157555, 138896, 55772, 14509, 174272, 84437, 156075, 83930, 90781, 110941, 159543, 61938, 89113, 71389, 65021, 71442, 130357, 28353, 113097, 114402, 109732, 140658, 141662, 13667]']
----------------------------------------
Unique values of n_items :
[   7   10   17   28  364  700 1125  423   13  174  394  443 1203 1263
   68  173  445    9  144  166  261  330 3465   56  188   22 2602  275
 1817  201  596   11   26   25  204   40 3656  322  416   36  637  283
    3  402  346   31 1112   50  211   20 1987  750  517   42  284    4
 4581 2024  813   66  153   32  218  351   67   14   16   48   47   71
   27  298  380  158   38   97 2232    5 1790 1302  171 2733  849  306
  910  635  232   57  125  269  398   65   84  292   79    8 6437 1667
   69   23  383   61  196   18   12  102  891   51  963    2 1138 2432
  580  547  907 2242   43  755  127   59 3338  122  980  167 1374  854
  428  296 1226  527  756  798  362  282  615  245   34  467 1697 1005
  785  236   63  395 1758  814   52  540  956  389 2798  277  117   44
  104 2011 1120 1679   33 1830  411 1477  896  529  522   19   81  746
   78   55  146  622  109  379  781  179 2457  195  657 1533   89  987
 1553  476   24 1212  592  293  256  181  308  118   30  231 1043  291
   41   15   80  684  752  161  189   29  365  252   35    6   58  357
  242  687  381  808  358 2046  121   90 1002  412  317 1592 1303  871
  914  128  151   37  709  185  738  305  278  607  216  399  274  328
  598  528  479 1253   85  234  107  129  338  968  112   21  734  142
  130  462 1386  132  869   73   99  662   76  224  766  260  180  281
  950  475  490   39 1308  564   86  749 1460  361   88  920  152  582
  229  302   72   93  183  698  647  255  427 1923  493  134  198   49
  431  336  663  106  140  149   74 2851  699  695  300  205  729 1265
  680  187  339  534   70  217   62   77  625  254  192  406  244  184
  199  633  488  378  793  250  376  515  168   96 1354  228   45   83
  212 1421  113  105  348  147 2377  110  550  100  141 1177  591 1319
  571  410  315 1363  900  156  583  384 1270  155  303  721  473   92
  353  354  454  557  177  116  424  111   60  324  226  239   54  541
 1839   82 1513  970  136  478  240   53  429  350  203  932  285  676
  138  979   46  143  289  131  491  120  455   94  552  163  148  145
  344  674 1118  235  135  457 1218  176  209   98  150  740  832  273
  495  200 1669  649  318  539  287  108  165  243  732  408  312  392
 1108  314  247  123  401  193  213  342  497  249   91  391 1594  265
   75 1147  352  329 1209  898  103  114  501  327  267  604  320  182
  507 1324  639   64  407  266  461  307  889  326  162  133  259  119
   95  701  206  169  405  271  279   87  263  386  251  191  486 1048
  304  418  115  126  686  373  223  690  340 1258  238  222  459  366
  888  918  237  137  241  286  221  413  175  426  297  164  280  301
  157  178  518  632  692  355  590  186  170  748  248  321  520  512
  290  310  257  335  268  368  101  893  219  566  693  124  367  214
  215  202  194  347  464  323  276  333  230  190  272  225  641  415
  393  313  483  396  258  299  139  159  154  471  207  294  220  227
  319  208]
----------------------------------------
Unique values of ratings :
['[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]'
 '[4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 3.0, 5.0, 4.0, 5.0]'
 '[4.0, 5.0, 5.0, 5.0, 4.0, 4.0, 4.0, 5.0, 5.0, 4.0, 4.0, 5.0, 4.0, 4.0, 4.0, 3.0, 4.0]'
 ...
 '[4.0, 3.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 2.0, 5.0]'
 '[5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 4.0, 4.0, 5.0, 5.0]'
 '[5.0, 4.0, 5.0, 5.0, 3.0, 4.0, 4.0, 3.0, 5.0, 5.0, 2.0, 4.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]']
----------------------------------------
Unique values of n_ratings :
[   7   10   17   28  364  700 1125  423   13  174  394  443 1203 1263
   68  173  445    9  144  166  261  330 3465   56  188   22 2602  275
 1817  201  596   11   26   25  204   40 3656  322  416   36  637  283
    3  402  346   31 1112   50  211   20 1987  750  517   42  284    4
 4581 2024  813   66  153   32  218  351   67   14   16   48   47   71
   27  298  380  158   38   97 2232    5 1790 1302  171 2733  849  306
  910  635  232   57  125  269  398   65   84  292   79    8 6437 1667
   69   23  383   61  196   18   12  102  891   51  963    2 1138 2432
  580  547  907 2242   43  755  127   59 3338  122  980  167 1374  854
  428  296 1226  527  756  798  362  282  615  245   34  467 1697 1005
  785  236   63  395 1758  814   52  540  956  389 2798  277  117   44
  104 2011 1120 1679   33 1830  411 1477  896  529  522   19   81  746
   78   55  146  622  109  379  781  179 2457  195  657 1533   89  987
 1553  476   24 1212  592  293  256  181  308  118   30  231 1043  291
   41   15   80  684  752  161  189   29  365  252   35    6   58  357
  242  687  381  808  358 2046  121   90 1002  412  317 1592 1303  871
  914  128  151   37  709  185  738  305  278  607  216  399  274  328
  598  528  479 1253   85  234  107  129  338  968  112   21  734  142
  130  462 1386  132  869   73   99  662   76  224  766  260  180  281
  950  475  490   39 1308  564   86  749 1460  361   88  920  152  582
  229  302   72   93  183  698  647  255  427 1923  493  134  198   49
  431  336  663  106  140  149   74 2851  699  695  300  205  729 1265
  680  187  339  534   70  217   62   77  625  254  192  406  244  184
  199  633  488  378  793  250  376  515  168   96 1354  228   45   83
  212 1421  113  105  348  147 2377  110  550  100  141 1177  591 1319
  571  410  315 1363  900  156  583  384 1270  155  303  721  473   92
  353  354  454  557  177  116  424  111   60  324  226  239   54  541
 1839   82 1513  970  136  478  240   53  429  350  203  932  285  676
  138  979   46  143  289  131  491  120  455   94  552  163  148  145
  344  674 1118  235  135  457 1218  176  209   98  150  740  832  273
  495  200 1669  649  318  539  287  108  165  243  732  408  312  392
 1108  314  247  123  401  193  213  342  497  249   91  391 1594  265
   75 1147  352  329 1209  898  103  114  501  327  267  604  320  182
  507 1324  639   64  407  266  461  307  889  326  162  133  259  119
   95  701  206  169  405  271  279   87  263  386  251  191  486 1048
  304  418  115  126  686  373  223  690  340 1258  238  222  459  366
  888  918  237  137  241  286  221  413  175  426  297  164  280  301
  157  178  518  632  692  355  590  186  170  748  248  321  520  512
  290  310  257  335  268  368  101  893  219  566  693  124  367  214
  215  202  194  347  464  323  276  333  230  190  272  225  641  415
  393  313  483  396  258  299  139  159  154  471  207  294  220  227
  319  208]
----------------------------------------
Unique values of name :
['huckleberry   or blueberry  coffee cake'
 'blender quiche   or whatever you have in your kitchen leftover'
 'sweet orange coleslaw' ... 'asparagus chicken with hollandaise sauce'
 'caribbean chicken and black beans' 'fragrant orange curry']
----------------------------------------
Unique values of minutes :
[   75    65    10    15     4    31    35    25    33   250    55    17
    18    40    22    20     0    30    19     5    90    45    23    89
    79    50    80    60   190    70   385   490    13     2  1920    38
   150   380   300   485   105    81   135    44    85    32   160   140
   610    95    28   310    27     8   195   130  1680   280   155   330
   505    16     3   120   370    51    52   245    42   125    49   560
   110   165   495   200     6   375    21    57    12     7   500   615
    53   430    68   205   285  1500   805    39   325   510  1490    24
   180    54     9  1475   365   305   100 10095   435   175   315   270
   243     1    34   260  2895    26    36   240   750   187    46   745
   210    62    43    76   420   405   360   555  1480   390   185    29
    11   145  1440  1455  5760    97   545   232   440   147    47    74
    58   550  2900    48   230  1620   480    41  1470   182  1460  1380
    14   680    37   675   520  1445   605   115   252   132  1800  1443
   248   218   400   255   235   425    72   530   602   620  2190   265
   492  1442   275  1080   770    88   486   107   225    83   184   487
   138   124  1450   112  1456 10090   320   170    67   740   126   103
   215   790  1200  2925  1485   167  2910  1580   780    77   525   730
   640   314   900   915    63   144    71    56  4350   735   223   153
   765   246   515 21615   570   308   214  1452   395    93   630  7210
   106   372   381   220   335  1090   301    64   104   128   600  2760
   143   660    59    78   249   725   188   840  1540  5820    66   608
  1465   482    84   720   645   800   616  2905   307   481 15860    99
   588  1515   109   158   625    94 10320  9740   290   410    87  2885
   825   795  1530   363   760  1020    73  4330   445 10080   970   540
    98    61  1520]
----------------------------------------
Unique values of tags :
["['time-to-make', 'course', 'main-ingredient', 'preparation', 'occasion', 'breads', 'breakfast', 'fruit', 'oven', 'easy', 'coffee-cakes', 'dietary', 'berries', 'blueberries', 'brunch', 'equipment', '4-hours-or-less']"
 "['weeknight', 'time-to-make', 'course', 'main-ingredient', 'cuisine', 'preparation', 'occasion', 'north-american', 'lunch', 'main-dish', 'eggs-dairy', 'pork', 'poultry', 'vegetables', 'american', 'oven', 'cheese', 'eggs', 'chicken', 'food-processor-blender', 'dietary', 'oamc-freezer-make-ahead', 'meat', 'equipment', 'small-appliance', 'number-of-servings', '4-hours-or-less']"
 "['15-minutes-or-less', 'time-to-make', 'course', 'main-ingredient', 'preparation', 'low-protein', 'salads', 'fruit', 'vegetables', 'easy', 'dietary', 'low-cholesterol', 'low-saturated-fat', 'healthy-2', 'low-in-something', 'apples', 'greens']"
 ...
 "['60-minutes-or-less', 'time-to-make', 'course', 'main-ingredient', 'preparation', 'main-dish', 'poultry', 'vegetables', 'easy', 'chicken', 'dietary', 'meat', 'chicken-breasts', 'asparagus']"
 "['60-minutes-or-less', 'time-to-make', 'main-ingredient', 'cuisine', 'preparation', 'north-american', 'beans', 'poultry', 'caribbean', 'central-american', 'chicken', 'stove-top', 'black-beans', 'meat', 'chicken-breasts', 'equipment']"
 "['30-minutes-or-less', 'time-to-make', 'course', 'main-ingredient', 'cuisine', 'preparation', 'occasion', 'appetizers', 'soups-stews', 'fruit', 'asian', 'middle-eastern', 'easy', 'dinner-party', 'vegetarian', 'dietary', 'citrus', 'oranges', 'taste-mood', 'savory', '3-steps-or-less']"]
----------------------------------------
Unique values of nutrition :
['[174.1, 4.0, 92.0, 8.0, 7.0, 3.0, 11.0]'
 '[308.4, 37.0, 8.0, 20.0, 21.0, 41.0, 3.0]'
 '[290.1, 21.0, 71.0, 14.0, 7.0, 8.0, 13.0]' ...
 '[287.0, 19.0, 4.0, 13.0, 67.0, 33.0, 1.0]'
 '[381.3, 6.0, 11.0, 13.0, 55.0, 4.0, 17.0]'
 '[94.4, 3.0, 55.0, 0.0, 2.0, 6.0, 5.0]']
----------------------------------------
Unique values of n_steps :
[11 10  6  5  8  7  9  4 13  3 20 12 14 16 15 19 18 17 21 22 26 24 28 30
 23 27 29]
----------------------------------------
Unique values of steps :
["['beat margarine and cream cheese at medium speed of an electric mixer until creamy', 'gradually 1 cup sugar , beating well', 'add egg , and beat well', 'combine flour , baking powder , and salt', 'stir into margarine mixture', 'stir in vanilla , then fold in berries', 'pour batter into a 9-inch round cake pan coated with cooking spray', 'combine 2 tablespoons sugar and cinnamon', 'sprinkle over batter', 'bake at 350f for 1 hour', 'cool on a wire rack']"
 "['preheat oven to 350f', 'generously grease a 9 inch pie pan', 'spread shredded cheese across bottom of pie pan', 'cover cheese with meat and vegetables', 'in a blender , combine eggs , baking mix , salt , garlic powder , onions , parsley , and milk', 'blend until smooth , then add olive oil', 'blend until combined , then pour mixture over meat and vegetable layer', 'sprinkle with paprika', 'bake in preheated oven for 40 minutes', 'cool 10 minutes before serving']"
 "['chop the apples', 'in a small bowl mix the orange juice concentate , mayo , dijon , and salt', 'in a large serving bowl toss the coleslaw mix , rice , and apples', 'mix the dressing with the slaw until well coated', 'stir in the pecans', 'chill before serving']"
 ...
 "['to marinate: place chicken in a nonporous glass dish or bowl', 'pour wine over chicken , then sprinkle with tarragon', 'cover dish and refrigerate to marinate for 2 hours', 'preheat oven to broil', 'remove chicken from dish or bowl discarding remaining marinade and broil for 25 minutes or until cooked through and juices run clear', 'meanwhile , steam asparagus to desired degree of doneness', 'prepare hollandaise sauce according to package directions', 'when chicken is cooked , arrange the breasts on a platter , place 4 spears of asparagus on each chicken breast and dribble with prepared hollandaise sauce to taste', 'sprinkle with cheese and serve']"
 "['coat a skillet with nonstick cooking spray', 'sprinkle pepper on chicken and cook in skillet over medium heat for 3-5 minutes , so that the surfaces have a nice brown color and are no longer opaque', 'remove the chicken to a plate and return the pan to heat', 'in the same skillet , heat olive oil', 'add onion', 'if the pan become dry , add 2 tablespoons of broth to skillet', 'cook for 5-6 minutes or until onion is soft , stirring frequently', 'in the last minute of cooking , add the garlic', 'add tomato sauce , remaining broth and rum to skillet and mix well', 'add green and / or red pepper , reserved chicken and seasonings', 'bring to a boil', 'reduce heat and simmer , uncovered , 15 min or until chicken is tender and liquid has thickened', 'stir in beans and heat another 2-3 minutes place rice on large platter and top with chicken and bean mix']"
 "['heat ghee or butter in a medium pot over low heat', 'add spices and stir until fragrant', 'stir in orange juice and cook slowly for 15 to 20 minutes', 'serve hot , in small bowls or cups , with or without spoons']"]
----------------------------------------
Unique values of description :
['cooking light published this in their book, five star recipes--the best of 10 years, and their staff voted this as one of their top five recipes from the first 10 years. it is very, very good, either for breakfast, brunch, or as dessert, warm out of the oven with a scoop of vanilla ice cream.'
 'the great part is you can use whatever leftovers (well...almost) you have on hand. this dish can be served hot or cold. freezes very well! use any cheese of your choice.'
 'this recipe came from one of my mom\'s cookbooks called "quilter\'s cooking companion".  it\'s easy to make and has great texture and flavor!'
 ...
 "this recipe came from another recipe site. it is mouthwatering delicious. beautiful presentation. simple, simple, simple to make. originally found the recipe in february and just got around to making it. i'm sorry i lost all of that time eating it! i'll make up for it now. cook time does not include 2 hours for marinating."
 'originally from shape magazine and adapted to suit my tastes and simplify the preparation. this is healthy and comforting with a pleasing, but approachable combination of spices that even picky eaters will enjoy. though full of flavor this is not spicy hot, so feel free to adjust to your own tastes. a word of caution, this makes 6 perfect portions for my weight watching lifestyle but if you have hungry eaters at your table, it may only serve 4 or 5.'

In [11]:
PP_users_df["len_items"]=PP_users_df["items"].str.count(r",")+1
PP_recipes_df["len_ingredients"]=PP_recipes_df["ingredient_ids"].str.count(r",")+1
max_len_ingredients=PP_recipes_df["len_ingredients"].max()
max_len_items=PP_users_df["len_items"].max()
PP_users_df.drop(columns=["len_items"],inplace=True)
PP_recipes_df.drop(columns=["len_ingredients"],inplace=True)

In [12]:
full_df_processed=DataFramePreprocessing(full_df,max_len_ingredients,max_len_items)
full_df_processed=full_df_processed.preprocessing()

In [13]:
PP_recipes_df["ingredient_ids_transformed"]=PP_recipes_df["ingredient_ids"].apply(lambda x: list(map(int,ast.literal_eval(x))))
all_ingredient_ids=np.unique(list(itertools.chain.from_iterable(list(PP_recipes_df["ingredient_ids_transformed"]))))
ingredient_continuous_ids=pd.Series([i for i in range(1,len(all_ingredient_ids)+1)],index=list(np.sort(all_ingredient_ids)))

In [14]:
def mapping_list(x:list,mapping_serie:pd.Series):
    return [mapping_serie.loc[i] if i in mapping_serie.index else 0 for i in x]

In [15]:
full_df_processed["ingredient_ids_continuous"]=full_df_processed["ingredient_ids"].apply(lambda x : mapping_list(x,ingredient_continuous_ids))

In [16]:
full_df_processed["full_text"]=full_df_processed["name"]+" [SEP] "+full_df_processed["description"]+" [SEP] "+full_df_processed["steps"]+" [SEP] "+full_df_processed["tags"]

In [17]:
scaler=StandardScaler()
full_df_processed=Scaler(scaler).scale(full_df_processed)

In [18]:
full_df_processed["rating_scaled"]=full_df_processed["rating"]/5

In [19]:
full_df_processed.to_parquet(path="./modules/dataframe/full_df_processed.parquet")

## Load of the dataframe

In [31]:
parquet_file = pq.ParquetFile("./modules/dataframe/full_df_processed.parquet")

chunks = []
for batch in parquet_file.iter_batches(batch_size=10000):
    chunks.append(batch.to_pandas())

full_df_processed = pd.concat(chunks, ignore_index=True)

In [32]:
print(f"Columns of the full processed dataframe:")
print(full_df_processed.columns)
print("----------------------------------------")
print(f"Shape of the full processed dataframe:")
print(full_df_processed.shape)
print("----------------------------------------")
print(f"Head of the full  processed dataframe:")
display(full_df_processed.head())
print("----------------------------------------")
for col in full_df_processed.columns:
    print(f"Exemple of {col} :")
    print(full_df_processed.iloc[0][col])
    print("----------------------------------------")
for col in full_df_processed.columns:
    print(f"The type of {col} is")
    print(full_df_processed[col].apply(type).unique())
    print("---------------------------------")

Columns of the full processed dataframe:
Index(['user_id', 'recipe_id', 'rating', 'i', 'techniques_recipes',
       'calorie_level', 'ingredient_ids', 'techniques_users', 'items',
       'n_items', 'ratings', 'n_ratings', 'name', 'minutes', 'tags',
       'nutrition', 'n_steps', 'steps', 'description', 'n_ingredients',
       'ingredient_ids_continuous', 'full_text', 'calorie_level_scaled',
       'n_items_scaled', 'n_ratings_scaled', 'minutes_scaled',
       'n_steps_scaled', 'n_ingredients_scaled', 'rating_scaled'],
      dtype='object')
----------------------------------------
Shape of the full processed dataframe:
(20000, 29)
----------------------------------------
Head of the full  processed dataframe:

,user_id,recipe_id,rating,i,techniques_recipes,calorie_level,ingredient_ids,techniques_users,items,n_items,...,n_ingredients,ingredient_ids_continuous,full_text,calorie_level_scaled,n_items_scaled,n_ratings_scaled,minutes_scaled,n_steps_scaled,n_ingredients_scaled,rating_scaled
0,231160,124810,5.0,170683,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,"[4574, 1910, 6906, 2499, 63, 332, 6270, 7470, ...","[3, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, ...","[8912, 20239, 117522, 79317, 154564, 34303, 17...",7,...,10,"[4560, 1904, 6880, 2493, 63, 331, 6248, 7443, ...",huckleberry or blueberry coffee cake [SEP] ...,-1.092504,-0.586471,-0.586471,-0.024165,0.561965,0.326400,1.0
1,142629,31342,5.0,120866,"[1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",1,"[1168, 1284, 8021, 2499, 330, 6270, 3217, 2318...","[6, 0, 0, 3, 1, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, ...","[122020, 150061, 117907, 82203, 119047, 141912...",10,...,12,"[1163, 1278, 7992, 2493, 329, 6248, 3209, 2312...",blender quiche or whatever you have in your ...,0.183190,-0.583351,-0.583351,-0.056047,0.306358,0.953249,1.0
2,822358,441841,4.0,23143,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,"[1648, 1706, 3347, 5298, 3044, 4623, 2148, 627...","[1, 1, 0, 2, 3, 0, 0, 0, 1, 5, 0, 1, 0, 0, 0, ...","[29762, 87945, 72371, 139098, 39471, 37756, 23...",17,...,8,"[1642, 1700, 3339, 5281, 3036, 4609, 2142, 624...",sweet orange coleslaw [SEP] this recipe came f...,0.183190,-0.576070,-0.576070,-0.231399,-0.716071,-0.300449,0.8
3,655579,211110,4.0,156542,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,"[7031, 5006, 339, 3203, 5975, 6270, 590, 0, 0,...","[10, 0, 0, 5, 11, 0, 0, 0, 0, 7, 1, 3, 0, 0, 1...","[34493, 71280, 73806, 68722, 114796, 35165, 33...",28,...,7,"[7005, 4990, 338, 3195, 5953, 6248, 588, 1, 1,...",wilted greens with garlic and balsamic vinegar...,-1.092504,-0.564629,-0.564629,-0.215458,-0.971678,-0.613873,0.8
4,35140,114469,5.0,30840,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",2,"[1240, 6270, 5006, 1257, 2683, 5168, 800, 2461...","[176, 4, 2, 55, 72, 0, 1, 7, 4, 141, 13, 15, 0...","[121723, 36692, 151294, 154017, 1206, 12803, 1...",364,...,9,"[1235, 6248, 4990, 1252, 2677, 5151, 798, 2455...",chicken in the limelight [SEP] very tender chi...,1.458883,-0.215162,-0.215162,-0.024165,-0.204856,0.012976,1.0

----------------------------------------
Exemple of user_id :
231160
----------------------------------------
Exemple of recipe_id :
124810
----------------------------------------
Exemple of rating :
5.0
----------------------------------------
Exemple of i :
170683
----------------------------------------
Exemple of techniques_recipes :
[1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
----------------------------------------
Exemple of calorie_level :
0
----------------------------------------
Exemple of ingredient_ids :
[4574 1910 6906 2499   63  332 6270 7470 3819 3497    0    0    0    0
    0    0    0    0    0    0]
----------------------------------------
Exemple of techniques_users :
[3 0 0 0 1 0 0 0 0 2 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 2 1 0 0 0 2 0 0 1
 0 0 0 0 0 1 2 0 0 0 1 0 0 0 0 0 0 1 0 0 1]
----------------------------------------
Exemple of items :
[  8912  20239 117522 ...      0      0      0]
----------------------------------------
Exemple of n_items :
7
----------------------------------------
Exemple of ratings :
[5 5 5 ... 0 0 0]
----------------------------------------
Exemple of n_ratings :
7
----------------------------------------
Exemple of name :
huckleberry   or blueberry  coffee cake
----------------------------------------
Exemple of minutes :
75
----------------------------------------
Exemple of tags :
time to make [SEP] course [SEP] main ingredient [SEP] preparation [SEP] occasion [SEP] breads [SEP] breakfast [SEP] fruit [SEP] oven [SEP] easy [SEP] coffee cakes [SEP] dietary [SEP] berries [SEP] blueberries [SEP] brunch [SEP] equipment [SEP] 4 hours or less
----------------------------------------
Exemple of nutrition :
[174.1   4.   92.    8.    7.    3.   11. ]
----------------------------------------
Exemple of n_steps :
11
----------------------------------------
Exemple of steps :
beat margarine and cream cheese at medium speed of an electric mixer until creamy [SEP] gradually 1 cup sugar , beating well [SEP] add egg , and beat well [SEP] combine flour , baking powder , and salt [SEP] stir into margarine mixture [SEP] stir in vanilla , then fold in berries [SEP] pour batter into a 9-inch round cake pan coated with cooking spray [SEP] combine 2 tablespoons sugar and cinnamon [SEP] sprinkle over batter [SEP] bake at 350f for 1 hour [SEP] cool on a wire rack
----------------------------------------
Exemple of description :
cooking light published this in their book, five star recipes--the best of 10 years, and their staff voted this as one of their top five recipes from the first 10 years. it is very, very good, either for breakfast, brunch, or as dessert, warm out of the oven with a scoop of vanilla ice cream.
----------------------------------------
Exemple of n_ingredients :
10
----------------------------------------
Exemple of ingredient_ids_continuous :
[4560 1904 6880 2493   63  331 6248 7443 3810 3489    1    1    1    1
    1    1    1    1    1    1]
----------------------------------------
Exemple of full_text :
huckleberry   or blueberry  coffee cake [SEP] cooking light published this in their book, five star recipes--the best of 10 years, and their staff voted this as one of their top five recipes from the first 10 years. it is very, very good, either for breakfast, brunch, or as dessert, warm out of the oven with a scoop of vanilla ice cream. [SEP] beat margarine and cream cheese at medium speed of an electric mixer until creamy [SEP] gradually 1 cup sugar , beating well [SEP] add egg , and beat well [SEP] combine flour , baking powder , and salt [SEP] stir into margarine mixture [SEP] stir in vanilla , then fold in berries [SEP] pour batter into a 9-inch round cake pan coated with cooking spray [SEP] combine 2 tablespoons sugar and cinnamon [SEP] sprinkle over batter [SEP] bake at 350f for 1 hour [SEP] cool on a wire rack [SEP] time to make [SEP] course [SEP] main ingredient [SEP] preparation [SEP] occasion [SEP] breads [SEP] breakfast [SEP] fruit [SEP] oven [SEP] easy [SEP] coffee cakes [SEP] dietary [SEP] berries [SEP] blueberries [SEP] brunch [SEP] equipment [SEP] 4 hours or less
----------------------------------------
Exemple of calorie_level_scaled :
-1.0925042165561725
----------------------------------------
Exemple of n_items_scaled :
-0.5864709401732145
----------------------------------------
Exemple of n_ratings_scaled :
-0.5864709401732145
----------------------------------------
Exemple of minutes_scaled :
-0.024164821296424114
----------------------------------------
Exemple of n_steps_scaled :
0.5619651098108102
----------------------------------------
Exemple of n_ingredients_scaled :
0.3264001738888866
----------------------------------------
Exemple of rating_scaled :
1.0
----------------------------------------
The type of user_id is
[<class 'int'>]
---------------------------------
The type of recipe_id is
[<class 'int'>]
---------------------------------
The type of rating is
[<class 'float'>]
---------------------------------
The type of i is
[<class 'int'>]
---------------------------------
The type of techniques_recipes is
[<class 'numpy.ndarray'>]
---------------------------------
The type of calorie_level is
[<class 'int'>]
---------------------------------
The type of ingredient_ids is
[<class 'numpy.ndarray'>]
---------------------------------
The type of techniques_users is
[<class 'numpy.ndarray'>]
---------------------------------
The type of items is
[<class 'numpy.ndarray'>]
---------------------------------
The type of n_items is
[<class 'int'>]
---------------------------------
The type of ratings is
[<class 'numpy.ndarray'>]
---------------------------------
The type of n_ratings is
[<class 'int'>]
---------------------------------
The type of name is
[<class 'str'>]
---------------------------------
The type of minutes is
[<class 'int'>]
---------------------------------
The type of tags is
[<class 'str'>]
---------------------------------
The type of nutrition is
[<class 'numpy.ndarray'>]
---------------------------------
The type of n_steps is
[<class 'int'>]
---------------------------------
The type of steps is
[<class 'str'>]
---------------------------------
The type of description is
[<class 'str'>]
---------------------------------
The type of n_ingredients is
[<class 'int'>]
---------------------------------
The type of ingredient_ids_continuous is
[<class 'numpy.ndarray'>]
---------------------------------
The type of full_text is
[<class 'str'>]
---------------------------------
The type of calorie_level_scaled is
[<class 'float'>]
---------------------------------
The type of n_items_scaled is
[<class 'float'>]
---------------------------------
The type of n_ratings_scaled is
[<class 'float'>]
---------------------------------
The type of minutes_scaled is
[<class 'float'>]
---------------------------------
The type of n_steps_scaled is
[<class 'float'>]
---------------------------------
The type of n_ingredients_scaled is
[<class 'float'>]
---------------------------------
The type of rating_scaled is
[<class 'float'>]
---------------------------------

In [ ]:
#df_text=full_df_processed["full_text"]

In [33]:
distilbert_model=DistilBertModel.from_pretrained("distilbert-base-uncased")
tokenizer=AutoTokenizer.from_pretrained("distilbert-base-uncased")

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertModel LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |  |
------------------------+------------+--+-
vocab_projector.bias    | UNEXPECTED |  |
vocab_layer_norm.bias   | UNEXPECTED |  |
vocab_transform.weight  | UNEXPECTED |  |
vocab_layer_norm.weight | UNEXPECTED |  |
vocab_transform.bias    | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
#bert_dataset=BERTCreationDataset(df_text)

In [ ]:
#generator=torch.Generator()
#generator.manual_seed(seed)
#bert_collate_function_object=BertCollateFunction(tokenizer=tokenizer)
#bert_dataloader=DataLoader(dataset=bert_dataset,batch_size=32,shuffle=False,collate_fn=bert_collate_function_object.collate_fn,worker_init_fn=seed_worker,generator=generator)

In [ ]:
#device = (torch.device("mps") if torch.backends.mps.is_available() else torch.device("cuda" if torch.cuda.is_available() else "cpu"))
#bert_extractor=BERTEmbeddingsExtractor(bert_model=distilbert_model,device=device)
#bert_extractor.get_bert_embeddings(dataloader=bert_dataloader,path="./modules/BERT_embeddings")

In [34]:
all_cls_embeddings=torch.load("./modules/BERT_embeddings/all_cls_embeddings.pt")
all_mean_embeddings=torch.load("./modules/BERT_embeddings/all_mean_embeddings.pt")

In [35]:
print(all_cls_embeddings.shape)
print(all_mean_embeddings.shape)

torch.Size([20000, 768])
torch.Size([20000, 768])

## Model

In [36]:
train_df,val_df,test_df,train_cls_embeddings,val_cls_embeddings,test_cls_embeddings,train_mean_embeddings,val_mean_embeddings,test_mean_embeddings=split_df(full_df_processed,cls_embeddings=all_cls_embeddings,mean_embeddings=all_mean_embeddings,random_state=seed)

In [37]:
train_dataset=CreationDataset(train_df,cls_embeddings=train_cls_embeddings,mean_embeddings=train_mean_embeddings)
val_dataset=CreationDataset(val_df,cls_embeddings=val_cls_embeddings,mean_embeddings=val_mean_embeddings)

In [38]:
train_dataset.__getitem__(10)

{'user_id': np.int64(440299),
 'recipe_id': np.int64(5012),
 'rating': np.float64(5.0),
 'i': np.int64(109198),
 'techniques_recipes': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 'calorie_level': np.int64(1),
 'ingredient_ids': array([  63, 5006, 2499, 7168, 7655, 7956, 6906,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32),
 'techniques_users': array([5, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0, 1, 1, 2,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2]),
 'items': array([ 18676,  75351, 109198, ...,      0,      0,      0], dtype=int32),
 'n_items': np.int64(10),
 'ratings': array([2, 5, 5, ..., 0, 0, 0], dtype=int32),
 'n_ratings': np.int64(10),
 'name': 'chicago style deep dish pizza crust',
 'minutes': np.int64(0),
 'tags': '15 minutes or less [SEP] time to make [SEP] course [SEP] cuisine [SEP] preparation [SEP] occasion [SEP] north american [SEP] healthy [SEP] breads [SEP] main dish [SEP] american [SEP] kid friendly [SEP] pizza [SEP] dietary [SEP] low sodium [SEP] low saturated fat [SEP] midwestern [SEP] yeast [SEP] low in something',
 'nutrition': array([300.8,  10. ,   6. ,   1. ,  18. ,   6. ,  16. ]),
 'n_steps': np.int64(10),
 'steps': 'whisk together water , yeast and sugar in a bowl and set aside to proof for 10 minutes [SEP] in a large bowl sift together flour and salt and sprinkle in thyme [SEP] mix eggs into yeast mixture [SEP] pour liquid into dry ingredients and mix until a soft sticky dough forms [SEP] remove dough to a lightly floured surface and knead 5 minutes , until dough is no longer sticky [SEP] place in a well oiled bowl , turning to coat all sides , cover and allow to rise until doubled in bulk 2 - 3 hours [SEP] punch dough down and place into a well oiled 12" pizza pan [SEP] using your hands , move dough around the bottom of the pan and 2 / 3 the way up the sides [SEP] set aside and let rise 10 minutes [SEP] brush crust lightly with olive oil and add toppings',
 'description': 'missing description',
 'n_ingredients': np.int64(7),
 'ingredient_ids_continuous': array([  63, 4990, 2493, 7142, 7628, 7927, 6880,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1]),
 'full_text': 'chicago style deep dish pizza crust [SEP] missing description [SEP] whisk together water , yeast and sugar in a bowl and set aside to proof for 10 minutes [SEP] in a large bowl sift together flour and salt and sprinkle in thyme [SEP] mix eggs into yeast mixture [SEP] pour liquid into dry ingredients and mix until a soft sticky dough forms [SEP] remove dough to a lightly floured surface and knead 5 minutes , until dough is no longer sticky [SEP] place in a well oiled bowl , turning to coat all sides , cover and allow to rise until doubled in bulk 2 - 3 hours [SEP] punch dough down and place into a well oiled 12" pizza pan [SEP] using your hands , move dough around the bottom of the pan and 2 / 3 the way up the sides [SEP] set aside and let rise 10 minutes [SEP] brush crust lightly with olive oil and add toppings [SEP] 15 minutes or less [SEP] time to make [SEP] course [SEP] cuisine [SEP] preparation [SEP] occasion [SEP] north american [SEP] healthy [SEP] breads [SEP] main dish [SEP] american [SEP] kid friendly [SEP] pizza [SEP] dietary [SEP] low sodium [SEP] low saturated fat [SEP] midwestern [SEP] yeast [SEP] low in something',
 'calorie_level_scaled': np.float64(0.18318963743281916),
 'n_items_scaled': np.float64(-0.5833506980103502),
 'n_ratings_scaled': np.float64(-0.5833506980103502),
 'minutes_scaled': np.float64(-0.2632815847911344),
 'n_steps_scaled': np.float64(0.30635795518125414),
 'n_ingredients_scaled': np.float64(-0.6138730368530573),
 'rating_scaled': np.float64(1.0),
 'cls_embeddings': tensor([-4.3926e-01, -8.0494e-02,  1.5189e-01, -9.7821e-02,  2.1476e-02,
         -9.6848e-02,  1.1897e-01,  2.9560e-01, -1.8832e-01, -2.4743e-01,
         -7.7781e-02, -3.0157e-02,  2.3765e-02,  2.2340e-01, -1.6420e-01,
          3.8480e-02,  1.2496e-01,  1.8147e-01,  1.5513e-01, -7.9278e-03,
         -9.4934e-02, -5.6202e-01,  5.7085e-02, -7.7405e-02, -4.0344e-03,
         -5.1196e-02, -1.5435e-01, -7.4455e-02,  6.3317e-02, -2.2641e-02,
         -7.6512e-03,  2.2540e-01,  5.2787e-02, -3.8075e-01,  3.3826e-01,
         -7.0280e-03,  4.1102e-01,  9.6607e-02,  6.5771e-02, -9.7780e-02,
         -3.7799e-02,  1.6033e-01,  4.1844e-01, -2.9992e-01, -1.0954e-02,
          3.6213e-02, -2.3884e+00, -4.2031e-02, -4.0388e-01, -2.9736e-01,
          1.8779e-01, -9.4406e-02,  6.0406e-02,  1.4631e-01,  1.6248e-01,
          2.8919e-01, -2.5865e-01,  5.9218e-01,  7.5641e-02,  9.8979e-02,
          1.4040e-01,  9.7290e-02, -8.9526e-02,  1.5988e-01, -8.6498e-02,
          5.7646e-02, -1.0825e-01,  2.4107e-01, -3.6068e-01,  5.2401e-01,
         -3.0505e-01, -9.6168e-02,  1.2739e-01, -4.8393e-02,  1.4532e-01,
         -1.3455e-01,  1.2733e-01,  4.5125e-02, -1.6926e-01,  1.6467e-01,
         -1.5193e-01, -7.5943e-04,  1.1529e-01,  2.1900e-01,  5.3455e-03,
          3.0130e-01, -2.5704e-01, -5.4670e-02,  2.0509e-01,  4.2851e-01,
         -7.1669e-02,  1.0851e-01,  2.6843e-01,  1.2738e-01,  2.0056e-01,
         -3.2625e-01,  1.0078e-01,  6.8375e-02,  4.5960e-01,  2.4739e-01,
         -8.1177e-02, -2.5300e-02,  1.5170e-01, -1.5651e-01,  7.5750e-02,
         -1.3712e-01, -1.6502e-01, -2.1027e-01,  4.6497e-02, -2.1874e+00,
          3.1626e-01,  3.0064e-01,  5.0905e-02, -1.0305e-01, -2.2824e-01,
         -3.5598e-02,  2.1088e-01,  1.6718e-01, -5.7841e-03, -1.3090e-01,
         -2.1021e-01,  5.6268e-01,  9.0708e-02, -1.1265e-01,  1.2016e-01,
          2.3129e-01,  4.8681e-02,  1.7640e-01,  2.9800e-01,  2.5420e-01,
          1.0875e-01,  2.0575e-01, -7.4310e-02, -7.6300e-02, -1.7633e-01,
          2.9544e-01,  2.1423e-01,  3.2646e-02,  8.2375e-02, -1.8468e-01,
         -3.8736e-01, -1.7824e-01, -2.7055e+00,  1.8994e-01,  3.7929e-01,
         -7.6290e-02, -1.1820e-01, -4.4574e-02,  6.1063e-03,  2.4709e-01,
          2.9772e-01,  9.8910e-02, -1.9427e-01,  3.5553e-02, -1.5927e-01,
          1.0789e-01, -2.2606e-01, -2.1794e-01,  1.8181e-01, -3.4848e-02,
          1.5071e-01, -2.9513e-02,  9.1261e-03, -2.3303e-01, -1.0360e-01,
          4.5750e-02,  1.4714e-01,  6.3765e-02, -9.0737e-02,  2.1855e-01,
         -1.2367e-01,  7.0138e-02,  4.5026e-01, -4.6074e-03,  2.3267e-01,
          5.5692e-02, -2.7977e-03,  1.7769e-01,  6.1988e-02, -9.6830e-02,
         -2.0099e-01,  4.1236e-01,  1.0160e-01,  3.8106e-02, -1.1563e-01,
         -2.2056e-01,  2.5084e-01, -1.7908e-01,  9.9776e-02,  2.7291e-01,
         -6.8151e-02, -1.2620e-01,  7.1326e-02, -1.0605e-01,  2.5336e-01,
          5.8718e-02,  1.4395e-02, -5.2991e-01,  2.7293e-01,  1.2887e-01,
         -1.6590e-01,  1.2687e-01,  5.4675e-02, -5.3884e-02, -2.9484e-01,
          3.6170e+00,  1.4138e-01, -6.3448e-02,  4.4450e-01,  1.6606e-01,
          4.0848e-02, -3.9796e-02,  7.0076e-02, -2.1353e-01,  2.2668e-01,
          4.6193e-02,  5.0917e-01,  3.5284e-02,  2.6627e-01, -2.0723e-01,
          1.9853e-01,  1.9341e-01,  3.4011e-02,  3.1242e-01, -2.0404e-01,
         -7.9438e-02, -3.8666e-02,  2.5389e-02,  7.2507e-02, -9.8698e-01,
          2.3620e-01, -1.5100e-01, -1.8318e-02,  3.1354e-01, -1.6759e-01,
         -1.7712e-01,  2.8211e-01,  1.3598e-01,  1.9277e-01, -5.3715e-02,
          1.0545e-01,  1.9678e-01,  3.1855e-01, -1.0173e-01, -2.9817e-01,
          1.7895e-01,  9.0379e-02,  1.7815e-02, -5.5551e-02, -2.3651e-01,
          2.0419e-01, -9.8801e-02,  5.9829e-02, -1.9271e-01,  1.0717e-01,
         -1.0795e-01,  1.0910e-01, -4.0347e-02, -1.3725e-01, -1.2285e-01,
         -3.3318e-01, -3.9065e-02,  2.4768e-01, -7.7587e-02, -3.1765e-01,
          4.7572e-03, -2.1586e-01, -1.2792e-01, -2.3080e-02, -1.0744e-02,
         -3.2111e-02,  5.0523e-02, -3.6639e-01, -3.6253e+00, -4.6896e-02,
         -1.9764e-01,  2.4940e-01,  1.8293e-01, -1.8048e-01, -6.8881e-02,
          2.2758e-01,  1.9996e-01,  2.8876e-02,  4.8408e-01,  4.4881e-02,
         -5.6767e-02,  1.6429e-01, -4.5936e-01, -2.7710e-02,  6.6913e-03,
         -4.1584e-02,  2.4304e-01, -1.7135e-01, -6.8945e-02,  2.0619e-01,
         -1.5350e-01,  8.4970e-02,  3.9959e-02,  1.0625e-01, -3.8985e-01,
          1.6164e-02, -1.3002e-01,  1.1247e-01, -1.8311e-02, -3.0952e-01,
         -3.8914e-02, -3.3916e-01, -3.8436e-01, -3.1450e+00, -2.2183e-01,
         -3.0344e-01, -1.0318e-01,  1.7709e-01, -2.5821e-01,  3.6708e-01,
         -3.2438e-01, -1.1967e-01,  3.4989e-01, -9.3760e-02, -1.4778e-03,
          1.3843e-01,  2.2801e-02,  2.8655e-01,  2.1295e-01,  3.0743e-01,
         -6.3854e-02,  1.7121e-01,  1.9922e-01,  2.3800e-01, -1.4183e-03,
          6.4107e-02,  2.0074e-01, -3.9903e-02,  1.6789e-01, -4.1472e-01,
          1.9357e-01, -2.9848e-01, -7.4997e-02, -7.2514e-02, -2.5927e-01,
         -1.6533e-01, -2.6010e-02, -1.5505e-01, -3.0497e-01, -5.5179e-02,
          3.0901e-01,  4.2258e-01,  2.2868e-01, -5.6734e-02,  6.1243e-01,
         -4.1364e-03, -1.0637e-01,  3.6192e-01,  1.5388e-01,  3.3474e-01,
         -2.8729e-01, -2.0390e-02,  2.1368e-01,  4.2972e-02,  4.4213e-02,
          1.0139e+00, -1.1801e-01,  1.9863e-01, -8.0165e-02,  3.6327e-01,
         -2.5541e-02,  1.8111e-01, -1.0952e-01,  2.6714e-01, -5.8549e-02,
          1.8645e-02, -1.2104e-01,  2.0790e-02, -1.7724e-01,  1.3623e-01,
         -1.9804e-01,  1.5318e-02,  2.8266e-04, -8.9608e-02,  9.7948e-02,
          1.2358e-01, -7.6754e-01, -1.8809e-01, -1.4006e-01, -1.1901e-01,
          1.3088e-01, -2.1835e-02,  2.5184e-01, -2.4893e-01,  2.5228e-02,
          8.2740e-02,  3.6527e-01, -1.0551e-01,  2.5268e-02, -2.2786e-01,
          4.3883e-02, -5.5502e-01,  4.0396e-03,  1.9241e-01,  1.1979e-01,
         -1.1047e-02, -1.5856e-01,  3.5303e-02,  1.4071e-01,  1.2140e-01,
         -7.5401e-01,  1.1205e-01, -2.9014e-01,  1.1509e-02, -1.8608e-01,
          8.8281e-02, -1.4376e-01, -1.0446e-01, -1.3785e-01, -1.5088e-01,
          2.6151e-01,  8.6337e-02,  1.5922e-01, -1.0641e-01,  7.4093e-02,
         -1.8800e-01,  9.9260e-03,  7.0240e-01,  1.0295e-01, -1.7421e-01,
          1.0592e-01, -8.1311e-03,  2.6202e-01,  3.4301e-01,  5.8355e-02,
          1.5202e-01, -1.0479e-02,  4.6642e-02, -1.1320e-01,  2.2798e-01,
         -2.2040e-01, -2.9426e-01,  2.6265e-01,  6.1722e-02, -2.9661e-02,
         -5.0082e-02, -5.1473e-01, -5.1829e-02, -1.6959e-01, -2.4901e-01,
          2.6857e-01,  1.9222e-01, -8.8533e-02,  2.6145e-01,  7.2822e-02,
         -1.9692e-02,  3.1027e-01, -1.5872e-02,  5.5843e-01,  1.5355e-01,
         -3.7643e-03,  7.8144e-02,  2.4584e-01,  1.3235e-01, -6.9386e-02,
         -1.3883e-01, -1.7797e-01, -4.9232e-02, -1.1112e-01,  9.2039e-04,
          2.3943e-02, -2.6821e-01,  1.4667e-02,  6.6110e-02,  1.9910e-02,
         -1.4981e+00,  2.0384e-01,  2.9461e-02, -2.3086e-02, -9.9821e-04,
         -2.1651e-01, -2.5298e-01,  3.6206e-01,  2.0126e-01, -1.1574e-01,
         -2.6054e-01,  5.0371e-02,  5.3175e-02,  1.3036e-02,  1.5861e-01,
         -6.1535e-02,  4.6658e-02, -1.2930e-01, -7.8859e-02,  7.8653e-02,
         -1.8516e-01,  4.0234e-01, -1.1792e-01, -1.5908e-01, -9.9499e-02,
         -1.4255e-01, -1.3257e-02,  2.7369e-01,  1.5458e-01,  5.2198e-02,
          1.0235e-01, -1.7776e-01, -3.1346e-01, -1.3864e-02,  9.2282e-02,
          5.3052e-01, -5.1862e-02, -1.3058e-01,  2.8180e-01,  1.9755e-01,
         -5.3865e-01,  1.8096e-01,  2.4673e-01, -1.8016e-02,  4.0770e-01,
          2.7373e-01, -1.4515e-01,  1.6720e-01,  1.8356e-02, -9.6378e-02,
          5.6726e-03, -1.5315e-01, -1.4712e-01, -5.4042e-02,  1.0330e-02,
          1.2818e-01,  1.7885e-01, -1.0342e-01,  6.6779e-02, -1.9739e-01,
          8.7679e-02, -1.7025e-01, -1.4321e-01,  3.8324e-01,  1.0955e-03,
         -5.9542e-01, -7.1815e-02,  4.3666e-02,  1.3095e-01,  1.7700e-01,
          3.1900e-01,  1.9722e-01, -1.7848e-01,  2.2193e-01, -3.3946e-01,
          1.7014e-01, -8.1590e-02,  1.6025e-01,  1.3697e-01, -6.3627e-02,
         -3.2961e-02, -2.3130e-01, -4.8519e-01,  2.6354e-01,  1.0429e-01,
         -7.5910e-02, -1.1619e-01,  6.7850e-02,  2.5178e-01,  6.7425e-03,
         -1.2294e-01, -3.5889e-01,  1.5538e-01,  1.6078e-01, -2.2705e-02,
          2.7021e-02,  1.0159e-01,  2.2105e-01, -8.6866e-02,  1.2526e-01,
         -4.4487e-02,  2.2335e-01,  2.7975e-01,  2.0670e-01,  3.2050e-02,
         -2.6862e-02,  8.3396e-02,  2.6668e-02, -2.5835e-02,  1.1574e-01,
          1.4106e-01,  1.3240e-01,  2.1088e-01,  1.6199e-01, -1.6636e-01,
         -3.8655e-01,  1.3989e-01, -1.0557e-01,  1.8918e+00,  2.5154e-01,
         -5.7866e-02,  1.1697e-01,  1.6432e-01, -4.6247e-03, -1.3474e-01,
          1.1874e-01, -2.6633e-01,  4.3818e-01,  1.1555e-01,  1.1806e-01,
         -1.2007e-01,  1.1425e-01,  2.8781e-01,  2.5333e-01, -2.2793e-02,
         -8.0757e-02, -3.5079e-01,  1.0841e-01, -4.2065e-01,  2.6400e-01,
          1.8109e-01, -1.4003e-01, -5.8306e-02,  1.3446e-01,  1.3160e-01,
         -9.6604e-02,  7.9812e-02,  7.0873e-02, -2.8947e-02, -1.1833e-01,
         -5.8746e-03,  3.7192e-01, -6.4857e-02,  5.1263e-02,  4.0038e-02,
         -2.2548e-01, -2.1406e-01,  2.4342e-01,  1.9408e-01, -4.4586e-01,
          3.2101e-01, -1.0224e-01, -6.9413e-02,  3.5498e-01, -1.9408e-01,
         -4.4596e-01,  1.1276e-01,  8.6103e-02,  1.5515e-02,  1.0798e-01,
         -2.6724e-01, -1.7683e-02, -9.2630e-02,  2.4824e-02, -8.5071e-02,
         -1.3467e-01, -3.1814e-01,  3.8439e-01,  2.1553e-02,  2.4649e-01,
          2.3472e-01, -1.0657e-01,  2.9153e-01,  1.0203e-01, -2.5465e-01,
          4.4665e-02,  5.8582e-02, -5.6107e-02, -7.8599e-02,  6.6927e-03,
          1.6225e-01,  2.4978e-01,  9.7655e-02, -1.6675e-01,  2.4094e-01,
         -1.5415e-01, -2.5830e-01, -2.3883e+00, -1.9858e-02,  5.4993e-02,
         -6.7387e-02, -5.0541e-02,  2.6674e-01,  1.5227e-01, -2.9625e-01,
         -2.2303e-01, -2.1996e-01,  3.8450e-01,  2.8356e-01,  8.0056e-02,
         -6.2887e-02,  2.1506e-01, -1.0166e-01,  7.5961e-02, -2.5285e-01,
          8.4287e-02, -3.8517e-02,  1.3316e-01, -2.4381e-02, -1.6394e-02,
         -2.1733e-01, -3.3400e-01, -2.9527e-02,  1.0207e-02, -2.6994e-01,
          7.2570e-02, -1.0175e-01, -9.6514e-02,  8.8585e-02, -7.8387e-02,
         -4.4849e-02, -2.5727e-01, -2.1486e-01, -3.9008e-02,  7.9355e-02,
         -6.0729e-02,  1.0334e-01, -1.2396e-01,  3.8213e-01, -2.5837e-02,
          1.9702e-01, -1.8630e-01,  8.3891e-02,  3.1181e-01, -2.4913e-01,
          4.2572e-01, -1.3803e-01,  1.3299e-01,  9.3797e-02, -2.0112e-02,
          2.6042e-01,  4.4999e-02,  7.8430e-02,  9.4429e-02,  1.6658e-02,
         -1.9302e-01, -2.5710e-02, -4.1273e-01,  4.8893e-02, -9.3181e-02,
          7.4541e-03,  3.2401e-01, -1.1291e-01, -9.1418e-02,  1.7469e-03,
          1.2941e-04, -8.7341e-02, -8.8551e-03, -1.3884e-01,  3.9764e-01,
          1.1009e-01,  6.6763e-02, -2.6532e-02,  2.3280e-01,  2.7811e-01,
          9.6838e-02,  5.6105e-02,  7.3123e-02, -2.0519e-01, -1.7856e-01,
         -3.6749e-02,  4.7213e-01, -6.8857e+00, -2.1297e-01, -6.5105e-02,
         -2.4579e-02, -9.7571e-02, -7.6994e-02,  1.2418e-01, -3.5733e-01,
          4.4367e-02,  3.5709e-02,  1.2189e-01,  3.7780e-02, -1.9954e-01,
         -8.9761e-02,  1.6379e-01,  4.0633e-01]),
 'mean_embeddings': tensor([-1.6662e-02,  4.2074e-02,  1.1839e-01,  2.1663e-01,  2.8436e-01,
         -1.2278e-01,  5.1610e-02, -4.1407e-02,  2.0320e-01, -3.3600e-01,
          7.4439e-02, -5.2773e-02,  3.5081e-02,  9.2372e-02, -1.8272e-01,
         -7.8776e-02,  1.9925e-01,  7.1945e-02, -2.0449e-02,  1.8879e-01,
          6.9198e-02, -2.2404e-01, -5.5204e-02,  1.5460e-02,  2.8019e-01,
          8.9466e-02, -2.0350e-01, -1.2886e-01,  2.9670e-02, -3.3339e-01,
          2.5904e-02,  2.1987e-02,  2.1461e-01, -2.1357e-01,  2.2484e-01,
          6.3922e-02,  1.6604e-01,  1.8941e-01, -1.7809e-01, -6.0738e-02,
         -2.4649e-01, -6.0080e-04,  2.1863e-01, -2.7786e-01,  6.9416e-03,
         -1.2261e-01,  9.4630e-02,  4.4575e-03, -4.4969e-01, -8.2545e-03,
          1.4209e-01, -1.1567e-01, -1.1929e-01, -2.2524e-01, -8.2005e-02,
          2.2596e-01, -1.3114e-01,  9.7403e-02, -2.8955e-02, -1.2073e-01,
         -7.0387e-02,  1.3208e-01,  2.0408e-02, -7.7899e-02, -9.8122e-02,
          5.9839e-02,  1.8793e-03,  2.1107e-01, -4.5596e-01,  2.4604e-01,
         -6.9107e-03, -2.4657e-02, -3.7652e-02,  2.1964e-02, -6.4047e-03,
         -7.8861e-02, -2.7291e-02,  9.2706e-02,  1.0847e-01,  3.2447e-02,
         -3.7829e-01, -1.6985e-01,  3.3011e-02,  2.2808e-01,  9.2148e-02,
          1.6660e-01,  3.5225e-02,  3.5488e-02, -9.8106e-02,  2.6056e-01,
          1.7566e-01,  1.9739e-02,  1.9184e-01, -1.4389e-01, -4.7654e-02,
         -1.5918e-01,  9.1089e-02,  1.3081e-01,  2.7996e-01,  4.3999e-01,
         -2.5351e-01, -1.9203e-01,  1.8737e-01,  2.8676e-01,  4.1147e-02,
         -4.0045e-02, -5.5076e-02,  4.3265e-02,  1.2789e-01,  2.3433e-01,
          2.6919e-01,  4.7187e-04,  1.4939e-01,  1.3466e-01, -1.6025e-01,
         -1.8985e-03, -1.4686e-01,  1.3129e-01, -8.1068e-02, -6.0758e-02,
         -2.1717e-01,  9.1166e-02,  1.8817e-01,  3.3244e-01, -8.3954e-02,
         -4.2420e-02, -1.4173e-01,  1.0564e-01,  1.0218e-01, -8.3232e-02,
         -8.3919e-02, -4.9405e-02,  1.3453e-01, -1.4936e-01, -1.3681e-01,
          1.0897e-01,  6.3241e-02, -6.3857e-02,  1.9044e-01, -1.2086e-01,
         -9.7653e-02,  1.9045e-01,  3.1758e-01,  2.0207e-02,  7.2904e-02,
         -4.2222e-02, -7.8990e-02, -4.9199e-02, -1.8191e-02,  1.4049e-01,
          3.1234e-01,  5.3246e-02, -1.0161e-01, -1.2028e-01, -8.8964e-02,
          1.5525e-01, -2.5567e-01,  2.8187e-02, -1.3531e-01, -1.6901e-03,
          2.6972e-01,  1.5388e-01,  1.5065e-01, -1.0779e-01,  8.8708e-02,
         -8.9132e-02,  1.5199e-01,  2.6249e-01, -1.4410e-01,  5.0402e-01,
         -6.9780e-02, -8.8512e-02,  5.0903e-01,  7.5069e-02, -9.5300e-02,
         -8.0811e-02,  2.2069e-01, -1.7781e-02, -2.2209e-02, -1.6306e-01,
         -6.6163e-01,  4.2049e-02,  3.9499e-02, -7.4795e-02, -1.6555e-02,
         -1.8578e-01,  1.0984e-01, -2.3248e-01,  1.8366e-01, -3.3351e-02,
         -9.4744e-02, -3.3248e-01, -5.4605e-02, -8.3824e-02,  1.6278e-01,
         -3.0224e-01, -9.3282e-02, -1.2763e-02, -3.8296e-02, -6.2403e-02,
          1.8829e-01,  1.6524e-01,  1.6218e-01, -7.1763e-02, -1.1963e-01,
         -6.1435e-02,  2.0407e-01, -1.2922e-01,  3.9056e-01, -1.3653e-01,
         -2.4571e-01,  1.4611e-01,  2.1571e-02, -1.8141e-01, -8.4120e-02,
         -3.5814e-02,  4.1551e-01, -1.1545e-03,  1.2304e-01, -1.1461e-01,
          4.7400e-02, -9.6703e-03, -1.6946e-01,  3.3210e-01, -2.4970e-01,
         -1.4372e-03,  2.4704e-01, -2.4014e-01,  1.0224e-01,  1.4134e-01,
          1.0560e-01, -2.8850e-01,  2.4860e-01,  3.7028e-02, -2.3876e-02,
          1.8398e-01,  2.6310e-01,  1.2688e-01,  1.6094e-01, -2.4885e-01,
          3.1678e-02,  1.4246e-01,  4.4628e-01, -1.7303e-01,  4.9229e-02,
         -6.0775e-02,  6.4991e-02,  2.3120e-01, -1.3854e-01, -4.1586e-01,
         -1.8144e-01, -1.6856e-01,  4.0423e-02, -2.8587e-01, -1.8045e-02,
         -1.2986e-01, -1.6718e-01, -7.4478e-02,  1.9822e-01,  4.4522e-02,
          5.0001e-02, -1.7799e-02,  3.5915e-01, -1.5545e-01, -1.9066e-01,
          3.1441e-02, -2.1154e-01,  1.2222e-01,  7.8136e-02,  1.0378e-01,
         -4.7484e-02, -1.0394e-01, -1.1279e-01,  1.8241e-01, -2.0625e-01,
         -4.3000e-01,  3.2139e-01,  8.7879e-02, -8.4488e-02, -1.7032e-01,
         -1.1894e-03,  2.9195e-01, -1.0774e-01,  2.5712e-01, -2.8101e-02,
         -2.5813e-01, -7.6533e-02, -1.8652e-01, -2.2178e-01, -3.1679e-01,
         -1.5726e-02,  2.0318e-01, -1.6029e-01, -2.3257e-02,  1.7688e-01,
         -1.2873e-02,  8.3163e-02,  1.9049e-01,  3.2567e-01, -1.0365e-01,
          5.8366e-02, -5.2214e-02,  4.9033e-02,  8.7247e-02, -4.7931e-01,
          5.8047e-02, -1.7386e-01, -2.4390e-01, -4.6199e+00, -1.7043e-01,

In [39]:
generator=torch.Generator()
generator.manual_seed(seed)
collate_function_object=CollateFunction(tokenizer=tokenizer)
collate_fn=collate_function_object.collate_fn
train_dataloader=DataLoader(train_dataset,batch_size=64,collate_fn=collate_fn,generator=generator,worker_init_fn=seed_worker,shuffle=True,drop_last=True)
val_dataloader=DataLoader(val_dataset,batch_size=64,collate_fn=collate_fn,generator=generator,worker_init_fn=seed_worker,shuffle=True,drop_last=True)

In [40]:
batch=next(iter(train_dataloader))
for key in list(batch.keys()):
    print(key)
    print(f"The shape of batch {key} is :")
    print(batch[key].shape)
    print("-------------------")

user_id
The shape of batch user_id is :
torch.Size([64, 1])
-------------------
recipe_id
The shape of batch recipe_id is :
torch.Size([64, 1])
-------------------
rating_scaled
The shape of batch rating_scaled is :
torch.Size([64, 1])
-------------------
i
The shape of batch i is :
torch.Size([64, 1])
-------------------
technique_recipes
The shape of batch technique_recipes is :
torch.Size([64, 58])
-------------------
calorie_level_scaled
The shape of batch calorie_level_scaled is :
torch.Size([64, 1])
-------------------
ingredient_ids
The shape of batch ingredient_ids is :
torch.Size([64, 20])
-------------------
techniques_users
The shape of batch techniques_users is :
torch.Size([64, 58])
-------------------
items
The shape of batch items is :
torch.Size([64, 6437])
-------------------
n_items_scaled
The shape of batch n_items_scaled is :
torch.Size([64, 1])
-------------------
ratings_scaled
The shape of batch ratings_scaled is :
torch.Size([64, 6437])
-------------------
n_ratings_scaled
The shape of batch n_ratings_scaled is :
torch.Size([64, 1])
-------------------
minutes_scaled
The shape of batch minutes_scaled is :
torch.Size([64, 1])
-------------------
nutrition
The shape of batch nutrition is :
torch.Size([64, 7])
-------------------
n_ingredients_scaled
The shape of batch n_ingredients_scaled is :
torch.Size([64, 1])
-------------------
ingredient_ids_continuous
The shape of batch ingredient_ids_continuous is :
torch.Size([64, 20])
-------------------
cls_embeddings
The shape of batch cls_embeddings is :
torch.Size([64, 768])
-------------------
mean_embeddings
The shape of batch mean_embeddings is :
torch.Size([64, 768])
-------------------

In [ ]:
#PP_recipes_df["ingredient_ids_transformed"]=PP_recipes_df["ingredient_ids"].apply(lambda x: list(map(int,ast.literal_eval(x))))
#all_ingredient_ids=np.unique(list(itertools.chain.from_iterable(list(PP_recipes_df["ingredient_ids_transformed"]))))
#ingredient_continuous_ids=pd.Series([i for i in range(1,len(all_ingredient_ids)+1)],index=list(np.sort(all_ingredient_ids)))

In [ ]:
#n_recipes_ids=len(np.unique(PP_recipes_df["i"]))
#n_ingredients_ids=len(all_ingredient_ids)

#print(f"There are {n_recipes_ids} recipe ids")
#print(f"There are {n_ingredients_ids} ingredient ids")

There are 178265 recipe ids
There are 7993 ingredient ids

In [ ]:
#hash_encoder=EncodedHashedEmbeddings(n_recipes_ids,1024,n_ingredients_ids,1024)
#hashed_recipes_ids_encoded_embeddings,hashed_ingredients_ids_encoded_embeddings=hash_encoder.get_encoded_hashed_embeddings("./modules/hashed_encoded_tables")

In [41]:
hashed_ingredients_ids_encoded_embeddings=torch.load("./modules/hashed_encoded_tables/hashed_embeddings_ingredients.pt")
hashed_recipes_ids_encoded_embeddings=torch.load("./modules/hashed_encoded_tables/hashed_embeddings_recipes.pt")

In [42]:
device = (torch.device("mps") if torch.backends.mps.is_available() else torch.device("cuda" if torch.cuda.is_available() else "cpu"))
model=RecommendationModel(hashed_ingredients_ids_encoded_embeddings=hashed_ingredients_ids_encoded_embeddings,hashed_recipes_ids_encoded_embeddings=hashed_recipes_ids_encoded_embeddings,device=device)

In [43]:
print(model)

RecommendationModel(
  (dhe_fnn_ingredient): Sequential(
    (0): Linear(in_features=1024, out_features=512, bias=True)
    (1): Mish()
    (2): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (3): Linear(in_features=512, out_features=1024, bias=True)
  )
  (projection_ingredient): Linear(in_features=1024, out_features=256, bias=True)
  (norm_encoded_ingredients): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
  (dhe_fnn_items): Sequential(
    (0): Linear(in_features=1024, out_features=512, bias=True)
    (1): Mish()
    (2): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (3): Linear(in_features=512, out_features=1024, bias=True)
  )
  (projection_items): Linear(in_features=1024, out_features=256, bias=True)
  (norm_encoded_items): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
  (projection_full_text): Linear(in_features=768, out_features=384, bias=True)
  (norm_full_text): LayerNorm((384,), eps=1e-05, elementwise_affine=True)
  (first_norm_add_features_recipes): LayerNorm((3,), eps=1e-05, elementwise_affine=True)
  (projection_add_features_recipes): Linear(in_features=3, out_features=12, bias=True)
  (norm_add_features_recipes): LayerNorm((12,), eps=1e-05, elementwise_affine=True)
  (first_norm_add_features_users): LayerNorm((2,), eps=1e-05, elementwise_affine=True)
  (projection_add_features_users): Linear(in_features=2, out_features=8, bias=True)
  (norm_add_features_users): LayerNorm((8,), eps=1e-05, elementwise_affine=True)
  (first_norm_nutrition): LayerNorm((7,), eps=1e-05, elementwise_affine=True)
  (projection_nutrition): Linear(in_features=7, out_features=14, bias=True)
  (norm_nutrition): LayerNorm((14,), eps=1e-05, elementwise_affine=True)
  (first_norm_techniques_users): LayerNorm((58,), eps=1e-05, elementwise_affine=True)
  (projection_techniques_users): Linear(in_features=58, out_features=58, bias=True)
  (norm_techniques_users): LayerNorm((58,), eps=1e-05, elementwise_affine=True)
  (first_norm_techniques_recipes): LayerNorm((58,), eps=1e-05, elementwise_affine=True)
  (projection_techniques_recipes): Linear(in_features=58, out_features=58, bias=True)
  (norm_techniques_recipes): LayerNorm((58,), eps=1e-05, elementwise_affine=True)
  (user_fnn): Sequential(
    (0): LayerNorm((322,), eps=1e-05, elementwise_affine=True)
    (1): Linear(in_features=322, out_features=161, bias=True)
    (2): LayerNorm((161,), eps=1e-05, elementwise_affine=True)
    (3): ReLU()
    (4): Dropout(p=0.3, inplace=False)
    (5): Linear(in_features=161, out_features=256, bias=True)
    (6): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
  )
  (recipe_fnn): Sequential(
    (0): LayerNorm((724,), eps=1e-05, elementwise_affine=True)
    (1): Linear(in_features=724, out_features=362, bias=True)
    (2): LayerNorm((362,), eps=1e-05, elementwise_affine=True)
    (3): ReLU()
    (4): Dropout(p=0.3, inplace=False)
    (5): Linear(in_features=362, out_features=256, bias=True)
    (6): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
  )
)

In [44]:
loss_fn=ContrastiveMSELoss(alpha=0.3,temperature=0.2)
trainer=Train(train_dataloader,val_dataloader,model,device,loss_fn)

In [45]:
trainer.run_training("modules/train_savings")

2026-04-02 19:29:59.858 | INFO     | modules.train:run_training:84 - Epoch 0 :
2026-04-02 19:32:48.210 | INFO     | modules.train:run_training:175 - Epoch 0 : train total loss = 1.1727715484592893
2026-04-02 19:32:48.211 | INFO     | modules.train:run_training:176 - Epoch 0 : train contrative loss = 3.815158455743702
2026-04-02 19:32:48.212 | INFO     | modules.train:run_training:177 - Epoch 0 : train MSE loss = 0.040319949734545904
2026-04-02 19:32:48.213 | INFO     | modules.train:run_training:179 - Epoch 0 : validation total loss = 1.1667602269545845
2026-04-02 19:32:48.214 | INFO     | modules.train:run_training:180 - Epoch 0 : validation contrastive loss = 3.7983742900516675
2026-04-02 19:32:48.215 | INFO     | modules.train:run_training:181 - Epoch 0 : validation MSE loss = 0.03892554524962021
2026-04-02 19:32:48.272 | INFO     | modules.train:run_training:84 - Epoch 1 :
2026-04-02 19:35:36.469 | INFO     | modules.train:run_training:175 - Epoch 1 : train total loss = 1.1679205506219776
2026-04-02 19:35:36.470 | INFO     | modules.train:run_training:176 - Epoch 1 : train contrative loss = 3.810438956689397
2026-04-02 19:35:36.471 | INFO     | modules.train:run_training:177 - Epoch 1 : train MSE loss = 0.03541259566715004
2026-04-02 19:35:36.471 | INFO     | modules.train:run_training:179 - Epoch 1 : validation total loss = 1.1656348886697188
2026-04-02 19:35:36.472 | INFO     | modules.train:run_training:180 - Epoch 1 : validation contrastive loss = 3.7947875261306763
2026-04-02 19:35:36.473 | INFO     | modules.train:run_training:181 - Epoch 1 : validation MSE loss = 0.03885512596563152
2026-04-02 19:35:36.545 | INFO     | modules.train:run_training:84 - Epoch 2 :
2026-04-02 19:38:24.055 | INFO     | modules.train:run_training:175 - Epoch 2 : train total loss = 1.16689008146251
2026-04-02 19:38:24.056 | INFO     | modules.train:run_training:176 - Epoch 2 : train contrative loss = 3.8077331190809196
2026-04-02 19:38:24.056 | INFO     | modules.train:run_training:177 - Epoch 2 : train MSE loss = 0.03510014327892333
2026-04-02 19:38:24.057 | INFO     | modules.train:run_training:179 - Epoch 2 : validation total loss = 1.1574916865514673
2026-04-02 19:38:24.057 | INFO     | modules.train:run_training:180 - Epoch 2 : validation contrastive loss = 3.7689842193023018
2026-04-02 19:38:24.059 | INFO     | modules.train:run_training:181 - Epoch 2 : validation MSE loss = 0.038280534598490464
2026-04-02 19:38:24.115 | INFO     | modules.train:run_training:84 - Epoch 3 :
2026-04-02 19:41:11.640 | INFO     | modules.train:run_training:175 - Epoch 3 : train total loss = 1.156891990145412
2026-04-02 19:41:11.641 | INFO     | modules.train:run_training:176 - Epoch 3 : train contrative loss = 3.771516354805833
2026-04-02 19:41:11.642 | INFO     | modules.train:run_training:177 - Epoch 3 : train MSE loss = 0.03633862165862335
2026-04-02 19:41:11.643 | INFO     | modules.train:run_training:179 - Epoch 3 : validation total loss = 1.150119493836942
2026-04-02 19:41:11.643 | INFO     | modules.train:run_training:180 - Epoch 3 : validation contrastive loss = 3.7401413088259488
2026-04-02 19:41:11.644 | INFO     | modules.train:run_training:181 - Epoch 3 : validation MSE loss = 0.04011005902176966
2026-04-02 19:41:11.760 | INFO     | modules.train:run_training:84 - Epoch 4 :
2026-04-02 19:44:00.047 | INFO     | modules.train:run_training:175 - Epoch 4 : train total loss = 1.1492896911201127
2026-04-02 19:44:00.048 | INFO     | modules.train:run_training:176 - Epoch 4 : train contrative loss = 3.74679281514719
2026-04-02 19:44:00.050 | INFO     | modules.train:run_training:177 - Epoch 4 : train MSE loss = 0.0360740067292039
2026-04-02 19:44:00.051 | INFO     | modules.train:run_training:179 - Epoch 4 : validation total loss = 1.14772316424743
2026-04-02 19:44:00.052 | INFO     | modules.train:run_training:180 - Epoch 4 : validation contrastive loss = 3.736264000768247
2026-04-02 19:44:00.054 | INFO     | modules.train:run_training:181 - Epoch 4 : validation MSE loss = 0.03834844504118613
2026-04-02 19:44:00.106 | INFO     | modules.train:run_training:84 - Epoch 5 :
2026-04-02 19:46:47.788 | INFO     | modules.train:run_training:175 - Epoch 5 : train total loss = 1.1411919522722926
2026-04-02 19:46:47.789 | INFO     | modules.train:run_training:176 - Epoch 5 : train contrative loss = 3.7204264183656885
2026-04-02 19:46:47.790 | INFO     | modules.train:run_training:177 - Epoch 5 : train MSE loss = 0.035805695023763615
2026-04-02 19:46:47.792 | INFO     | modules.train:run_training:179 - Epoch 5 : validation total loss = 1.1475890019665593
2026-04-02 19:46:47.793 | INFO     | modules.train:run_training:180 - Epoch 5 : validation contrastive loss = 3.73405385017395
2026-04-02 19:46:47.793 | INFO     | modules.train:run_training:181 - Epoch 5 : validation MSE loss = 0.039104009492565754
2026-04-02 19:46:47.853 | INFO     | modules.train:run_training:84 - Epoch 6 :
2026-04-02 19:49:36.110 | INFO     | modules.train:run_training:175 - Epoch 6 : train total loss = 1.1320810963254455
2026-04-02 19:49:36.111 | INFO     | modules.train:run_training:176 - Epoch 6 : train contrative loss = 3.6910331380476644
2026-04-02 19:49:36.114 | INFO     | modules.train:run_training:177 - Epoch 6 : train MSE loss = 0.035387300890485904
2026-04-02 19:49:36.115 | INFO     | modules.train:run_training:179 - Epoch 6 : validation total loss = 1.1514133992402449
2026-04-02 19:49:36.115 | INFO     | modules.train:run_training:180 - Epoch 6 : validation contrastive loss = 3.7456463886343916
2026-04-02 19:49:36.116 | INFO     | modules.train:run_training:181 - Epoch 6 : validation MSE loss = 0.039599190931767225
2026-04-02 19:49:36.116 | INFO     | modules.train:run_training:84 - Epoch 7 :
2026-04-02 19:52:24.081 | INFO     | modules.train:run_training:175 - Epoch 7 : train total loss = 1.1204120631611676
2026-04-02 19:52:24.082 | INFO     | modules.train:run_training:176 - Epoch 7 : train contrative loss = 3.654825090268336
2026-04-02 19:52:24.083 | INFO     | modules.train:run_training:177 - Epoch 7 : train MSE loss = 0.03423498667896204
2026-04-02 19:52:24.083 | INFO     | modules.train:run_training:179 - Epoch 7 : validation total loss = 1.166059621002363
2026-04-02 19:52:24.084 | INFO     | modules.train:run_training:180 - Epoch 7 : validation contrastive loss = 3.7889708539713984
2026-04-02 19:52:24.085 | INFO     | modules.train:run_training:181 - Epoch 7 : validation MSE loss = 0.04195474274456501
2026-04-02 19:52:24.085 | WARNING  | modules.train:run_training:201 - Training stops after 7 epochs
2026/04/02 19:52:24 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/02 19:52:24 WARNING mlflow.pytorch: Saving pytorch model by Pickle or CloudPickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization.The recommended safe alternative is to set 'export_model' to True to save the pytorch model using the safe graph model format.
2026/04/02 19:52:50 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.
2026/04/02 19:53:12 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.

In [29]:
batch=next(iter(train_dataloader))

In [30]:
print(batch["rating_scaled"].shape)

torch.Size([32, 1])