In [2]:
from google.colab import drive
import os

drive.mount('/content/drive')
if not os.path.exists('/content/drive/MyDrive/Recipes-Recommendation-System'):
    os.makedirs("/content/drive/MyDrive/Recipes-Recommendation-System")
    %cd /content/drive/MyDrive/Recipes-Recommendation-System
    !git clone https://github.com/soheil-housni/Recipes-Recommendation-System.git \
        /content/drive/MyDrive/Recipes-Recommendation-System

else:
    %cd /content/drive/MyDrive/Recipes-Recommendation-System
    !git pull origin main

print(os.getcwd())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/Recipes-Recommendation-System
From https://github.com/soheil-housni/Recipes-Recommendation-System
 * branch            main       -> FETCH_HEAD
Already up to date.
/content/drive/MyDrive/Recipes-Recommendation-System

In [3]:
!pip install mlflow
!pip install loguru
!pip install optuna

Requirement already satisfied: mlflow in /usr/local/lib/python3.12/dist-packages (3.11.1)
Requirement already satisfied: mlflow-skinny==3.11.1 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.11.1)
Requirement already satisfied: mlflow-tracing==3.11.1 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.11.1)
Requirement already satisfied: Flask-CORS<7 in /usr/local/lib/python3.12/dist-packages (from mlflow) (6.0.2)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.13.5)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.18.4)
Requirement already satisfied: cryptography<47,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (43.0.3)
Requirement already satisfied: docker<8,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (7.1.0)
Requirement already satisfied: graphene<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.4.3)
Requirement already satisfied: gunicorn<26 in /usr/local/lib/python3.12/dist-packages (from mlflow) (25.3.0)
Requirement already satisfied: huey<3,>=2.5.4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.6.0)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.2.2)
Requirement already satisfied: pyarrow<24,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (18.1.0)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)
Requirement already satisfied: skops<1 in /usr/local/lib/python3.12/dist-packages (from mlflow) (0.13.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.49)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (8.3.2)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (3.1.2)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (0.102.0)
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (0.135.3)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (3.1.46)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (1.38.0)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (26.0)
Requirement already satisfied: protobuf<8,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (2.12.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (1.2.2)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (0.5.5)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (0.44.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.23.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.3.10)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography<47,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.8)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (3.2.8)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2026.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.4.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography<47,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (2.47.0)
Requirement already satisfied: starlette>=0.46.0 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (0.52.1)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (0.0.4)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.11.1->mlflow) (4.0.12)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.11.1->mlflow) (3.23.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.59b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.11.1->mlflow) (0.59b0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.11.1->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.11.1->mlflow) (2.41.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (2026.2.25)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<1->mlflow-skinny==3.11.1->mlflow) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.11.1->mlflow) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (4.9.1)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from starlette>=0.46.0->fastapi<1->mlflow-skinny==3.11.1->mlflow) (4.13.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (0.6.3)
Requirement already satisfied: loguru in /usr/local/lib/python3.12/dist-packages (0.7.3)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.8.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)

In [1]:
import pandas as pd
import numpy as np
import ast
import numpy as np
import torch
import mmh3
from transformers import AutoTokenizer,DistilBertModel
import itertools
import pyarrow.parquet as pq
from torch.utils.data import DataLoader
from sklearn.preprocessing import StandardScaler
import mlflow
from modules.data_preparation import BERTCreationDataset, CreationDataset,CollateFunction,CollateFunctionInferenceRecipes,CollateFunctionInferenceUsers,BertCollateFunction
from modules.extraction import BERTEmbeddingsExtractor,EncodedHashedEmbeddings
from modules.inference import InferencePreprocessingRecipes,InferencePreprocessingUsers,RecipesRecommender
from modules.model import ContrastiveMSELoss,RecommendationModel,OptunaFunction,Test,Train
from modules.preprocessing import AfterSplitPreprocessingUsersFeatures,AfterSplitPreprocessingRecipesFeatures,BeforeSplitPreprocessingRecipesFeatures,BeforeSplitPreprocessingUsersFeatures,Scaler, ScalerInferenceRecipes, ScalerInferenceUsers,split_df
from modules.recipes_extraction import RecipesEmbeddingsExtractor,creation_recipes_set
from modules.utils import seed_worker,set_seed,load
import optuna
from loguru import logger
import gc
import os
import plotly.io as pio
import joblib
from mlflow.tracking import MlflowClient
pio.renderers.default = "vscode"
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

In [2]:
seed=42
set_seed(seed=seed)

In [3]:
mlflow.set_tracking_uri("file:./mlflow_runs/mlruns")
mlflow.set_experiment("Recipes_Recommendation_System_model_training")

c:\Users\sh032\anaconda3\Lib\site-packages\mlflow\tracking\_tracking_service\utils.py:184: FutureWarning:

The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.

<Experiment: artifact_location=('file:///C:/Users/sh032/OneDrive - HEC Montréal/Documents/Master 1/Recipe '
 'recommendation system/mlflow_runs/mlruns/896236271089450697'), creation_time=1776517499453, experiment_id='896236271089450697', last_update_time=1776517499453, lifecycle_stage='active', name='Recipes_Recommendation_System_model_training', tags={}, workspace='default'>

In [4]:
client=MlflowClient()

## Creation of the processed dataframe

In [3]:
interactions_train_df=pd.read_csv("data/interactions_train.csv")
PP_recipes_df=pd.read_csv("data/PP_recipes.csv")
PP_users_df=pd.read_csv("data/PP_users.csv")
RAW_interactions_df=pd.read_csv("data/RAW_interactions.csv")
RAW_recipes_df=pd.read_csv("data/RAW_recipes.csv")

In [4]:
interactions_train_df_filtered=interactions_train_df.sample(n=20000,replace=False,random_state=seed)

In [5]:
print(interactions_train_df_filtered.shape)

(20000, 6)

In [6]:
RAW_recipes_df.rename(columns={"id":"recipe_id"},inplace=True)
PP_recipes_df.rename(columns={"techniques":"techniques_recipes"},inplace=True)
PP_users_df.rename(columns={"techniques":"techniques_users"},inplace=True)

In [7]:
print("interactions_train_df_filtered columns:")
print(interactions_train_df_filtered.columns)
print("------------------------------------------------------------------")
print("PP_recipes_df columns:")
print(PP_recipes_df.columns)
print("-------------------------------------------------------------------")
print("PP_users_df columns:")
print(PP_users_df.columns)
print("----------------------------------------------------------------------")
print("RAW_interactions_df columns:")
print(RAW_interactions_df.columns)
print("------------------------------------------------------------------------")
print("RAW_recipes_df columns:")
print(RAW_recipes_df.columns)

interactions_train_df_filtered columns:
Index(['user_id', 'recipe_id', 'date', 'rating', 'u', 'i'], dtype='object')
------------------------------------------------------------------
PP_recipes_df columns:
Index(['id', 'i', 'name_tokens', 'ingredient_tokens', 'steps_tokens',
       'techniques_recipes', 'calorie_level', 'ingredient_ids'],
      dtype='object')
-------------------------------------------------------------------
PP_users_df columns:
Index(['u', 'techniques_users', 'items', 'n_items', 'ratings', 'n_ratings'], dtype='object')
----------------------------------------------------------------------
RAW_interactions_df columns:
Index(['user_id', 'recipe_id', 'date', 'rating', 'review'], dtype='object')
------------------------------------------------------------------------
RAW_recipes_df columns:
Index(['name', 'recipe_id', 'minutes', 'contributor_id', 'submitted', 'tags',
       'nutrition', 'n_steps', 'steps', 'description', 'ingredients',
       'n_ingredients'],
      dtype='object')

In [8]:
full_df=interactions_train_df_filtered.merge(PP_recipes_df,on="i",how="left",suffixes=(None,"_1")).merge(PP_users_df,on="u",how="left",suffixes=(None,"_2")).merge(RAW_interactions_df,on=["user_id","recipe_id"],how="left",suffixes=(None,"_3")).merge(RAW_recipes_df,on=["recipe_id"],how="left",suffixes=(None,"_3"))

In [9]:
full_df=full_df.drop(columns=["review",'rating_3',"id","ingredients","submitted","contributor_id","date_3","date","steps_tokens","ingredient_tokens","name_tokens","u"],axis=1)
full_df.to_parquet(path="./modules/dataframes/full_df.parquet")

In [10]:
full_parquet_file=pq.ParquetFile("./modules/dataframes/full_df.parquet")
full_df=load(full_parquet_file)

In [11]:
print(f"Columns of the full dataframe:")
print(full_df.columns)
print("----------------------------------------")
print(f"Shape of the full dataframe:")
print(full_df.shape)
print("----------------------------------------")
print(f"Columns of the filtered interaction dataframe:")
print(interactions_train_df_filtered.shape)
print("----------------------------------------")
print(f"Head of the full  dataframe:")
display(full_df.head())
print("----------------------------------------")
for col in full_df.columns:
    print(f"Unique values of {col} :")
    print(full_df[col].unique())
    print("----------------------------------------")
for col in full_df.columns:
    print(f"The type of {col} is")
    print(full_df[col].apply(type).unique())
    print("---------------------------------")

Columns of the full dataframe:
Index(['user_id', 'recipe_id', 'rating', 'i', 'techniques_recipes',
       'calorie_level', 'ingredient_ids', 'techniques_users', 'items',
       'n_items', 'ratings', 'n_ratings', 'name', 'minutes', 'tags',
       'nutrition', 'n_steps', 'steps', 'description', 'n_ingredients'],
      dtype='object')
----------------------------------------
Shape of the full dataframe:
(20000, 20)
----------------------------------------
Columns of the filtered interaction dataframe:
(20000, 6)
----------------------------------------
Head of the full  dataframe:

,user_id,recipe_id,rating,i,techniques_recipes,calorie_level,ingredient_ids,techniques_users,items,n_items,ratings,n_ratings,name,minutes,tags,nutrition,n_steps,steps,description,n_ingredients
0,231160,124810,5.0,170682,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,"[4574, 1910, 6906, 2499, 63, 332, 6270, 7470, ...","[3, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, ...","[8911, 20238, 117521, 79316, 154563, 34302, 17...",7,"[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]",7,huckleberry or blueberry coffee cake,75,"['time-to-make', 'course', 'main-ingredient', ...","[174.1, 4.0, 92.0, 8.0, 7.0, 3.0, 11.0]",11,['beat margarine and cream cheese at medium sp...,"cooking light published this in their book, fi...",10
1,142629,31342,5.0,120865,"[1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",1,"[1168, 1284, 8021, 2499, 330, 6270, 3217, 2318...","[6, 0, 0, 3, 1, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, ...","[122019, 150060, 117906, 82202, 119046, 141911...",10,"[4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 3.0, 5.0, 4.0, ...",10,blender quiche or whatever you have in your ...,65,"['weeknight', 'time-to-make', 'course', 'main-...","[308.4, 37.0, 8.0, 20.0, 21.0, 41.0, 3.0]",10,"['preheat oven to 350f', 'generously grease a ...",the great part is you can use whatever leftove...,12
2,822358,441841,4.0,23142,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,"[1648, 1706, 3347, 5298, 3044, 4623, 2148, 6270]","[1, 1, 0, 2, 3, 0, 0, 0, 1, 5, 0, 1, 0, 0, 0, ...","[29761, 87944, 72370, 139097, 39470, 37755, 23...",17,"[4.0, 5.0, 5.0, 5.0, 4.0, 4.0, 4.0, 5.0, 5.0, ...",17,sweet orange coleslaw,10,"['15-minutes-or-less', 'time-to-make', 'course...","[290.1, 21.0, 71.0, 14.0, 7.0, 8.0, 13.0]",6,"['chop the apples', 'in a small bowl mix the o...",this recipe came from one of my mom's cookbook...,8
3,655579,211110,4.0,156541,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,"[7031, 5006, 339, 3203, 5975, 6270, 590]","[10, 0, 0, 5, 11, 0, 0, 0, 0, 7, 1, 3, 0, 0, 1...","[34492, 71279, 73805, 68721, 114795, 35164, 33...",28,"[2.0, 3.0, 4.0, 2.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...",28,wilted greens with garlic and balsamic vinegar,15,"['15-minutes-or-less', 'time-to-make', 'course...","[77.5, 10.0, 5.0, 5.0, 2.0, 4.0, 1.0]",5,"['cut the greens into strips 1 inch wide', 'in...",this simple but delicious side dish can be mad...,7
4,35140,114469,5.0,30839,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",2,"[1240, 6270, 5006, 1257, 2683, 5168, 800, 2461...","[176, 4, 2, 55, 72, 0, 1, 7, 4, 141, 13, 15, 0...","[121722, 36691, 151293, 154016, 1205, 12802, 1...",364,"[5.0, 5.0, 0.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...",364,chicken in the limelight,75,"['time-to-make', 'course', 'main-ingredient', ...","[645.9, 69.0, 11.0, 22.0, 80.0, 54.0, 4.0]",8,"['preheat oven to 350', 'grate lime peel and s...",very tender chicken soaked with flavor,9

----------------------------------------
Unique values of user_id :
[231160 142629 822358 ... 241982 164867 137854]
----------------------------------------
Unique values of recipe_id :
[124810  31342 441841 ...  98278 274099 283283]
----------------------------------------
Unique values of rating :
[5. 4. 3. 2. 0. 1.]
----------------------------------------
Unique values of i :
[170682 120865  23142 ... 108495 128044  25867]
----------------------------------------
Unique values of techniques_recipes :
['[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'
 '[1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'
 '[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]'
 ...
 '[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]'
 '[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]'
 '[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]']
----------------------------------------
Unique values of calorie_level :
[0 1 2]
----------------------------------------
Unique values of ingredient_ids :
['[4574, 1910, 6906, 2499, 63, 332, 6270, 7470, 3819, 3497]'
 '[1168, 1284, 8021, 2499, 330, 6270, 3217, 2318, 2856, 4717, 5006, 5168]'
 '[1648, 1706, 3347, 5298, 3044, 4623, 2148, 6270]' ...
 '[1254, 1165, 2374, 3716, 222, 1168]'
 '[1786, 5319, 1252, 5006, 5010, 3203, 1257, 7233, 6212, 3399, 1511, 1563, 68, 5975, 553, 1706]'
 '[3244, 7821, 1527, 2010, 1119, 4884, 2809, 3406, 5058]']
----------------------------------------
Unique values of techniques_users :
['[3, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]'
 '[6, 0, 0, 3, 1, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 4, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 3, 0, 2]'
 '[1, 1, 0, 2, 3, 0, 0, 0, 1, 5, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 2, 1, 0, 1, 0, 0, 4, 1, 0, 0, 0, 0, 0, 4, 0, 1, 4, 1, 1, 0, 0, 1, 3, 3, 1, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 2, 1, 2]'
 ...
 '[6, 0, 0, 2, 3, 0, 0, 0, 0, 5, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 4, 0, 0, 2, 1, 0, 0, 0, 0, 1, 1, 0, 0, 3, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 1]'
 '[9, 0, 0, 3, 3, 0, 0, 1, 0, 5, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 2, 5, 1, 0, 0, 0, 6, 0, 1, 2, 0, 1, 0, 0, 0, 3, 2, 0, 0, 3, 1, 0, 1, 0, 0, 0, 3, 1, 2, 1, 3]'
 '[37, 3, 0, 16, 21, 0, 0, 1, 0, 20, 6, 2, 0, 0, 2, 0, 6, 0, 0, 4, 4, 4, 0, 2, 0, 0, 2, 4, 14, 3, 0, 0, 0, 28, 0, 4, 9, 4, 5, 0, 0, 3, 13, 5, 1, 1, 15, 1, 0, 1, 0, 1, 0, 3, 0, 2, 4, 4]']
----------------------------------------
Unique values of items :
['[8911, 20238, 117521, 79316, 154563, 34302, 170682]'
 '[122019, 150060, 117906, 82202, 119046, 141911, 171519, 120865, 71287, 171522]'
 '[29761, 87944, 72370, 139097, 39470, 37755, 23142, 71578, 77036, 137338, 161477, 153736, 40366, 83647, 168229, 16010, 59580]'
 ...
 '[156329, 47112, 9002, 48914, 82283, 44569, 12384, 107161, 81246, 37900]'
 '[164203, 21935, 116632, 93494, 93193, 34860, 2267, 121932, 23646, 97372, 3332, 99368, 158194, 18103, 92882, 162858, 89027, 89140]'
 '[162186, 151953, 91760, 83170, 51796, 39867, 151177, 168722, 95442, 46843, 173363, 61869, 1754, 15430, 85086, 71955, 126328, 139970, 22578, 170817, 40735, 78551, 82136, 155665, 50048, 112281, 4864, 139149, 94090, 44321, 19812, 21692, 52532, 74837, 24305, 17876, 51263, 93685, 11814, 47251, 72474, 1921, 178015, 157555, 138896, 55772, 14509, 174272, 84437, 156075, 83930, 90781, 110941, 159543, 61938, 89113, 71389, 65021, 71442, 130357, 28353, 113097, 114402, 109732, 140658, 141662, 13667]']
----------------------------------------
Unique values of n_items :
[   7   10   17   28  364  700 1125  423   13  174  394  443 1203 1263
   68  173  445    9  144  166  261  330 3465   56  188   22 2602  275
 1817  201  596   11   26   25  204   40 3656  322  416   36  637  283
    3  402  346   31 1112   50  211   20 1987  750  517   42  284    4
 4581 2024  813   66  153   32  218  351   67   14   16   48   47   71
   27  298  380  158   38   97 2232    5 1790 1302  171 2733  849  306
  910  635  232   57  125  269  398   65   84  292   79    8 6437 1667
   69   23  383   61  196   18   12  102  891   51  963    2 1138 2432
  580  547  907 2242   43  755  127   59 3338  122  980  167 1374  854
  428  296 1226  527  756  798  362  282  615  245   34  467 1697 1005
  785  236   63  395 1758  814   52  540  956  389 2798  277  117   44
  104 2011 1120 1679   33 1830  411 1477  896  529  522   19   81  746
   78   55  146  622  109  379  781  179 2457  195  657 1533   89  987
 1553  476   24 1212  592  293  256  181  308  118   30  231 1043  291
   41   15   80  684  752  161  189   29  365  252   35    6   58  357
  242  687  381  808  358 2046  121   90 1002  412  317 1592 1303  871
  914  128  151   37  709  185  738  305  278  607  216  399  274  328
  598  528  479 1253   85  234  107  129  338  968  112   21  734  142
  130  462 1386  132  869   73   99  662   76  224  766  260  180  281
  950  475  490   39 1308  564   86  749 1460  361   88  920  152  582
  229  302   72   93  183  698  647  255  427 1923  493  134  198   49
  431  336  663  106  140  149   74 2851  699  695  300  205  729 1265
  680  187  339  534   70  217   62   77  625  254  192  406  244  184
  199  633  488  378  793  250  376  515  168   96 1354  228   45   83
  212 1421  113  105  348  147 2377  110  550  100  141 1177  591 1319
  571  410  315 1363  900  156  583  384 1270  155  303  721  473   92
  353  354  454  557  177  116  424  111   60  324  226  239   54  541
 1839   82 1513  970  136  478  240   53  429  350  203  932  285  676
  138  979   46  143  289  131  491  120  455   94  552  163  148  145
  344  674 1118  235  135  457 1218  176  209   98  150  740  832  273
  495  200 1669  649  318  539  287  108  165  243  732  408  312  392
 1108  314  247  123  401  193  213  342  497  249   91  391 1594  265
   75 1147  352  329 1209  898  103  114  501  327  267  604  320  182
  507 1324  639   64  407  266  461  307  889  326  162  133  259  119
   95  701  206  169  405  271  279   87  263  386  251  191  486 1048
  304  418  115  126  686  373  223  690  340 1258  238  222  459  366
  888  918  237  137  241  286  221  413  175  426  297  164  280  301
  157  178  518  632  692  355  590  186  170  748  248  321  520  512
  290  310  257  335  268  368  101  893  219  566  693  124  367  214
  215  202  194  347  464  323  276  333  230  190  272  225  641  415
  393  313  483  396  258  299  139  159  154  471  207  294  220  227
  319  208]
----------------------------------------
Unique values of ratings :
['[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]'
 '[4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 3.0, 5.0, 4.0, 5.0]'
 '[4.0, 5.0, 5.0, 5.0, 4.0, 4.0, 4.0, 5.0, 5.0, 4.0, 4.0, 5.0, 4.0, 4.0, 4.0, 3.0, 4.0]'
 ...
 '[4.0, 3.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 2.0, 5.0]'
 '[5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 4.0, 4.0, 5.0, 5.0]'
 '[5.0, 4.0, 5.0, 5.0, 3.0, 4.0, 4.0, 3.0, 5.0, 5.0, 2.0, 4.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]']
----------------------------------------
Unique values of n_ratings :
[   7   10   17   28  364  700 1125  423   13  174  394  443 1203 1263
   68  173  445    9  144  166  261  330 3465   56  188   22 2602  275
 1817  201  596   11   26   25  204   40 3656  322  416   36  637  283
    3  402  346   31 1112   50  211   20 1987  750  517   42  284    4
 4581 2024  813   66  153   32  218  351   67   14   16   48   47   71
   27  298  380  158   38   97 2232    5 1790 1302  171 2733  849  306
  910  635  232   57  125  269  398   65   84  292   79    8 6437 1667
   69   23  383   61  196   18   12  102  891   51  963    2 1138 2432
  580  547  907 2242   43  755  127   59 3338  122  980  167 1374  854
  428  296 1226  527  756  798  362  282  615  245   34  467 1697 1005
  785  236   63  395 1758  814   52  540  956  389 2798  277  117   44
  104 2011 1120 1679   33 1830  411 1477  896  529  522   19   81  746
   78   55  146  622  109  379  781  179 2457  195  657 1533   89  987
 1553  476   24 1212  592  293  256  181  308  118   30  231 1043  291
   41   15   80  684  752  161  189   29  365  252   35    6   58  357
  242  687  381  808  358 2046  121   90 1002  412  317 1592 1303  871
  914  128  151   37  709  185  738  305  278  607  216  399  274  328
  598  528  479 1253   85  234  107  129  338  968  112   21  734  142
  130  462 1386  132  869   73   99  662   76  224  766  260  180  281
  950  475  490   39 1308  564   86  749 1460  361   88  920  152  582
  229  302   72   93  183  698  647  255  427 1923  493  134  198   49
  431  336  663  106  140  149   74 2851  699  695  300  205  729 1265
  680  187  339  534   70  217   62   77  625  254  192  406  244  184
  199  633  488  378  793  250  376  515  168   96 1354  228   45   83
  212 1421  113  105  348  147 2377  110  550  100  141 1177  591 1319
  571  410  315 1363  900  156  583  384 1270  155  303  721  473   92
  353  354  454  557  177  116  424  111   60  324  226  239   54  541
 1839   82 1513  970  136  478  240   53  429  350  203  932  285  676
  138  979   46  143  289  131  491  120  455   94  552  163  148  145
  344  674 1118  235  135  457 1218  176  209   98  150  740  832  273
  495  200 1669  649  318  539  287  108  165  243  732  408  312  392
 1108  314  247  123  401  193  213  342  497  249   91  391 1594  265
   75 1147  352  329 1209  898  103  114  501  327  267  604  320  182
  507 1324  639   64  407  266  461  307  889  326  162  133  259  119
   95  701  206  169  405  271  279   87  263  386  251  191  486 1048
  304  418  115  126  686  373  223  690  340 1258  238  222  459  366
  888  918  237  137  241  286  221  413  175  426  297  164  280  301
  157  178  518  632  692  355  590  186  170  748  248  321  520  512
  290  310  257  335  268  368  101  893  219  566  693  124  367  214
  215  202  194  347  464  323  276  333  230  190  272  225  641  415
  393  313  483  396  258  299  139  159  154  471  207  294  220  227
  319  208]
----------------------------------------
Unique values of name :
['huckleberry   or blueberry  coffee cake'
 'blender quiche   or whatever you have in your kitchen leftover'
 'sweet orange coleslaw' ... 'asparagus chicken with hollandaise sauce'
 'caribbean chicken and black beans' 'fragrant orange curry']
----------------------------------------
Unique values of minutes :
[   75    65    10    15     4    31    35    25    33   250    55    17
    18    40    22    20     0    30    19     5    90    45    23    89
    79    50    80    60   190    70   385   490    13     2  1920    38
   150   380   300   485   105    81   135    44    85    32   160   140
   610    95    28   310    27     8   195   130  1680   280   155   330
   505    16     3   120   370    51    52   245    42   125    49   560
   110   165   495   200     6   375    21    57    12     7   500   615
    53   430    68   205   285  1500   805    39   325   510  1490    24
   180    54     9  1475   365   305   100 10095   435   175   315   270
   243     1    34   260  2895    26    36   240   750   187    46   745
   210    62    43    76   420   405   360   555  1480   390   185    29
    11   145  1440  1455  5760    97   545   232   440   147    47    74
    58   550  2900    48   230  1620   480    41  1470   182  1460  1380
    14   680    37   675   520  1445   605   115   252   132  1800  1443
   248   218   400   255   235   425    72   530   602   620  2190   265
   492  1442   275  1080   770    88   486   107   225    83   184   487
   138   124  1450   112  1456 10090   320   170    67   740   126   103
   215   790  1200  2925  1485   167  2910  1580   780    77   525   730
   640   314   900   915    63   144    71    56  4350   735   223   153
   765   246   515 21615   570   308   214  1452   395    93   630  7210
   106   372   381   220   335  1090   301    64   104   128   600  2760
   143   660    59    78   249   725   188   840  1540  5820    66   608
  1465   482    84   720   645   800   616  2905   307   481 15860    99
   588  1515   109   158   625    94 10320  9740   290   410    87  2885
   825   795  1530   363   760  1020    73  4330   445 10080   970   540
    98    61  1520]
----------------------------------------
Unique values of tags :
["['time-to-make', 'course', 'main-ingredient', 'preparation', 'occasion', 'breads', 'breakfast', 'fruit', 'oven', 'easy', 'coffee-cakes', 'dietary', 'berries', 'blueberries', 'brunch', 'equipment', '4-hours-or-less']"
 "['weeknight', 'time-to-make', 'course', 'main-ingredient', 'cuisine', 'preparation', 'occasion', 'north-american', 'lunch', 'main-dish', 'eggs-dairy', 'pork', 'poultry', 'vegetables', 'american', 'oven', 'cheese', 'eggs', 'chicken', 'food-processor-blender', 'dietary', 'oamc-freezer-make-ahead', 'meat', 'equipment', 'small-appliance', 'number-of-servings', '4-hours-or-less']"
 "['15-minutes-or-less', 'time-to-make', 'course', 'main-ingredient', 'preparation', 'low-protein', 'salads', 'fruit', 'vegetables', 'easy', 'dietary', 'low-cholesterol', 'low-saturated-fat', 'healthy-2', 'low-in-something', 'apples', 'greens']"
 ...
 "['60-minutes-or-less', 'time-to-make', 'course', 'main-ingredient', 'preparation', 'main-dish', 'poultry', 'vegetables', 'easy', 'chicken', 'dietary', 'meat', 'chicken-breasts', 'asparagus']"
 "['60-minutes-or-less', 'time-to-make', 'main-ingredient', 'cuisine', 'preparation', 'north-american', 'beans', 'poultry', 'caribbean', 'central-american', 'chicken', 'stove-top', 'black-beans', 'meat', 'chicken-breasts', 'equipment']"
 "['30-minutes-or-less', 'time-to-make', 'course', 'main-ingredient', 'cuisine', 'preparation', 'occasion', 'appetizers', 'soups-stews', 'fruit', 'asian', 'middle-eastern', 'easy', 'dinner-party', 'vegetarian', 'dietary', 'citrus', 'oranges', 'taste-mood', 'savory', '3-steps-or-less']"]
----------------------------------------
Unique values of nutrition :
['[174.1, 4.0, 92.0, 8.0, 7.0, 3.0, 11.0]'
 '[308.4, 37.0, 8.0, 20.0, 21.0, 41.0, 3.0]'
 '[290.1, 21.0, 71.0, 14.0, 7.0, 8.0, 13.0]' ...
 '[287.0, 19.0, 4.0, 13.0, 67.0, 33.0, 1.0]'
 '[381.3, 6.0, 11.0, 13.0, 55.0, 4.0, 17.0]'
 '[94.4, 3.0, 55.0, 0.0, 2.0, 6.0, 5.0]']
----------------------------------------
Unique values of n_steps :
[11 10  6  5  8  7  9  4 13  3 20 12 14 16 15 19 18 17 21 22 26 24 28 30
 23 27 29]
----------------------------------------
Unique values of steps :
["['beat margarine and cream cheese at medium speed of an electric mixer until creamy', 'gradually 1 cup sugar , beating well', 'add egg , and beat well', 'combine flour , baking powder , and salt', 'stir into margarine mixture', 'stir in vanilla , then fold in berries', 'pour batter into a 9-inch round cake pan coated with cooking spray', 'combine 2 tablespoons sugar and cinnamon', 'sprinkle over batter', 'bake at 350f for 1 hour', 'cool on a wire rack']"
 "['preheat oven to 350f', 'generously grease a 9 inch pie pan', 'spread shredded cheese across bottom of pie pan', 'cover cheese with meat and vegetables', 'in a blender , combine eggs , baking mix , salt , garlic powder , onions , parsley , and milk', 'blend until smooth , then add olive oil', 'blend until combined , then pour mixture over meat and vegetable layer', 'sprinkle with paprika', 'bake in preheated oven for 40 minutes', 'cool 10 minutes before serving']"
 "['chop the apples', 'in a small bowl mix the orange juice concentate , mayo , dijon , and salt', 'in a large serving bowl toss the coleslaw mix , rice , and apples', 'mix the dressing with the slaw until well coated', 'stir in the pecans', 'chill before serving']"
 ...
 "['to marinate: place chicken in a nonporous glass dish or bowl', 'pour wine over chicken , then sprinkle with tarragon', 'cover dish and refrigerate to marinate for 2 hours', 'preheat oven to broil', 'remove chicken from dish or bowl discarding remaining marinade and broil for 25 minutes or until cooked through and juices run clear', 'meanwhile , steam asparagus to desired degree of doneness', 'prepare hollandaise sauce according to package directions', 'when chicken is cooked , arrange the breasts on a platter , place 4 spears of asparagus on each chicken breast and dribble with prepared hollandaise sauce to taste', 'sprinkle with cheese and serve']"
 "['coat a skillet with nonstick cooking spray', 'sprinkle pepper on chicken and cook in skillet over medium heat for 3-5 minutes , so that the surfaces have a nice brown color and are no longer opaque', 'remove the chicken to a plate and return the pan to heat', 'in the same skillet , heat olive oil', 'add onion', 'if the pan become dry , add 2 tablespoons of broth to skillet', 'cook for 5-6 minutes or until onion is soft , stirring frequently', 'in the last minute of cooking , add the garlic', 'add tomato sauce , remaining broth and rum to skillet and mix well', 'add green and / or red pepper , reserved chicken and seasonings', 'bring to a boil', 'reduce heat and simmer , uncovered , 15 min or until chicken is tender and liquid has thickened', 'stir in beans and heat another 2-3 minutes place rice on large platter and top with chicken and bean mix']"
 "['heat ghee or butter in a medium pot over low heat', 'add spices and stir until fragrant', 'stir in orange juice and cook slowly for 15 to 20 minutes', 'serve hot , in small bowls or cups , with or without spoons']"]
----------------------------------------
Unique values of description :
['cooking light published this in their book, five star recipes--the best of 10 years, and their staff voted this as one of their top five recipes from the first 10 years. it is very, very good, either for breakfast, brunch, or as dessert, warm out of the oven with a scoop of vanilla ice cream.'
 'the great part is you can use whatever leftovers (well...almost) you have on hand. this dish can be served hot or cold. freezes very well! use any cheese of your choice.'
 'this recipe came from one of my mom\'s cookbooks called "quilter\'s cooking companion".  it\'s easy to make and has great texture and flavor!'
 ...
 "this recipe came from another recipe site. it is mouthwatering delicious. beautiful presentation. simple, simple, simple to make. originally found the recipe in february and just got around to making it. i'm sorry i lost all of that time eating it! i'll make up for it now. cook time does not include 2 hours for marinating."
 'originally from shape magazine and adapted to suit my tastes and simplify the preparation. this is healthy and comforting with a pleasing, but approachable combination of spices that even picky eaters will enjoy. though full of flavor this is not spicy hot, so feel free to adjust to your own tastes. a word of caution, this makes 6 perfect portions for my weight watching lifestyle but if you have hungry eaters at your table, it may only serve 4 or 5.'

In [12]:
PP_users_df["len_items"]=PP_users_df["items"].str.count(r",")+1
PP_recipes_df["len_ingredients"]=PP_recipes_df["ingredient_ids"].str.count(r",")+1
max_len_ingredients=PP_recipes_df["len_ingredients"].max()
max_len_items=PP_users_df["len_items"].max()
PP_users_df.drop(columns=["len_items"],inplace=True)
PP_recipes_df.drop(columns=["len_ingredients"],inplace=True)

In [13]:
before_split_users_processor=BeforeSplitPreprocessingUsersFeatures(full_df,max_len_items=max_len_items)
full_df_processed=before_split_users_processor.preprocessing()

In [14]:
before_split_recipes_processor=BeforeSplitPreprocessingRecipesFeatures(full_df_processed,max_len_ingredients=max_len_ingredients)
full_df_processed=before_split_recipes_processor.preprocessing()

In [15]:
full_df_processed["rating_scaled"]=full_df_processed["rating"]/5
full_df_processed["ratings_scaled"]=full_df_processed["ratings"].apply(lambda x: list(map(lambda x: x/5,x)))

In [16]:
PP_recipes_df["ingredient_ids_transformed"]=PP_recipes_df["ingredient_ids"].apply(lambda x: list(map(lambda x: int(x)+1,ast.literal_eval(x))))
all_ingredient_ids=np.unique(list(itertools.chain.from_iterable(list(PP_recipes_df["ingredient_ids_transformed"]))))
ingredient_continuous_ids=pd.Series([i for i in range(1,len(all_ingredient_ids)+1)],index=list(np.sort(all_ingredient_ids)))

In [20]:
def mapping_list(x:list,mapping_serie:pd.Series):
    return [mapping_serie.loc[i] if i in mapping_serie.index else 0 for i in x]

In [21]:
full_df_processed["ingredient_ids_continuous"]=full_df_processed["ingredient_ids"].apply(lambda x : mapping_list(x,ingredient_continuous_ids))

In [22]:
full_df_processed["full_text"]=full_df_processed["name"]+" [SEP] "+full_df_processed["description"]+" [SEP] "+full_df_processed["steps"]+" [SEP] "+full_df_processed["tags"]

In [ ]:
#full_df_processed.to_parquet(path="./modules/dataframes/full_df_processed.parquet")

In [ ]:
#full_processed_parquet_file = pq.ParquetFile("./modules/dataframes/full_df_processed.parquet")
#full_df_processed=load(full_processed_parquet_file)

In [ ]:
#df_text=full_df_processed["full_text"]

In [ ]:
#distilbert_model=DistilBertModel.from_pretrained("distilbert-base-uncased")
#tokenizer=AutoTokenizer.from_pretrained("distilbert-base-uncased")

In [ ]:
#bert_dataset=BERTCreationDataset(df_text)

In [ ]:
#generator=torch.Generator()
#generator.manual_seed(seed)
#bert_collate_function_object=BertCollateFunction(tokenizer=tokenizer)
#bert_dataloader=DataLoader(dataset=bert_dataset,batch_size=32,shuffle=False,collate_fn=bert_collate_function_object.collate_fn,worker_init_fn=seed_worker,generator=generator)

In [ ]:
#device = (torch.device("mps") if torch.backends.mps.is_available() else torch.device("cuda" if torch.cuda.is_available() else "cpu"))
#bert_extractor=BERTEmbeddingsExtractor(bert_model=distilbert_model,device=device)
#bert_extractor.get_bert_embeddings(dataloader=bert_dataloader,path="./modules/BERT_embeddings")

In [23]:
all_cls_embeddings=torch.load("./modules/BERT_embeddings/all_cls_embeddings.pt")
all_mean_embeddings=torch.load("./modules/BERT_embeddings/all_mean_embeddings.pt")
print(all_cls_embeddings.shape)
print(all_mean_embeddings.shape)

torch.Size([20000, 768])
torch.Size([20000, 768])

In [24]:
train_df,val_df,test_df,train_cls_embeddings,val_cls_embeddings,test_cls_embeddings,train_mean_embeddings,val_mean_embeddings,test_mean_embeddings=split_df(full_df_processed,cls_embeddings=all_cls_embeddings,mean_embeddings=all_mean_embeddings,random_state=seed)

In [25]:
after_split_preprocessor_users=AfterSplitPreprocessingUsersFeatures(train_df)
train_df_processed=after_split_preprocessor_users.preprocessing(train_df)
val_df_processed=after_split_preprocessor_users.preprocessing(val_df)
test_df_processed=after_split_preprocessor_users.preprocessing(test_df)

In [26]:
after_split_preprocessor_recipes=AfterSplitPreprocessingRecipesFeatures(train_df)
train_df_processed=after_split_preprocessor_recipes.preprocessing(train_df_processed)
val_df_processed=after_split_preprocessor_recipes.preprocessing(val_df_processed)
test_df_processed=after_split_preprocessor_recipes.preprocessing(test_df_processed)

In [27]:
scaler_users=StandardScaler()
scaler_recipes=StandardScaler()
scale_processor=Scaler(scaler_users,scaler_recipes)
train_df_processed,val_df_processed,test_df_processed=scale_processor.scale(train_df_processed,val_df_processed,test_df_processed)

In [28]:
joblib.dump(scale_processor.scaler_users, "./modules/scalers/scaler_users.pkl")
joblib.dump(scale_processor.scaler_recipes, "./modules/scalers/scaler_recipes.pkl")

['./modules/scalers/scaler_recipes.pkl']

In [29]:
scaler_users=joblib.load("./modules/scalers/scaler_users.pkl")
scaler_recipes=joblib.load("./modules/scalers/scaler_recipes.pkl")

In [30]:
train_df.to_parquet(path="./modules/dataframes/train_df.parquet")

train_df_processed.to_parquet(path="./modules/dataframes/train_df_processed.parquet")
val_df_processed.to_parquet(path="./modules/dataframes/val_df_processed.parquet")
test_df_processed.to_parquet(path="./modules/dataframes/test_df_processed.parquet")

torch.save(train_cls_embeddings,f"./modules/BERT_embeddings/train_cls_embeddings.pt")
torch.save(val_cls_embeddings,f"./modules/BERT_embeddings/val_cls_embeddings.pt")
torch.save(test_cls_embeddings,f"./modules/BERT_embeddings/test_cls_embeddings.pt")

torch.save(train_mean_embeddings,f"./modules/BERT_embeddings/train_mean_embeddings.pt")
torch.save(val_mean_embeddings,f"./modules/BERT_embeddings/val_mean_embeddings.pt")
torch.save(test_mean_embeddings,f"./modules/BERT_embeddings/test_mean_embeddings.pt")

## Load of the dataframes

In [5]:
PP_recipes_df=pd.read_csv("data/PP_recipes.csv")
PP_users_df=pd.read_csv("data/PP_users.csv")

full_parquet_file=pq.ParquetFile("./modules/dataframes/full_df.parquet")
full_processed_parquet_file=pq.ParquetFile("./modules/dataframes/full_df_processed.parquet")
train_parquet_file=pq.ParquetFile("./modules/dataframes/train_df.parquet")
train_processed_parquet_file = pq.ParquetFile("./modules/dataframes/train_df_processed.parquet")
val_processed_parquet_file= pq.ParquetFile("./modules/dataframes/val_df_processed.parquet")
test_processed_parquet_file= pq.ParquetFile("./modules/dataframes/test_df_processed.parquet")

full_df=load(full_parquet_file)
full_df_processed=load(full_processed_parquet_file)
train_df=load(train_parquet_file)
train_df_processed =load(train_processed_parquet_file)
val_df_processed=load(val_processed_parquet_file)
test_df_processed=load(test_processed_parquet_file)

train_cls_embeddings=torch.load(f"./modules/BERT_embeddings/train_cls_embeddings.pt")
val_cls_embeddings=torch.load(f"./modules/BERT_embeddings/val_cls_embeddings.pt")
test_cls_embeddings=torch.load(f"./modules/BERT_embeddings/test_cls_embeddings.pt")

train_mean_embeddings=torch.load(f"./modules/BERT_embeddings/train_mean_embeddings.pt")
val_mean_embeddings=torch.load(f"./modules/BERT_embeddings/val_mean_embeddings.pt")
test_mean_embeddings=torch.load(f"./modules/BERT_embeddings/test_mean_embeddings.pt")

all_cls_embeddings=torch.load("./modules/BERT_embeddings/all_cls_embeddings.pt")
all_mean_embeddings=torch.load("./modules/BERT_embeddings/all_mean_embeddings.pt")

In [8]:
print(f"Columns of the full processed dataframe:")
print(train_df_processed.columns)
print("----------------------------------------")
print(f"Shape of the full processed dataframe:")
print(train_df_processed.shape)
print("----------------------------------------")
print(f"Head of the full  processed dataframe:")
display(train_df_processed.head())
print("----------------------------------------")
for col in train_df_processed.columns:
    print(f"Exemple of {col} :")
    print(train_df_processed.iloc[0][col])
    print("----------------------------------------")
for col in train_df_processed.columns:
    print(f"The type of {col} is")
    print(train_df_processed[col].apply(type).unique())
    print("---------------------------------")

Columns of the full processed dataframe:
Index(['user_id', 'recipe_id', 'rating', 'i', 'techniques_recipes',
       'calorie_level', 'ingredient_ids', 'techniques_users', 'items',
       'n_items', 'ratings', 'n_ratings', 'name', 'minutes', 'tags',
       'nutrition', 'n_steps', 'steps', 'description', 'n_ingredients',
       'rating_scaled', 'ratings_scaled', 'ingredient_ids_continuous',
       'full_text', 'n_items_scaled', 'n_ratings_scaled',
       'calorie_level_scaled', 'minutes_scaled', 'n_steps_scaled',
       'n_ingredients_scaled'],
      dtype='object')
----------------------------------------
Shape of the full processed dataframe:
(14000, 30)
----------------------------------------
Head of the full  processed dataframe:

,user_id,recipe_id,rating,i,techniques_recipes,calorie_level,ingredient_ids,techniques_users,items,n_items,...,rating_scaled,ratings_scaled,ingredient_ids_continuous,full_text,n_items_scaled,n_ratings_scaled,calorie_level_scaled,minutes_scaled,n_steps_scaled,n_ingredients_scaled
0,175728,11770,5,109126,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,"[4624, 6655, 217, 6927, 6336, 4864, 0, 0, 0, 0...","[87, 2, 0, 27, 42, 1, 1, 7, 0, 80, 3, 3, 1, 0,...","[154350, 54820, 77571, 45268, 124558, 38966, 1...",202,...,1.0,"[1.0, 1.0, 0.8, 1.0, 0.8, 1.0, 0.8, 0.6, 0.8, ...","[4609, 6629, 215, 6900, 6313, 4847, 0, 0, 0, 0...",walnut brewery asiago cheese dip [SEP] this a ...,-0.386555,-0.386555,-1.086207,-0.156327,0.050739,-0.923525
1,50510,350360,4,53777,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",2,"[5314, 5007, 3204, 5011, 7214, 589, 2595, 2857...","[127, 1, 2, 91, 191, 0, 0, 14, 3, 176, 10, 12,...","[59108, 117303, 16669, 165155, 78915, 115100, ...",580,...,0.8,"[0.8, 1.0, 1.0, 0.8, 1.0, 0.8, 0.8, 1.0, 1.0, ...","[5295, 4990, 3195, 4994, 7187, 586, 2588, 2849...",nif s penne with feta [SEP] a delicious and fr...,0.004451,0.004451,1.461012,-0.142037,-0.715266,0.643517
2,9749,13099,4,13490,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,"[151, 1125, 5299, 1910, 4764, 156, 6907, 6277,...","[44, 1, 1, 23, 33, 0, 1, 5, 2, 35, 10, 5, 0, 0...","[75852, 104812, 129769, 99788, 101820, 166815,...",144,...,0.8,"[0.8, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 1.0, ...","[149, 1119, 5281, 1903, 4748, 154, 6880, 6254,...",mom s waldorf salad [SEP] this is my mother's ...,-0.446551,-0.446551,0.187403,-0.184908,-0.970601,-0.296708
3,161283,56695,0,115884,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,"[2731, 3485, 2405, 2500, 6271, 3487, 64, 4054,...","[33, 1, 0, 10, 12, 0, 0, 5, 0, 30, 6, 3, 0, 0,...","[130597, 16122, 49703, 152649, 103416, 36541, ...",92,...,0.0,"[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...","[2723, 3476, 2398, 2493, 6248, 3478, 63, 4041,...",the very best salisbury steak [SEP] this is ou...,-0.500340,-0.500340,0.187403,-0.099165,-0.204596,0.643517
4,463436,286054,4,60799,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,"[4718, 7999, 3045, 3830, 0, 0, 0, 0, 0, 0, 0, ...","[111, 1, 2, 69, 82, 0, 1, 9, 1, 114, 17, 20, 1...","[32365, 145711, 157654, 141020, 35883, 67138, ...",395,...,0.8,"[1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 1.0, 1.0, 1.0, ...","[4702, 7969, 3036, 3820, 0, 0, 0, 0, 0, 0, 0, ...",o j yogurt shake [SEP] this is a yummy and ...,-0.186914,-0.186914,-1.086207,-0.227780,-0.970601,-1.550341

----------------------------------------
Exemple of user_id :
175728
----------------------------------------
Exemple of recipe_id :
11770
----------------------------------------
Exemple of rating :
5
----------------------------------------
Exemple of i :
109126
----------------------------------------
Exemple of techniques_recipes :
[1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
----------------------------------------
Exemple of calorie_level :
0
----------------------------------------
Exemple of ingredient_ids :
[4624 6655  217 6927 6336 4864    0    0    0    0    0    0    0    0
    0    0    0    0    0    0]
----------------------------------------
Exemple of techniques_users :
[87  2  0 27 42  1  1  7  0 80  3  3  1  0  3  0 40  0  0  5 20  8  2  8
  9  0  4  4 43  4  1  1  1 58  0  3 19  6 14  1  1  6 29 35  5  1 20  3
  0  5  2  3  0 18  5 18 10 20]
----------------------------------------
Exemple of items :
[154350  54820  77571 ...      0      0      0]
----------------------------------------
Exemple of n_items :
202
----------------------------------------
Exemple of ratings :
[5 5 4 ... 0 0 0]
----------------------------------------
Exemple of n_ratings :
202
----------------------------------------
Exemple of name :
walnut brewery asiago cheese dip
----------------------------------------
Exemple of minutes :
30
----------------------------------------
Exemple of tags :
30 minutes or less [SEP] time to make [SEP] course [SEP] main ingredient [SEP] cuisine [SEP] preparation [SEP] occasion [SEP] north american [SEP] appetizers [SEP] eggs dairy [SEP] american [SEP] oven [SEP] dips [SEP] dietary [SEP] copycat [SEP] novelty [SEP] equipment [SEP] number of servings
----------------------------------------
Exemple of nutrition :
[163.5  23.   18.    6.    5.   44.    1. ]
----------------------------------------
Exemple of n_steps :
9
----------------------------------------
Exemple of steps :
reconstitute sun-dried tomatoes in hot water [SEP] clean , rinse and slice green onions and mushrooms [SEP] squeeze all the water out of the tomatoes , then julieene into fine strips [SEP] combine all ingredients except tomatoes , then add the sun-dried toimatoes [SEP] place into an oven-proof container [SEP] top with remaining 1 t [SEP] of asiago cheese [SEP] bake at 350 for about 15 minutes or until bubbly [SEP] serve immediately with toasted beer bread
----------------------------------------
Exemple of description :
this a copycat recipe from the walnut brewery in littleton colorado. it's really good on baked spuds.
----------------------------------------
Exemple of n_ingredients :
6
----------------------------------------
Exemple of rating_scaled :
1.0
----------------------------------------
Exemple of ratings_scaled :
[1.  1.  0.8 ... 0.  0.  0. ]
----------------------------------------
Exemple of ingredient_ids_continuous :
[4609 6629  215 6900 6313 4847    0    0    0    0    0    0    0    0
    0    0    0    0    0    0]
----------------------------------------
Exemple of full_text :
walnut brewery asiago cheese dip [SEP] this a copycat recipe from the walnut brewery in littleton colorado. it's really good on baked spuds. [SEP] reconstitute sun-dried tomatoes in hot water [SEP] clean , rinse and slice green onions and mushrooms [SEP] squeeze all the water out of the tomatoes , then julieene into fine strips [SEP] combine all ingredients except tomatoes , then add the sun-dried toimatoes [SEP] place into an oven-proof container [SEP] top with remaining 1 t [SEP] of asiago cheese [SEP] bake at 350 for about 15 minutes or until bubbly [SEP] serve immediately with toasted beer bread [SEP] 30 minutes or less [SEP] time to make [SEP] course [SEP] main ingredient [SEP] cuisine [SEP] preparation [SEP] occasion [SEP] north american [SEP] appetizers [SEP] eggs dairy [SEP] american [SEP] oven [SEP] dips [SEP] dietary [SEP] copycat [SEP] novelty [SEP] equipment [SEP] number of servings
----------------------------------------
Exemple of n_items_scaled :
-0.38655530277588895
----------------------------------------
Exemple of n_ratings_scaled :
-0.38655530277588895
----------------------------------------
Exemple of calorie_level_scaled :
-1.0862070718545758
----------------------------------------
Exemple of minutes_scaled :
-0.15632717377028346
----------------------------------------
Exemple of n_steps_scaled :
0.05073871781348626
----------------------------------------
Exemple of n_ingredients_scaled :
-0.9235247200060333
----------------------------------------
The type of user_id is
[<class 'int'>]
---------------------------------
The type of recipe_id is
[<class 'int'>]
---------------------------------
The type of rating is
[<class 'int'>]
---------------------------------
The type of i is
[<class 'int'>]
---------------------------------
The type of techniques_recipes is
[<class 'numpy.ndarray'>]
---------------------------------
The type of calorie_level is
[<class 'int'>]
---------------------------------
The type of ingredient_ids is
[<class 'numpy.ndarray'>]
---------------------------------
The type of techniques_users is
[<class 'numpy.ndarray'>]
---------------------------------
The type of items is
[<class 'numpy.ndarray'>]
---------------------------------
The type of n_items is
[<class 'int'>]
---------------------------------
The type of ratings is
[<class 'numpy.ndarray'>]
---------------------------------
The type of n_ratings is
[<class 'int'>]
---------------------------------
The type of name is
[<class 'str'>]
---------------------------------
The type of minutes is
[<class 'int'>]
---------------------------------
The type of tags is
[<class 'str'>]
---------------------------------
The type of nutrition is
[<class 'numpy.ndarray'>]
---------------------------------
The type of n_steps is
[<class 'int'>]
---------------------------------
The type of steps is
[<class 'str'>]
---------------------------------
The type of description is
[<class 'str'>]
---------------------------------
The type of n_ingredients is
[<class 'int'>]
---------------------------------
The type of rating_scaled is
[<class 'float'>]
---------------------------------
The type of ratings_scaled is
[<class 'numpy.ndarray'>]
---------------------------------
The type of ingredient_ids_continuous is
[<class 'numpy.ndarray'>]
---------------------------------
The type of full_text is
[<class 'str'>]
---------------------------------
The type of n_items_scaled is
[<class 'float'>]
---------------------------------
The type of n_ratings_scaled is
[<class 'float'>]
---------------------------------
The type of calorie_level_scaled is
[<class 'float'>]
---------------------------------
The type of minutes_scaled is
[<class 'float'>]
---------------------------------
The type of n_steps_scaled is
[<class 'float'>]
---------------------------------
The type of n_ingredients_scaled is
[<class 'float'>]
---------------------------------

## Model

In [9]:
train_dataset=CreationDataset(train_df_processed,cls_embeddings=train_cls_embeddings,mean_embeddings=train_mean_embeddings)
val_dataset=CreationDataset(val_df_processed,cls_embeddings=val_cls_embeddings,mean_embeddings=val_mean_embeddings)

In [10]:
train_dataset.__getitem__(10)

{'user_id': np.int64(440300),
 'recipe_id': np.int64(5013),
 'rating': np.int64(5),
 'i': np.int64(109198),
 'techniques_recipes': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 'calorie_level': np.int64(1),
 'ingredient_ids': array([  64, 5007, 2500, 7169, 7656, 7957, 6907,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32),
 'techniques_users': array([5, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0, 1, 1, 2,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2]),
 'items': array([ 18676,  75351, 109198, ...,      0,      0,      0], dtype=int32),
 'n_items': np.int64(10),
 'ratings': array([2, 5, 5, ..., 0, 0, 0], dtype=int32),
 'n_ratings': np.int64(10),
 'name': 'chicago style deep dish pizza crust',
 'minutes': np.int64(0),
 'tags': '15 minutes or less [SEP] time to make [SEP] course [SEP] cuisine [SEP] preparation [SEP] occasion [SEP] north american [SEP] healthy [SEP] breads [SEP] main dish [SEP] american [SEP] kid friendly [SEP] pizza [SEP] dietary [SEP] low sodium [SEP] low saturated fat [SEP] midwestern [SEP] yeast [SEP] low in something',
 'nutrition': array([300.8,  10. ,   6. ,   1. ,  18. ,   6. ,  16. ]),
 'n_steps': np.int64(10),
 'steps': 'whisk together water , yeast and sugar in a bowl and set aside to proof for 10 minutes [SEP] in a large bowl sift together flour and salt and sprinkle in thyme [SEP] mix eggs into yeast mixture [SEP] pour liquid into dry ingredients and mix until a soft sticky dough forms [SEP] remove dough to a lightly floured surface and knead 5 minutes , until dough is no longer sticky [SEP] place in a well oiled bowl , turning to coat all sides , cover and allow to rise until doubled in bulk 2 - 3 hours [SEP] punch dough down and place into a well oiled 12" pizza pan [SEP] using your hands , move dough around the bottom of the pan and 2 / 3 the way up the sides [SEP] set aside and let rise 10 minutes [SEP] brush crust lightly with olive oil and add toppings',
 'description': 'missing description',
 'n_ingredients': np.int64(7),
 'rating_scaled': np.float64(1.0),
 'ratings_scaled': array([0.4, 1. , 1. , ..., 0. , 0. , 0. ]),
 'ingredient_ids_continuous': array([  63, 4990, 2493, 7142, 7628, 7927, 6880,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0]),
 'full_text': 'chicago style deep dish pizza crust [SEP] missing description [SEP] whisk together water , yeast and sugar in a bowl and set aside to proof for 10 minutes [SEP] in a large bowl sift together flour and salt and sprinkle in thyme [SEP] mix eggs into yeast mixture [SEP] pour liquid into dry ingredients and mix until a soft sticky dough forms [SEP] remove dough to a lightly floured surface and knead 5 minutes , until dough is no longer sticky [SEP] place in a well oiled bowl , turning to coat all sides , cover and allow to rise until doubled in bulk 2 - 3 hours [SEP] punch dough down and place into a well oiled 12" pizza pan [SEP] using your hands , move dough around the bottom of the pan and 2 / 3 the way up the sides [SEP] set aside and let rise 10 minutes [SEP] brush crust lightly with olive oil and add toppings [SEP] 15 minutes or less [SEP] time to make [SEP] course [SEP] cuisine [SEP] preparation [SEP] occasion [SEP] north american [SEP] healthy [SEP] breads [SEP] main dish [SEP] american [SEP] kid friendly [SEP] pizza [SEP] dietary [SEP] low sodium [SEP] low saturated fat [SEP] midwestern [SEP] yeast [SEP] low in something',
 'n_items_scaled': np.float64(-0.5851617088561376),
 'n_ratings_scaled': np.float64(-0.5851617088561376),
 'calorie_level_scaled': np.float64(0.18740256013571407),
 'minutes_scaled': np.float64(-0.24207057982625665),
 'n_steps_scaled': np.float64(0.30607374635008233),
 'n_ingredients_scaled': np.float64(-0.6101164182635486),
 'cls_embeddings': tensor([-4.3926e-01, -8.0494e-02,  1.5189e-01, -9.7821e-02,  2.1476e-02,
         -9.6848e-02,  1.1897e-01,  2.9560e-01, -1.8832e-01, -2.4743e-01,
         -7.7781e-02, -3.0157e-02,  2.3765e-02,  2.2340e-01, -1.6420e-01,
          3.8480e-02,  1.2496e-01,  1.8147e-01,  1.5513e-01, -7.9278e-03,
         -9.4934e-02, -5.6202e-01,  5.7085e-02, -7.7405e-02, -4.0344e-03,
         -5.1196e-02, -1.5435e-01, -7.4455e-02,  6.3317e-02, -2.2641e-02,
         -7.6512e-03,  2.2540e-01,  5.2787e-02, -3.8075e-01,  3.3826e-01,
         -7.0280e-03,  4.1102e-01,  9.6607e-02,  6.5771e-02, -9.7780e-02,
         -3.7799e-02,  1.6033e-01,  4.1844e-01, -2.9992e-01, -1.0954e-02,
          3.6213e-02, -2.3884e+00, -4.2031e-02, -4.0388e-01, -2.9736e-01,
          1.8779e-01, -9.4406e-02,  6.0406e-02,  1.4631e-01,  1.6248e-01,
          2.8919e-01, -2.5865e-01,  5.9218e-01,  7.5641e-02,  9.8979e-02,
          1.4040e-01,  9.7290e-02, -8.9526e-02,  1.5988e-01, -8.6498e-02,
          5.7646e-02, -1.0825e-01,  2.4107e-01, -3.6068e-01,  5.2401e-01,
         -3.0505e-01, -9.6168e-02,  1.2739e-01, -4.8393e-02,  1.4532e-01,
         -1.3455e-01,  1.2733e-01,  4.5125e-02, -1.6926e-01,  1.6467e-01,
         -1.5193e-01, -7.5943e-04,  1.1529e-01,  2.1900e-01,  5.3455e-03,
          3.0130e-01, -2.5704e-01, -5.4670e-02,  2.0509e-01,  4.2851e-01,
         -7.1669e-02,  1.0851e-01,  2.6843e-01,  1.2738e-01,  2.0056e-01,
         -3.2625e-01,  1.0078e-01,  6.8375e-02,  4.5960e-01,  2.4739e-01,
         -8.1177e-02, -2.5300e-02,  1.5170e-01, -1.5651e-01,  7.5750e-02,
         -1.3712e-01, -1.6502e-01, -2.1027e-01,  4.6497e-02, -2.1874e+00,
          3.1626e-01,  3.0064e-01,  5.0905e-02, -1.0305e-01, -2.2824e-01,
         -3.5598e-02,  2.1088e-01,  1.6718e-01, -5.7841e-03, -1.3090e-01,
         -2.1021e-01,  5.6268e-01,  9.0708e-02, -1.1265e-01,  1.2016e-01,
          2.3129e-01,  4.8681e-02,  1.7640e-01,  2.9800e-01,  2.5420e-01,
          1.0875e-01,  2.0575e-01, -7.4310e-02, -7.6300e-02, -1.7633e-01,
          2.9544e-01,  2.1423e-01,  3.2646e-02,  8.2375e-02, -1.8468e-01,
         -3.8736e-01, -1.7824e-01, -2.7055e+00,  1.8994e-01,  3.7929e-01,
         -7.6290e-02, -1.1820e-01, -4.4574e-02,  6.1063e-03,  2.4709e-01,
          2.9772e-01,  9.8910e-02, -1.9427e-01,  3.5553e-02, -1.5927e-01,
          1.0789e-01, -2.2606e-01, -2.1794e-01,  1.8181e-01, -3.4848e-02,
          1.5071e-01, -2.9513e-02,  9.1261e-03, -2.3303e-01, -1.0360e-01,
          4.5750e-02,  1.4714e-01,  6.3765e-02, -9.0737e-02,  2.1855e-01,
         -1.2367e-01,  7.0138e-02,  4.5026e-01, -4.6074e-03,  2.3267e-01,
          5.5692e-02, -2.7977e-03,  1.7769e-01,  6.1988e-02, -9.6830e-02,
         -2.0099e-01,  4.1236e-01,  1.0160e-01,  3.8106e-02, -1.1563e-01,
         -2.2056e-01,  2.5084e-01, -1.7908e-01,  9.9776e-02,  2.7291e-01,
         -6.8151e-02, -1.2620e-01,  7.1326e-02, -1.0605e-01,  2.5336e-01,
          5.8718e-02,  1.4395e-02, -5.2991e-01,  2.7293e-01,  1.2887e-01,
         -1.6590e-01,  1.2687e-01,  5.4675e-02, -5.3884e-02, -2.9484e-01,
          3.6170e+00,  1.4138e-01, -6.3448e-02,  4.4450e-01,  1.6606e-01,
          4.0848e-02, -3.9796e-02,  7.0076e-02, -2.1353e-01,  2.2668e-01,
          4.6193e-02,  5.0917e-01,  3.5284e-02,  2.6627e-01, -2.0723e-01,
          1.9853e-01,  1.9341e-01,  3.4011e-02,  3.1242e-01, -2.0404e-01,
         -7.9438e-02, -3.8666e-02,  2.5389e-02,  7.2507e-02, -9.8698e-01,
          2.3620e-01, -1.5100e-01, -1.8318e-02,  3.1354e-01, -1.6759e-01,
         -1.7712e-01,  2.8211e-01,  1.3598e-01,  1.9277e-01, -5.3715e-02,
          1.0545e-01,  1.9678e-01,  3.1855e-01, -1.0173e-01, -2.9817e-01,
          1.7895e-01,  9.0379e-02,  1.7815e-02, -5.5551e-02, -2.3651e-01,
          2.0419e-01, -9.8801e-02,  5.9829e-02, -1.9271e-01,  1.0717e-01,
         -1.0795e-01,  1.0910e-01, -4.0347e-02, -1.3725e-01, -1.2285e-01,
         -3.3318e-01, -3.9065e-02,  2.4768e-01, -7.7587e-02, -3.1765e-01,
          4.7572e-03, -2.1586e-01, -1.2792e-01, -2.3080e-02, -1.0744e-02,
         -3.2111e-02,  5.0523e-02, -3.6639e-01, -3.6253e+00, -4.6896e-02,
         -1.9764e-01,  2.4940e-01,  1.8293e-01, -1.8048e-01, -6.8881e-02,
          2.2758e-01,  1.9996e-01,  2.8876e-02,  4.8408e-01,  4.4881e-02,
         -5.6767e-02,  1.6429e-01, -4.5936e-01, -2.7710e-02,  6.6913e-03,
         -4.1584e-02,  2.4304e-01, -1.7135e-01, -6.8945e-02,  2.0619e-01,
         -1.5350e-01,  8.4970e-02,  3.9959e-02,  1.0625e-01, -3.8985e-01,
          1.6164e-02, -1.3002e-01,  1.1247e-01, -1.8311e-02, -3.0952e-01,
         -3.8914e-02, -3.3916e-01, -3.8436e-01, -3.1450e+00, -2.2183e-01,
         -3.0344e-01, -1.0318e-01,  1.7709e-01, -2.5821e-01,  3.6708e-01,
         -3.2438e-01, -1.1967e-01,  3.4989e-01, -9.3760e-02, -1.4778e-03,
          1.3843e-01,  2.2801e-02,  2.8655e-01,  2.1295e-01,  3.0743e-01,
         -6.3854e-02,  1.7121e-01,  1.9922e-01,  2.3800e-01, -1.4183e-03,
          6.4107e-02,  2.0074e-01, -3.9903e-02,  1.6789e-01, -4.1472e-01,
          1.9357e-01, -2.9848e-01, -7.4997e-02, -7.2514e-02, -2.5927e-01,
         -1.6533e-01, -2.6010e-02, -1.5505e-01, -3.0497e-01, -5.5179e-02,
          3.0901e-01,  4.2258e-01,  2.2868e-01, -5.6734e-02,  6.1243e-01,
         -4.1364e-03, -1.0637e-01,  3.6192e-01,  1.5388e-01,  3.3474e-01,
         -2.8729e-01, -2.0390e-02,  2.1368e-01,  4.2972e-02,  4.4213e-02,
          1.0139e+00, -1.1801e-01,  1.9863e-01, -8.0165e-02,  3.6327e-01,
         -2.5541e-02,  1.8111e-01, -1.0952e-01,  2.6714e-01, -5.8549e-02,
          1.8645e-02, -1.2104e-01,  2.0790e-02, -1.7724e-01,  1.3623e-01,
         -1.9804e-01,  1.5318e-02,  2.8266e-04, -8.9608e-02,  9.7948e-02,
          1.2358e-01, -7.6754e-01, -1.8809e-01, -1.4006e-01, -1.1901e-01,
          1.3088e-01, -2.1835e-02,  2.5184e-01, -2.4893e-01,  2.5228e-02,
          8.2740e-02,  3.6527e-01, -1.0551e-01,  2.5268e-02, -2.2786e-01,
          4.3883e-02, -5.5502e-01,  4.0396e-03,  1.9241e-01,  1.1979e-01,
         -1.1047e-02, -1.5856e-01,  3.5303e-02,  1.4071e-01,  1.2140e-01,
         -7.5401e-01,  1.1205e-01, -2.9014e-01,  1.1509e-02, -1.8608e-01,
          8.8281e-02, -1.4376e-01, -1.0446e-01, -1.3785e-01, -1.5088e-01,
          2.6151e-01,  8.6337e-02,  1.5922e-01, -1.0641e-01,  7.4093e-02,
         -1.8800e-01,  9.9260e-03,  7.0240e-01,  1.0295e-01, -1.7421e-01,
          1.0592e-01, -8.1311e-03,  2.6202e-01,  3.4301e-01,  5.8355e-02,
          1.5202e-01, -1.0479e-02,  4.6642e-02, -1.1320e-01,  2.2798e-01,
         -2.2040e-01, -2.9426e-01,  2.6265e-01,  6.1722e-02, -2.9661e-02,
         -5.0082e-02, -5.1473e-01, -5.1829e-02, -1.6959e-01, -2.4901e-01,
          2.6857e-01,  1.9222e-01, -8.8533e-02,  2.6145e-01,  7.2822e-02,
         -1.9692e-02,  3.1027e-01, -1.5872e-02,  5.5843e-01,  1.5355e-01,
         -3.7643e-03,  7.8144e-02,  2.4584e-01,  1.3235e-01, -6.9386e-02,
         -1.3883e-01, -1.7797e-01, -4.9232e-02, -1.1112e-01,  9.2039e-04,
          2.3943e-02, -2.6821e-01,  1.4667e-02,  6.6110e-02,  1.9910e-02,
         -1.4981e+00,  2.0384e-01,  2.9461e-02, -2.3086e-02, -9.9821e-04,
         -2.1651e-01, -2.5298e-01,  3.6206e-01,  2.0126e-01, -1.1574e-01,
         -2.6054e-01,  5.0371e-02,  5.3175e-02,  1.3036e-02,  1.5861e-01,
         -6.1535e-02,  4.6658e-02, -1.2930e-01, -7.8859e-02,  7.8653e-02,
         -1.8516e-01,  4.0234e-01, -1.1792e-01, -1.5908e-01, -9.9499e-02,
         -1.4255e-01, -1.3257e-02,  2.7369e-01,  1.5458e-01,  5.2198e-02,
          1.0235e-01, -1.7776e-01, -3.1346e-01, -1.3864e-02,  9.2282e-02,
          5.3052e-01, -5.1862e-02, -1.3058e-01,  2.8180e-01,  1.9755e-01,
         -5.3865e-01,  1.8096e-01,  2.4673e-01, -1.8016e-02,  4.0770e-01,
          2.7373e-01, -1.4515e-01,  1.6720e-01,  1.8356e-02, -9.6378e-02,
          5.6726e-03, -1.5315e-01, -1.4712e-01, -5.4042e-02,  1.0330e-02,
          1.2818e-01,  1.7885e-01, -1.0342e-01,  6.6779e-02, -1.9739e-01,
          8.7679e-02, -1.7025e-01, -1.4321e-01,  3.8324e-01,  1.0955e-03,
         -5.9542e-01, -7.1815e-02,  4.3666e-02,  1.3095e-01,  1.7700e-01,
          3.1900e-01,  1.9722e-01, -1.7848e-01,  2.2193e-01, -3.3946e-01,
          1.7014e-01, -8.1590e-02,  1.6025e-01,  1.3697e-01, -6.3627e-02,
         -3.2961e-02, -2.3130e-01, -4.8519e-01,  2.6354e-01,  1.0429e-01,
         -7.5910e-02, -1.1619e-01,  6.7850e-02,  2.5178e-01,  6.7425e-03,
         -1.2294e-01, -3.5889e-01,  1.5538e-01,  1.6078e-01, -2.2705e-02,
          2.7021e-02,  1.0159e-01,  2.2105e-01, -8.6866e-02,  1.2526e-01,
         -4.4487e-02,  2.2335e-01,  2.7975e-01,  2.0670e-01,  3.2050e-02,
         -2.6862e-02,  8.3396e-02,  2.6668e-02, -2.5835e-02,  1.1574e-01,
          1.4106e-01,  1.3240e-01,  2.1088e-01,  1.6199e-01, -1.6636e-01,
         -3.8655e-01,  1.3989e-01, -1.0557e-01,  1.8918e+00,  2.5154e-01,
         -5.7866e-02,  1.1697e-01,  1.6432e-01, -4.6247e-03, -1.3474e-01,
          1.1874e-01, -2.6633e-01,  4.3818e-01,  1.1555e-01,  1.1806e-01,
         -1.2007e-01,  1.1425e-01,  2.8781e-01,  2.5333e-01, -2.2793e-02,
         -8.0757e-02, -3.5079e-01,  1.0841e-01, -4.2065e-01,  2.6400e-01,
          1.8109e-01, -1.4003e-01, -5.8306e-02,  1.3446e-01,  1.3160e-01,
         -9.6604e-02,  7.9812e-02,  7.0873e-02, -2.8947e-02, -1.1833e-01,
         -5.8746e-03,  3.7192e-01, -6.4857e-02,  5.1263e-02,  4.0038e-02,
         -2.2548e-01, -2.1406e-01,  2.4342e-01,  1.9408e-01, -4.4586e-01,
          3.2101e-01, -1.0224e-01, -6.9413e-02,  3.5498e-01, -1.9408e-01,
         -4.4596e-01,  1.1276e-01,  8.6103e-02,  1.5515e-02,  1.0798e-01,
         -2.6724e-01, -1.7683e-02, -9.2630e-02,  2.4824e-02, -8.5071e-02,
         -1.3467e-01, -3.1814e-01,  3.8439e-01,  2.1553e-02,  2.4649e-01,
          2.3472e-01, -1.0657e-01,  2.9153e-01,  1.0203e-01, -2.5465e-01,
          4.4665e-02,  5.8582e-02, -5.6107e-02, -7.8599e-02,  6.6927e-03,
          1.6225e-01,  2.4978e-01,  9.7655e-02, -1.6675e-01,  2.4094e-01,
         -1.5415e-01, -2.5830e-01, -2.3883e+00, -1.9858e-02,  5.4993e-02,
         -6.7387e-02, -5.0541e-02,  2.6674e-01,  1.5227e-01, -2.9625e-01,
         -2.2303e-01, -2.1996e-01,  3.8450e-01,  2.8356e-01,  8.0056e-02,
         -6.2887e-02,  2.1506e-01, -1.0166e-01,  7.5961e-02, -2.5285e-01,
          8.4287e-02, -3.8517e-02,  1.3316e-01, -2.4381e-02, -1.6394e-02,
         -2.1733e-01, -3.3400e-01, -2.9527e-02,  1.0207e-02, -2.6994e-01,
          7.2570e-02, -1.0175e-01, -9.6514e-02,  8.8585e-02, -7.8387e-02,
         -4.4849e-02, -2.5727e-01, -2.1486e-01, -3.9008e-02,  7.9355e-02,
         -6.0729e-02,  1.0334e-01, -1.2396e-01,  3.8213e-01, -2.5837e-02,
          1.9702e-01, -1.8630e-01,  8.3891e-02,  3.1181e-01, -2.4913e-01,
          4.2572e-01, -1.3803e-01,  1.3299e-01,  9.3797e-02, -2.0112e-02,
          2.6042e-01,  4.4999e-02,  7.8430e-02,  9.4429e-02,  1.6658e-02,
         -1.9302e-01, -2.5710e-02, -4.1273e-01,  4.8893e-02, -9.3181e-02,
          7.4541e-03,  3.2401e-01, -1.1291e-01, -9.1418e-02,  1.7469e-03,
          1.2941e-04, -8.7341e-02, -8.8551e-03, -1.3884e-01,  3.9764e-01,
          1.1009e-01,  6.6763e-02, -2.6532e-02,  2.3280e-01,  2.7811e-01,
          9.6838e-02,  5.6105e-02,  7.3123e-02, -2.0519e-01, -1.7856e-01,
         -3.6749e-02,  4.7213e-01, -6.8857e+00, -2.1297e-01, -6.5105e-02,
         -2.4579e-02, -9.7571e-02, -7.6994e-02,  1.2418e-01, -3.5733e-01,
          4.4367e-02,  3.5709e-02,  1.2189e-01,  3.7780e-02, -1.9954e-01,
         -8.9761e-02,  1.6379e-01,  4.0633e-01]),
 'mean_embeddings': tensor([-1.6662e-02,  4.2074e-02,  1.1839e-01,  2.1663e-01,  2.8436e-01,
         -1.2278e-01,  5.1610e-02, -4.1407e-02,  2.0320e-01, -3.3600e-01,
          7.4439e-02, -5.2773e-02,  3.5081e-02,  9.2372e-02, -1.8272e-01,
         -7.8776e-02,  1.9925e-01,  7.1945e-02, -2.0449e-02,  1.8879e-01,
          6.9198e-02, -2.2404e-01, -5.5204e-02,  1.5460e-02,  2.8019e-01,
          8.9466e-02, -2.0350e-01, -1.2886e-01,  2.9670e-02, -3.3339e-01,
          2.5904e-02,  2.1987e-02,  2.1461e-01, -2.1357e-01,  2.2484e-01,
          6.3922e-02,  1.6604e-01,  1.8941e-01, -1.7809e-01, -6.0738e-02,
         -2.4649e-01, -6.0080e-04,  2.1863e-01, -2.7786e-01,  6.9416e-03,
         -1.2261e-01,  9.4630e-02,  4.4575e-03, -4.4969e-01, -8.2545e-03,
          1.4209e-01, -1.1567e-01, -1.1929e-01, -2.2524e-01, -8.2005e-02,
          2.2596e-01, -1.3114e-01,  9.7403e-02, -2.8955e-02, -1.2073e-01,
         -7.0387e-02,  1.3208e-01,  2.0408e-02, -7.7899e-02, -9.8122e-02,
          5.9839e-02,  1.8793e-03,  2.1107e-01, -4.5596e-01,  2.4604e-01,
         -6.9107e-03, -2.4657e-02, -3.7652e-02,  2.1964e-02, -6.4047e-03,
         -7.8861e-02, -2.7291e-02,  9.2706e-02,  1.0847e-01,  3.2447e-02,
         -3.7829e-01, -1.6985e-01,  3.3011e-02,  2.2808e-01,  9.2148e-02,
          1.6660e-01,  3.5225e-02,  3.5488e-02, -9.8106e-02,  2.6056e-01,
          1.7566e-01,  1.9739e-02,  1.9184e-01, -1.4389e-01, -4.7654e-02,
         -1.5918e-01,  9.1089e-02,  1.3081e-01,  2.7996e-01,  4.3999e-01,
         -2.5351e-01, -1.9203e-01,  1.8737e-01,  2.8676e-01,  4.1147e-02,
         -4.0045e-02, -5.5076e-02,  4.3265e-02,  1.2789e-01,  2.3433e-01,
          2.6919e-01,  4.7187e-04,  1.4939e-01,  1.3466e-01, -1.6025e-01,
         -1.8985e-03, -1.4686e-01,  1.3129e-01, -8.1068e-02, -6.0758e-02,
         -2.1717e-01,  9.1166e-02,  1.8817e-01,  3.3244e-01, -8.3954e-02,
         -4.2420e-02, -1.4173e-01,  1.0564e-01,  1.0218e-01, -8.3232e-02,
         -8.3919e-02, -4.9405e-02,  1.3453e-01, -1.4936e-01, -1.3681e-01,
          1.0897e-01,  6.3241e-02, -6.3857e-02,  1.9044e-01, -1.2086e-01,
         -9.7653e-02,  1.9045e-01,  3.1758e-01,  2.0207e-02,  7.2904e-02,
         -4.2222e-02, -7.8990e-02, -4.9199e-02, -1.8191e-02,  1.4049e-01,
          3.1234e-01,  5.3246e-02, -1.0161e-01, -1.2028e-01, -8.8964e-02,
          1.5525e-01, -2.5567e-01,  2.8187e-02, -1.3531e-01, -1.6901e-03,
          2.6972e-01,  1.5388e-01,  1.5065e-01, -1.0779e-01,  8.8708e-02,
         -8.9132e-02,  1.5199e-01,  2.6249e-01, -1.4410e-01,  5.0402e-01,
         -6.9780e-02, -8.8512e-02,  5.0903e-01,  7.5069e-02, -9.5300e-02,
         -8.0811e-02,  2.2069e-01, -1.7781e-02, -2.2209e-02, -1.6306e-01,
         -6.6163e-01,  4.2049e-02,  3.9499e-02, -7.4795e-02, -1.6555e-02,
         -1.8578e-01,  1.0984e-01, -2.3248e-01,  1.8366e-01, -3.3351e-02,
         -9.4744e-02, -3.3248e-01, -5.4605e-02, -8.3824e-02,  1.6278e-01,
         -3.0224e-01, -9.3282e-02, -1.2763e-02, -3.8296e-02, -6.2403e-02,
          1.8829e-01,  1.6524e-01,  1.6218e-01, -7.1763e-02, -1.1963e-01,
         -6.1435e-02,  2.0407e-01, -1.2922e-01,  3.9056e-01, -1.3653e-01,
         -2.4571e-01,  1.4611e-01,  2.1571e-02, -1.8141e-01, -8.4120e-02,
         -3.5814e-02,  4.1551e-01, -1.1545e-03,  1.2304e-01, -1.1461e-01,
          4.7400e-02, -9.6703e-03, -1.6946e-01,  3.3210e-01, -2.4970e-01,
         -1.4372e-03,  2.4704e-01, -2.4014e-01,  1.0224e-01,  1.4134e-01,
          1.0560e-01, -2.8850e-01,  2.4860e-01,  3.7028e-02, -2.3876e-02,
          1.8398e-01,  2.6310e-01,  1.2688e-01,  1.6094e-01, -2.4885e-01,
          3.1678e-02,  1.4246e-01,  4.4628e-01, -1.7303e-01,  4.9229e-02,
         -6.0775e-02,  6.4991e-02,  2.3120e-01, -1.3854e-01, -4.1586e-01,
         -1.8144e-01, -1.6856e-01,  4.0423e-02, -2.8587e-01, -1.8045e-02,
         -1.2986e-01, -1.6718e-01, -7.4478e-02,  1.9822e-01,  4.4522e-02,
          5.0001e-02, -1.7799e-02,  3.5915e-01, -1.5545e-01, -1.9066e-01,
          3.1441e-02, -2.1154e-01,  1.2222e-01,  7.8136e-02,  1.0378e-01,
         -4.7484e-02, -1.0394e-01, -1.1279e-01,  1.8241e-01, -2.0625e-01,
         -4.3000e-01,  3.2139e-01,  8.7879e-02, -8.4488e-02, -1.7032e-01,
         -1.1894e-03,  2.9195e-01, -1.0774e-01,  2.5712e-01, -2.8101e-02,
         -2.5813e-01, -7.6533e-02, -1.8652e-01, -2.2178e-01, -3.1679e-01,
         -1.5726e-02,  2.0318e-01, -1.6029e-01, -2.3257e-02,  1.7688e-01,
         -1.2873e-02,  8.3163e-02,  1.9049e-01,  3.2567e-01, -1.0365e-01,
          5.8366e-02, -5.2214e-02,  4.9033e-02,  8.7247e-02, -4.7931e-01,

In [11]:
generator=torch.Generator()
generator.manual_seed(seed)
collate_function_object=CollateFunction()
collate_fn=collate_function_object.collate_fn
train_dataloader=DataLoader(train_dataset,batch_size=64,collate_fn=collate_fn,generator=generator,worker_init_fn=seed_worker,shuffle=True,drop_last=True)
val_dataloader=DataLoader(val_dataset,batch_size=64,collate_fn=collate_fn,generator=generator,worker_init_fn=seed_worker,shuffle=True,drop_last=True)

In [12]:
batch=next(iter(train_dataloader))
for key in list(batch.keys()):
    print(key)
    print(f"The shape of batch {key} is :")
    print(batch[key].shape)
    print("-------------------")

user_id
The shape of batch user_id is :
torch.Size([64, 1])
-------------------
recipe_id
The shape of batch recipe_id is :
torch.Size([64, 1])
-------------------
rating_scaled
The shape of batch rating_scaled is :
torch.Size([64, 1])
-------------------
i
The shape of batch i is :
torch.Size([64, 1])
-------------------
technique_recipes
The shape of batch technique_recipes is :
torch.Size([64, 58])
-------------------
calorie_level_scaled
The shape of batch calorie_level_scaled is :
torch.Size([64, 1])
-------------------
techniques_users
The shape of batch techniques_users is :
torch.Size([64, 58])
-------------------
items
The shape of batch items is :
torch.Size([64, 6437])
-------------------
n_items_scaled
The shape of batch n_items_scaled is :
torch.Size([64, 1])
-------------------
ratings_scaled
The shape of batch ratings_scaled is :
torch.Size([64, 6437])
-------------------
n_ratings_scaled
The shape of batch n_ratings_scaled is :
torch.Size([64, 1])
-------------------
minutes_scaled
The shape of batch minutes_scaled is :
torch.Size([64, 1])
-------------------
nutrition
The shape of batch nutrition is :
torch.Size([64, 7])
-------------------
n_ingredients_scaled
The shape of batch n_ingredients_scaled is :
torch.Size([64, 1])
-------------------
n_steps_scaled
The shape of batch n_steps_scaled is :
torch.Size([64, 1])
-------------------
ingredient_ids_continuous
The shape of batch ingredient_ids_continuous is :
torch.Size([64, 20])
-------------------
cls_embeddings
The shape of batch cls_embeddings is :
torch.Size([64, 768])
-------------------
mean_embeddings
The shape of batch mean_embeddings is :
torch.Size([64, 768])
-------------------

In [ ]:
#PP_recipes_df["ingredient_ids_transformed"]=PP_recipes_df["ingredient_ids"].apply(lambda x: list(map(int,ast.literal_eval(x))))
#all_ingredient_ids=np.unique(list(itertools.chain.from_iterable(list(PP_recipes_df["ingredient_ids_transformed"]))))
#ingredient_continuous_ids=pd.Series([i for i in range(1,len(all_ingredient_ids)+1)],index=list(np.sort(all_ingredient_ids)))
#ingredient_continuous_ids.to_pickle("./modules/dataframes/ingredient_continuous_ids.pkl")

In [ ]:
#ingredient_continuous_ids=pd.read_pickle("./modules/dataframes/ingredient_continuous_ids.pkl")
#n_recipes_ids=len(np.unique(PP_recipes_df["i"]))
#n_ingredients_ids=len(all_ingredient_ids)

#print(f"There are {n_recipes_ids} recipe ids")
#print(f"There are {n_ingredients_ids} ingredient ids")

There are 178265 recipe ids
There are 7993 ingredient ids

In [ ]:
#hash_encoder=EncodedHashedEmbeddings(n_recipes_ids,512,n_ingredients_ids,512)
#hashed_recipes_ids_encoded_embeddings,hashed_ingredients_ids_encoded_embeddings=hash_encoder.get_encoded_hashed_embeddings("./modules/hashed_encoded_tables")

In [11]:
hashed_ingredients_ids_encoded_embeddings=torch.load("./modules/hashed_encoded_tables/hashed_embeddings_ingredients.pt")
hashed_recipes_ids_encoded_embeddings=torch.load("./modules/hashed_encoded_tables/hashed_embeddings_recipes.pt")

In [12]:
print(hashed_recipes_ids_encoded_embeddings.shape)
print(hashed_ingredients_ids_encoded_embeddings.shape)

torch.Size([178267, 512])
torch.Size([7995, 512])

In [13]:
#Loss with alpha = 0.3 and temperature = 0.2
loss_alpha=0.3
temperature=0.2
device=(torch.device("mps") if torch.backends.mps.is_available() else torch.device("cuda" if torch.cuda.is_available() else "cpu"))
hyperparemeters_ranges={
    "batch_size":[32, 64],
    "dropout":{
        "low":0.05,
        "high":0.3,
        "step":0.05
    },
    "projec_dropout":{
        "low":0.05,
        "high":0.3,
        "step":0.05
    },
    "lr":{
        "low":1e-4,
        "high":1e-2,
        "log":True
    },
    "weight_decay":{
        "low":1e-5,
        "high":1e-3,
        "log":True
    },
    "warmup_prop":{
        "low":0.01,
        "high":0.1,
        "step":0.01
    },
    "mean_mode": [True, False]
}
optuna_object=OptunaFunction(train_df=train_df_processed,val_df=val_df_processed,train_cls_embeddings=train_cls_embeddings,
                             val_cls_embeddings=val_cls_embeddings,train_mean_embeddings=train_mean_embeddings,
                             val_mean_embeddings=val_mean_embeddings,hashed_ingredients_ids_encoded_embeddings=hashed_ingredients_ids_encoded_embeddings,
                             hashed_recipes_ids_encoded_embeddings=hashed_recipes_ids_encoded_embeddings,loss_alpha=loss_alpha,temperature=temperature,
                             device=device,hyperparemeters_ranges=hyperparemeters_ranges)

In [15]:
study=optuna.create_study(direction="minimize",pruner=optuna.pruners.MedianPruner(),storage="sqlite:///optuna_study.db",load_if_exists=True,study_name="recommendation_system_model_study")

[I 2026-04-18 13:18:22,586] Using an existing study with name 'recommendation_system_model_study' instead of creating a new one.

In [16]:
study.optimize(optuna_object.objective,n_trials=10)

2026-04-18 13:18:40.059 | INFO     | modules.optuna_function:objective:85 - Trial number 0:
2026-04-18 13:18:40.060 | INFO     | modules.optuna_function:objective:86 - batch_size:64_dropout:0,3_projec_dropout:0,25_lr:0,008834724109738035_weight_decay:0,0006779624554541989_warmup_prop:0,01_mean_mode:True_loss_temp:0,2_loss_alpha:0,3
2026-04-18 13:18:40.061 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-18 13:19:49.040 | INFO     | modules.train:run_training:178 - Epoch 0 : train total loss = 1.1700043656410428
2026-04-18 13:19:49.041 | INFO     | modules.train:run_training:179 - Epoch 0 : train contrastive loss = 3.8111283286995845
2026-04-18 13:19:49.042 | INFO     | modules.train:run_training:180 - Epoch 0 : train MSE loss = 0.03809402538292588
2026-04-18 13:19:49.043 | INFO     | modules.train:run_training:182 - Epoch 0 : validation total loss = 1.1644546907881033
2026-04-18 13:19:49.044 | INFO     | modules.train:run_training:183 - Epoch 0 : validation contrastive loss = 3.7901397684346074
2026-04-18 13:19:49.046 | INFO     | modules.train:run_training:184 - Epoch 0 : validation MSE loss = 0.03916102661953672
2026-04-18 13:19:49.116 | INFO     | modules.train:run_training:89 - Epoch 1 :
2026-04-18 13:20:57.476 | INFO     | modules.train:run_training:178 - Epoch 1 : train total loss = 1.1671571321443681
2026-04-18 13:20:57.477 | INFO     | modules.train:run_training:179 - Epoch 1 : train contrastive loss = 3.8079353592811374
2026-04-18 13:20:57.478 | INFO     | modules.train:run_training:180 - Epoch 1 : train MSE loss = 0.035394956379137726
2026-04-18 13:20:57.479 | INFO     | modules.train:run_training:182 - Epoch 1 : validation total loss = 1.1550744823787524
2026-04-18 13:20:57.481 | INFO     | modules.train:run_training:183 - Epoch 1 : validation contrastive loss = 3.761490287988082
2026-04-18 13:20:57.482 | INFO     | modules.train:run_training:184 - Epoch 1 : validation MSE loss = 0.0380390920959737
2026-04-18 13:20:57.554 | INFO     | modules.train:run_training:89 - Epoch 2 :
2026-04-18 13:22:06.528 | INFO     | modules.train:run_training:178 - Epoch 2 : train total loss = 1.1557013545561274
2026-04-18 13:22:06.529 | INFO     | modules.train:run_training:179 - Epoch 2 : train contrastive loss = 3.767535274181891
2026-04-18 13:22:06.530 | INFO     | modules.train:run_training:180 - Epoch 2 : train MSE loss = 0.036343897940642245
2026-04-18 13:22:06.530 | INFO     | modules.train:run_training:182 - Epoch 2 : validation total loss = 1.148720655752265
2026-04-18 13:22:06.531 | INFO     | modules.train:run_training:183 - Epoch 2 : validation contrastive loss = 3.7408287110535996
2026-04-18 13:22:06.532 | INFO     | modules.train:run_training:184 - Epoch 2 : validation MSE loss = 0.03781714235715892
2026-04-18 13:22:06.611 | INFO     | modules.train:run_training:89 - Epoch 3 :
2026-04-18 13:23:17.520 | INFO     | modules.train:run_training:178 - Epoch 3 : train total loss = 1.1486171396500473
2026-04-18 13:23:17.521 | INFO     | modules.train:run_training:179 - Epoch 3 : train contrastive loss = 3.7439140420441235
2026-04-18 13:23:17.523 | INFO     | modules.train:run_training:180 - Epoch 3 : train MSE loss = 0.03634696558903937
2026-04-18 13:23:17.524 | INFO     | modules.train:run_training:182 - Epoch 3 : validation total loss = 1.1467548168223838
2026-04-18 13:23:17.524 | INFO     | modules.train:run_training:183 - Epoch 3 : validation contrastive loss = 3.730956124222797
2026-04-18 13:23:17.525 | INFO     | modules.train:run_training:184 - Epoch 3 : validation MSE loss = 0.039239909722591226
2026-04-18 13:23:17.599 | INFO     | modules.train:run_training:89 - Epoch 4 :
2026-04-18 13:24:28.338 | INFO     | modules.train:run_training:178 - Epoch 4 : train total loss = 1.1414205858466822
2026-04-18 13:24:28.339 | INFO     | modules.train:run_training:179 - Epoch 4 : train contrastive loss = 3.7206588928852606
2026-04-18 13:24:28.340 | INFO     | modules.train:run_training:180 - Epoch 4 : train MSE loss = 0.03603267500501707
2026-04-18 13:24:28.341 | INFO     | modules.train:run_training:182 - Epoch 4 : validation total loss = 1.150555107904517
2026-04-18 13:24:28.343 | INFO     | modules.train:run_training:183 - Epoch 4 : validation contrastive loss = 3.7404496462448784
2026-04-18 13:24:28.344 | INFO     | modules.train:run_training:184 - Epoch 4 : validation MSE loss = 0.040600231524718845
2026-04-18 13:24:28.372 | INFO     | modules.train:run_training:89 - Epoch 5 :
2026-04-18 13:25:39.826 | INFO     | modules.train:run_training:178 - Epoch 5 : train total loss = 1.1330078818382474
2026-04-18 13:25:39.829 | INFO     | modules.train:run_training:179 - Epoch 5 : train contrastive loss = 3.6934093269733115
2026-04-18 13:25:39.830 | INFO     | modules.train:run_training:180 - Epoch 5 : train MSE loss = 0.03569291429508717
2026-04-18 13:25:39.830 | INFO     | modules.train:run_training:182 - Epoch 5 : validation total loss = 1.1542737354402957
2026-04-18 13:25:39.831 | INFO     | modules.train:run_training:183 - Epoch 5 : validation contrastive loss = 3.754929677299831
2026-04-18 13:25:39.831 | INFO     | modules.train:run_training:184 - Epoch 5 : validation MSE loss = 0.03970684827831776
2026-04-18 13:25:39.832 | WARNING  | modules.train:run_training:204 - Training stops after 5 epochs
2026/04/18 13:25:40 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/18 13:25:41 WARNING mlflow.pytorch: Saving pytorch model by Pickle or CloudPickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is to set `serialization_format` to 'pt2' to save the PyTorch model using the safe graph model format.
2026/04/18 13:25:48 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.
2026/04/18 13:26:08 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.

----------------------------------------------------------------------------------------------------

[I 2026-04-18 13:26:14,303] Trial 0 finished with value: 1.1467548168223838 and parameters: {'batch_size': 64, 'dropout': 0.3, 'projec_dropout': 0.25, 'lr': 0.008834724109738035, 'weight_decay': 0.0006779624554541989, 'warmup_prop': 0.01, 'mean_mode': True}. Best is trial 0 with value: 1.1467548168223838.
2026-04-18 13:26:14.868 | INFO     | modules.optuna_function:objective:85 - Trial number 1:
2026-04-18 13:26:14.869 | INFO     | modules.optuna_function:objective:86 - batch_size:32_dropout:0,3_projec_dropout:0,2_lr:0,006752329720101161_weight_decay:5,195328204771679e-05_warmup_prop:0,04_mean_mode:False_loss_temp:0,2_loss_alpha:0,3
2026-04-18 13:26:14.870 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-18 13:27:25.164 | INFO     | modules.train:run_training:178 - Epoch 0 : train total loss = 0.9778979015568574
2026-04-18 13:27:25.165 | INFO     | modules.train:run_training:179 - Epoch 0 : train contrastive loss = 3.1686162583069617
2026-04-18 13:27:25.166 | INFO     | modules.train:run_training:180 - Epoch 0 : train MSE loss = 0.03901855306256588
2026-04-18 13:27:25.167 | INFO     | modules.train:run_training:182 - Epoch 0 : validation total loss = 0.9654249914230839
2026-04-18 13:27:25.169 | INFO     | modules.train:run_training:183 - Epoch 0 : validation contrastive loss = 3.1284148462357058
2026-04-18 13:27:25.172 | INFO     | modules.train:run_training:184 - Epoch 0 : validation MSE loss = 0.038429288644223444
2026-04-18 13:27:25.233 | INFO     | modules.train:run_training:89 - Epoch 1 :
2026-04-18 13:28:33.315 | INFO     | modules.train:run_training:178 - Epoch 1 : train total loss = 0.9645473478315079
2026-04-18 13:28:33.316 | INFO     | modules.train:run_training:179 - Epoch 1 : train contrastive loss = 3.1295193169155167
2026-04-18 13:28:33.317 | INFO     | modules.train:run_training:180 - Epoch 1 : train MSE loss = 0.0367021685289283
2026-04-18 13:28:33.319 | INFO     | modules.train:run_training:182 - Epoch 1 : validation total loss = 0.9607979738584129
2026-04-18 13:28:33.319 | INFO     | modules.train:run_training:183 - Epoch 1 : validation contrastive loss = 3.1104002229629026
2026-04-18 13:28:33.320 | INFO     | modules.train:run_training:184 - Epoch 1 : validation MSE loss = 0.03953982009902917
2026-04-18 13:28:33.392 | INFO     | modules.train:run_training:89 - Epoch 2 :
2026-04-18 13:29:41.491 | INFO     | modules.train:run_training:178 - Epoch 2 : train total loss = 0.9589108137298776
2026-04-18 13:29:41.493 | INFO     | modules.train:run_training:179 - Epoch 2 : train contrastive loss = 3.110648933209871
2026-04-18 13:29:41.494 | INFO     | modules.train:run_training:180 - Epoch 2 : train MSE loss = 0.036737283857995365
2026-04-18 13:29:41.495 | INFO     | modules.train:run_training:182 - Epoch 2 : validation total loss = 0.9568283109254735
2026-04-18 13:29:41.496 | INFO     | modules.train:run_training:183 - Epoch 2 : validation contrastive loss = 3.1006082796281382
2026-04-18 13:29:41.496 | INFO     | modules.train:run_training:184 - Epoch 2 : validation MSE loss = 0.038065418145389
2026-04-18 13:29:41.568 | INFO     | modules.train:run_training:89 - Epoch 3 :
2026-04-18 13:30:49.571 | INFO     | modules.train:run_training:178 - Epoch 3 : train total loss = 0.9538360321276248
2026-04-18 13:30:49.572 | INFO     | modules.train:run_training:179 - Epoch 3 : train contrastive loss = 3.094607963714774
2026-04-18 13:30:49.572 | INFO     | modules.train:run_training:180 - Epoch 3 : train MSE loss = 0.03636229716910548
2026-04-18 13:30:49.574 | INFO     | modules.train:run_training:182 - Epoch 3 : validation total loss = 0.9571507162945245
2026-04-18 13:30:49.575 | INFO     | modules.train:run_training:183 - Epoch 3 : validation contrastive loss = 3.0991671495540167
2026-04-18 13:30:49.576 | INFO     | modules.train:run_training:184 - Epoch 3 : validation MSE loss = 0.03914362238219348
2026-04-18 13:30:49.611 | INFO     | modules.train:run_training:89 - Epoch 4 :
2026-04-18 13:31:57.926 | INFO     | modules.train:run_training:178 - Epoch 4 : train total loss = 0.9477996747062736
2026-04-18 13:31:57.927 | INFO     | modules.train:run_training:179 - Epoch 4 : train contrastive loss = 3.075012214669374
2026-04-18 13:31:57.928 | INFO     | modules.train:run_training:180 - Epoch 4 : train MSE loss = 0.036137107853485735
2026-04-18 13:31:57.929 | INFO     | modules.train:run_training:182 - Epoch 4 : validation total loss = 0.9600481025634273
2026-04-18 13:31:57.930 | INFO     | modules.train:run_training:183 - Epoch 4 : validation contrastive loss = 3.1080012218926543
2026-04-18 13:31:57.931 | INFO     | modules.train:run_training:184 - Epoch 4 : validation MSE loss = 0.0394967107743185
2026-04-18 13:31:57.932 | WARNING  | modules.train:run_training:204 - Training stops after 4 epochs
2026/04/18 13:31:58 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/18 13:31:58 WARNING mlflow.pytorch: Saving pytorch model by Pickle or CloudPickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is to set `serialization_format` to 'pt2' to save the PyTorch model using the safe graph model format.
2026/04/18 13:32:10 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.
2026/04/18 13:32:26 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.

----------------------------------------------------------------------------------------------------

[I 2026-04-18 13:32:33,051] Trial 1 finished with value: 0.9568283109254735 and parameters: {'batch_size': 32, 'dropout': 0.3, 'projec_dropout': 0.2, 'lr': 0.006752329720101161, 'weight_decay': 5.195328204771679e-05, 'warmup_prop': 0.04, 'mean_mode': False}. Best is trial 1 with value: 0.9568283109254735.
2026-04-18 13:32:33.634 | INFO     | modules.optuna_function:objective:85 - Trial number 2:
2026-04-18 13:32:33.635 | INFO     | modules.optuna_function:objective:86 - batch_size:64_dropout:0,05_projec_dropout:0,1_lr:0,0001634316560750821_weight_decay:1,7058847746216797e-05_warmup_prop:0,03_mean_mode:False_loss_temp:0,2_loss_alpha:0,3
2026-04-18 13:32:33.636 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-18 13:33:43.715 | INFO     | modules.train:run_training:178 - Epoch 0 : train total loss = 1.1715094561970563
2026-04-18 13:33:43.716 | INFO     | modules.train:run_training:179 - Epoch 0 : train contrastive loss = 3.794558388377548
2026-04-18 13:33:43.718 | INFO     | modules.train:run_training:180 - Epoch 0 : train MSE loss = 0.04734555578047256
2026-04-18 13:33:43.719 | INFO     | modules.train:run_training:182 - Epoch 0 : validation total loss = 1.147254749484684
2026-04-18 13:33:43.721 | INFO     | modules.train:run_training:183 - Epoch 0 : validation contrastive loss = 3.734005814013274
2026-04-18 13:33:43.722 | INFO     | modules.train:run_training:184 - Epoch 0 : validation MSE loss = 0.03864707706658089
2026-04-18 13:33:43.779 | INFO     | modules.train:run_training:89 - Epoch 1 :
2026-04-18 13:34:52.816 | INFO     | modules.train:run_training:178 - Epoch 1 : train total loss = 1.1450207413883384
2026-04-18 13:34:52.817 | INFO     | modules.train:run_training:179 - Epoch 1 : train contrastive loss = 3.731725208256223
2026-04-18 13:34:52.818 | INFO     | modules.train:run_training:180 - Epoch 1 : train MSE loss = 0.03643303138520056
2026-04-18 13:34:52.819 | INFO     | modules.train:run_training:182 - Epoch 1 : validation total loss = 1.136875129264334
2026-04-18 13:34:52.820 | INFO     | modules.train:run_training:183 - Epoch 1 : validation contrastive loss = 3.7015461921691895
2026-04-18 13:34:52.820 | INFO     | modules.train:run_training:184 - Epoch 1 : validation MSE loss = 0.03773031628731152
2026-04-18 13:34:52.888 | INFO     | modules.train:run_training:89 - Epoch 2 :
2026-04-18 13:36:02.297 | INFO     | modules.train:run_training:178 - Epoch 2 : train total loss = 1.1277065173201604
2026-04-18 13:36:02.298 | INFO     | modules.train:run_training:179 - Epoch 2 : train contrastive loss = 3.6716295076072765
2026-04-18 13:36:02.300 | INFO     | modules.train:run_training:180 - Epoch 2 : train MSE loss = 0.03745374195448576
2026-04-18 13:36:02.301 | INFO     | modules.train:run_training:182 - Epoch 2 : validation total loss = 1.1370635628700256
2026-04-18 13:36:02.302 | INFO     | modules.train:run_training:183 - Epoch 2 : validation contrastive loss = 3.690872845442399
2026-04-18 13:36:02.303 | INFO     | modules.train:run_training:184 - Epoch 2 : validation MSE loss = 0.042573810312087124
2026-04-18 13:36:02.327 | INFO     | modules.train:run_training:89 - Epoch 3 :
2026-04-18 13:37:12.336 | INFO     | modules.train:run_training:178 - Epoch 3 : train total loss = 1.1113712251733203
2026-04-18 13:37:12.338 | INFO     | modules.train:run_training:179 - Epoch 3 : train contrastive loss = 3.613470076420985
2026-04-18 13:37:12.339 | INFO     | modules.train:run_training:180 - Epoch 3 : train MSE loss = 0.039043078916745445
2026-04-18 13:37:12.339 | INFO     | modules.train:run_training:182 - Epoch 3 : validation total loss = 1.1318802859472192
2026-04-18 13:37:12.340 | INFO     | modules.train:run_training:183 - Epoch 3 : validation contrastive loss = 3.672367230705593
2026-04-18 13:37:12.341 | INFO     | modules.train:run_training:184 - Epoch 3 : validation MSE loss = 0.04310011940643839
2026-04-18 13:37:12.419 | INFO     | modules.train:run_training:89 - Epoch 4 :
2026-04-18 13:38:22.986 | INFO     | modules.train:run_training:178 - Epoch 4 : train total loss = 1.0958280891453454
2026-04-18 13:38:22.987 | INFO     | modules.train:run_training:179 - Epoch 4 : train contrastive loss = 3.5565742101144355
2026-04-18 13:38:22.988 | INFO     | modules.train:run_training:180 - Epoch 4 : train MSE loss = 0.0412225385512644
2026-04-18 13:38:22.988 | INFO     | modules.train:run_training:182 - Epoch 4 : validation total loss = 1.1358587119890295
2026-04-18 13:38:22.989 | INFO     | modules.train:run_training:183 - Epoch 4 : validation contrastive loss = 3.6774016929709394
2026-04-18 13:38:22.989 | INFO     | modules.train:run_training:184 - Epoch 4 : validation MSE loss = 0.04662594737728005
2026-04-18 13:38:23.035 | INFO     | modules.train:run_training:89 - Epoch 5 :
2026-04-18 13:39:33.000 | INFO     | modules.train:run_training:178 - Epoch 5 : train total loss = 1.0802361951508652
2026-04-18 13:39:33.001 | INFO     | modules.train:run_training:179 - Epoch 5 : train contrastive loss = 3.499750684160705
2026-04-18 13:39:33.002 | INFO     | modules.train:run_training:180 - Epoch 5 : train MSE loss = 0.043301347147570834
2026-04-18 13:39:33.003 | INFO     | modules.train:run_training:182 - Epoch 5 : validation total loss = 1.141755575719087
2026-04-18 13:39:33.004 | INFO     | modules.train:run_training:183 - Epoch 5 : validation contrastive loss = 3.68555035798446
2026-04-18 13:39:33.006 | INFO     | modules.train:run_training:184 - Epoch 5 : validation MSE loss = 0.051557744974675385
2026-04-18 13:39:33.007 | WARNING  | modules.train:run_training:204 - Training stops after 5 epochs
2026/04/18 13:39:33 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/18 13:39:33 WARNING mlflow.pytorch: Saving pytorch model by Pickle or CloudPickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is to set `serialization_format` to 'pt2' to save the PyTorch model using the safe graph model format.
2026/04/18 13:39:46 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.
2026/04/18 13:39:57 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.

----------------------------------------------------------------------------------------------------

[I 2026-04-18 13:39:59,709] Trial 2 finished with value: 1.1318802859472192 and parameters: {'batch_size': 64, 'dropout': 0.05, 'projec_dropout': 0.1, 'lr': 0.0001634316560750821, 'weight_decay': 1.7058847746216797e-05, 'warmup_prop': 0.03, 'mean_mode': False}. Best is trial 1 with value: 0.9568283109254735.
2026-04-18 13:40:00.279 | INFO     | modules.optuna_function:objective:85 - Trial number 3:
2026-04-18 13:40:00.280 | INFO     | modules.optuna_function:objective:86 - batch_size:32_dropout:0,3_projec_dropout:0,3_lr:0,0007188161668743731_weight_decay:0,00010318144696906423_warmup_prop:0,03_mean_mode:False_loss_temp:0,2_loss_alpha:0,3
2026-04-18 13:40:00.283 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-18 13:41:10.014 | INFO     | modules.train:run_training:178 - Epoch 0 : train total loss = 0.9814230839229557
2026-04-18 13:41:10.016 | INFO     | modules.train:run_training:179 - Epoch 0 : train contrastive loss = 3.1690172570793798
2026-04-18 13:41:10.016 | INFO     | modules.train:run_training:180 - Epoch 0 : train MSE loss = 0.04388267283479191
2026-04-18 13:41:10.018 | INFO     | modules.train:run_training:182 - Epoch 0 : validation total loss = 0.9625159751984381
2026-04-18 13:41:10.019 | INFO     | modules.train:run_training:183 - Epoch 0 : validation contrastive loss = 3.1154474237913727
2026-04-18 13:41:10.021 | INFO     | modules.train:run_training:184 - Epoch 0 : validation MSE loss = 0.03983101526635789
2026-04-18 13:41:10.085 | INFO     | modules.train:run_training:89 - Epoch 1 :
2026-04-18 13:42:18.716 | INFO     | modules.train:run_training:178 - Epoch 1 : train total loss = 0.9630628251374722
2026-04-18 13:42:18.717 | INFO     | modules.train:run_training:179 - Epoch 1 : train contrastive loss = 3.1254853727615672
2026-04-18 13:42:18.717 | INFO     | modules.train:run_training:180 - Epoch 1 : train MSE loss = 0.03631025424026788
2026-04-18 13:42:18.719 | INFO     | modules.train:run_training:182 - Epoch 1 : validation total loss = 0.9584131881754886
2026-04-18 13:42:18.720 | INFO     | modules.train:run_training:183 - Epoch 1 : validation contrastive loss = 3.1020033385163996
2026-04-18 13:42:18.721 | INFO     | modules.train:run_training:184 - Epoch 1 : validation MSE loss = 0.039731641730634114
2026-04-18 13:42:18.798 | INFO     | modules.train:run_training:89 - Epoch 2 :
2026-04-18 13:43:26.652 | INFO     | modules.train:run_training:178 - Epoch 2 : train total loss = 0.9546629905155103
2026-04-18 13:43:26.653 | INFO     | modules.train:run_training:179 - Epoch 2 : train contrastive loss = 3.098766981055044
2026-04-18 13:43:26.654 | INFO     | modules.train:run_training:180 - Epoch 2 : train MSE loss = 0.035761229462657355
2026-04-18 13:43:26.655 | INFO     | modules.train:run_training:182 - Epoch 2 : validation total loss = 0.9517513487928657
2026-04-18 13:43:26.655 | INFO     | modules.train:run_training:183 - Epoch 2 : validation contrastive loss = 3.0805161512026222
2026-04-18 13:43:26.656 | INFO     | modules.train:run_training:184 - Epoch 2 : validation MSE loss = 0.03942351401232744
2026-04-18 13:43:26.731 | INFO     | modules.train:run_training:89 - Epoch 3 :
2026-04-18 13:44:35.378 | INFO     | modules.train:run_training:178 - Epoch 3 : train total loss = 0.943992549276461
2026-04-18 13:44:35.379 | INFO     | modules.train:run_training:179 - Epoch 3 : train contrastive loss = 3.0619697063411127
2026-04-18 13:44:35.379 | INFO     | modules.train:run_training:180 - Epoch 3 : train MSE loss = 0.03628800310795483
2026-04-18 13:44:35.380 | INFO     | modules.train:run_training:182 - Epoch 3 : validation total loss = 0.9535735967338727
2026-04-18 13:44:35.381 | INFO     | modules.train:run_training:183 - Epoch 3 : validation contrastive loss = 3.084613207847841
2026-04-18 13:44:35.383 | INFO     | modules.train:run_training:184 - Epoch 3 : validation MSE loss = 0.040270846702599075
2026-04-18 13:44:35.407 | INFO     | modules.train:run_training:89 - Epoch 4 :
2026-04-18 13:45:43.961 | INFO     | modules.train:run_training:178 - Epoch 4 : train total loss = 0.9328193082143841
2026-04-18 13:45:43.962 | INFO     | modules.train:run_training:179 - Epoch 4 : train contrastive loss = 3.026513547591814
2026-04-18 13:45:43.963 | INFO     | modules.train:run_training:180 - Epoch 4 : train MSE loss = 0.03552172836598256
2026-04-18 13:45:43.963 | INFO     | modules.train:run_training:182 - Epoch 4 : validation total loss = 0.9573298551703012
2026-04-18 13:45:43.964 | INFO     | modules.train:run_training:183 - Epoch 4 : validation contrastive loss = 3.0958052091701056
2026-04-18 13:45:43.965 | INFO     | modules.train:run_training:184 - Epoch 4 : validation MSE loss = 0.040840371932473876
2026-04-18 13:45:43.965 | WARNING  | modules.train:run_training:204 - Training stops after 4 epochs
2026/04/18 13:45:44 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/18 13:45:44 WARNING mlflow.pytorch: Saving pytorch model by Pickle or CloudPickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is to set `serialization_format` to 'pt2' to save the PyTorch model using the safe graph model format.
2026/04/18 13:45:56 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.
2026/04/18 13:46:06 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.

----------------------------------------------------------------------------------------------------

[I 2026-04-18 13:46:19,616] Trial 3 finished with value: 0.9517513487928657 and parameters: {'batch_size': 32, 'dropout': 0.3, 'projec_dropout': 0.3, 'lr': 0.0007188161668743731, 'weight_decay': 0.00010318144696906423, 'warmup_prop': 0.03, 'mean_mode': False}. Best is trial 3 with value: 0.9517513487928657.
2026-04-18 13:46:20.182 | INFO     | modules.optuna_function:objective:85 - Trial number 4:
2026-04-18 13:46:20.183 | INFO     | modules.optuna_function:objective:86 - batch_size:64_dropout:0,3_projec_dropout:0,2_lr:0,00017731617223446755_weight_decay:6,669861714210607e-05_warmup_prop:0,060000000000000005_mean_mode:False_loss_temp:0,2_loss_alpha:0,3
2026-04-18 13:46:20.183 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-18 13:47:29.726 | INFO     | modules.train:run_training:178 - Epoch 0 : train total loss = 1.1879161076808193
2026-04-18 13:47:29.727 | INFO     | modules.train:run_training:179 - Epoch 0 : train contrastive loss = 3.8191415060550793
2026-04-18 13:47:29.728 | INFO     | modules.train:run_training:180 - Epoch 0 : train MSE loss = 0.06024800877112451
2026-04-18 13:47:29.729 | INFO     | modules.train:run_training:182 - Epoch 0 : validation total loss = 1.1658256598140881
2026-04-18 13:47:29.731 | INFO     | modules.train:run_training:183 - Epoch 0 : validation contrastive loss = 3.788108680559241
2026-04-18 13:47:29.732 | INFO     | modules.train:run_training:184 - Epoch 0 : validation MSE loss = 0.04198999644216636
2026-04-18 13:47:29.791 | INFO     | modules.train:run_training:89 - Epoch 1 :
2026-04-18 13:48:39.905 | INFO     | modules.train:run_training:178 - Epoch 1 : train total loss = 1.1653945752240102
2026-04-18 13:48:39.906 | INFO     | modules.train:run_training:179 - Epoch 1 : train contrastive loss = 3.802143577041976
2026-04-18 13:48:39.908 | INFO     | modules.train:run_training:180 - Epoch 1 : train MSE loss = 0.03535921841757286
2026-04-18 13:48:39.909 | INFO     | modules.train:run_training:182 - Epoch 1 : validation total loss = 1.153256716935531
2026-04-18 13:48:39.910 | INFO     | modules.train:run_training:183 - Epoch 1 : validation contrastive loss = 3.752301247223564
2026-04-18 13:48:39.910 | INFO     | modules.train:run_training:184 - Epoch 1 : validation MSE loss = 0.039380412184349865
2026-04-18 13:48:39.986 | INFO     | modules.train:run_training:89 - Epoch 2 :
2026-04-18 13:49:49.755 | INFO     | modules.train:run_training:178 - Epoch 2 : train total loss = 1.153467376297767
2026-04-18 13:49:49.756 | INFO     | modules.train:run_training:179 - Epoch 2 : train contrastive loss = 3.761225041993167
2026-04-18 13:49:49.757 | INFO     | modules.train:run_training:180 - Epoch 2 : train MSE loss = 0.035856870725033206
2026-04-18 13:49:49.758 | INFO     | modules.train:run_training:182 - Epoch 2 : validation total loss = 1.1477221587429876
2026-04-18 13:49:49.759 | INFO     | modules.train:run_training:183 - Epoch 2 : validation contrastive loss = 3.733853780704996
2026-04-18 13:49:49.761 | INFO     | modules.train:run_training:184 - Epoch 2 : validation MSE loss = 0.03937998424162683
2026-04-18 13:49:49.828 | INFO     | modules.train:run_training:89 - Epoch 3 :
2026-04-18 13:50:59.693 | INFO     | modules.train:run_training:178 - Epoch 3 : train total loss = 1.1459907550330555
2026-04-18 13:50:59.694 | INFO     | modules.train:run_training:179 - Epoch 3 : train contrastive loss = 3.7372085052892703
2026-04-18 13:50:59.694 | INFO     | modules.train:run_training:180 - Epoch 3 : train MSE loss = 0.03546879746002752
2026-04-18 13:50:59.695 | INFO     | modules.train:run_training:182 - Epoch 3 : validation total loss = 1.1468170311139978
2026-04-18 13:50:59.697 | INFO     | modules.train:run_training:183 - Epoch 3 : validation contrastive loss = 3.7299316136733345
2026-04-18 13:50:59.697 | INFO     | modules.train:run_training:184 - Epoch 3 : validation MSE loss = 0.039767863674332264
2026-04-18 13:50:59.768 | INFO     | modules.train:run_training:89 - Epoch 4 :
2026-04-18 13:52:09.883 | INFO     | modules.train:run_training:178 - Epoch 4 : train total loss = 1.1395920044785246
2026-04-18 13:52:09.885 | INFO     | modules.train:run_training:179 - Epoch 4 : train contrastive loss = 3.7167695793536826
2026-04-18 13:52:09.886 | INFO     | modules.train:run_training:180 - Epoch 4 : train MSE loss = 0.03508726274167452
2026-04-18 13:52:09.887 | INFO     | modules.train:run_training:182 - Epoch 4 : validation total loss = 1.1448075926822165
2026-04-18 13:52:09.888 | INFO     | modules.train:run_training:183 - Epoch 4 : validation contrastive loss = 3.7230573737103008
2026-04-18 13:52:09.890 | INFO     | modules.train:run_training:184 - Epoch 4 : validation MSE loss = 0.039843321413449616
2026-04-18 13:52:09.969 | INFO     | modules.train:run_training:89 - Epoch 5 :
2026-04-18 13:53:20.400 | INFO     | modules.train:run_training:178 - Epoch 5 : train total loss = 1.130742304915682
2026-04-18 13:53:20.400 | INFO     | modules.train:run_training:179 - Epoch 5 : train contrastive loss = 3.687833687581054
2026-04-18 13:53:20.401 | INFO     | modules.train:run_training:180 - Epoch 5 : train MSE loss = 0.03484593456986984
2026-04-18 13:53:20.403 | INFO     | modules.train:run_training:182 - Epoch 5 : validation total loss = 1.1486714663712874
2026-04-18 13:53:20.404 | INFO     | modules.train:run_training:183 - Epoch 5 : validation contrastive loss = 3.7348275236461475
2026-04-18 13:53:20.405 | INFO     | modules.train:run_training:184 - Epoch 5 : validation MSE loss = 0.04031881428850086
2026-04-18 13:53:20.430 | INFO     | modules.train:run_training:89 - Epoch 6 :
2026-04-18 13:54:30.499 | INFO     | modules.train:run_training:178 - Epoch 6 : train total loss = 1.1233926218584043
2026-04-18 13:54:30.500 | INFO     | modules.train:run_training:179 - Epoch 6 : train contrastive loss = 3.6633133516399137
2026-04-18 13:54:30.501 | INFO     | modules.train:run_training:180 - Epoch 6 : train MSE loss = 0.034855096284812745
2026-04-18 13:54:30.502 | INFO     | modules.train:run_training:182 - Epoch 6 : validation total loss = 1.1496537586917048
2026-04-18 13:54:30.503 | INFO     | modules.train:run_training:183 - Epoch 6 : validation contrastive loss = 3.737383308617965
2026-04-18 13:54:30.503 | INFO     | modules.train:run_training:184 - Epoch 6 : validation MSE loss = 0.04062674571152614
2026-04-18 13:54:30.504 | WARNING  | modules.train:run_training:204 - Training stops after 6 epochs
2026/04/18 13:54:30 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/18 13:54:31 WARNING mlflow.pytorch: Saving pytorch model by Pickle or CloudPickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is to set `serialization_format` to 'pt2' to save the PyTorch model using the safe graph model format.
2026/04/18 13:54:42 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.
2026/04/18 13:54:52 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.

----------------------------------------------------------------------------------------------------

[I 2026-04-18 13:55:00,871] Trial 4 finished with value: 1.1448075926822165 and parameters: {'batch_size': 64, 'dropout': 0.3, 'projec_dropout': 0.2, 'lr': 0.00017731617223446755, 'weight_decay': 6.669861714210607e-05, 'warmup_prop': 0.060000000000000005, 'mean_mode': False}. Best is trial 3 with value: 0.9517513487928657.
2026-04-18 13:55:01.449 | INFO     | modules.optuna_function:objective:85 - Trial number 5:
2026-04-18 13:55:01.450 | INFO     | modules.optuna_function:objective:86 - batch_size:32_dropout:0,1_projec_dropout:0,3_lr:0,0006418734880444401_weight_decay:0,0001681295795906461_warmup_prop:0,06999999999999999_mean_mode:True_loss_temp:0,2_loss_alpha:0,3
2026-04-18 13:55:01.452 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-18 13:56:11.100 | INFO     | modules.train:run_training:178 - Epoch 0 : train total loss = 0.9805423834231134
2026-04-18 13:56:11.101 | INFO     | modules.train:run_training:179 - Epoch 0 : train contrastive loss = 3.161586904962221
2026-04-18 13:56:11.102 | INFO     | modules.train:run_training:180 - Epoch 0 : train MSE loss = 0.04580896310678745
2026-04-18 13:56:11.102 | INFO     | modules.train:run_training:182 - Epoch 0 : validation total loss = 0.9607021180532311
2026-04-18 13:56:11.104 | INFO     | modules.train:run_training:183 - Epoch 0 : validation contrastive loss = 3.111553648466705
2026-04-18 13:56:11.105 | INFO     | modules.train:run_training:184 - Epoch 0 : validation MSE loss = 0.038908553710307485
2026-04-18 13:56:11.172 | INFO     | modules.train:run_training:89 - Epoch 1 :
2026-04-18 13:57:19.104 | INFO     | modules.train:run_training:178 - Epoch 1 : train total loss = 0.9603274358219086
2026-04-18 13:57:19.105 | INFO     | modules.train:run_training:179 - Epoch 1 : train contrastive loss = 3.1161111301361015
2026-04-18 13:57:19.105 | INFO     | modules.train:run_training:180 - Epoch 1 : train MSE loss = 0.03642008938129727
2026-04-18 13:57:19.108 | INFO     | modules.train:run_training:182 - Epoch 1 : validation total loss = 0.9527778330669608
2026-04-18 13:57:19.108 | INFO     | modules.train:run_training:183 - Epoch 1 : validation contrastive loss = 3.0839559339707896
2026-04-18 13:57:19.109 | INFO     | modules.train:run_training:184 - Epoch 1 : validation MSE loss = 0.03941574501955221
2026-04-18 13:57:19.179 | INFO     | modules.train:run_training:89 - Epoch 2 :
2026-04-18 13:58:27.250 | INFO     | modules.train:run_training:178 - Epoch 2 : train total loss = 0.9480128630620664
2026-04-18 13:58:27.251 | INFO     | modules.train:run_training:179 - Epoch 2 : train contrastive loss = 3.0748008072239856
2026-04-18 13:58:27.252 | INFO     | modules.train:run_training:180 - Epoch 2 : train MSE loss = 0.03653226402488024
2026-04-18 13:58:27.254 | INFO     | modules.train:run_training:182 - Epoch 2 : validation total loss = 0.9465762235785043
2026-04-18 13:58:27.255 | INFO     | modules.train:run_training:183 - Epoch 2 : validation contrastive loss = 3.0634035935965915
2026-04-18 13:58:27.256 | INFO     | modules.train:run_training:184 - Epoch 2 : validation MSE loss = 0.03936444214415005
2026-04-18 13:58:27.328 | INFO     | modules.train:run_training:89 - Epoch 3 :
2026-04-18 13:59:35.167 | INFO     | modules.train:run_training:178 - Epoch 3 : train total loss = 0.9352792802882686
2026-04-18 13:59:35.168 | INFO     | modules.train:run_training:179 - Epoch 3 : train contrastive loss = 3.032920456041733
2026-04-18 13:59:35.169 | INFO     | modules.train:run_training:180 - Epoch 3 : train MSE loss = 0.03629015549778666
2026-04-18 13:59:35.171 | INFO     | modules.train:run_training:182 - Epoch 3 : validation total loss = 0.9498335571699245
2026-04-18 13:59:35.172 | INFO     | modules.train:run_training:183 - Epoch 3 : validation contrastive loss = 3.0712363694303777
2026-04-18 13:59:35.173 | INFO     | modules.train:run_training:184 - Epoch 3 : validation MSE loss = 0.040660867497565284
2026-04-18 13:59:35.201 | INFO     | modules.train:run_training:89 - Epoch 4 :
2026-04-18 14:00:42.929 | INFO     | modules.train:run_training:178 - Epoch 4 : train total loss = 0.9253347010034173
2026-04-18 14:00:42.930 | INFO     | modules.train:run_training:179 - Epoch 4 : train contrastive loss = 3.0016724430450856
2026-04-18 14:00:42.930 | INFO     | modules.train:run_training:180 - Epoch 4 : train MSE loss = 0.035475618052520114
2026-04-18 14:00:42.932 | INFO     | modules.train:run_training:182 - Epoch 4 : validation total loss = 0.9561086418808148
2026-04-18 14:00:42.934 | INFO     | modules.train:run_training:183 - Epoch 4 : validation contrastive loss = 3.089607407969813
2026-04-18 14:00:42.935 | INFO     | modules.train:run_training:184 - Epoch 4 : validation MSE loss = 0.041751975724373454
2026-04-18 14:00:42.936 | WARNING  | modules.train:run_training:204 - Training stops after 4 epochs
2026/04/18 14:00:43 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/18 14:00:43 WARNING mlflow.pytorch: Saving pytorch model by Pickle or CloudPickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is to set `serialization_format` to 'pt2' to save the PyTorch model using the safe graph model format.
2026/04/18 14:00:54 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.
2026/04/18 14:01:05 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.

----------------------------------------------------------------------------------------------------

[I 2026-04-18 14:01:11,702] Trial 5 finished with value: 0.9465762235785043 and parameters: {'batch_size': 32, 'dropout': 0.1, 'projec_dropout': 0.3, 'lr': 0.0006418734880444401, 'weight_decay': 0.0001681295795906461, 'warmup_prop': 0.06999999999999999, 'mean_mode': True}. Best is trial 5 with value: 0.9465762235785043.
2026-04-18 14:01:12.436 | INFO     | modules.optuna_function:objective:85 - Trial number 6:
2026-04-18 14:01:12.437 | INFO     | modules.optuna_function:objective:86 - batch_size:64_dropout:0,05_projec_dropout:0,3_lr:0,005817200547429063_weight_decay:1,3477437675661758e-05_warmup_prop:0,08_mean_mode:False_loss_temp:0,2_loss_alpha:0,3
2026-04-18 14:01:12.440 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-18 14:02:23.953 | INFO     | modules.train:run_training:178 - Epoch 0 : train total loss = 1.1680312878494963
2026-04-18 14:02:23.954 | INFO     | modules.train:run_training:179 - Epoch 0 : train contrastive loss = 3.797605397504404
2026-04-18 14:02:23.955 | INFO     | modules.train:run_training:180 - Epoch 0 : train MSE loss = 0.04107089091194879
2026-04-18 14:02:23.955 | INFO     | modules.train:run_training:182 - Epoch 0 : validation total loss = 1.1524149827335193
2026-04-18 14:02:23.956 | INFO     | modules.train:run_training:183 - Epoch 0 : validation contrastive loss = 3.7506205258162124
2026-04-18 14:02:23.957 | INFO     | modules.train:run_training:184 - Epoch 0 : validation MSE loss = 0.0388982468487128
[I 2026-04-18 14:02:24,502] Trial 6 pruned.
2026-04-18 14:02:25.086 | INFO     | modules.optuna_function:objective:85 - Trial number 7:
2026-04-18 14:02:25.087 | INFO     | modules.optuna_function:objective:86 - batch_size:32_dropout:0,2_projec_dropout:0,2_lr:0,0013844812885690293_weight_decay:1,65014939934253e-05_warmup_prop:0,04_mean_mode:False_loss_temp:0,2_loss_alpha:0,3
2026-04-18 14:02:25.088 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-18 14:03:33.741 | INFO     | modules.train:run_training:178 - Epoch 0 : train total loss = 0.9759425147174425
2026-04-18 14:03:33.742 | INFO     | modules.train:run_training:179 - Epoch 0 : train contrastive loss = 3.1574888158444683
2026-04-18 14:03:33.744 | INFO     | modules.train:run_training:180 - Epoch 0 : train MSE loss = 0.04099404815908359
2026-04-18 14:03:33.745 | INFO     | modules.train:run_training:182 - Epoch 0 : validation total loss = 0.9601134465586755
2026-04-18 14:03:33.746 | INFO     | modules.train:run_training:183 - Epoch 0 : validation contrastive loss = 3.1093167335756364
2026-04-18 14:03:33.748 | INFO     | modules.train:run_training:184 - Epoch 0 : validation MSE loss = 0.03902627130149193
2026-04-18 14:03:33.806 | INFO     | modules.train:run_training:89 - Epoch 1 :
2026-04-18 14:04:42.212 | INFO     | modules.train:run_training:178 - Epoch 1 : train total loss = 0.9614757418086927
2026-04-18 14:04:42.213 | INFO     | modules.train:run_training:179 - Epoch 1 : train contrastive loss = 3.1195953170549404
2026-04-18 14:04:42.214 | INFO     | modules.train:run_training:180 - Epoch 1 : train MSE loss = 0.03656730235999693
2026-04-18 14:04:42.215 | INFO     | modules.train:run_training:182 - Epoch 1 : validation total loss = 0.9565815271869782
2026-04-18 14:04:42.216 | INFO     | modules.train:run_training:183 - Epoch 1 : validation contrastive loss = 3.097046334256408
2026-04-18 14:04:42.217 | INFO     | modules.train:run_training:184 - Epoch 1 : validation MSE loss = 0.03923942431587205
2026-04-18 14:04:42.298 | INFO     | modules.train:run_training:89 - Epoch 2 :
2026-04-18 14:05:50.472 | INFO     | modules.train:run_training:178 - Epoch 2 : train total loss = 0.9558599218896652
2026-04-18 14:05:50.473 | INFO     | modules.train:run_training:179 - Epoch 2 : train contrastive loss = 3.101521200664529
2026-04-18 14:05:50.475 | INFO     | modules.train:run_training:180 - Epoch 2 : train MSE loss = 0.03629075483796219
2026-04-18 14:05:50.476 | INFO     | modules.train:run_training:182 - Epoch 2 : validation total loss = 0.956344969810978
2026-04-18 14:05:50.477 | INFO     | modules.train:run_training:183 - Epoch 2 : validation contrastive loss = 3.098733430267662
2026-04-18 14:05:50.478 | INFO     | modules.train:run_training:184 - Epoch 2 : validation MSE loss = 0.038178434991027396
2026-04-18 14:05:50.547 | INFO     | modules.train:run_training:89 - Epoch 3 :
2026-04-18 14:06:58.739 | INFO     | modules.train:run_training:178 - Epoch 3 : train total loss = 0.9499861386602476
2026-04-18 14:06:58.740 | INFO     | modules.train:run_training:179 - Epoch 3 : train contrastive loss = 3.0831928826033113
2026-04-18 14:06:58.742 | INFO     | modules.train:run_training:180 - Epoch 3 : train MSE loss = 0.035754629136947595
2026-04-18 14:06:58.743 | INFO     | modules.train:run_training:182 - Epoch 3 : validation total loss = 0.9592271652272952
2026-04-18 14:06:58.744 | INFO     | modules.train:run_training:183 - Epoch 3 : validation contrastive loss = 3.1050937611569642
2026-04-18 14:06:58.745 | INFO     | modules.train:run_training:184 - Epoch 3 : validation MSE loss = 0.039570003707883175
2026-04-18 14:06:58.774 | INFO     | modules.train:run_training:89 - Epoch 4 :
2026-04-18 14:08:07.017 | INFO     | modules.train:run_training:178 - Epoch 4 : train total loss = 0.9426414039096789
2026-04-18 14:08:07.018 | INFO     | modules.train:run_training:179 - Epoch 4 : train contrastive loss = 3.05978636828931
2026-04-18 14:08:07.018 | INFO     | modules.train:run_training:180 - Epoch 4 : train MSE loss = 0.035293511807645755
2026-04-18 14:08:07.020 | INFO     | modules.train:run_training:182 - Epoch 4 : validation total loss = 0.9619642169244828
2026-04-18 14:08:07.020 | INFO     | modules.train:run_training:183 - Epoch 4 : validation contrastive loss = 3.112149061695222
2026-04-18 14:08:07.023 | INFO     | modules.train:run_training:184 - Epoch 4 : validation MSE loss = 0.04045637917294297
2026-04-18 14:08:07.024 | WARNING  | modules.train:run_training:204 - Training stops after 4 epochs
2026/04/18 14:08:07 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/18 14:08:07 WARNING mlflow.pytorch: Saving pytorch model by Pickle or CloudPickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is to set `serialization_format` to 'pt2' to save the PyTorch model using the safe graph model format.
2026/04/18 14:08:31 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.
2026/04/18 14:08:41 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.

----------------------------------------------------------------------------------------------------

[I 2026-04-18 14:08:51,703] Trial 7 finished with value: 0.956344969810978 and parameters: {'batch_size': 32, 'dropout': 0.2, 'projec_dropout': 0.2, 'lr': 0.0013844812885690293, 'weight_decay': 1.65014939934253e-05, 'warmup_prop': 0.04, 'mean_mode': False}. Best is trial 5 with value: 0.9465762235785043.
2026-04-18 14:08:52.449 | INFO     | modules.optuna_function:objective:85 - Trial number 8:
2026-04-18 14:08:52.450 | INFO     | modules.optuna_function:objective:86 - batch_size:64_dropout:0,1_projec_dropout:0,3_lr:0,001877714943251037_weight_decay:2,3227782711772806e-05_warmup_prop:0,02_mean_mode:True_loss_temp:0,2_loss_alpha:0,3
2026-04-18 14:08:52.451 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-18 14:10:04.484 | INFO     | modules.train:run_training:178 - Epoch 0 : train total loss = 1.1683571437083253
2026-04-18 14:10:04.485 | INFO     | modules.train:run_training:179 - Epoch 0 : train contrastive loss = 3.802050120239958
2026-04-18 14:10:04.486 | INFO     | modules.train:run_training:180 - Epoch 0 : train MSE loss = 0.03963151657013991
2026-04-18 14:10:04.488 | INFO     | modules.train:run_training:182 - Epoch 0 : validation total loss = 1.1538889252621194
2026-04-18 14:10:04.489 | INFO     | modules.train:run_training:183 - Epoch 0 : validation contrastive loss = 3.755170137985893
2026-04-18 14:10:04.490 | INFO     | modules.train:run_training:184 - Epoch 0 : validation MSE loss = 0.039054059241290975
[I 2026-04-18 14:10:05,016] Trial 8 pruned.
2026-04-18 14:10:05.593 | INFO     | modules.optuna_function:objective:85 - Trial number 9:
2026-04-18 14:10:05.594 | INFO     | modules.optuna_function:objective:86 - batch_size:64_dropout:0,2_projec_dropout:0,1_lr:0,009551149538488587_weight_decay:2,6459561191165836e-05_warmup_prop:0,09_mean_mode:True_loss_temp:0,2_loss_alpha:0,3
2026-04-18 14:10:05.596 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-18 14:11:16.148 | INFO     | modules.train:run_training:178 - Epoch 0 : train total loss = 1.168876649042882
2026-04-18 14:11:16.149 | INFO     | modules.train:run_training:179 - Epoch 0 : train contrastive loss = 3.801953684299364
2026-04-18 14:11:16.150 | INFO     | modules.train:run_training:180 - Epoch 0 : train MSE loss = 0.040414997641373115
2026-04-18 14:11:16.152 | INFO     | modules.train:run_training:182 - Epoch 0 : validation total loss = 1.150739161864571
2026-04-18 14:11:16.153 | INFO     | modules.train:run_training:183 - Epoch 0 : validation contrastive loss = 3.7447133634401406
2026-04-18 14:11:16.155 | INFO     | modules.train:run_training:184 - Epoch 0 : validation MSE loss = 0.03903586994451673
[I 2026-04-18 14:11:16,730] Trial 9 pruned.

In [ ]:
study_loaded=optuna.load_study(study_name="recommendation_system_model_study",storage="sqlite:///optuna_study.db")

In [ ]:
"""
study_best_components={
    "study_best_params":study_loaded.best_params,
    "study_best_value":study_loaded.best_value
}
torch.save(study_best_components,"./study_best_components.pt")
"""

In [19]:
fig=optuna.visualization.plot_param_importances(study_loaded)
fig.show()

In [20]:
fig=optuna.visualization.plot_parallel_coordinate(study_loaded)
fig.show()

In [21]:
fig=optuna.visualization.plot_optimization_history(study_loaded)
fig.show()

In [ ]:
"""
best_model_name="Best_Recommendation_System_model"
best_model_uri=f"runs:/7edda145087b428f97b3f753e1301f0b/model_5"
registration=mlflow.register_model(best_model_uri,best_model_name)
"""

c:\Users\sh032\anaconda3\Lib\site-packages\mlflow\tracking\_model_registry\utils.py:220: FutureWarning:

The filesystem model registry backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.

Successfully registered model 'Best_Recommendation_System_model'.
2026/04/19 19:46:39 WARNING mlflow.tracking._model_registry.fluent: Run with id 7edda145087b428f97b3f753e1301f0b has no artifacts at artifact path 'model_5', registering model based on models:/m-d2b1b983ece842189a76e5eb1fce4715 instead
Created version '1' of model 'Best_Recommendation_System_model'.

In [ ]:
"""
client.transition_model_version_stage(
    name="Best_Recommendation_System_model",
    version=1,
    stage="Staging"
)
"""

C:\Users\sh032\AppData\Local\Temp\ipykernel_20180\3505277116.py:1: FutureWarning:

``mlflow.tracking.client.MlflowClient.transition_model_version_stage`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages

<ModelVersion: aliases=[], creation_timestamp=1776642399527, current_stage='Staging', deployment_job_state=None, description=None, last_updated_timestamp=1776642427017, metrics=[<Metric: dataset_digest=None, dataset_name=None, key='best_validation_contrastive_loss', model_id='m-d2b1b983ece842189a76e5eb1fce4715', run_id='7edda145087b428f97b3f753e1301f0b', step=0, timestamp=1776520843130, value=3.0634035935965915>,
 <Metric: dataset_digest=None, dataset_name=None, key='best_validation_MSE_loss', model_id='m-d2b1b983ece842189a76e5eb1fce4715', run_id='7edda145087b428f97b3f753e1301f0b', step=0, timestamp=1776520843130, value=0.03936444214415005>,
 <Metric: dataset_digest=None, dataset_name=None, key='best_validation_total_loss', model_id='m-d2b1b983ece842189a76e5eb1fce4715', run_id='7edda145087b428f97b3f753e1301f0b', step=0, timestamp=1776520843130, value=0.9465762235785043>,
 <Metric: dataset_digest=None, dataset_name=None, key='epoch_train_contrastive_loss', model_id='m-d2b1b983ece842189a76e5eb1fce4715', run_id='7edda145087b428f97b3f753e1301f0b', step=0, timestamp=1776520843153, value=3.161586904962221>,
 <Metric: dataset_digest=None, dataset_name=None, key='epoch_train_mse_loss', model_id='m-d2b1b983ece842189a76e5eb1fce4715', run_id='7edda145087b428f97b3f753e1301f0b', step=0, timestamp=1776520843153, value=0.04580896310678745>,
 <Metric: dataset_digest=None, dataset_name=None, key='epoch_train_total_loss', model_id='m-d2b1b983ece842189a76e5eb1fce4715', run_id='7edda145087b428f97b3f753e1301f0b', step=0, timestamp=1776520843153, value=0.9805423834231134>,
 <Metric: dataset_digest=None, dataset_name=None, key='epoch_validation_contrastive_loss', model_id='m-d2b1b983ece842189a76e5eb1fce4715', run_id='7edda145087b428f97b3f753e1301f0b', step=0, timestamp=1776520843153, value=3.111553648466705>,
 <Metric: dataset_digest=None, dataset_name=None, key='epoch_validation_mse_loss', model_id='m-d2b1b983ece842189a76e5eb1fce4715', run_id='7edda145087b428f97b3f753e1301f0b', step=0, timestamp=1776520843153, value=0.038908553710307485>,
 <Metric: dataset_digest=None, dataset_name=None, key='epoch_validation_total_loss', model_id='m-d2b1b983ece842189a76e5eb1fce4715', run_id='7edda145087b428f97b3f753e1301f0b', step=0, timestamp=1776520843153, value=0.9607021180532311>], model_id='m-d2b1b983ece842189a76e5eb1fce4715', name='Best_Recommendation_System_model', params={'batch_size': '32',
 'dropout': '0.1',
 'loss_alpha': '0.3',
 'loss_temperature': '0.2',
 'lr': '0.0006418734880444401',
 'mean_mode': 'True',
 'projec_dropout': '0.3',
 'warmup_prop': '0.06999999999999999',
 'weight_decay': '0.0001681295795906461'}, run_id='7edda145087b428f97b3f753e1301f0b', run_link=None, source='models:/m-d2b1b983ece842189a76e5eb1fce4715', status='READY', status_message=None, tags={}, user_id=None, version=1, workspace='default'>

In [ ]:
"""
model_version=client.get_model_version("Best_Recommendation_System_model",1)
version=int(model_version.version)
client.set_model_version_tag(name="Best_Recommendation_System_model",key="Role",value="Challenger",version=version)
client.set_model_version_tag(name="Best_Recommendation_System_model",key="Stage",value="Staging",version=version)
client.set_registered_model_alias(name="Best_Recommendation_System_model",alias="Challenger",version=version)
"""

In [6]:
device = (torch.device("mps") if torch.backends.mps.is_available() else torch.device("cuda" if torch.cuda.is_available() else "cpu"))

model_version=client.get_model_version("Best_Recommendation_System_model",1)
best_model_registered_uri=f"models:/Best_Recommendation_System_model/{model_version.version}"
best_recommendation_model=mlflow.pytorch.load_model(best_model_registered_uri,map_location=torch.device("cpu"))
best_recommendation_model.device=device


batch_size=int(model_version.params["batch_size"])
loss_temperature=float(model_version.params["loss_temperature"])
loss_alpha=float(model_version.params["loss_alpha"])
run_id=model_version.run_id

test_dataset=CreationDataset(test_df_processed,test_cls_embeddings,test_mean_embeddings)
generator=torch.Generator()
generator.manual_seed(seed)
collate_function_object=CollateFunction()
collate_fn=collate_function_object.collate_fn
test_dataloader=DataLoader(test_dataset,batch_size=batch_size,collate_fn=collate_fn,generator=generator,worker_init_fn=seed_worker,shuffle=True,drop_last=True)

tester=Test(test_dataloader=test_dataloader,model=best_recommendation_model,device=device,loss_alpha=loss_alpha,loss_temperature=loss_temperature)
test_total_loss,test_contrastive_loss,test_mse_loss=tester.run_testing(f"./test_savings",run_id=run_id)

c:\Users\sh032\anaconda3\Lib\site-packages\mlflow\tracking\_model_registry\utils.py:220: FutureWarning:

The filesystem model registry backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.

2026/04/22 19:03:04 WARNING mlflow.pytorch: Stored model version '2.10.0+cu128' does not match installed PyTorch version '2.8.0+cpu'
2026-04-22 19:03:05.332 | INFO     | modules.test:run_testing:25 - Start of the test :
2026-04-22 19:05:05.426 | INFO     | modules.test:run_testing:63 - Test Total loss = 0.950422175468937
2026-04-22 19:05:05.427 | INFO     | modules.test:run_testing:64 - Test Contrastive loss = 3.0739834693170365
2026-04-22 19:05:05.427 | INFO     | modules.test:run_testing:65 - Test MSE loss = 0.04032442552508206

In [ ]:
"""
model_version=client.get_model_version("Best_Recommendation_System_model",1)
version=int(model_version.version)
test_metrics=torch.load("./test_savings/test_metrics.pt",weights_only=False)
for key,value in test_metrics.items():
    client.set_model_version_tag("Best_Recommendation_System_model",version=1,key=key,value=value)
"""

In [7]:
recipes_df,recipes_set_cls_embeddings,recipes_set_mean_embeddings=creation_recipes_set(full_df,all_cls_embeddings,all_mean_embeddings,path="./modules/recipes_set")

In [8]:
print(recipes_df.shape)
print(recipes_set_cls_embeddings.shape)
print(recipes_set_mean_embeddings.shape)

(15423, 13)
torch.Size([15423, 768])
torch.Size([15423, 768])

In [9]:
PP_recipes_df=pd.read_csv("data/PP_recipes.csv")
PP_recipes_df["len_ingredients"]=PP_recipes_df["ingredient_ids"].str.count(r",")+1
max_len_ingredients=PP_recipes_df["len_ingredients"].max()
PP_recipes_df.drop(columns=["len_ingredients"],inplace=True)

In [10]:
recipe_before_split_processor=BeforeSplitPreprocessingRecipesFeatures(recipes_df,max_len_ingredients)
recipes_df_processed=recipe_before_split_processor.preprocessing()

In [11]:
ingredient_continuous_ids=pd.read_pickle("./modules/dataframes/ingredient_continuous_ids.pkl")

In [12]:
def mapping_list(x:list,mapping_serie:pd.Series):
    return [mapping_serie.loc[i] if i in mapping_serie.index else 0 for i in x]
recipes_df_processed["ingredient_ids_continuous"]=recipes_df_processed["ingredient_ids"].apply(lambda x : mapping_list(x,ingredient_continuous_ids))

In [13]:
recipes_df_processed["full_text"]=recipes_df_processed["name"]+" [SEP] "+recipes_df_processed["description"]+" [SEP] "+recipes_df_processed["steps"]+" [SEP] "+recipes_df_processed["tags"]

In [14]:
recipe_after_split_processor=AfterSplitPreprocessingRecipesFeatures(train_df)
recipes_df_processed=recipe_after_split_processor.preprocessing(recipes_df_processed)

In [15]:
scaler_recipes=joblib.load("./modules/scalers/scaler_recipes.pkl")
recipes_scaler=ScalerInferenceRecipes(scaler_recipes)
recipes_df_processed=recipes_scaler.scale(recipes_df_processed)

In [16]:
recipes_df_processed.to_parquet("./modules/recipes_set/recipes_df_processed.parquet")

In [6]:
recipes_processed_parquet_file=pq.ParquetFile("./modules/recipes_set/recipes_df_processed.parquet")
recipes_parquet_file=pq.ParquetFile("./modules/recipes_set/recipes_df.parquet")

recipes_df=load(recipes_parquet_file)
recipes_df_processed=load(recipes_processed_parquet_file)
recipes_set_cls_embeddings=torch.load("./modules/recipes_set/recipes_set_cls_embeddings.pt")
recipes_set_mean_embeddings=torch.load("./modules/recipes_set/recipes_set_mean_embeddings.pt")

In [7]:
print(recipes_df.columns)

Index(['recipe_id', 'i', 'name', 'description', 'tags', 'calorie_level',
       'minutes', 'n_ingredients', 'ingredient_ids', 'nutrition', 'n_steps',
       'steps', 'techniques_recipes'],
      dtype='object')

In [8]:
print(recipes_df_processed.columns)
print(recipes_df_processed.shape)
print(recipes_set_cls_embeddings.shape)
print(recipes_set_mean_embeddings.shape)

Index(['recipe_id', 'i', 'name', 'description', 'tags', 'calorie_level',
       'minutes', 'n_ingredients', 'ingredient_ids', 'nutrition', 'n_steps',
       'steps', 'techniques_recipes', 'ingredient_ids_continuous', 'full_text',
       'calorie_level_scaled', 'minutes_scaled', 'n_steps_scaled',
       'n_ingredients_scaled'],
      dtype='object')
(15423, 19)
torch.Size([15423, 768])
torch.Size([15423, 768])

In [9]:
device = (torch.device("mps") if torch.backends.mps.is_available() else torch.device("cuda" if torch.cuda.is_available() else "cpu"))

model_version=client.get_model_version("Best_Recommendation_System_model",1)
best_model_registered_uri=f"models:/Best_Recommendation_System_model/1"
best_recommendation_model=mlflow.pytorch.load_model(best_model_registered_uri,map_location=torch.device("cpu"))
best_recommendation_model.device=device

batch_size=int(model_version.params["batch_size"])
recipes_dataset=CreationDataset(recipes_df_processed,recipes_set_cls_embeddings,recipes_set_mean_embeddings)
generator=torch.Generator()
generator.manual_seed(seed)
collate_function_object=CollateFunctionInferenceRecipes()
collate_fn=collate_function_object.collate_fn
recipes_dataloader=DataLoader(recipes_dataset,batch_size=batch_size,collate_fn=collate_fn,generator=generator,worker_init_fn=seed_worker,shuffle=False,drop_last=False)


recipes_embeddings_extractor=RecipesEmbeddingsExtractor(model=best_recommendation_model,device=device)
recipes_embeddings=recipes_embeddings_extractor.get_recipes_embeddings(dataloader=recipes_dataloader,path=f"./modules/recipes_set")

c:\Users\sh032\anaconda3\Lib\site-packages\mlflow\tracking\_model_registry\utils.py:220: FutureWarning:

The filesystem model registry backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.

2026/04/22 19:09:11 WARNING mlflow.pytorch: Stored model version '2.10.0+cu128' does not match installed PyTorch version '2.8.0+cpu'

In [9]:
recipes_embeddings=torch.load("./modules/recipes_set/recipes_embeddings.pt")
print(recipes_embeddings.shape)

torch.Size([15423, 256])

In [7]:
recipes_parquet_file=pq.ParquetFile("./modules/recipes_set/recipes_df.parquet")
recipes_df=load(recipes_parquet_file)

recipes_embeddings=torch.load(f"./modules/recipes_set/recipes_embeddings.pt")

scaler_user=joblib.load("./modules/scalers/scaler_users.pkl")

PP_users_df["len_items"]=PP_users_df["items"].str.count(r",")+1
max_len_items=PP_users_df["len_items"].max()
PP_users_df.drop(columns=["len_items"],inplace=True)

n_techniques_users=len(full_df_processed.loc[~full_df_processed["techniques_users"].isna(),"techniques_users"].iloc[0])

print(max_len_items)
print(n_techniques_users)

6437
58

In [ ]:
device = (torch.device("mps") if torch.backends.mps.is_available() else torch.device("cuda" if torch.cuda.is_available() else "cpu"))

best_model_registered_uri=f"models:/Best_Recommendation_System_model/1"
best_recommendation_model=mlflow.pytorch.load_model(best_model_registered_uri,map_location=torch.device("cpu"))
best_recommendation_model.device=device

recipes_recommender=RecipesRecommender(device=device,model=best_recommendation_model,recipes_embeddings=recipes_embeddings,recipes_df=recipes_df,train_df=train_df,scaler_user=scaler_user,max_len_items=max_len_items,n_techniques_users=n_techniques_users)

2026/04/22 20:52:35 WARNING mlflow.pytorch: Stored model version '2.10.0+cu128' does not match installed PyTorch version '2.8.0+cpu'

In [12]:
user_id=full_df.loc[full_df["rating"]==5,"user_id"].iloc[0]
ratings=full_df.loc[full_df["rating"]==5,"ratings"].iloc[0]
items=full_df.loc[full_df["rating"]==5,"items"].iloc[0]
techniques_users=full_df.loc[full_df["rating"]==5,"techniques_users"].iloc[0]
n_items=full_df.loc[full_df["rating"]==5,"n_items"].iloc[0]
n_ratings=full_df.loc[full_df["rating"]==5,"n_ratings"].iloc[0]
n_recommended_recipes=5

recommended_recipes=recipes_recommender.get_recommendations(
    user_id=user_id,
    ratings=ratings,
    items=items,
    techniques_users=techniques_users,
    n_items=n_items,
    n_ratings=n_ratings,
    n_recommended_recipes=n_recommended_recipes
)

c:\Users\sh032\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning:

X does not have valid feature names, but StandardScaler was fitted with feature names

In [13]:
display(recommended_recipes)

,recipe_id,i,name,description,tags,calorie_level,minutes,n_ingredients,ingredient_ids,nutrition,n_steps,steps,techniques_recipes,cos_sim_scores
10256,70046,117001,white pizza with shellfish,this is a quick dinner solution for the weekda...,"['60-minutes-or-less', 'time-to-make', 'course...",0,35,9,"[5483, 5006, 4814, 3184, 6336, 6487, 7213, 344...","[185.8, 21.0, 7.0, 7.0, 22.0, 30.0, 1.0]",7,"['heat oven to 400', 'place pizza crust on a g...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.952273
3600,63624,40832,the best darn way to barbecue chicken,this chicken is basted with a buttery herb sau...,"['weeknight', 'time-to-make', 'course', 'main-...",2,70,11,"[1240, 4574, 2325, 3184, 6183, 7168, 5106, 382...","[882.0, 129.0, 1.0, 34.0, 59.0, 86.0, 0.0]",11,['prepare the chicken as indicated then wash i...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.949260
13124,100353,150519,baked spaghetti casserole,we love the market day spaghetti pie casserole...,"['60-minutes-or-less', 'time-to-make', 'course...",2,45,13,"[132, 5180, 2499, 4717, 4574, 3484, 3184, 5010...","[4002.7, 278.0, 65.0, 81.0, 443.0, 321.0, 118.0]",16,['preheat oven to 350 and pam a 13x9 deep baki...,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.948888
11753,211537,134346,beijing chicken and dumplings,"ah, the comforting feeling of a big pot of chi...","['time-to-make', 'course', 'main-ingredient', ...",0,100,15,"[1240, 1257, 5975, 3269, 1251, 3184, 6696, 762...","[240.5, 23.0, 15.0, 25.0, 37.0, 21.0, 2.0]",7,"['in a large soup pot , combine all ingredient...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0.945110
5916,93317,67152,savory chicken egg rolls with sweet and sour ...,"a fun change from ordinary egg rolls, this chi...","['time-to-make', 'course', 'main-ingredient', ...",0,65,18,"[3492, 2499, 1706, 8021, 6335, 1093, 893, 3046...","[162.0, 4.0, 15.0, 8.0, 15.0, 3.0, 8.0]",9,['combine all filling ingredients in a large b...,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0.944351