In [1]:
import pandas as pd
import numpy as np
import ast
import random
import numpy as np
from modules import DataFramePreprocessing
import torch
from torch.nn import Embedding
import mmh3
from transformers import get_linear_schedule_with_warmup,AutoTokenizer,DistilBertModel

In [2]:
interactions_train_df=pd.read_csv("data/interactions_train.csv")
PP_recipes_df=pd.read_csv("data/PP_recipes.csv")
PP_users_df=pd.read_csv("data/PP_users.csv")
RAW_interactions_df=pd.read_csv("data/RAW_interactions.csv")
RAW_recipes_df=pd.read_csv("data/RAW_recipes.csv")

In [3]:
interactions_train_df_filtered=interactions_train_df.sample(n=50000,replace=False)

In [4]:
print(interactions_train_df_filtered.shape)

(50000, 6)

In [5]:
RAW_recipes_df.rename(columns={"id":"recipe_id"},inplace=True)
PP_recipes_df.rename(columns={"techniques":"techniques_recipes"},inplace=True)
PP_users_df.rename(columns={"techniques":"techniques_users"},inplace=True)

In [6]:
print("interactions_train_df_filtered columns:")
print(interactions_train_df_filtered.columns)
print("------------------------------------------------------------------")
print("PP_recipes_df columns:")
print(PP_recipes_df.columns)
print("-------------------------------------------------------------------")
print("PP_users_df columns:")
print(PP_users_df.columns)
print("----------------------------------------------------------------------")
print("RAW_interactions_df columns:")
print(RAW_interactions_df.columns)
print("------------------------------------------------------------------------")
print("RAW_recipes_df columns:")
print(RAW_recipes_df.columns)

interactions_train_df_filtered columns:
Index(['user_id', 'recipe_id', 'date', 'rating', 'u', 'i'], dtype='object')
------------------------------------------------------------------
PP_recipes_df columns:
Index(['id', 'i', 'name_tokens', 'ingredient_tokens', 'steps_tokens',
       'techniques_recipes', 'calorie_level', 'ingredient_ids'],
      dtype='object')
-------------------------------------------------------------------
PP_users_df columns:
Index(['u', 'techniques_users', 'items', 'n_items', 'ratings', 'n_ratings'], dtype='object')
----------------------------------------------------------------------
RAW_interactions_df columns:
Index(['user_id', 'recipe_id', 'date', 'rating', 'review'], dtype='object')
------------------------------------------------------------------------
RAW_recipes_df columns:
Index(['name', 'recipe_id', 'minutes', 'contributor_id', 'submitted', 'tags',
       'nutrition', 'n_steps', 'steps', 'description', 'ingredients',
       'n_ingredients'],
      dtype='object')

In [7]:
full_df=interactions_train_df_filtered.merge(PP_recipes_df,on="i",how="left",suffixes=(None,"_1")).merge(PP_users_df,on="u",how="left",suffixes=(None,"_2")).merge(RAW_interactions_df,on=["user_id","recipe_id"],how="left",suffixes=(None,"_3")).merge(RAW_recipes_df,on=["recipe_id"],how="left",suffixes=(None,"_3"))

In [ ]:
full_df=full_df.drop(columns=["review",'rating_3',"id","ingredients","submitted","contributor_id","date_3","date","steps_tokens","ingredient_tokens","name_tokens","u"],axis=1)

In [9]:
print(f"Columns of the full dataframe:")
print(full_df.columns)
print("----------------------------------------")
print(f"Shape of the full dataframe:")
print(full_df.shape)
print("----------------------------------------")
print(f"Columns of the filtered interaction dataframe:")
print(interactions_train_df_filtered.shape)
print("----------------------------------------")
print(f"Head of the full  dataframe:")
display(full_df.head())
print("----------------------------------------")
for col in full_df.columns:
    print(f"Unique values of {col} :")
    print(full_df[col].unique())
    print("----------------------------------------")
for col in full_df.columns:
    print(f"The type of {col} is")
    print(full_df[col].apply(type).unique())
    print("---------------------------------")

Columns of the full dataframe:
Index(['user_id', 'recipe_id', 'rating', 'i', 'techniques_recipes',
       'calorie_level', 'ingredient_ids', 'techniques_users', 'items',
       'n_items', 'ratings', 'n_ratings', 'review', 'name', 'minutes', 'tags',
       'nutrition', 'n_steps', 'steps', 'description', 'n_ingredients'],
      dtype='object')
----------------------------------------
Shape of the full dataframe:
(50000, 21)
----------------------------------------
Columns of the filtered interaction dataframe:
(50000, 6)
----------------------------------------
Head of the full  dataframe:

,user_id,recipe_id,rating,i,techniques_recipes,calorie_level,ingredient_ids,techniques_users,items,n_items,...,n_ratings,review,name,minutes,tags,nutrition,n_steps,steps,description,n_ingredients
0,89366,151621,5.0,165827,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...",2,"[5890, 1954, 5314, 840, 6335, 3203, 7705, 3810...","[4, 1, 0, 1, 2, 0, 1, 0, 0, 4, 0, 0, 0, 1, 0, ...","[109573, 68779, 176014, 14451, 165827, 69725, ...",8,...,8,Loved this! I made sure each of my shrimp were...,shrimp and pasta with creole cream sauce,48,"['60-minutes-or-less', 'time-to-make', 'course...","[906.9, 72.0, 2.0, 23.0, 96.0, 135.0, 24.0]",18,"['peel and devein shrimp', 'toss shrimp with c...",from southern living.,10
1,179133,275036,5.0,104393,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,"[2991, 3440, 5010, 3203, 840, 5006, 6273, 5180]","[357, 7, 3, 144, 158, 0, 3, 23, 2, 322, 13, 29...","[90890, 135961, 12856, 128256, 37047, 153154, ...",970,...,970,This was very nice! I used red bell pepper and...,easy weeknight corn,15,"['15-minutes-or-less', 'time-to-make', 'course...","[270.4, 20.0, 4.0, 3.0, 11.0, 37.0, 12.0]",6,"['in pan / dutch oven , add butter , olive oil...",i threw some things together in a dutch oven a...,8
2,1812036,32871,5.0,99923,"[1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,"[3729, 840, 6906, 5298, 1388]","[4, 0, 0, 4, 3, 0, 0, 0, 0, 5, 0, 1, 0, 0, 0, ...","[89900, 163127, 109865, 90632, 167568, 99923, ...",9,...,9,These are addicting! I also followed the advic...,chocolate toffee graham treats,25,"['30-minutes-or-less', 'time-to-make', 'course...","[177.7, 19.0, 57.0, 3.0, 1.0, 34.0, 5.0]",12,"['preheat oven to 350', 'arrange graham cracke...",these are delicious and easy (only 5 ingredien...,5
3,560491,167273,5.0,31341,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,"[840, 6906, 1680, 6389, 1388, 4493]","[497, 10, 3, 169, 257, 0, 1, 50, 11, 456, 21, ...","[12790, 65277, 78451, 104846, 71019, 122679, 5...",1253,...,1253,These were really good! My DSs were a little ...,chocolate chip biscuits aussie style,30,"['30-minutes-or-less', 'time-to-make', 'course...","[98.9, 8.0, 27.0, 1.0, 2.0, 16.0, 4.0]",8,"['cream together the butter and sugar', 'add t...","these are a very ""moresome"" bikky:) i used to ...",6
4,55756,45755,4.0,17323,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, ...",1,"[5574, 340, 6531, 6335, 7946, 7041, 6696, 2809...","[1, 0, 0, 1, 3, 0, 0, 0, 0, 8, 7, 2, 0, 0, 1, ...","[126928, 1108, 40888, 46727, 149767, 117646, 1...",22,...,22,this was very good! i couldn't readily find ho...,szechuan pork crock pot,255,"['weeknight', 'time-to-make', 'course', 'main-...","[416.4, 25.0, 39.0, 52.0, 82.0, 24.0, 7.0]",5,['trim chops of excess fat and brown on both s...,all the pleasure of a chinese meal right out o...,13

----------------------------------------
Unique values of user_id :
[  89366  179133 1812036 ...  716888 1688413  377077]
----------------------------------------
Unique values of recipe_id :
[151621 275036  32871 ... 379967 181797 411112]
----------------------------------------
Unique values of rating :
[5. 4. 0. 3. 2. 1.]
----------------------------------------
Unique values of i :
[165827 104393  99923 ... 156917 138541 125582]
----------------------------------------
Unique values of techniques_recipes :
['[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0]'
 '[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'
 '[1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'
 ...
 '[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'
 '[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'
 '[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]']
----------------------------------------
Unique values of calorie_level :
[2 1 0]
----------------------------------------
Unique values of ingredient_ids :
['[5890, 1954, 5314, 840, 6335, 3203, 7705, 3810, 2856, 5180]'
 '[2991, 3440, 5010, 3203, 840, 5006, 6273, 5180]'
 '[3729, 840, 6906, 5298, 1388]' ... '[5648, 840, 2832, 6374, 3217]'
 '[840, 2786, 6270, 6906, 2757]'
 '[1252, 2128, 999, 7362, 1257, 840, 5006]']
----------------------------------------
Unique values of techniques_users :
['[4, 1, 0, 1, 2, 0, 1, 0, 0, 4, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0]'
 '[357, 7, 3, 144, 158, 0, 3, 23, 2, 322, 13, 29, 1, 2, 18, 0, 152, 0, 1, 24, 51, 40, 3, 35, 1, 0, 10, 32, 219, 63, 0, 9, 1, 215, 0, 18, 109, 20, 54, 0, 3, 39, 121, 104, 6, 7, 92, 7, 0, 11, 1, 19, 1, 29, 57, 91, 40, 73]'
 '[4, 0, 0, 4, 3, 0, 0, 0, 0, 5, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]'
 ...
 '[2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'
 '[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'
 '[2, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]']
----------------------------------------
Unique values of items :
['[109573, 68779, 176014, 14451, 165827, 69725, 114402, 170786]'
 '[90890, 135961, 12856, 128256, 37047, 153154, 43103, 19651, 39511, 169929, 1022, 63785, 128131, 73875, 147571, 47485, 156063, 63999, 43834, 29880, 106162, 164445, 38413, 123503, 80000, 93318, 46604, 69019, 138955, 7901, 113588, 175236, 148917, 153685, 23894, 64696, 36125, 134348, 38758, 37084, 25023, 103661, 88478, 2627, 101963, 20533, 33794, 157664, 42836, 44444, 141968, 17856, 175967, 8722, 114625, 41204, 155785, 10015, 73995, 111854, 140898, 131697, 105538, 164087, 130878, 11376, 54884, 22938, 53881, 114193, 132152, 104261, 113511, 157581, 159649, 111162, 11359, 11482, 100060, 98728, 21024, 121777, 86723, 52621, 157129, 176948, 16897, 94731, 37473, 177003, 138375, 140730, 31260, 126646, 1601, 41130, 145861, 54832, 170906, 28771, 129198, 168757, 121725, 34313, 103904, 47599, 82539, 15562, 93630, 85293, 9890, 41533, 124718, 110847, 13671, 6063, 52578, 98905, 41011, 105298, 85260, 61631, 160198, 142586, 4163, 85170, 164735, 45380, 134999, 118542, 173028, 153735, 170516, 102693, 71879, 159783, 86884, 119201, 44879, 54494, 174987, 96470, 12928, 115801, 83588, 115272, 29285, 50752, 91330, 164438, 134133, 150505, 41410, 149075, 22647, 136194, 151590, 41706, 82319, 22265, 165853, 155306, 136913, 42334, 105062, 87848, 171872, 15467, 80499, 142194, 23194, 5298, 155993, 39736, 58997, 37318, 112779, 166369, 158493, 115146, 65101, 109989, 93262, 137590, 156691, 122323, 16651, 171401, 119444, 42613, 115898, 172297, 90550, 6800, 109407, 42624, 151685, 128891, 79603, 169169, 22742, 1005, 30836, 104037, 47496, 166243, 76506, 25163, 147613, 39121, 84920, 110395, 4664, 32114, 492, 9355, 143519, 12339, 147383, 96774, 119415, 54889, 8784, 56764, 85357, 150224, 117561, 154555, 78532, 132197, 70562, 38646, 58751, 49032, 129646, 137153, 82381, 49951, 13981, 100980, 114326, 135967, 68042, 7950, 112130, 146603, 116472, 59316, 154720, 89997, 19042, 43906, 114946, 88720, 14996, 72798, 149352, 12758, 83481, 140953, 136794, 122779, 151885, 71002, 33879, 119275, 24289, 177628, 73468, 85876, 157566, 82704, 3922, 165421, 174225, 32618, 114991, 69990, 54303, 132934, 64086, 93924, 119238, 104857, 60853, 175176, 53175, 160654, 137736, 98698, 9121, 93948, 126803, 61897, 112084, 75057, 159062, 49060, 13970, 167576, 32103, 140700, 34971, 143082, 63988, 42818, 137534, 133747, 140556, 88268, 73532, 114943, 8998, 52372, 58994, 146543, 114445, 108352, 5144, 154792, 49687, 66749, 156406, 54220, 28688, 141730, 113612, 8332, 164235, 10758, 74656, 89485, 13329, 159705, 37504, 99954, 95126, 175433, 153506, 49046, 23937, 165617, 171393, 130541, 87041, 70630, 168242, 31284, 84432, 62418, 85678, 6505, 43818, 32263, 77116, 147451, 167035, 18727, 102178, 74046, 89989, 66699, 36943, 153731, 46255, 144535, 48965, 149143, 110059, 104393, 145366, 167732, 21021, 64917, 90489, 103320, 8239, 50966, 98129, 28444, 151688, 59001, 12032, 90730, 123547, 162147, 163595, 143400, 100831, 52108, 20586, 73029, 95209, 15685, 52517, 56262, 156170, 174236, 49041, 167508, 64422, 17920, 59675, 51969, 98495, 152687, 166227, 140772, 55666, 81006, 122555, 54443, 94983, 7485, 29328, 42031, 30462, 15530, 99159, 68744, 127367, 33199, 89758, 79357, 40393, 34121, 95033, 20700, 55650, 150290, 108775, 146646, 166581, 71468, 147879, 63891, 15778, 116260, 167546, 134527, 58818, 134326, 144980, 26556, 13674, 10225, 50260, 41708, 48052, 161115, 129860, 156276, 91573, 2573, 135224, 30292, 176136, 156103, 9442, 120461, 64064, 140573, 40801, 162731, 69145, 164081, 81933, 99682, 95845, 26745, 100408, 40892, 161590, 100589, 17528, 151140, 91312, 120727, 41918, 175596, 26105, 23400, 174559, 65544, 165159, 42941, 23264, 29784, 54874, 131369, 58182, 21927, 119305, 87087, 167039, 101648, 57522, 80613, 49124, 42791, 6454, 164019, 12689, 20218, 77598, 3780, 5128, 143455, 149532, 117598, 54349, 19915, 38744, 29183, 33125, 14762, 168257, 68081, 59052, 34893, 162409, 76504, 124413, 60561, 12172, 24048, 33330, 23163, 6331, 73461, 33453, 7142, 43689, 31313, 19963, 65571, 113302, 126260, 150936, 53831, 108184, 84431, 164257, 105797, 9527, 177325, 70309, 30204, 176612, 62211, 135505, 130154, 125045, 52425, 132354, 158780, 23553, 75088, 164073, 83386, 17396, 162907, 125039, 127563, 161368, 149202, 163374, 11293, 165946, 3035, 99992, 42839, 113501, 43560, 42508, 87386, 152305, 25766, 4270, 5148, 71309, 110340, 166210, 118945, 14802, 141332, 64736, 114116, 900, 114944, 178048, 159369, 6026, 38545, 20800, 42518, 161699, 94098, 121885, 159018, 37463, 86492, 5187, 128809, 104457, 76132, 137891, 63152, 166012, 62356, 102135, 20816, 50481, 160683, 132106, 53194, 154155, 123895, 52923, 56936, 101665, 42932, 22365, 134040, 103008, 45834, 159895, 39662, 165928, 125595, 2444, 139353, 147061, 9466, 116465, 32998, 5708, 153200, 66684, 19907, 19035, 114531, 136371, 110236, 40573, 12703, 175, 100274, 138470, 120406, 85703, 22598, 31666, 12143, 173655, 3583, 108850, 44986, 97241, 83580, 157753, 81554, 6711, 60508, 99325, 39386, 95620, 39466, 83251, 165886, 140676, 1224, 23707, 96688, 69071, 10907, 50939, 66421, 31144, 64685, 152056, 169508, 167924, 45893, 80263, 58656, 45794, 50418, 154364, 161053, 144385, 113291, 41501, 66005, 13278, 103173, 77306, 177242, 174466, 116918, 20695, 172682, 40800, 155672, 73812, 111339, 155157, 78187, 61681, 18096, 85662, 84705, 66930, 79904, 173509, 14208, 154618, 60781, 132527, 37457, 165911, 67688, 78939, 28961, 67858, 168903, 112968, 71207, 50534, 25997, 177473, 63395, 145217, 45597, 123024, 5940, 53332, 58304, 92973, 100758, 26854, 26734, 154708, 35136, 68969, 21615, 88251, 30467, 78386, 147985, 124625, 29548, 80914, 97785, 116367, 159002, 30513, 147137, 112098, 46633, 149838, 47194, 65015, 80823, 24037, 24555, 68460, 165750, 156991, 64843, 105934, 62613, 43940, 60568, 31921, 6899, 67737, 1677, 31427, 151719, 10419, 38331, 148487, 83672, 174782, 159738, 106976, 2745, 64729, 168082, 123237, 63076, 136202, 37907, 173251, 114044, 73923, 61321, 20324, 77823, 17851, 157487, 110262, 145705, 33459, 121180, 137895, 149468, 104662, 38415, 34099, 66478, 75241, 54778, 12413, 1061, 57082, 133125, 140762, 109076, 9909, 143259, 109794, 159358, 13992, 93367, 160853, 140946, 34985, 95775, 158706, 93377, 142316, 9212, 133367, 13553, 141905, 141820, 66747, 17398, 115161, 85303, 6808, 146376, 73028, 174350, 25828, 137148, 86195, 73170, 114831, 88151, 148899, 158388, 28072, 40220, 14417, 26572, 82676, 85117, 50686, 140220, 80733, 119248, 119784, 173272, 150110, 74116, 59289, 11994, 1896, 7551, 32441, 106511, 31560, 81068, 173127, 14185, 109717, 64949, 174461, 52226, 164130, 158732, 175169, 137746, 5036, 162169, 158129, 176523, 144614, 62969, 61437, 176596, 59566, 141424, 2394, 133449, 108062, 143433, 167451, 48774, 158749, 168060, 134198, 122601, 52514, 99948, 47076, 177206, 164127, 41045, 56305, 79405, 171461, 20678, 170679, 64844, 565, 73460, 13643, 84240, 64755, 36852, 163269, 61434, 128896, 139507, 93665, 84835, 121920, 106011, 98385, 164010, 120739, 84245, 144638, 14737, 66344, 39401, 162261, 29868, 170000, 120373, 99, 43314, 50627, 19315, 49079, 134426, 144438, 101116, 72459, 104370, 131328, 51014, 102214, 87279, 124232, 132245, 118975, 7356, 72090, 127244, 4987, 12821, 157190, 159159, 132785, 3242]'
 '[89900, 163127, 109865, 90632, 167568, 99923, 63298, 176768, 23940]' ...
 '[164087, 4814]' '[154008, 156917]'
 '[14430, 164880, 143964, 170377, 1334, 19887]']
----------------------------------------
Unique values of n_items :
[   8  970    9 1253   22  649   31  348  980   69  963  185   23  418
  271 1839  130  277   71  657  189 3656  107   80   14  182 1112   26
   15 1048    3   18   76   39  910  752   33  497   20 6437  282   73
  416   67 2432  180   66  226  155 1263 1138  146  190  749   59  281
   21   17   16    2  566  534  108  338 3465 1987  145  195 4581  335
 1177  117  968  956  473  362  150   40 1758    6   11 2046   44  176
  755 2377    5  907   94 2242 1265 2232   19  223  798  580   32  236
  483 1679  231   85   87 2457  854   10  401  135   13   52   24 1147
  793  229 1363  686  100  302   37  318    4   86 1513  808  491 1386
   53  122  467  351  700  169  129  888  445   77  118   51   42  411
  893    7 1209  699   91  407   30  766 1302   47   57  423 1817  391
  402  625 1830   89   36  415 2798  462  592  187 1533  376 1203 1697
 3338  357  203 1790  746   64  405 1319  814 1226  729  144  186  296
   98 1125   34  615   78  709  692  455  159 1258   49  120  255 1667
   79 1923   35  140  459  690  571   41   12  395   60   88  507  225
  138  103  914  200  486  114  124  896  495  426  280  406  698   29
 1002  111  137   63  471  738   82  297  898 1477  301  637   55  308
 1460  408  136   74  143   46  110   56   48  676  918   65  550  353
  206  785 2851  142  177  133   92   50  598 2733   72  662   43  632
  889  750  123  424   38  399   68  393  412   99 1669   70   95  153
  151  932  920  396  979  490   75  781  211 1108  171  221  321   27
  330  354  275  141  398  175  680  248  900  342   58   28  285  674
  250  199  188  166  384 2011  552  461  161   45  204  380  260  184
  475  259 1592  174  352  269  126  454  254  121  540   25  891  869
  244  267  168  520  249  413   84  306  871 1594  291  212  242  591
  128  327  564  479  687  289  346  109  192  740   97  283  157  361
  539   61 1270  639  635  622  317   62  239  240  527  541  326  213
  119 2602  663 1118  721  583  298  112  132  164  329  528  547 1553
   81  734  501  237  324   90  115  305  293  299  148   96 1308  294
   54  457  647  218  695  684  383  389  207  257  165  340  476 1324
  344  152  278  193  181  217  323  350  179  987  102  183  222  201
  265  287  428  104  950 1354  368 1212  373  590  517  113  149  263
  756  209  693  512  304 1374 1303  307  312  228  339  202  366 1421
  230  227  268 2024 1043  274  147  292  252  607  333  196  427  522
  849  515  378  162  748  443  310  214  219  127  272  732  208  241
  205  139  173  290 1005  529  604  273  832 1120   93  224  170 1218
  167  156  101   83  105  813  392  245  493  251  367  319  247  261
  429  106  701  410  258  235  336  641  365  347  238  134  328  215
  633  125  518  216  582  279  232  163  266  313  364  320  381  431
  379  358  478  300  234  243  256  154  303  596  191  284  315  394
  198  355  314  220  116  131  488  178  286  194  464  158  322  557
  386  276]
----------------------------------------
Unique values of ratings :
['[5.0, 2.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]'
 '[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 4.0, 4.0, 5.0, 4.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, 5.0, 5.0, 0.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 0.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 0.0, 5.0, 3.0, 5.0, 4.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 4.0, 4.0, 4.0, 5.0, 4.0, 5.0, 5.0, 4.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 0.0, 4.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 0.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 0.0, 0.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 4.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 0.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 4.0, 4.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 0.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 4.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0]'
 '[5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0]' ...
 '[4.0, 4.0, 0.0, 4.0, 5.0, 4.0, 5.0, 0.0]'
 '[5.0, 0.0, 0.0, 5.0, 5.0, 5.0, 3.0, 4.0, 5.0]'
 '[4.0, 5.0, 2.0, 3.0, 2.0, 4.0]']
----------------------------------------
Unique values of n_ratings :
[   8  970    9 1253   22  649   31  348  980   69  963  185   23  418
  271 1839  130  277   71  657  189 3656  107   80   14  182 1112   26
   15 1048    3   18   76   39  910  752   33  497   20 6437  282   73
  416   67 2432  180   66  226  155 1263 1138  146  190  749   59  281
   21   17   16    2  566  534  108  338 3465 1987  145  195 4581  335
 1177  117  968  956  473  362  150   40 1758    6   11 2046   44  176
  755 2377    5  907   94 2242 1265 2232   19  223  798  580   32  236
  483 1679  231   85   87 2457  854   10  401  135   13   52   24 1147
  793  229 1363  686  100  302   37  318    4   86 1513  808  491 1386
   53  122  467  351  700  169  129  888  445   77  118   51   42  411
  893    7 1209  699   91  407   30  766 1302   47   57  423 1817  391
  402  625 1830   89   36  415 2798  462  592  187 1533  376 1203 1697
 3338  357  203 1790  746   64  405 1319  814 1226  729  144  186  296
   98 1125   34  615   78  709  692  455  159 1258   49  120  255 1667
   79 1923   35  140  459  690  571   41   12  395   60   88  507  225
  138  103  914  200  486  114  124  896  495  426  280  406  698   29

In [10]:
full_df_processed=DataFramePreprocessing(full_df)
full_df_processed=full_df_processed.preprocessing()

In [18]:
print(f"Columns of the full processed dataframe:")
print(full_df_processed.columns)
print("----------------------------------------")
print(f"Shape of the full processed dataframe:")
print(full_df_processed.shape)
print("----------------------------------------")
print(f"Head of the full  processed dataframe:")
display(full_df_processed.head())
print("----------------------------------------")
for col in full_df_processed.columns:
    print(f"Exemple of {col} :")
    print(full_df_processed.iloc[0][col])
    print("----------------------------------------")
for col in full_df_processed.columns:
    print(f"The type of {col} is")
    print(full_df_processed[col].apply(type).unique())
    print("---------------------------------")

Columns of the full processed dataframe:
Index(['user_id', 'recipe_id', 'rating', 'i', 'techniques_recipes',
       'calorie_level', 'ingredient_ids', 'techniques_users', 'items',
       'n_items', 'ratings', 'n_ratings', 'review', 'name', 'minutes', 'tags',
       'nutrition', 'n_steps', 'steps', 'description', 'n_ingredients'],
      dtype='object')
----------------------------------------
Shape of the full processed dataframe:
(50000, 21)
----------------------------------------
Head of the full  processed dataframe:

,user_id,recipe_id,rating,i,techniques_recipes,calorie_level,ingredient_ids,techniques_users,items,n_items,...,n_ratings,review,name,minutes,tags,nutrition,n_steps,steps,description,n_ingredients
0,89366,151621,5.0,165828,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...",2,"[5890, 1954, 5314, 840, 6335, 3203, 7705, 3810...","[4, 1, 0, 1, 2, 0, 1, 0, 0, 4, 0, 0, 0, 1, 0, ...","[109573, 68779, 176014, 14451, 165827, 69725, ...",8,...,8,Loved this! I made sure each of my shrimp were...,shrimp and pasta with creole cream sauce,48,60 minutes or less [SEP] time to make [SEP] co...,"[906.9, 72.0, 2.0, 23.0, 96.0, 135.0, 24.0]",18,peel and devein shrimp [SEP] toss shrimp with ...,from southern living.,10
1,179133,275036,5.0,104394,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,"[2991, 3440, 5010, 3203, 840, 5006, 6273, 5180]","[357, 7, 3, 144, 158, 0, 3, 23, 2, 322, 13, 29...","[90890, 135961, 12856, 128256, 37047, 153154, ...",970,...,970,This was very nice! I used red bell pepper and...,easy weeknight corn,15,15 minutes or less [SEP] time to make [SEP] co...,"[270.4, 20.0, 4.0, 3.0, 11.0, 37.0, 12.0]",6,"in pan / dutch oven , add butter , olive oil ,...",i threw some things together in a dutch oven a...,8
2,1812036,32871,5.0,99924,"[1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,"[3729, 840, 6906, 5298, 1388]","[4, 0, 0, 4, 3, 0, 0, 0, 0, 5, 0, 1, 0, 0, 0, ...","[89900, 163127, 109865, 90632, 167568, 99923, ...",9,...,9,These are addicting! I also followed the advic...,chocolate toffee graham treats,25,30 minutes or less [SEP] time to make [SEP] co...,"[177.7, 19.0, 57.0, 3.0, 1.0, 34.0, 5.0]",12,preheat oven to 350 [SEP] arrange graham crack...,these are delicious and easy (only 5 ingredien...,5
3,560491,167273,5.0,31342,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,"[840, 6906, 1680, 6389, 1388, 4493]","[497, 10, 3, 169, 257, 0, 1, 50, 11, 456, 21, ...","[12790, 65277, 78451, 104846, 71019, 122679, 5...",1253,...,1253,These were really good! My DSs were a little ...,chocolate chip biscuits aussie style,30,30 minutes or less [SEP] time to make [SEP] co...,"[98.9, 8.0, 27.0, 1.0, 2.0, 16.0, 4.0]",8,cream together the butter and sugar [SEP] add ...,"these are a very ""moresome"" bikky:) i used to ...",6
4,55756,45755,4.0,17324,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, ...",1,"[5574, 340, 6531, 6335, 7946, 7041, 6696, 2809...","[1, 0, 0, 1, 3, 0, 0, 0, 0, 8, 7, 2, 0, 0, 1, ...","[126928, 1108, 40888, 46727, 149767, 117646, 1...",22,...,22,this was very good! i couldn't readily find ho...,szechuan pork crock pot,255,weeknight [SEP] time to make [SEP] course [SEP...,"[416.4, 25.0, 39.0, 52.0, 82.0, 24.0, 7.0]",5,trim chops of excess fat and brown on both sid...,all the pleasure of a chinese meal right out o...,13

----------------------------------------
Exemple of user_id :
89366
----------------------------------------
Exemple of recipe_id :
151621
----------------------------------------
Exemple of rating :
5.0
----------------------------------------
Exemple of i :
165828
----------------------------------------
Exemple of techniques_recipes :
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0]
----------------------------------------
Exemple of calorie_level :
2
----------------------------------------
Exemple of ingredient_ids :
[5890, 1954, 5314, 840, 6335, 3203, 7705, 3810, 2856, 5180]
----------------------------------------
Exemple of techniques_users :
[4, 1, 0, 1, 2, 0, 1, 0, 0, 4, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0]
----------------------------------------
Exemple of items :

In [13]:
tokenizer=AutoTokenizer.from_pretrained("distilbert-base-uncased")

In [14]:
text_tokenized=tokenizer(full_df_processed.iloc[0]["steps"],return_tensors="pt",max_length=256,padding="max_length",truncation=True)

In [25]:
for key in list(text_tokenized.keys()):
    print(key+"_steps")
    print(type(key))

input_ids_steps
<class 'str'>
attention_mask_steps
<class 'str'>