In [1]:
from google.colab import drive
import os

drive.mount('/content/drive')
if not os.path.exists('/content/drive/MyDrive/Recipes-Recommendation-System'):
    os.makedirs("/content/drive/MyDrive/Recipes-Recommendation-System")
    %cd /content/drive/MyDrive/Recipes-Recommendation-System
    !git clone https://github.com/soheil-housni/Recipes-Recommendation-System.git \
        /content/drive/MyDrive/Recipes-Recommendation-System

else:
    %cd /content/drive/MyDrive/Recipes-Recommendation-System
    !git pull origin main

print(os.getcwd())

Mounted at /content/drive
/content/drive/MyDrive/Recipes-Recommendation-System
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 7 (delta 4), reused 7 (delta 4), pack-reused 0 (from 0)
Unpacking objects: 100% (7/7), 2.47 KiB | 0 bytes/s, done.
From https://github.com/soheil-housni/Recipes-Recommendation-System
 * branch            main       -> FETCH_HEAD
   c839d0a..00366a5  main       -> origin/main
Updating c839d0a..00366a5
Fast-forward
 main.ipynb                   | 232 +++++++++++++++++++------------------------
 modules/__init__.py          |   3 +-
 modules/load_parquet_file.py |   2 +-
 scaler.pkl                   | Bin 0 -> 1159 bytes
 4 files changed, 103 insertions(+), 134 deletions(-)
 create mode 100644 scaler.pkl
/content/drive/MyDrive/Recipes-Recommendation-System

In [2]:
!pip install mlflow
!pip install loguru
!pip install optuna

Collecting mlflow
  Downloading mlflow-3.11.1-py3-none-any.whl.metadata (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.2/49.2 kB 4.9 MB/s eta 0:00:00
Collecting mlflow-skinny==3.11.1 (from mlflow)
  Downloading mlflow_skinny-3.11.1-py3-none-any.whl.metadata (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.0/50.0 kB 3.2 MB/s eta 0:00:00
Collecting mlflow-tracing==3.11.1 (from mlflow)
  Downloading mlflow_tracing-3.11.1-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Downloading flask_cors-6.0.2-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.13.4)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.18.4)
Requirement already satisfied: cryptography<47,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (43.0.3)
Collecting docker<8,>=4.0.0 (from mlflow)
  Downloading docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<26 (from mlflow)
  Downloading gunicorn-25.3.0-py3-none-any.whl.metadata (5.5 kB)
Collecting huey<3,>=2.5.4 (from mlflow)
  Downloading huey-2.6.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.2.2)
Requirement already satisfied: pyarrow<24,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (18.1.0)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)
Collecting skops<1 (from mlflow)
  Downloading skops-0.13.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.48)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (8.3.1)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (3.1.2)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.11.1->mlflow)
  Downloading databricks_sdk-0.102.0-py3-none-any.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 4.5 MB/s eta 0:00:00
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (0.135.2)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (3.1.46)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (1.38.0)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (26.0)
Requirement already satisfied: protobuf<8,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (2.12.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (1.2.2)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (0.5.5)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.11.1->mlflow) (0.42.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.23.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.3.10)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography<47,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.7)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.8-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.3.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography<47,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (2.47.0)
Requirement already satisfied: starlette>=0.46.0 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (0.52.1)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (0.0.4)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.11.1->mlflow) (4.0.12)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.11.1->mlflow) (3.23.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.59b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.11.1->mlflow) (0.59b0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.11.1->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.11.1->mlflow) (2.41.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (2026.2.25)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<1->mlflow-skinny==3.11.1->mlflow) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.11.1->mlflow) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (4.9.1)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from starlette>=0.46.0->fastapi<1->mlflow-skinny==3.11.1->mlflow) (4.13.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (0.6.3)
Downloading mlflow-3.11.1-py3-none-any.whl (10.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 72.4 MB/s eta 0:00:00:00:01:01
Downloading mlflow_skinny-3.11.1-py3-none-any.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 97.8 MB/s eta 0:00:00
Downloading mlflow_tracing-3.11.1-py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 71.4 MB/s eta 0:00:00
Downloading docker-7.1.0-py3-none-any.whl (147 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 11.1 MB/s eta 0:00:00
Downloading flask_cors-6.0.2-py3-none-any.whl (13 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 11.3 MB/s eta 0:00:00
Downloading gunicorn-25.3.0-py3-none-any.whl (208 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.4/208.4 kB 19.8 MB/s eta 0:00:00
Downloading huey-2.6.0-py3-none-any.whl (76 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.0/77.0 kB 5.3 MB/s eta 0:00:00
Downloading skops-0.13.0-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.2/131.2 kB 19.1 MB/s eta 0:00:00
Downloading databricks_sdk-0.102.0-py3-none-any.whl (838 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 838.5/838.5 kB 46.0 MB/s eta 0:00:00
Downloading graphql_core-3.2.8-py3-none-any.whl (207 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 24.0 MB/s eta 0:00:00
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Installing collected packages: huey, gunicorn, graphql-core, graphql-relay, docker, skops, graphene, Flask-CORS, databricks-sdk, mlflow-tracing, mlflow-skinny, mlflow
Successfully installed Flask-CORS-6.0.2 databricks-sdk-0.102.0 docker-7.1.0 graphene-3.4.3 graphql-core-3.2.8 graphql-relay-3.2.0 gunicorn-25.3.0 huey-2.6.0 mlflow-3.11.1 mlflow-skinny-3.11.1 mlflow-tracing-3.11.1 skops-0.13.0
Collecting loguru
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Downloading loguru-0.7.3-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 7.5 MB/s eta 0:00:00
Installing collected packages: loguru
Successfully installed loguru-0.7.3
Collecting optuna
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.48)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 35.0 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.8.0

In [3]:
import pandas as pd
import numpy as np
import ast
import numpy as np
import torch
import mmh3
from transformers import AutoTokenizer,DistilBertModel
import itertools
import pyarrow.parquet as pq
from torch.utils.data import DataLoader
from sklearn.preprocessing import StandardScaler
import mlflow
from modules import BeforeSplitPreprocessing, AfterSplitPreprocessing, CreationDataset,CollateFunction,set_seed,seed_worker,EncodedHashedEmbeddings,Scaler,split_df,RecommendationModel,Train,BERTCreationDataset,BERTCreationDataset,BERTEmbeddingsExtractor,BertCollateFunction,ContrastiveMSELoss,OptunaFunction,load
import optuna
from loguru import logger
import gc
import os
import plotly.io as pio
import joblib
pio.renderers.default = "vscode"
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

In [4]:
seed=42
set_seed(seed=seed)

In [5]:
mlflow.set_tracking_uri("file:./mlflow_runs/mlruns")
mlflow.set_experiment("Recipes_Recommendation_System_model_training")

/usr/local/lib/python3.12/dist-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning:

The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.

2026/04/08 23:41:07 INFO mlflow.tracking.fluent: Experiment with name 'Recipes_Recommendation_System_model_training' does not exist. Creating a new experiment.

<Experiment: artifact_location='file:///content/drive/MyDrive/Recipes-Recommendation-System/mlflow_runs/mlruns/503138512899622791', creation_time=1775691667057, experiment_id='503138512899622791', last_update_time=1775691667057, lifecycle_stage='active', name='Recipes_Recommendation_System_model_training', tags={}, trace_location=None, workspace='default'>

## Creation of the processed dataframe

In [3]:
interactions_train_df=pd.read_csv("data/interactions_train.csv")
PP_recipes_df=pd.read_csv("data/PP_recipes.csv")
PP_users_df=pd.read_csv("data/PP_users.csv")
RAW_interactions_df=pd.read_csv("data/RAW_interactions.csv")
RAW_recipes_df=pd.read_csv("data/RAW_recipes.csv")

In [17]:
interactions_train_df_filtered=interactions_train_df.sample(n=20000,replace=False,random_state=42)

In [6]:
print(interactions_train_df_filtered.shape)

(20000, 6)

In [18]:
RAW_recipes_df.rename(columns={"id":"recipe_id"},inplace=True)
PP_recipes_df.rename(columns={"techniques":"techniques_recipes"},inplace=True)
PP_users_df.rename(columns={"techniques":"techniques_users"},inplace=True)

In [8]:
print("interactions_train_df_filtered columns:")
print(interactions_train_df_filtered.columns)
print("------------------------------------------------------------------")
print("PP_recipes_df columns:")
print(PP_recipes_df.columns)
print("-------------------------------------------------------------------")
print("PP_users_df columns:")
print(PP_users_df.columns)
print("----------------------------------------------------------------------")
print("RAW_interactions_df columns:")
print(RAW_interactions_df.columns)
print("------------------------------------------------------------------------")
print("RAW_recipes_df columns:")
print(RAW_recipes_df.columns)

interactions_train_df_filtered columns:
Index(['user_id', 'recipe_id', 'date', 'rating', 'u', 'i'], dtype='object')
------------------------------------------------------------------
PP_recipes_df columns:
Index(['id', 'i', 'name_tokens', 'ingredient_tokens', 'steps_tokens',
       'techniques_recipes', 'calorie_level', 'ingredient_ids'],
      dtype='object')
-------------------------------------------------------------------
PP_users_df columns:
Index(['u', 'techniques_users', 'items', 'n_items', 'ratings', 'n_ratings'], dtype='object')
----------------------------------------------------------------------
RAW_interactions_df columns:
Index(['user_id', 'recipe_id', 'date', 'rating', 'review'], dtype='object')
------------------------------------------------------------------------
RAW_recipes_df columns:
Index(['name', 'recipe_id', 'minutes', 'contributor_id', 'submitted', 'tags',
       'nutrition', 'n_steps', 'steps', 'description', 'ingredients',
       'n_ingredients'],
      dtype='object')

In [9]:
full_df=interactions_train_df_filtered.merge(PP_recipes_df,on="i",how="left",suffixes=(None,"_1")).merge(PP_users_df,on="u",how="left",suffixes=(None,"_2")).merge(RAW_interactions_df,on=["user_id","recipe_id"],how="left",suffixes=(None,"_3")).merge(RAW_recipes_df,on=["recipe_id"],how="left",suffixes=(None,"_3"))

In [10]:
full_df=full_df.drop(columns=["review",'rating_3',"id","ingredients","submitted","contributor_id","date_3","date","steps_tokens","ingredient_tokens","name_tokens","u"],axis=1)

In [11]:
print(f"Columns of the full dataframe:")
print(full_df.columns)
print("----------------------------------------")
print(f"Shape of the full dataframe:")
print(full_df.shape)
print("----------------------------------------")
print(f"Columns of the filtered interaction dataframe:")
print(interactions_train_df_filtered.shape)
print("----------------------------------------")
print(f"Head of the full  dataframe:")
display(full_df.head())
print("----------------------------------------")
for col in full_df.columns:
    print(f"Unique values of {col} :")
    print(full_df[col].unique())
    print("----------------------------------------")
for col in full_df.columns:
    print(f"The type of {col} is")
    print(full_df[col].apply(type).unique())
    print("---------------------------------")

Columns of the full dataframe:
Index(['user_id', 'recipe_id', 'rating', 'i', 'techniques_recipes',
       'calorie_level', 'ingredient_ids', 'techniques_users', 'items',
       'n_items', 'ratings', 'n_ratings', 'name', 'minutes', 'tags',
       'nutrition', 'n_steps', 'steps', 'description', 'n_ingredients'],
      dtype='object')
----------------------------------------
Shape of the full dataframe:
(20000, 20)
----------------------------------------
Columns of the filtered interaction dataframe:
(20000, 6)
----------------------------------------
Head of the full  dataframe:

,user_id,recipe_id,rating,i,techniques_recipes,calorie_level,ingredient_ids,techniques_users,items,n_items,ratings,n_ratings,name,minutes,tags,nutrition,n_steps,steps,description,n_ingredients
0,231160,124810,5.0,170682,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,"[4574, 1910, 6906, 2499, 63, 332, 6270, 7470, ...","[3, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, ...","[8911, 20238, 117521, 79316, 154563, 34302, 17...",7,"[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]",7,huckleberry or blueberry coffee cake,75,"['time-to-make', 'course', 'main-ingredient', ...","[174.1, 4.0, 92.0, 8.0, 7.0, 3.0, 11.0]",11,['beat margarine and cream cheese at medium sp...,"cooking light published this in their book, fi...",10
1,142629,31342,5.0,120865,"[1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",1,"[1168, 1284, 8021, 2499, 330, 6270, 3217, 2318...","[6, 0, 0, 3, 1, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, ...","[122019, 150060, 117906, 82202, 119046, 141911...",10,"[4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 3.0, 5.0, 4.0, ...",10,blender quiche or whatever you have in your ...,65,"['weeknight', 'time-to-make', 'course', 'main-...","[308.4, 37.0, 8.0, 20.0, 21.0, 41.0, 3.0]",10,"['preheat oven to 350f', 'generously grease a ...",the great part is you can use whatever leftove...,12
2,822358,441841,4.0,23142,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,"[1648, 1706, 3347, 5298, 3044, 4623, 2148, 6270]","[1, 1, 0, 2, 3, 0, 0, 0, 1, 5, 0, 1, 0, 0, 0, ...","[29761, 87944, 72370, 139097, 39470, 37755, 23...",17,"[4.0, 5.0, 5.0, 5.0, 4.0, 4.0, 4.0, 5.0, 5.0, ...",17,sweet orange coleslaw,10,"['15-minutes-or-less', 'time-to-make', 'course...","[290.1, 21.0, 71.0, 14.0, 7.0, 8.0, 13.0]",6,"['chop the apples', 'in a small bowl mix the o...",this recipe came from one of my mom's cookbook...,8
3,655579,211110,4.0,156541,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,"[7031, 5006, 339, 3203, 5975, 6270, 590]","[10, 0, 0, 5, 11, 0, 0, 0, 0, 7, 1, 3, 0, 0, 1...","[34492, 71279, 73805, 68721, 114795, 35164, 33...",28,"[2.0, 3.0, 4.0, 2.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...",28,wilted greens with garlic and balsamic vinegar,15,"['15-minutes-or-less', 'time-to-make', 'course...","[77.5, 10.0, 5.0, 5.0, 2.0, 4.0, 1.0]",5,"['cut the greens into strips 1 inch wide', 'in...",this simple but delicious side dish can be mad...,7
4,35140,114469,5.0,30839,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",2,"[1240, 6270, 5006, 1257, 2683, 5168, 800, 2461...","[176, 4, 2, 55, 72, 0, 1, 7, 4, 141, 13, 15, 0...","[121722, 36691, 151293, 154016, 1205, 12802, 1...",364,"[5.0, 5.0, 0.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...",364,chicken in the limelight,75,"['time-to-make', 'course', 'main-ingredient', ...","[645.9, 69.0, 11.0, 22.0, 80.0, 54.0, 4.0]",8,"['preheat oven to 350', 'grate lime peel and s...",very tender chicken soaked with flavor,9

----------------------------------------
Unique values of user_id :
[231160 142629 822358 ... 241982 164867 137854]
----------------------------------------
Unique values of recipe_id :
[124810  31342 441841 ...  98278 274099 283283]
----------------------------------------
Unique values of rating :
[5. 4. 3. 2. 0. 1.]
----------------------------------------
Unique values of i :
[170682 120865  23142 ... 108495 128044  25867]
----------------------------------------
Unique values of techniques_recipes :
['[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'
 '[1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'
 '[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]'
 ...
 '[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]'
 '[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]'
 '[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]']
----------------------------------------
Unique values of calorie_level :
[0 1 2]
----------------------------------------
Unique values of ingredient_ids :
['[4574, 1910, 6906, 2499, 63, 332, 6270, 7470, 3819, 3497]'
 '[1168, 1284, 8021, 2499, 330, 6270, 3217, 2318, 2856, 4717, 5006, 5168]'
 '[1648, 1706, 3347, 5298, 3044, 4623, 2148, 6270]' ...
 '[1254, 1165, 2374, 3716, 222, 1168]'
 '[1786, 5319, 1252, 5006, 5010, 3203, 1257, 7233, 6212, 3399, 1511, 1563, 68, 5975, 553, 1706]'
 '[3244, 7821, 1527, 2010, 1119, 4884, 2809, 3406, 5058]']
----------------------------------------
Unique values of techniques_users :
['[3, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]'
 '[6, 0, 0, 3, 1, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 4, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 3, 0, 2]'
 '[1, 1, 0, 2, 3, 0, 0, 0, 1, 5, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 2, 1, 0, 1, 0, 0, 4, 1, 0, 0, 0, 0, 0, 4, 0, 1, 4, 1, 1, 0, 0, 1, 3, 3, 1, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 2, 1, 2]'
 ...
 '[6, 0, 0, 2, 3, 0, 0, 0, 0, 5, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 4, 0, 0, 2, 1, 0, 0, 0, 0, 1, 1, 0, 0, 3, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 1]'
 '[9, 0, 0, 3, 3, 0, 0, 1, 0, 5, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 2, 5, 1, 0, 0, 0, 6, 0, 1, 2, 0, 1, 0, 0, 0, 3, 2, 0, 0, 3, 1, 0, 1, 0, 0, 0, 3, 1, 2, 1, 3]'
 '[37, 3, 0, 16, 21, 0, 0, 1, 0, 20, 6, 2, 0, 0, 2, 0, 6, 0, 0, 4, 4, 4, 0, 2, 0, 0, 2, 4, 14, 3, 0, 0, 0, 28, 0, 4, 9, 4, 5, 0, 0, 3, 13, 5, 1, 1, 15, 1, 0, 1, 0, 1, 0, 3, 0, 2, 4, 4]']
----------------------------------------
Unique values of items :
['[8911, 20238, 117521, 79316, 154563, 34302, 170682]'
 '[122019, 150060, 117906, 82202, 119046, 141911, 171519, 120865, 71287, 171522]'
 '[29761, 87944, 72370, 139097, 39470, 37755, 23142, 71578, 77036, 137338, 161477, 153736, 40366, 83647, 168229, 16010, 59580]'
 ...
 '[156329, 47112, 9002, 48914, 82283, 44569, 12384, 107161, 81246, 37900]'
 '[164203, 21935, 116632, 93494, 93193, 34860, 2267, 121932, 23646, 97372, 3332, 99368, 158194, 18103, 92882, 162858, 89027, 89140]'
 '[162186, 151953, 91760, 83170, 51796, 39867, 151177, 168722, 95442, 46843, 173363, 61869, 1754, 15430, 85086, 71955, 126328, 139970, 22578, 170817, 40735, 78551, 82136, 155665, 50048, 112281, 4864, 139149, 94090, 44321, 19812, 21692, 52532, 74837, 24305, 17876, 51263, 93685, 11814, 47251, 72474, 1921, 178015, 157555, 138896, 55772, 14509, 174272, 84437, 156075, 83930, 90781, 110941, 159543, 61938, 89113, 71389, 65021, 71442, 130357, 28353, 113097, 114402, 109732, 140658, 141662, 13667]']
----------------------------------------
Unique values of n_items :
[   7   10   17   28  364  700 1125  423   13  174  394  443 1203 1263
   68  173  445    9  144  166  261  330 3465   56  188   22 2602  275
 1817  201  596   11   26   25  204   40 3656  322  416   36  637  283
    3  402  346   31 1112   50  211   20 1987  750  517   42  284    4
 4581 2024  813   66  153   32  218  351   67   14   16   48   47   71
   27  298  380  158   38   97 2232    5 1790 1302  171 2733  849  306
  910  635  232   57  125  269  398   65   84  292   79    8 6437 1667
   69   23  383   61  196   18   12  102  891   51  963    2 1138 2432
  580  547  907 2242   43  755  127   59 3338  122  980  167 1374  854
  428  296 1226  527  756  798  362  282  615  245   34  467 1697 1005
  785  236   63  395 1758  814   52  540  956  389 2798  277  117   44
  104 2011 1120 1679   33 1830  411 1477  896  529  522   19   81  746
   78   55  146  622  109  379  781  179 2457  195  657 1533   89  987
 1553  476   24 1212  592  293  256  181  308  118   30  231 1043  291
   41   15   80  684  752  161  189   29  365  252   35    6   58  357
  242  687  381  808  358 2046  121   90 1002  412  317 1592 1303  871
  914  128  151   37  709  185  738  305  278  607  216  399  274  328
  598  528  479 1253   85  234  107  129  338  968  112   21  734  142
  130  462 1386  132  869   73   99  662   76  224  766  260  180  281
  950  475  490   39 1308  564   86  749 1460  361   88  920  152  582
  229  302   72   93  183  698  647  255  427 1923  493  134  198   49
  431  336  663  106  140  149   74 2851  699  695  300  205  729 1265
  680  187  339  534   70  217   62   77  625  254  192  406  244  184
  199  633  488  378  793  250  376  515  168   96 1354  228   45   83
  212 1421  113  105  348  147 2377  110  550  100  141 1177  591 1319
  571  410  315 1363  900  156  583  384 1270  155  303  721  473   92
  353  354  454  557  177  116  424  111   60  324  226  239   54  541
 1839   82 1513  970  136  478  240   53  429  350  203  932  285  676
  138  979   46  143  289  131  491  120  455   94  552  163  148  145
  344  674 1118  235  135  457 1218  176  209   98  150  740  832  273
  495  200 1669  649  318  539  287  108  165  243  732  408  312  392
 1108  314  247  123  401  193  213  342  497  249   91  391 1594  265
   75 1147  352  329 1209  898  103  114  501  327  267  604  320  182
  507 1324  639   64  407  266  461  307  889  326  162  133  259  119
   95  701  206  169  405  271  279   87  263  386  251  191  486 1048
  304  418  115  126  686  373  223  690  340 1258  238  222  459  366
  888  918  237  137  241  286  221  413  175  426  297  164  280  301
  157  178  518  632  692  355  590  186  170  748  248  321  520  512
  290  310  257  335  268  368  101  893  219  566  693  124  367  214
  215  202  194  347  464  323  276  333  230  190  272  225  641  415
  393  313  483  396  258  299  139  159  154  471  207  294  220  227
  319  208]
----------------------------------------
Unique values of ratings :
['[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]'
 '[4.0, 5.0, 5.0, 5.0, 4.0, 5.0, 3.0, 5.0, 4.0, 5.0]'
 '[4.0, 5.0, 5.0, 5.0, 4.0, 4.0, 4.0, 5.0, 5.0, 4.0, 4.0, 5.0, 4.0, 4.0, 4.0, 3.0, 4.0]'
 ...
 '[4.0, 3.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 2.0, 5.0]'
 '[5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 4.0, 4.0, 5.0, 5.0]'
 '[5.0, 4.0, 5.0, 5.0, 3.0, 4.0, 4.0, 3.0, 5.0, 5.0, 2.0, 4.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]']
----------------------------------------
Unique values of n_ratings :
[   7   10   17   28  364  700 1125  423   13  174  394  443 1203 1263
   68  173  445    9  144  166  261  330 3465   56  188   22 2602  275
 1817  201  596   11   26   25  204   40 3656  322  416   36  637  283
    3  402  346   31 1112   50  211   20 1987  750  517   42  284    4
 4581 2024  813   66  153   32  218  351   67   14   16   48   47   71
   27  298  380  158   38   97 2232    5 1790 1302  171 2733  849  306
  910  635  232   57  125  269  398   65   84  292   79    8 6437 1667
   69   23  383   61  196   18   12  102  891   51  963    2 1138 2432
  580  547  907 2242   43  755  127   59 3338  122  980  167 1374  854
  428  296 1226  527  756  798  362  282  615  245   34  467 1697 1005
  785  236   63  395 1758  814   52  540  956  389 2798  277  117   44
  104 2011 1120 1679   33 1830  411 1477  896  529  522   19   81  746
   78   55  146  622  109  379  781  179 2457  195  657 1533   89  987
 1553  476   24 1212  592  293  256  181  308  118   30  231 1043  291
   41   15   80  684  752  161  189   29  365  252   35    6   58  357
  242  687  381  808  358 2046  121   90 1002  412  317 1592 1303  871
  914  128  151   37  709  185  738  305  278  607  216  399  274  328
  598  528  479 1253   85  234  107  129  338  968  112   21  734  142
  130  462 1386  132  869   73   99  662   76  224  766  260  180  281
  950  475  490   39 1308  564   86  749 1460  361   88  920  152  582
  229  302   72   93  183  698  647  255  427 1923  493  134  198   49
  431  336  663  106  140  149   74 2851  699  695  300  205  729 1265
  680  187  339  534   70  217   62   77  625  254  192  406  244  184
  199  633  488  378  793  250  376  515  168   96 1354  228   45   83
  212 1421  113  105  348  147 2377  110  550  100  141 1177  591 1319
  571  410  315 1363  900  156  583  384 1270  155  303  721  473   92
  353  354  454  557  177  116  424  111   60  324  226  239   54  541
 1839   82 1513  970  136  478  240   53  429  350  203  932  285  676
  138  979   46  143  289  131  491  120  455   94  552  163  148  145
  344  674 1118  235  135  457 1218  176  209   98  150  740  832  273
  495  200 1669  649  318  539  287  108  165  243  732  408  312  392
 1108  314  247  123  401  193  213  342  497  249   91  391 1594  265
   75 1147  352  329 1209  898  103  114  501  327  267  604  320  182
  507 1324  639   64  407  266  461  307  889  326  162  133  259  119
   95  701  206  169  405  271  279   87  263  386  251  191  486 1048
  304  418  115  126  686  373  223  690  340 1258  238  222  459  366
  888  918  237  137  241  286  221  413  175  426  297  164  280  301
  157  178  518  632  692  355  590  186  170  748  248  321  520  512
  290  310  257  335  268  368  101  893  219  566  693  124  367  214
  215  202  194  347  464  323  276  333  230  190  272  225  641  415
  393  313  483  396  258  299  139  159  154  471  207  294  220  227
  319  208]
----------------------------------------
Unique values of name :
['huckleberry   or blueberry  coffee cake'
 'blender quiche   or whatever you have in your kitchen leftover'
 'sweet orange coleslaw' ... 'asparagus chicken with hollandaise sauce'
 'caribbean chicken and black beans' 'fragrant orange curry']
----------------------------------------
Unique values of minutes :
[   75    65    10    15     4    31    35    25    33   250    55    17
    18    40    22    20     0    30    19     5    90    45    23    89
    79    50    80    60   190    70   385   490    13     2  1920    38
   150   380   300   485   105    81   135    44    85    32   160   140
   610    95    28   310    27     8   195   130  1680   280   155   330
   505    16     3   120   370    51    52   245    42   125    49   560
   110   165   495   200     6   375    21    57    12     7   500   615
    53   430    68   205   285  1500   805    39   325   510  1490    24
   180    54     9  1475   365   305   100 10095   435   175   315   270
   243     1    34   260  2895    26    36   240   750   187    46   745
   210    62    43    76   420   405   360   555  1480   390   185    29
    11   145  1440  1455  5760    97   545   232   440   147    47    74
    58   550  2900    48   230  1620   480    41  1470   182  1460  1380
    14   680    37   675   520  1445   605   115   252   132  1800  1443
   248   218   400   255   235   425    72   530   602   620  2190   265
   492  1442   275  1080   770    88   486   107   225    83   184   487
   138   124  1450   112  1456 10090   320   170    67   740   126   103
   215   790  1200  2925  1485   167  2910  1580   780    77   525   730
   640   314   900   915    63   144    71    56  4350   735   223   153
   765   246   515 21615   570   308   214  1452   395    93   630  7210
   106   372   381   220   335  1090   301    64   104   128   600  2760
   143   660    59    78   249   725   188   840  1540  5820    66   608
  1465   482    84   720   645   800   616  2905   307   481 15860    99
   588  1515   109   158   625    94 10320  9740   290   410    87  2885
   825   795  1530   363   760  1020    73  4330   445 10080   970   540
    98    61  1520]
----------------------------------------
Unique values of tags :
["['time-to-make', 'course', 'main-ingredient', 'preparation', 'occasion', 'breads', 'breakfast', 'fruit', 'oven', 'easy', 'coffee-cakes', 'dietary', 'berries', 'blueberries', 'brunch', 'equipment', '4-hours-or-less']"
 "['weeknight', 'time-to-make', 'course', 'main-ingredient', 'cuisine', 'preparation', 'occasion', 'north-american', 'lunch', 'main-dish', 'eggs-dairy', 'pork', 'poultry', 'vegetables', 'american', 'oven', 'cheese', 'eggs', 'chicken', 'food-processor-blender', 'dietary', 'oamc-freezer-make-ahead', 'meat', 'equipment', 'small-appliance', 'number-of-servings', '4-hours-or-less']"
 "['15-minutes-or-less', 'time-to-make', 'course', 'main-ingredient', 'preparation', 'low-protein', 'salads', 'fruit', 'vegetables', 'easy', 'dietary', 'low-cholesterol', 'low-saturated-fat', 'healthy-2', 'low-in-something', 'apples', 'greens']"
 ...
 "['60-minutes-or-less', 'time-to-make', 'course', 'main-ingredient', 'preparation', 'main-dish', 'poultry', 'vegetables', 'easy', 'chicken', 'dietary', 'meat', 'chicken-breasts', 'asparagus']"
 "['60-minutes-or-less', 'time-to-make', 'main-ingredient', 'cuisine', 'preparation', 'north-american', 'beans', 'poultry', 'caribbean', 'central-american', 'chicken', 'stove-top', 'black-beans', 'meat', 'chicken-breasts', 'equipment']"
 "['30-minutes-or-less', 'time-to-make', 'course', 'main-ingredient', 'cuisine', 'preparation', 'occasion', 'appetizers', 'soups-stews', 'fruit', 'asian', 'middle-eastern', 'easy', 'dinner-party', 'vegetarian', 'dietary', 'citrus', 'oranges', 'taste-mood', 'savory', '3-steps-or-less']"]
----------------------------------------
Unique values of nutrition :
['[174.1, 4.0, 92.0, 8.0, 7.0, 3.0, 11.0]'
 '[308.4, 37.0, 8.0, 20.0, 21.0, 41.0, 3.0]'
 '[290.1, 21.0, 71.0, 14.0, 7.0, 8.0, 13.0]' ...
 '[287.0, 19.0, 4.0, 13.0, 67.0, 33.0, 1.0]'
 '[381.3, 6.0, 11.0, 13.0, 55.0, 4.0, 17.0]'
 '[94.4, 3.0, 55.0, 0.0, 2.0, 6.0, 5.0]']
----------------------------------------
Unique values of n_steps :
[11 10  6  5  8  7  9  4 13  3 20 12 14 16 15 19 18 17 21 22 26 24 28 30
 23 27 29]
----------------------------------------
Unique values of steps :
["['beat margarine and cream cheese at medium speed of an electric mixer until creamy', 'gradually 1 cup sugar , beating well', 'add egg , and beat well', 'combine flour , baking powder , and salt', 'stir into margarine mixture', 'stir in vanilla , then fold in berries', 'pour batter into a 9-inch round cake pan coated with cooking spray', 'combine 2 tablespoons sugar and cinnamon', 'sprinkle over batter', 'bake at 350f for 1 hour', 'cool on a wire rack']"
 "['preheat oven to 350f', 'generously grease a 9 inch pie pan', 'spread shredded cheese across bottom of pie pan', 'cover cheese with meat and vegetables', 'in a blender , combine eggs , baking mix , salt , garlic powder , onions , parsley , and milk', 'blend until smooth , then add olive oil', 'blend until combined , then pour mixture over meat and vegetable layer', 'sprinkle with paprika', 'bake in preheated oven for 40 minutes', 'cool 10 minutes before serving']"
 "['chop the apples', 'in a small bowl mix the orange juice concentate , mayo , dijon , and salt', 'in a large serving bowl toss the coleslaw mix , rice , and apples', 'mix the dressing with the slaw until well coated', 'stir in the pecans', 'chill before serving']"
 ...
 "['to marinate: place chicken in a nonporous glass dish or bowl', 'pour wine over chicken , then sprinkle with tarragon', 'cover dish and refrigerate to marinate for 2 hours', 'preheat oven to broil', 'remove chicken from dish or bowl discarding remaining marinade and broil for 25 minutes or until cooked through and juices run clear', 'meanwhile , steam asparagus to desired degree of doneness', 'prepare hollandaise sauce according to package directions', 'when chicken is cooked , arrange the breasts on a platter , place 4 spears of asparagus on each chicken breast and dribble with prepared hollandaise sauce to taste', 'sprinkle with cheese and serve']"
 "['coat a skillet with nonstick cooking spray', 'sprinkle pepper on chicken and cook in skillet over medium heat for 3-5 minutes , so that the surfaces have a nice brown color and are no longer opaque', 'remove the chicken to a plate and return the pan to heat', 'in the same skillet , heat olive oil', 'add onion', 'if the pan become dry , add 2 tablespoons of broth to skillet', 'cook for 5-6 minutes or until onion is soft , stirring frequently', 'in the last minute of cooking , add the garlic', 'add tomato sauce , remaining broth and rum to skillet and mix well', 'add green and / or red pepper , reserved chicken and seasonings', 'bring to a boil', 'reduce heat and simmer , uncovered , 15 min or until chicken is tender and liquid has thickened', 'stir in beans and heat another 2-3 minutes place rice on large platter and top with chicken and bean mix']"
 "['heat ghee or butter in a medium pot over low heat', 'add spices and stir until fragrant', 'stir in orange juice and cook slowly for 15 to 20 minutes', 'serve hot , in small bowls or cups , with or without spoons']"]
----------------------------------------
Unique values of description :
['cooking light published this in their book, five star recipes--the best of 10 years, and their staff voted this as one of their top five recipes from the first 10 years. it is very, very good, either for breakfast, brunch, or as dessert, warm out of the oven with a scoop of vanilla ice cream.'
 'the great part is you can use whatever leftovers (well...almost) you have on hand. this dish can be served hot or cold. freezes very well! use any cheese of your choice.'
 'this recipe came from one of my mom\'s cookbooks called "quilter\'s cooking companion".  it\'s easy to make and has great texture and flavor!'
 ...
 "this recipe came from another recipe site. it is mouthwatering delicious. beautiful presentation. simple, simple, simple to make. originally found the recipe in february and just got around to making it. i'm sorry i lost all of that time eating it! i'll make up for it now. cook time does not include 2 hours for marinating."
 'originally from shape magazine and adapted to suit my tastes and simplify the preparation. this is healthy and comforting with a pleasing, but approachable combination of spices that even picky eaters will enjoy. though full of flavor this is not spicy hot, so feel free to adjust to your own tastes. a word of caution, this makes 6 perfect portions for my weight watching lifestyle but if you have hungry eaters at your table, it may only serve 4 or 5.'

In [4]:
PP_users_df["len_items"]=PP_users_df["items"].str.count(r",")+1
PP_recipes_df["len_ingredients"]=PP_recipes_df["ingredient_ids"].str.count(r",")+1
max_len_ingredients=PP_recipes_df["len_ingredients"].max()
max_len_items=PP_users_df["len_items"].max()
PP_users_df.drop(columns=["len_items"],inplace=True)
PP_recipes_df.drop(columns=["len_ingredients"],inplace=True)

In [13]:
full_df_processed=BeforeSplitPreprocessing(full_df,max_len_ingredients,max_len_items)
full_df_processed=full_df_processed.preprocessing()

In [14]:
full_df_processed["rating_scaled"]=full_df_processed["rating"]/5

In [20]:
PP_recipes_df["ingredient_ids_transformed"]=PP_recipes_df["ingredient_ids"].apply(lambda x: list(map(int,ast.literal_eval(x))))
all_ingredient_ids=np.unique(list(itertools.chain.from_iterable(list(PP_recipes_df["ingredient_ids_transformed"]))))
ingredient_continuous_ids=pd.Series([i for i in range(1,len(all_ingredient_ids)+1)],index=list(np.sort(all_ingredient_ids)))

In [16]:
def mapping_list(x:list,mapping_serie:pd.Series):
    return [mapping_serie.loc[i] if i in mapping_serie.index else 0 for i in x]

In [17]:
full_df_processed["ingredient_ids_continuous"]=full_df_processed["ingredient_ids"].apply(lambda x : mapping_list(x,ingredient_continuous_ids))

In [18]:
full_df_processed["full_text"]=full_df_processed["name"]+" [SEP] "+full_df_processed["description"]+" [SEP] "+full_df_processed["steps"]+" [SEP] "+full_df_processed["tags"]

In [20]:
full_df_processed.to_parquet(path="./modules/dataframes/full_df_processed.parquet")

In [6]:
full_parquet_file = pq.ParquetFile("./modules/dataframes/full_df_processed.parquet")
full_df_processed=load(full_parquet_file)

In [ ]:
#df_text=full_df_processed["full_text"]

In [7]:
#distilbert_model=DistilBertModel.from_pretrained("distilbert-base-uncased")
tokenizer=AutoTokenizer.from_pretrained("distilbert-base-uncased")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning:


Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
#bert_dataset=BERTCreationDataset(df_text)

In [ ]:
#generator=torch.Generator()
#generator.manual_seed(seed)
#bert_collate_function_object=BertCollateFunction(tokenizer=tokenizer)
#bert_dataloader=DataLoader(dataset=bert_dataset,batch_size=32,shuffle=False,collate_fn=bert_collate_function_object.collate_fn,worker_init_fn=seed_worker,generator=generator)

In [ ]:
#device = (torch.device("mps") if torch.backends.mps.is_available() else torch.device("cuda" if torch.cuda.is_available() else "cpu"))
#bert_extractor=BERTEmbeddingsExtractor(bert_model=distilbert_model,device=device)
#bert_extractor.get_bert_embeddings(dataloader=bert_dataloader,path="./modules/BERT_embeddings")

In [8]:
all_cls_embeddings=torch.load("./modules/BERT_embeddings/all_cls_embeddings.pt")
all_mean_embeddings=torch.load("./modules/BERT_embeddings/all_mean_embeddings.pt")
print(all_cls_embeddings.shape)
print(all_mean_embeddings.shape)

torch.Size([20000, 768])
torch.Size([20000, 768])

In [9]:
train_df,val_df,test_df,train_cls_embeddings,val_cls_embeddings,test_cls_embeddings,train_mean_embeddings,val_mean_embeddings,test_mean_embeddings=split_df(full_df_processed,cls_embeddings=all_cls_embeddings,mean_embeddings=all_mean_embeddings,random_state=seed)

In [10]:
after_split_preprocessor=AfterSplitPreprocessing(train_df,val_df,test_df)
train_df_processed,val_df_processed,test_df_processed=after_split_preprocessor.preprocessing()

In [11]:
scaler=StandardScaler()
scale_processor=Scaler(scaler)
train_df_processed,val_df_processed,test_df_processed=scale_processor.scale(train_df_processed,val_df_processed,test_df_processed)

In [13]:
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']

In [40]:
train_df_processed.to_parquet(path="./modules/dataframes/train_df_processed.parquet")
val_df_processed.to_parquet(path="./modules/dataframes/val_df_processed.parquet")
test_df_processed.to_parquet(path="./modules/dataframes/test_df_processed.parquet")

## Load of the dataframe

In [19]:
train_parquet_file = pq.ParquetFile("./modules/dataframes/train_df_processed.parquet")
val_parquet_file= pq.ParquetFile("./modules/dataframes/val_df_processed.parquet")
test_parquet_file= pq.ParquetFile("./modules/dataframes/test_df_processed.parquet")

train_df_processed =load(train_parquet_file)
val_df_processed=load(val_parquet_file)
test_df_processed=load(test_parquet_file)

In [14]:
print(f"Columns of the full processed dataframe:")
print(train_df_processed.columns)
print("----------------------------------------")
print(f"Shape of the full processed dataframe:")
print(train_df_processed.shape)
print("----------------------------------------")
print(f"Head of the full  processed dataframe:")
display(train_df_processed.head())
print("----------------------------------------")
for col in train_df_processed.columns:
    print(f"Exemple of {col} :")
    print(train_df_processed.iloc[0][col])
    print("----------------------------------------")
for col in train_df_processed.columns:
    print(f"The type of {col} is")
    print(train_df_processed[col].apply(type).unique())
    print("---------------------------------")

Columns of the full processed dataframe:
Index(['user_id', 'recipe_id', 'rating', 'i', 'techniques_recipes',
       'calorie_level', 'ingredient_ids', 'techniques_users', 'items',
       'n_items', 'ratings', 'n_ratings', 'name', 'minutes', 'tags',
       'nutrition', 'n_steps', 'steps', 'description', 'n_ingredients',
       'rating_scaled', 'ingredient_ids_continuous', 'full_text',
       'calorie_level_scaled', 'n_items_scaled', 'n_ratings_scaled',
       'minutes_scaled', 'n_steps_scaled', 'n_ingredients_scaled'],
      dtype='object')
----------------------------------------
Shape of the full processed dataframe:
(14000, 29)
----------------------------------------
Head of the full  processed dataframe:

,user_id,recipe_id,rating,i,techniques_recipes,calorie_level,ingredient_ids,techniques_users,items,n_items,...,n_ingredients,rating_scaled,ingredient_ids_continuous,full_text,calorie_level_scaled,n_items_scaled,n_ratings_scaled,minutes_scaled,n_steps_scaled,n_ingredients_scaled
3600,175727,11769,5.0,109126,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,"[4623, 6654, 216, 6926, 6335, 4863, 0, 0, 0, 0...","[87, 2, 0, 27, 42, 1, 1, 7, 0, 80, 3, 3, 1, 0,...","[154350, 54820, 77571, 45268, 124558, 38966, 1...",202,...,6,1.0,"[4609, 6629, 215, 6900, 6313, 4847, 1, 1, 1, 1...",walnut brewery asiago cheese dip [SEP] this a ...,-1.086207,-0.386555,-0.386555,-0.156327,0.050739,-0.923525
16216,50509,350359,4.0,53777,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",2,"[5313, 5006, 3203, 5010, 7213, 588, 2594, 2856...","[127, 1, 2, 91, 191, 0, 0, 14, 3, 176, 10, 12,...","[59108, 117303, 16669, 165155, 78915, 115100, ...",580,...,11,0.8,"[5295, 4990, 3195, 4994, 7187, 586, 2588, 2849...",nif s penne with feta [SEP] a delicious and fr...,1.461012,0.004451,0.004451,-0.142037,-0.715266,0.643517
18996,9748,13098,4.0,13490,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,"[150, 1124, 5298, 1909, 4763, 155, 6906, 6276,...","[44, 1, 1, 23, 33, 0, 1, 5, 2, 35, 10, 5, 0, 0...","[75852, 104812, 129769, 99788, 101820, 166815,...",144,...,8,0.8,"[149, 1119, 5281, 1903, 4748, 154, 6880, 6254,...",mom s waldorf salad [SEP] this is my mother's ...,0.187403,-0.446551,-0.446551,-0.184908,-0.970601,-0.296708
14414,161282,56694,0.0,115884,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,"[2730, 3484, 2404, 2499, 6270, 3486, 63, 4053,...","[33, 1, 0, 10, 12, 0, 0, 5, 0, 30, 6, 3, 0, 0,...","[130597, 16122, 49703, 152649, 103416, 36541, ...",92,...,11,0.0,"[2723, 3476, 2398, 2493, 6248, 3478, 63, 4041,...",the very best salisbury steak [SEP] this is ou...,0.187403,-0.500340,-0.500340,-0.099165,-0.204596,0.643517
4882,463435,286053,4.0,60799,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,"[4717, 7998, 3044, 3829, 0, 0, 0, 0, 0, 0, 0, ...","[111, 1, 2, 69, 82, 0, 1, 9, 1, 114, 17, 20, 1...","[32365, 145711, 157654, 141020, 35883, 67138, ...",395,...,4,0.8,"[4702, 7969, 3036, 3820, 1, 1, 1, 1, 1, 1, 1, ...",o j yogurt shake [SEP] this is a yummy and ...,-1.086207,-0.186914,-0.186914,-0.227780,-0.970601,-1.550341

----------------------------------------
Exemple of user_id :
175727
----------------------------------------
Exemple of recipe_id :
11769
----------------------------------------
Exemple of rating :
5.0
----------------------------------------
Exemple of i :
109126
----------------------------------------
Exemple of techniques_recipes :
[1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
----------------------------------------
Exemple of calorie_level :
0
----------------------------------------
Exemple of ingredient_ids :
[4623 6654  216 6926 6335 4863    0    0    0    0    0    0    0    0
    0    0    0    0    0    0]
----------------------------------------
Exemple of techniques_users :
[87  2  0 27 42  1  1  7  0 80  3  3  1  0  3  0 40  0  0  5 20  8  2  8
  9  0  4  4 43  4  1  1  1 58  0  3 19  6 14  1  1  6 29 35  5  1 20  3
  0  5  2  3  0 18  5 18 10 20]
----------------------------------------
Exemple of items :
[154350  54820  77571 ...      0      0      0]
----------------------------------------
Exemple of n_items :
202
----------------------------------------
Exemple of ratings :
[5 5 4 ... 0 0 0]
----------------------------------------
Exemple of n_ratings :
202
----------------------------------------
Exemple of name :
walnut brewery asiago cheese dip
----------------------------------------
Exemple of minutes :
30
----------------------------------------
Exemple of tags :
30 minutes or less [SEP] time to make [SEP] course [SEP] main ingredient [SEP] cuisine [SEP] preparation [SEP] occasion [SEP] north american [SEP] appetizers [SEP] eggs dairy [SEP] american [SEP] oven [SEP] dips [SEP] dietary [SEP] copycat [SEP] novelty [SEP] equipment [SEP] number of servings
----------------------------------------
Exemple of nutrition :
[163.5  23.   18.    6.    5.   44.    1. ]
----------------------------------------
Exemple of n_steps :
9
----------------------------------------
Exemple of steps :
reconstitute sun-dried tomatoes in hot water [SEP] clean , rinse and slice green onions and mushrooms [SEP] squeeze all the water out of the tomatoes , then julieene into fine strips [SEP] combine all ingredients except tomatoes , then add the sun-dried toimatoes [SEP] place into an oven-proof container [SEP] top with remaining 1 t [SEP] of asiago cheese [SEP] bake at 350 for about 15 minutes or until bubbly [SEP] serve immediately with toasted beer bread
----------------------------------------
Exemple of description :
this a copycat recipe from the walnut brewery in littleton colorado. it's really good on baked spuds.
----------------------------------------
Exemple of n_ingredients :
6
----------------------------------------
Exemple of rating_scaled :
1.0
----------------------------------------
Exemple of ingredient_ids_continuous :
[4609 6629  215 6900 6313 4847    1    1    1    1    1    1    1    1
    1    1    1    1    1    1]
----------------------------------------
Exemple of full_text :
walnut brewery asiago cheese dip [SEP] this a copycat recipe from the walnut brewery in littleton colorado. it's really good on baked spuds. [SEP] reconstitute sun-dried tomatoes in hot water [SEP] clean , rinse and slice green onions and mushrooms [SEP] squeeze all the water out of the tomatoes , then julieene into fine strips [SEP] combine all ingredients except tomatoes , then add the sun-dried toimatoes [SEP] place into an oven-proof container [SEP] top with remaining 1 t [SEP] of asiago cheese [SEP] bake at 350 for about 15 minutes or until bubbly [SEP] serve immediately with toasted beer bread [SEP] 30 minutes or less [SEP] time to make [SEP] course [SEP] main ingredient [SEP] cuisine [SEP] preparation [SEP] occasion [SEP] north american [SEP] appetizers [SEP] eggs dairy [SEP] american [SEP] oven [SEP] dips [SEP] dietary [SEP] copycat [SEP] novelty [SEP] equipment [SEP] number of servings
----------------------------------------
Exemple of calorie_level_scaled :
-1.0862070718545758
----------------------------------------
Exemple of n_items_scaled :
-0.38655530277588895
----------------------------------------
Exemple of n_ratings_scaled :
-0.38655530277588895
----------------------------------------
Exemple of minutes_scaled :
-0.15632717377028346
----------------------------------------
Exemple of n_steps_scaled :
0.05073871781348626
----------------------------------------
Exemple of n_ingredients_scaled :
-0.9235247200060333
----------------------------------------
The type of user_id is
[<class 'int'>]
---------------------------------
The type of recipe_id is
[<class 'int'>]
---------------------------------
The type of rating is
[<class 'float'>]
---------------------------------
The type of i is
[<class 'int'>]
---------------------------------
The type of techniques_recipes is
[<class 'numpy.ndarray'>]
---------------------------------
The type of calorie_level is
[<class 'int'>]
---------------------------------
The type of ingredient_ids is
[<class 'numpy.ndarray'>]
---------------------------------
The type of techniques_users is
[<class 'numpy.ndarray'>]
---------------------------------
The type of items is
[<class 'numpy.ndarray'>]
---------------------------------
The type of n_items is
[<class 'int'>]
---------------------------------
The type of ratings is
[<class 'numpy.ndarray'>]
---------------------------------
The type of n_ratings is
[<class 'int'>]
---------------------------------
The type of name is
[<class 'str'>]
---------------------------------
The type of minutes is
[<class 'int'>]
---------------------------------
The type of tags is
[<class 'str'>]
---------------------------------
The type of nutrition is
[<class 'numpy.ndarray'>]
---------------------------------
The type of n_steps is
[<class 'int'>]
---------------------------------
The type of steps is
[<class 'str'>]
---------------------------------
The type of description is
[<class 'str'>]
---------------------------------
The type of n_ingredients is
[<class 'int'>]
---------------------------------
The type of rating_scaled is
[<class 'float'>]
---------------------------------
The type of ingredient_ids_continuous is
[<class 'numpy.ndarray'>]
---------------------------------
The type of full_text is
[<class 'str'>]
---------------------------------
The type of calorie_level_scaled is
[<class 'float'>]
---------------------------------
The type of n_items_scaled is
[<class 'float'>]
---------------------------------
The type of n_ratings_scaled is
[<class 'float'>]
---------------------------------
The type of minutes_scaled is
[<class 'float'>]
---------------------------------
The type of n_steps_scaled is
[<class 'float'>]
---------------------------------
The type of n_ingredients_scaled is
[<class 'float'>]
---------------------------------

## Model

In [15]:
train_dataset=CreationDataset(train_df_processed,cls_embeddings=train_cls_embeddings,mean_embeddings=train_mean_embeddings)
val_dataset=CreationDataset(val_df_processed,cls_embeddings=val_cls_embeddings,mean_embeddings=val_mean_embeddings)

In [16]:
train_dataset.__getitem__(10)

{'user_id': np.int64(440299),
 'recipe_id': np.int64(5012),
 'rating': np.float64(5.0),
 'i': np.int64(109198),
 'techniques_recipes': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 'calorie_level': np.int64(1),
 'ingredient_ids': array([  63, 5006, 2499, 7168, 7655, 7956, 6906,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32),
 'techniques_users': array([5, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0, 1, 1, 2,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2]),
 'items': array([ 18676,  75351, 109198, ...,      0,      0,      0], dtype=int32),
 'n_items': np.int64(10),
 'ratings': array([2, 5, 5, ..., 0, 0, 0], dtype=int32),
 'n_ratings': np.int64(10),
 'name': 'chicago style deep dish pizza crust',
 'minutes': np.int64(0),
 'tags': '15 minutes or less [SEP] time to make [SEP] course [SEP] cuisine [SEP] preparation [SEP] occasion [SEP] north american [SEP] healthy [SEP] breads [SEP] main dish [SEP] american [SEP] kid friendly [SEP] pizza [SEP] dietary [SEP] low sodium [SEP] low saturated fat [SEP] midwestern [SEP] yeast [SEP] low in something',
 'nutrition': array([300.8,  10. ,   6. ,   1. ,  18. ,   6. ,  16. ]),
 'n_steps': np.int64(10),
 'steps': 'whisk together water , yeast and sugar in a bowl and set aside to proof for 10 minutes [SEP] in a large bowl sift together flour and salt and sprinkle in thyme [SEP] mix eggs into yeast mixture [SEP] pour liquid into dry ingredients and mix until a soft sticky dough forms [SEP] remove dough to a lightly floured surface and knead 5 minutes , until dough is no longer sticky [SEP] place in a well oiled bowl , turning to coat all sides , cover and allow to rise until doubled in bulk 2 - 3 hours [SEP] punch dough down and place into a well oiled 12" pizza pan [SEP] using your hands , move dough around the bottom of the pan and 2 / 3 the way up the sides [SEP] set aside and let rise 10 minutes [SEP] brush crust lightly with olive oil and add toppings',
 'description': 'missing description',
 'n_ingredients': np.int64(7),
 'rating_scaled': np.float64(1.0),
 'ingredient_ids_continuous': array([  63, 4990, 2493, 7142, 7628, 7927, 6880,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1]),
 'full_text': 'chicago style deep dish pizza crust [SEP] missing description [SEP] whisk together water , yeast and sugar in a bowl and set aside to proof for 10 minutes [SEP] in a large bowl sift together flour and salt and sprinkle in thyme [SEP] mix eggs into yeast mixture [SEP] pour liquid into dry ingredients and mix until a soft sticky dough forms [SEP] remove dough to a lightly floured surface and knead 5 minutes , until dough is no longer sticky [SEP] place in a well oiled bowl , turning to coat all sides , cover and allow to rise until doubled in bulk 2 - 3 hours [SEP] punch dough down and place into a well oiled 12" pizza pan [SEP] using your hands , move dough around the bottom of the pan and 2 / 3 the way up the sides [SEP] set aside and let rise 10 minutes [SEP] brush crust lightly with olive oil and add toppings [SEP] 15 minutes or less [SEP] time to make [SEP] course [SEP] cuisine [SEP] preparation [SEP] occasion [SEP] north american [SEP] healthy [SEP] breads [SEP] main dish [SEP] american [SEP] kid friendly [SEP] pizza [SEP] dietary [SEP] low sodium [SEP] low saturated fat [SEP] midwestern [SEP] yeast [SEP] low in something',
 'calorie_level_scaled': np.float64(0.18740256013571407),
 'n_items_scaled': np.float64(-0.5851617088561376),
 'n_ratings_scaled': np.float64(-0.5851617088561376),
 'minutes_scaled': np.float64(-0.24207057982625665),
 'n_steps_scaled': np.float64(0.30607374635008233),
 'n_ingredients_scaled': np.float64(-0.6101164182635486),
 'cls_embeddings': tensor([-4.3926e-01, -8.0494e-02,  1.5189e-01, -9.7821e-02,  2.1476e-02,
         -9.6848e-02,  1.1897e-01,  2.9560e-01, -1.8832e-01, -2.4743e-01,
         -7.7781e-02, -3.0157e-02,  2.3765e-02,  2.2340e-01, -1.6420e-01,
          3.8480e-02,  1.2496e-01,  1.8147e-01,  1.5513e-01, -7.9278e-03,
         -9.4934e-02, -5.6202e-01,  5.7085e-02, -7.7405e-02, -4.0344e-03,
         -5.1196e-02, -1.5435e-01, -7.4455e-02,  6.3317e-02, -2.2641e-02,
         -7.6512e-03,  2.2540e-01,  5.2787e-02, -3.8075e-01,  3.3826e-01,
         -7.0280e-03,  4.1102e-01,  9.6607e-02,  6.5771e-02, -9.7780e-02,
         -3.7799e-02,  1.6033e-01,  4.1844e-01, -2.9992e-01, -1.0954e-02,
          3.6213e-02, -2.3884e+00, -4.2031e-02, -4.0388e-01, -2.9736e-01,
          1.8779e-01, -9.4406e-02,  6.0406e-02,  1.4631e-01,  1.6248e-01,
          2.8919e-01, -2.5865e-01,  5.9218e-01,  7.5641e-02,  9.8979e-02,
          1.4040e-01,  9.7290e-02, -8.9526e-02,  1.5988e-01, -8.6498e-02,
          5.7646e-02, -1.0825e-01,  2.4107e-01, -3.6068e-01,  5.2401e-01,
         -3.0505e-01, -9.6168e-02,  1.2739e-01, -4.8393e-02,  1.4532e-01,
         -1.3455e-01,  1.2733e-01,  4.5125e-02, -1.6926e-01,  1.6467e-01,
         -1.5193e-01, -7.5943e-04,  1.1529e-01,  2.1900e-01,  5.3455e-03,
          3.0130e-01, -2.5704e-01, -5.4670e-02,  2.0509e-01,  4.2851e-01,
         -7.1669e-02,  1.0851e-01,  2.6843e-01,  1.2738e-01,  2.0056e-01,
         -3.2625e-01,  1.0078e-01,  6.8375e-02,  4.5960e-01,  2.4739e-01,
         -8.1177e-02, -2.5300e-02,  1.5170e-01, -1.5651e-01,  7.5750e-02,
         -1.3712e-01, -1.6502e-01, -2.1027e-01,  4.6497e-02, -2.1874e+00,
          3.1626e-01,  3.0064e-01,  5.0905e-02, -1.0305e-01, -2.2824e-01,
         -3.5598e-02,  2.1088e-01,  1.6718e-01, -5.7841e-03, -1.3090e-01,
         -2.1021e-01,  5.6268e-01,  9.0708e-02, -1.1265e-01,  1.2016e-01,
          2.3129e-01,  4.8681e-02,  1.7640e-01,  2.9800e-01,  2.5420e-01,
          1.0875e-01,  2.0575e-01, -7.4310e-02, -7.6300e-02, -1.7633e-01,
          2.9544e-01,  2.1423e-01,  3.2646e-02,  8.2375e-02, -1.8468e-01,
         -3.8736e-01, -1.7824e-01, -2.7055e+00,  1.8994e-01,  3.7929e-01,
         -7.6290e-02, -1.1820e-01, -4.4574e-02,  6.1063e-03,  2.4709e-01,
          2.9772e-01,  9.8910e-02, -1.9427e-01,  3.5553e-02, -1.5927e-01,
          1.0789e-01, -2.2606e-01, -2.1794e-01,  1.8181e-01, -3.4848e-02,
          1.5071e-01, -2.9513e-02,  9.1261e-03, -2.3303e-01, -1.0360e-01,
          4.5750e-02,  1.4714e-01,  6.3765e-02, -9.0737e-02,  2.1855e-01,
         -1.2367e-01,  7.0138e-02,  4.5026e-01, -4.6074e-03,  2.3267e-01,
          5.5692e-02, -2.7977e-03,  1.7769e-01,  6.1988e-02, -9.6830e-02,
         -2.0099e-01,  4.1236e-01,  1.0160e-01,  3.8106e-02, -1.1563e-01,
         -2.2056e-01,  2.5084e-01, -1.7908e-01,  9.9776e-02,  2.7291e-01,
         -6.8151e-02, -1.2620e-01,  7.1326e-02, -1.0605e-01,  2.5336e-01,
          5.8718e-02,  1.4395e-02, -5.2991e-01,  2.7293e-01,  1.2887e-01,
         -1.6590e-01,  1.2687e-01,  5.4675e-02, -5.3884e-02, -2.9484e-01,
          3.6170e+00,  1.4138e-01, -6.3448e-02,  4.4450e-01,  1.6606e-01,
          4.0848e-02, -3.9796e-02,  7.0076e-02, -2.1353e-01,  2.2668e-01,
          4.6193e-02,  5.0917e-01,  3.5284e-02,  2.6627e-01, -2.0723e-01,
          1.9853e-01,  1.9341e-01,  3.4011e-02,  3.1242e-01, -2.0404e-01,
         -7.9438e-02, -3.8666e-02,  2.5389e-02,  7.2507e-02, -9.8698e-01,
          2.3620e-01, -1.5100e-01, -1.8318e-02,  3.1354e-01, -1.6759e-01,
         -1.7712e-01,  2.8211e-01,  1.3598e-01,  1.9277e-01, -5.3715e-02,
          1.0545e-01,  1.9678e-01,  3.1855e-01, -1.0173e-01, -2.9817e-01,
          1.7895e-01,  9.0379e-02,  1.7815e-02, -5.5551e-02, -2.3651e-01,
          2.0419e-01, -9.8801e-02,  5.9829e-02, -1.9271e-01,  1.0717e-01,
         -1.0795e-01,  1.0910e-01, -4.0347e-02, -1.3725e-01, -1.2285e-01,
         -3.3318e-01, -3.9065e-02,  2.4768e-01, -7.7587e-02, -3.1765e-01,
          4.7572e-03, -2.1586e-01, -1.2792e-01, -2.3080e-02, -1.0744e-02,
         -3.2111e-02,  5.0523e-02, -3.6639e-01, -3.6253e+00, -4.6896e-02,
         -1.9764e-01,  2.4940e-01,  1.8293e-01, -1.8048e-01, -6.8881e-02,
          2.2758e-01,  1.9996e-01,  2.8876e-02,  4.8408e-01,  4.4881e-02,
         -5.6767e-02,  1.6429e-01, -4.5936e-01, -2.7710e-02,  6.6913e-03,
         -4.1584e-02,  2.4304e-01, -1.7135e-01, -6.8945e-02,  2.0619e-01,
         -1.5350e-01,  8.4970e-02,  3.9959e-02,  1.0625e-01, -3.8985e-01,
          1.6164e-02, -1.3002e-01,  1.1247e-01, -1.8311e-02, -3.0952e-01,
         -3.8914e-02, -3.3916e-01, -3.8436e-01, -3.1450e+00, -2.2183e-01,
         -3.0344e-01, -1.0318e-01,  1.7709e-01, -2.5821e-01,  3.6708e-01,
         -3.2438e-01, -1.1967e-01,  3.4989e-01, -9.3760e-02, -1.4778e-03,
          1.3843e-01,  2.2801e-02,  2.8655e-01,  2.1295e-01,  3.0743e-01,
         -6.3854e-02,  1.7121e-01,  1.9922e-01,  2.3800e-01, -1.4183e-03,
          6.4107e-02,  2.0074e-01, -3.9903e-02,  1.6789e-01, -4.1472e-01,
          1.9357e-01, -2.9848e-01, -7.4997e-02, -7.2514e-02, -2.5927e-01,
         -1.6533e-01, -2.6010e-02, -1.5505e-01, -3.0497e-01, -5.5179e-02,
          3.0901e-01,  4.2258e-01,  2.2868e-01, -5.6734e-02,  6.1243e-01,
         -4.1364e-03, -1.0637e-01,  3.6192e-01,  1.5388e-01,  3.3474e-01,
         -2.8729e-01, -2.0390e-02,  2.1368e-01,  4.2972e-02,  4.4213e-02,
          1.0139e+00, -1.1801e-01,  1.9863e-01, -8.0165e-02,  3.6327e-01,
         -2.5541e-02,  1.8111e-01, -1.0952e-01,  2.6714e-01, -5.8549e-02,
          1.8645e-02, -1.2104e-01,  2.0790e-02, -1.7724e-01,  1.3623e-01,
         -1.9804e-01,  1.5318e-02,  2.8266e-04, -8.9608e-02,  9.7948e-02,
          1.2358e-01, -7.6754e-01, -1.8809e-01, -1.4006e-01, -1.1901e-01,
          1.3088e-01, -2.1835e-02,  2.5184e-01, -2.4893e-01,  2.5228e-02,
          8.2740e-02,  3.6527e-01, -1.0551e-01,  2.5268e-02, -2.2786e-01,
          4.3883e-02, -5.5502e-01,  4.0396e-03,  1.9241e-01,  1.1979e-01,
         -1.1047e-02, -1.5856e-01,  3.5303e-02,  1.4071e-01,  1.2140e-01,
         -7.5401e-01,  1.1205e-01, -2.9014e-01,  1.1509e-02, -1.8608e-01,
          8.8281e-02, -1.4376e-01, -1.0446e-01, -1.3785e-01, -1.5088e-01,
          2.6151e-01,  8.6337e-02,  1.5922e-01, -1.0641e-01,  7.4093e-02,
         -1.8800e-01,  9.9260e-03,  7.0240e-01,  1.0295e-01, -1.7421e-01,
          1.0592e-01, -8.1311e-03,  2.6202e-01,  3.4301e-01,  5.8355e-02,
          1.5202e-01, -1.0479e-02,  4.6642e-02, -1.1320e-01,  2.2798e-01,
         -2.2040e-01, -2.9426e-01,  2.6265e-01,  6.1722e-02, -2.9661e-02,
         -5.0082e-02, -5.1473e-01, -5.1829e-02, -1.6959e-01, -2.4901e-01,
          2.6857e-01,  1.9222e-01, -8.8533e-02,  2.6145e-01,  7.2822e-02,
         -1.9692e-02,  3.1027e-01, -1.5872e-02,  5.5843e-01,  1.5355e-01,
         -3.7643e-03,  7.8144e-02,  2.4584e-01,  1.3235e-01, -6.9386e-02,
         -1.3883e-01, -1.7797e-01, -4.9232e-02, -1.1112e-01,  9.2039e-04,
          2.3943e-02, -2.6821e-01,  1.4667e-02,  6.6110e-02,  1.9910e-02,
         -1.4981e+00,  2.0384e-01,  2.9461e-02, -2.3086e-02, -9.9821e-04,
         -2.1651e-01, -2.5298e-01,  3.6206e-01,  2.0126e-01, -1.1574e-01,
         -2.6054e-01,  5.0371e-02,  5.3175e-02,  1.3036e-02,  1.5861e-01,
         -6.1535e-02,  4.6658e-02, -1.2930e-01, -7.8859e-02,  7.8653e-02,
         -1.8516e-01,  4.0234e-01, -1.1792e-01, -1.5908e-01, -9.9499e-02,
         -1.4255e-01, -1.3257e-02,  2.7369e-01,  1.5458e-01,  5.2198e-02,
          1.0235e-01, -1.7776e-01, -3.1346e-01, -1.3864e-02,  9.2282e-02,
          5.3052e-01, -5.1862e-02, -1.3058e-01,  2.8180e-01,  1.9755e-01,
         -5.3865e-01,  1.8096e-01,  2.4673e-01, -1.8016e-02,  4.0770e-01,
          2.7373e-01, -1.4515e-01,  1.6720e-01,  1.8356e-02, -9.6378e-02,
          5.6726e-03, -1.5315e-01, -1.4712e-01, -5.4042e-02,  1.0330e-02,
          1.2818e-01,  1.7885e-01, -1.0342e-01,  6.6779e-02, -1.9739e-01,
          8.7679e-02, -1.7025e-01, -1.4321e-01,  3.8324e-01,  1.0955e-03,
         -5.9542e-01, -7.1815e-02,  4.3666e-02,  1.3095e-01,  1.7700e-01,
          3.1900e-01,  1.9722e-01, -1.7848e-01,  2.2193e-01, -3.3946e-01,
          1.7014e-01, -8.1590e-02,  1.6025e-01,  1.3697e-01, -6.3627e-02,
         -3.2961e-02, -2.3130e-01, -4.8519e-01,  2.6354e-01,  1.0429e-01,
         -7.5910e-02, -1.1619e-01,  6.7850e-02,  2.5178e-01,  6.7425e-03,
         -1.2294e-01, -3.5889e-01,  1.5538e-01,  1.6078e-01, -2.2705e-02,
          2.7021e-02,  1.0159e-01,  2.2105e-01, -8.6866e-02,  1.2526e-01,
         -4.4487e-02,  2.2335e-01,  2.7975e-01,  2.0670e-01,  3.2050e-02,
         -2.6862e-02,  8.3396e-02,  2.6668e-02, -2.5835e-02,  1.1574e-01,
          1.4106e-01,  1.3240e-01,  2.1088e-01,  1.6199e-01, -1.6636e-01,
         -3.8655e-01,  1.3989e-01, -1.0557e-01,  1.8918e+00,  2.5154e-01,
         -5.7866e-02,  1.1697e-01,  1.6432e-01, -4.6247e-03, -1.3474e-01,
          1.1874e-01, -2.6633e-01,  4.3818e-01,  1.1555e-01,  1.1806e-01,
         -1.2007e-01,  1.1425e-01,  2.8781e-01,  2.5333e-01, -2.2793e-02,
         -8.0757e-02, -3.5079e-01,  1.0841e-01, -4.2065e-01,  2.6400e-01,
          1.8109e-01, -1.4003e-01, -5.8306e-02,  1.3446e-01,  1.3160e-01,
         -9.6604e-02,  7.9812e-02,  7.0873e-02, -2.8947e-02, -1.1833e-01,
         -5.8746e-03,  3.7192e-01, -6.4857e-02,  5.1263e-02,  4.0038e-02,
         -2.2548e-01, -2.1406e-01,  2.4342e-01,  1.9408e-01, -4.4586e-01,
          3.2101e-01, -1.0224e-01, -6.9413e-02,  3.5498e-01, -1.9408e-01,
         -4.4596e-01,  1.1276e-01,  8.6103e-02,  1.5515e-02,  1.0798e-01,
         -2.6724e-01, -1.7683e-02, -9.2630e-02,  2.4824e-02, -8.5071e-02,
         -1.3467e-01, -3.1814e-01,  3.8439e-01,  2.1553e-02,  2.4649e-01,
          2.3472e-01, -1.0657e-01,  2.9153e-01,  1.0203e-01, -2.5465e-01,
          4.4665e-02,  5.8582e-02, -5.6107e-02, -7.8599e-02,  6.6927e-03,
          1.6225e-01,  2.4978e-01,  9.7655e-02, -1.6675e-01,  2.4094e-01,
         -1.5415e-01, -2.5830e-01, -2.3883e+00, -1.9858e-02,  5.4993e-02,
         -6.7387e-02, -5.0541e-02,  2.6674e-01,  1.5227e-01, -2.9625e-01,
         -2.2303e-01, -2.1996e-01,  3.8450e-01,  2.8356e-01,  8.0056e-02,
         -6.2887e-02,  2.1506e-01, -1.0166e-01,  7.5961e-02, -2.5285e-01,
          8.4287e-02, -3.8517e-02,  1.3316e-01, -2.4381e-02, -1.6394e-02,
         -2.1733e-01, -3.3400e-01, -2.9527e-02,  1.0207e-02, -2.6994e-01,
          7.2570e-02, -1.0175e-01, -9.6514e-02,  8.8585e-02, -7.8387e-02,
         -4.4849e-02, -2.5727e-01, -2.1486e-01, -3.9008e-02,  7.9355e-02,
         -6.0729e-02,  1.0334e-01, -1.2396e-01,  3.8213e-01, -2.5837e-02,
          1.9702e-01, -1.8630e-01,  8.3891e-02,  3.1181e-01, -2.4913e-01,
          4.2572e-01, -1.3803e-01,  1.3299e-01,  9.3797e-02, -2.0112e-02,
          2.6042e-01,  4.4999e-02,  7.8430e-02,  9.4429e-02,  1.6658e-02,
         -1.9302e-01, -2.5710e-02, -4.1273e-01,  4.8893e-02, -9.3181e-02,
          7.4541e-03,  3.2401e-01, -1.1291e-01, -9.1418e-02,  1.7469e-03,
          1.2941e-04, -8.7341e-02, -8.8551e-03, -1.3884e-01,  3.9764e-01,
          1.1009e-01,  6.6763e-02, -2.6532e-02,  2.3280e-01,  2.7811e-01,
          9.6838e-02,  5.6105e-02,  7.3123e-02, -2.0519e-01, -1.7856e-01,
         -3.6749e-02,  4.7213e-01, -6.8857e+00, -2.1297e-01, -6.5105e-02,
         -2.4579e-02, -9.7571e-02, -7.6994e-02,  1.2418e-01, -3.5733e-01,
          4.4367e-02,  3.5709e-02,  1.2189e-01,  3.7780e-02, -1.9954e-01,
         -8.9761e-02,  1.6379e-01,  4.0633e-01]),
 'mean_embeddings': tensor([-1.6662e-02,  4.2074e-02,  1.1839e-01,  2.1663e-01,  2.8436e-01,
         -1.2278e-01,  5.1610e-02, -4.1407e-02,  2.0320e-01, -3.3600e-01,
          7.4439e-02, -5.2773e-02,  3.5081e-02,  9.2372e-02, -1.8272e-01,
         -7.8776e-02,  1.9925e-01,  7.1945e-02, -2.0449e-02,  1.8879e-01,
          6.9198e-02, -2.2404e-01, -5.5204e-02,  1.5460e-02,  2.8019e-01,
          8.9466e-02, -2.0350e-01, -1.2886e-01,  2.9670e-02, -3.3339e-01,
          2.5904e-02,  2.1987e-02,  2.1461e-01, -2.1357e-01,  2.2484e-01,
          6.3922e-02,  1.6604e-01,  1.8941e-01, -1.7809e-01, -6.0738e-02,
         -2.4649e-01, -6.0080e-04,  2.1863e-01, -2.7786e-01,  6.9416e-03,
         -1.2261e-01,  9.4630e-02,  4.4575e-03, -4.4969e-01, -8.2545e-03,
          1.4209e-01, -1.1567e-01, -1.1929e-01, -2.2524e-01, -8.2005e-02,
          2.2596e-01, -1.3114e-01,  9.7403e-02, -2.8955e-02, -1.2073e-01,
         -7.0387e-02,  1.3208e-01,  2.0408e-02, -7.7899e-02, -9.8122e-02,
          5.9839e-02,  1.8793e-03,  2.1107e-01, -4.5596e-01,  2.4604e-01,
         -6.9107e-03, -2.4657e-02, -3.7652e-02,  2.1964e-02, -6.4047e-03,
         -7.8861e-02, -2.7291e-02,  9.2706e-02,  1.0847e-01,  3.2447e-02,
         -3.7829e-01, -1.6985e-01,  3.3011e-02,  2.2808e-01,  9.2148e-02,
          1.6660e-01,  3.5225e-02,  3.5488e-02, -9.8106e-02,  2.6056e-01,
          1.7566e-01,  1.9739e-02,  1.9184e-01, -1.4389e-01, -4.7654e-02,
         -1.5918e-01,  9.1089e-02,  1.3081e-01,  2.7996e-01,  4.3999e-01,
         -2.5351e-01, -1.9203e-01,  1.8737e-01,  2.8676e-01,  4.1147e-02,
         -4.0045e-02, -5.5076e-02,  4.3265e-02,  1.2789e-01,  2.3433e-01,
          2.6919e-01,  4.7187e-04,  1.4939e-01,  1.3466e-01, -1.6025e-01,
         -1.8985e-03, -1.4686e-01,  1.3129e-01, -8.1068e-02, -6.0758e-02,
         -2.1717e-01,  9.1166e-02,  1.8817e-01,  3.3244e-01, -8.3954e-02,
         -4.2420e-02, -1.4173e-01,  1.0564e-01,  1.0218e-01, -8.3232e-02,
         -8.3919e-02, -4.9405e-02,  1.3453e-01, -1.4936e-01, -1.3681e-01,
          1.0897e-01,  6.3241e-02, -6.3857e-02,  1.9044e-01, -1.2086e-01,
         -9.7653e-02,  1.9045e-01,  3.1758e-01,  2.0207e-02,  7.2904e-02,
         -4.2222e-02, -7.8990e-02, -4.9199e-02, -1.8191e-02,  1.4049e-01,
          3.1234e-01,  5.3246e-02, -1.0161e-01, -1.2028e-01, -8.8964e-02,
          1.5525e-01, -2.5567e-01,  2.8187e-02, -1.3531e-01, -1.6901e-03,
          2.6972e-01,  1.5388e-01,  1.5065e-01, -1.0779e-01,  8.8708e-02,
         -8.9132e-02,  1.5199e-01,  2.6249e-01, -1.4410e-01,  5.0402e-01,
         -6.9780e-02, -8.8512e-02,  5.0903e-01,  7.5069e-02, -9.5300e-02,
         -8.0811e-02,  2.2069e-01, -1.7781e-02, -2.2209e-02, -1.6306e-01,
         -6.6163e-01,  4.2049e-02,  3.9499e-02, -7.4795e-02, -1.6555e-02,
         -1.8578e-01,  1.0984e-01, -2.3248e-01,  1.8366e-01, -3.3351e-02,
         -9.4744e-02, -3.3248e-01, -5.4605e-02, -8.3824e-02,  1.6278e-01,
         -3.0224e-01, -9.3282e-02, -1.2763e-02, -3.8296e-02, -6.2403e-02,
          1.8829e-01,  1.6524e-01,  1.6218e-01, -7.1763e-02, -1.1963e-01,
         -6.1435e-02,  2.0407e-01, -1.2922e-01,  3.9056e-01, -1.3653e-01,
         -2.4571e-01,  1.4611e-01,  2.1571e-02, -1.8141e-01, -8.4120e-02,
         -3.5814e-02,  4.1551e-01, -1.1545e-03,  1.2304e-01, -1.1461e-01,
          4.7400e-02, -9.6703e-03, -1.6946e-01,  3.3210e-01, -2.4970e-01,
         -1.4372e-03,  2.4704e-01, -2.4014e-01,  1.0224e-01,  1.4134e-01,
          1.0560e-01, -2.8850e-01,  2.4860e-01,  3.7028e-02, -2.3876e-02,
          1.8398e-01,  2.6310e-01,  1.2688e-01,  1.6094e-01, -2.4885e-01,
          3.1678e-02,  1.4246e-01,  4.4628e-01, -1.7303e-01,  4.9229e-02,
         -6.0775e-02,  6.4991e-02,  2.3120e-01, -1.3854e-01, -4.1586e-01,
         -1.8144e-01, -1.6856e-01,  4.0423e-02, -2.8587e-01, -1.8045e-02,
         -1.2986e-01, -1.6718e-01, -7.4478e-02,  1.9822e-01,  4.4522e-02,
          5.0001e-02, -1.7799e-02,  3.5915e-01, -1.5545e-01, -1.9066e-01,
          3.1441e-02, -2.1154e-01,  1.2222e-01,  7.8136e-02,  1.0378e-01,
         -4.7484e-02, -1.0394e-01, -1.1279e-01,  1.8241e-01, -2.0625e-01,
         -4.3000e-01,  3.2139e-01,  8.7879e-02, -8.4488e-02, -1.7032e-01,
         -1.1894e-03,  2.9195e-01, -1.0774e-01,  2.5712e-01, -2.8101e-02,
         -2.5813e-01, -7.6533e-02, -1.8652e-01, -2.2178e-01, -3.1679e-01,
         -1.5726e-02,  2.0318e-01, -1.6029e-01, -2.3257e-02,  1.7688e-01,
         -1.2873e-02,  8.3163e-02,  1.9049e-01,  3.2567e-01, -1.0365e-01,
          5.8366e-02, -5.2214e-02,  4.9033e-02,  8.7247e-02, -4.7931e-01,
          5.8047e-02, -1.7386e-01, -2.4390e-01, -4.6199e+00, -1.7043e-01,

In [17]:
generator=torch.Generator()
generator.manual_seed(seed)
collate_function_object=CollateFunction(tokenizer=tokenizer)
collate_fn=collate_function_object.collate_fn
train_dataloader=DataLoader(train_dataset,batch_size=64,collate_fn=collate_fn,generator=generator,worker_init_fn=seed_worker,shuffle=True,drop_last=True)
val_dataloader=DataLoader(val_dataset,batch_size=64,collate_fn=collate_fn,generator=generator,worker_init_fn=seed_worker,shuffle=True,drop_last=True)

In [18]:
batch=next(iter(train_dataloader))
for key in list(batch.keys()):
    print(key)
    print(f"The shape of batch {key} is :")
    print(batch[key].shape)
    print("-------------------")

user_id
The shape of batch user_id is :
torch.Size([64, 1])
-------------------
recipe_id
The shape of batch recipe_id is :
torch.Size([64, 1])
-------------------
rating_scaled
The shape of batch rating_scaled is :
torch.Size([64, 1])
-------------------
i
The shape of batch i is :
torch.Size([64, 1])
-------------------
technique_recipes
The shape of batch technique_recipes is :
torch.Size([64, 58])
-------------------
calorie_level_scaled
The shape of batch calorie_level_scaled is :
torch.Size([64, 1])
-------------------
ingredient_ids
The shape of batch ingredient_ids is :
torch.Size([64, 20])
-------------------
techniques_users
The shape of batch techniques_users is :
torch.Size([64, 58])
-------------------
items
The shape of batch items is :
torch.Size([64, 6437])
-------------------
n_items_scaled
The shape of batch n_items_scaled is :
torch.Size([64, 1])
-------------------
ratings_scaled
The shape of batch ratings_scaled is :
torch.Size([64, 6437])
-------------------
n_ratings_scaled
The shape of batch n_ratings_scaled is :
torch.Size([64, 1])
-------------------
minutes_scaled
The shape of batch minutes_scaled is :
torch.Size([64, 1])
-------------------
nutrition
The shape of batch nutrition is :
torch.Size([64, 7])
-------------------
n_ingredients_scaled
The shape of batch n_ingredients_scaled is :
torch.Size([64, 1])
-------------------
ingredient_ids_continuous
The shape of batch ingredient_ids_continuous is :
torch.Size([64, 20])
-------------------
cls_embeddings
The shape of batch cls_embeddings is :
torch.Size([64, 768])
-------------------
mean_embeddings
The shape of batch mean_embeddings is :
torch.Size([64, 768])
-------------------

In [ ]:
#PP_recipes_df["ingredient_ids_transformed"]=PP_recipes_df["ingredient_ids"].apply(lambda x: list(map(int,ast.literal_eval(x))))
#all_ingredient_ids=np.unique(list(itertools.chain.from_iterable(list(PP_recipes_df["ingredient_ids_transformed"]))))
#ingredient_continuous_ids=pd.Series([i for i in range(1,len(all_ingredient_ids)+1)],index=list(np.sort(all_ingredient_ids)))

In [ ]:
#n_recipes_ids=len(np.unique(PP_recipes_df["i"]))
#n_ingredients_ids=len(all_ingredient_ids)

#print(f"There are {n_recipes_ids} recipe ids")
#print(f"There are {n_ingredients_ids} ingredient ids")

There are 178265 recipe ids
There are 7993 ingredient ids

In [ ]:
#hash_encoder=EncodedHashedEmbeddings(n_recipes_ids,512,n_ingredients_ids,512)
#hashed_recipes_ids_encoded_embeddings,hashed_ingredients_ids_encoded_embeddings=hash_encoder.get_encoded_hashed_embeddings("./modules/hashed_encoded_tables")

In [19]:
hashed_ingredients_ids_encoded_embeddings=torch.load("./modules/hashed_encoded_tables/hashed_embeddings_ingredients.pt")
hashed_recipes_ids_encoded_embeddings=torch.load("./modules/hashed_encoded_tables/hashed_embeddings_recipes.pt")

In [20]:
tokenizer=AutoTokenizer.from_pretrained("distilbert-base-uncased")
device = (torch.device("mps") if torch.backends.mps.is_available() else torch.device("cuda" if torch.cuda.is_available() else "cpu"))
print(device)

cuda

In [25]:
#Loss with alpha = 0.3 and temperature = 0.2
loss_alpha=0.3
temperature=0.2
hyperparemeters_ranges={
    "batch_size":[32, 64],
    "dropout":{
        "low":0.05,
        "high":0.3,
        "step":0.05
    },
    "projec_dropout":{
        "low":0.05,
        "high":0.3,
        "step":0.05
    },
    "lr":{
        "low":1e-4,
        "high":1e-2,
        "log":True
    },
    "weight_decay":{
        "low":1e-5,
        "high":1e-3,
        "log":True
    },
    "warmup_prop":{
        "low":0.01,
        "high":0.1,
        "step":0.01
    },
    "mean_mode": [True, False]
}
optuna_object=OptunaFunction(train_df=train_df_processed,val_df=val_df_processed,train_cls_embeddings=train_cls_embeddings,
                             val_cls_embeddings=val_cls_embeddings,train_mean_embeddings=train_mean_embeddings,
                             val_mean_embeddings=val_mean_embeddings,hashed_ingredients_ids_encoded_embeddings=hashed_ingredients_ids_encoded_embeddings,
                             hashed_recipes_ids_encoded_embeddings=hashed_recipes_ids_encoded_embeddings,loss_alpha=loss_alpha,temperature=temperature,
                             device=device,tokenizer=tokenizer,hyperparemeters_ranges=hyperparemeters_ranges)

In [30]:
study=optuna.create_study(direction="minimize",pruner=optuna.pruners.MedianPruner(),storage="sqlite:///optuna_study.db",load_if_exists=True,study_name="recommendation_model_study")

[I 2026-04-08 23:50:21,903] Using an existing study with name 'recommendation_model_study' instead of creating a new one.

In [31]:
study.optimize(optuna_object.objective,n_trials=10)

2026-04-08 23:50:40.895 | INFO     | modules.optuna_function:objective:88 - Trial number 0:
2026-04-08 23:50:40.896 | INFO     | modules.optuna_function:objective:89 - batch_size:64_dropout:0,15000000000000002_projec_dropout:0,1_lr:0,0004724968056532259_weight_decay:1,371295256336384e-05_warmup_prop:0,060000000000000005_mean_mode:False_loss_temp:0,2_loss_alpha:0,3
2026-04-08 23:50:40.897 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-08 23:51:49.959 | INFO     | modules.train:run_training:180 - Epoch 0 : train total loss = 1.178026832571817
2026-04-08 23:51:49.960 | INFO     | modules.train:run_training:181 - Epoch 0 : train contrastive loss = 3.817592550855164
2026-04-08 23:51:49.961 | INFO     | modules.train:run_training:182 - Epoch 0 : train MSE loss = 0.04678431115702752
2026-04-08 23:51:49.962 | INFO     | modules.train:run_training:184 - Epoch 0 : validation total loss = 1.163207067095715
2026-04-08 23:51:49.962 | INFO     | modules.train:run_training:185 - Epoch 0 : validation contrastive loss = 3.785812574884166
2026-04-08 23:51:49.963 | INFO     | modules.train:run_training:186 - Epoch 0 : validation MSE loss = 0.03923321086103502
2026-04-08 23:51:50.029 | INFO     | modules.train:run_training:89 - Epoch 1 :
2026-04-08 23:53:00.066 | INFO     | modules.train:run_training:180 - Epoch 1 : train total loss = 1.1569127757614905
2026-04-08 23:53:00.067 | INFO     | modules.train:run_training:181 - Epoch 1 : train contrastive loss = 3.772872994799133
2026-04-08 23:53:00.068 | INFO     | modules.train:run_training:182 - Epoch 1 : train MSE loss = 0.035786902433722664
2026-04-08 23:53:00.069 | INFO     | modules.train:run_training:184 - Epoch 1 : validation total loss = 1.1453330568645312
2026-04-08 23:53:00.069 | INFO     | modules.train:run_training:185 - Epoch 1 : validation contrastive loss = 3.7288540394409844
2026-04-08 23:53:00.070 | INFO     | modules.train:run_training:186 - Epoch 1 : validation MSE loss = 0.03810970645154948
2026-04-08 23:53:00.159 | INFO     | modules.train:run_training:89 - Epoch 2 :
2026-04-08 23:54:10.327 | INFO     | modules.train:run_training:180 - Epoch 2 : train total loss = 1.1426810490975685
2026-04-08 23:54:10.328 | INFO     | modules.train:run_training:181 - Epoch 2 : train contrastive loss = 3.7237683993960737
2026-04-08 23:54:10.330 | INFO     | modules.train:run_training:182 - Epoch 2 : train MSE loss = 0.036500691141454725
2026-04-08 23:54:10.331 | INFO     | modules.train:run_training:184 - Epoch 2 : validation total loss = 1.1384472458258919
2026-04-08 23:54:10.333 | INFO     | modules.train:run_training:185 - Epoch 2 : validation contrastive loss = 3.703659767689912
2026-04-08 23:54:10.334 | INFO     | modules.train:run_training:186 - Epoch 2 : validation MSE loss = 0.0390703944367883
2026-04-08 23:54:10.405 | INFO     | modules.train:run_training:89 - Epoch 3 :
2026-04-08 23:55:20.890 | INFO     | modules.train:run_training:180 - Epoch 3 : train total loss = 1.1274941793275535
2026-04-08 23:55:20.891 | INFO     | modules.train:run_training:181 - Epoch 3 : train contrastive loss = 3.671966955202435
2026-04-08 23:55:20.893 | INFO     | modules.train:run_training:182 - Epoch 3 : train MSE loss = 0.03700576867019638
2026-04-08 23:55:20.894 | INFO     | modules.train:run_training:184 - Epoch 3 : validation total loss = 1.1344977643178857
2026-04-08 23:55:20.895 | INFO     | modules.train:run_training:185 - Epoch 3 : validation contrastive loss = 3.6882412433624268
2026-04-08 23:55:20.896 | INFO     | modules.train:run_training:186 - Epoch 3 : validation MSE loss = 0.04003621415113625
2026-04-08 23:55:20.968 | INFO     | modules.train:run_training:89 - Epoch 4 :
2026-04-08 23:56:31.471 | INFO     | modules.train:run_training:180 - Epoch 4 : train total loss = 1.1115042649277853
2026-04-08 23:56:31.472 | INFO     | modules.train:run_training:181 - Epoch 4 : train contrastive loss = 3.6181144440939668
2026-04-08 23:56:31.473 | INFO     | modules.train:run_training:182 - Epoch 4 : train MSE loss = 0.0372426877003334
2026-04-08 23:56:31.475 | INFO     | modules.train:run_training:184 - Epoch 4 : validation total loss = 1.1390393894651663
2026-04-08 23:56:31.476 | INFO     | modules.train:run_training:185 - Epoch 4 : validation contrastive loss = 3.6954628591952114
2026-04-08 23:56:31.478 | INFO     | modules.train:run_training:186 - Epoch 4 : validation MSE loss = 0.043429249371199505
2026-04-08 23:56:31.504 | INFO     | modules.train:run_training:89 - Epoch 5 :
2026-04-08 23:57:41.454 | INFO     | modules.train:run_training:180 - Epoch 5 : train total loss = 1.0946991492848877
2026-04-08 23:57:41.455 | INFO     | modules.train:run_training:181 - Epoch 5 : train contrastive loss = 3.5596821526868627
2026-04-08 23:57:41.456 | INFO     | modules.train:run_training:182 - Epoch 5 : train MSE loss = 0.03827779668323491
2026-04-08 23:57:41.458 | INFO     | modules.train:run_training:184 - Epoch 5 : validation total loss = 1.1453397170357082
2026-04-08 23:57:41.459 | INFO     | modules.train:run_training:185 - Epoch 5 : validation contrastive loss = 3.712986806164617
2026-04-08 23:57:41.461 | INFO     | modules.train:run_training:186 - Epoch 5 : validation MSE loss = 0.04491947396941807
2026-04-08 23:57:41.462 | WARNING  | modules.train:run_training:206 - Training stops after 5 epochs
2026/04/08 23:57:42 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/08 23:57:42 WARNING mlflow.pytorch: Saving pytorch model by Pickle or CloudPickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is to set `serialization_format` to 'pt2' to save the PyTorch model using the safe graph model format.
2026/04/08 23:57:43 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.
2026/04/08 23:57:57 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.

----------------------------------------------------------------------------------------------------

[I 2026-04-08 23:58:00,644] Trial 0 finished with value: 1.1344977643178857 and parameters: {'batch_size': 64, 'dropout': 0.15000000000000002, 'projec_dropout': 0.1, 'lr': 0.0004724968056532259, 'weight_decay': 1.371295256336384e-05, 'warmup_prop': 0.060000000000000005, 'mean_mode': False}. Best is trial 0 with value: 1.1344977643178857.
2026-04-08 23:58:01.305 | INFO     | modules.optuna_function:objective:88 - Trial number 1:
2026-04-08 23:58:01.306 | INFO     | modules.optuna_function:objective:89 - batch_size:64_dropout:0,05_projec_dropout:0,2_lr:0,00013340658743746087_weight_decay:3,6677632134421984e-05_warmup_prop:0,08_mean_mode:True_loss_temp:0,2_loss_alpha:0,3
2026-04-08 23:58:01.307 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-08 23:59:13.465 | INFO     | modules.train:run_training:180 - Epoch 0 : train total loss = 1.1853736562466404
2026-04-08 23:59:13.467 | INFO     | modules.train:run_training:181 - Epoch 0 : train contrastive loss = 3.8196088633406053
2026-04-08 23:59:13.468 | INFO     | modules.train:run_training:182 - Epoch 0 : train MSE loss = 0.05641564334648738
2026-04-08 23:59:13.469 | INFO     | modules.train:run_training:184 - Epoch 0 : validation total loss = 1.162885352321293
2026-04-08 23:59:13.471 | INFO     | modules.train:run_training:185 - Epoch 0 : validation contrastive loss = 3.786676199539848
2026-04-08 23:59:13.472 | INFO     | modules.train:run_training:186 - Epoch 0 : validation MSE loss = 0.03840349513389494
2026-04-08 23:59:13.533 | INFO     | modules.train:run_training:89 - Epoch 1 :
2026-04-09 00:00:23.641 | INFO     | modules.train:run_training:180 - Epoch 1 : train total loss = 1.1620935108683526
2026-04-09 00:00:23.642 | INFO     | modules.train:run_training:181 - Epoch 1 : train contrastive loss = 3.7902964626977202
2026-04-09 00:00:23.643 | INFO     | modules.train:run_training:182 - Epoch 1 : train MSE loss = 0.03572075439770834
2026-04-09 00:00:23.644 | INFO     | modules.train:run_training:184 - Epoch 1 : validation total loss = 1.1469466763993967
2026-04-09 00:00:23.644 | INFO     | modules.train:run_training:185 - Epoch 1 : validation contrastive loss = 3.7343428083088086
2026-04-09 00:00:23.645 | INFO     | modules.train:run_training:186 - Epoch 1 : validation MSE loss = 0.038062544802770666
2026-04-09 00:00:23.716 | INFO     | modules.train:run_training:89 - Epoch 2 :
2026-04-09 00:01:33.850 | INFO     | modules.train:run_training:180 - Epoch 2 : train total loss = 1.1464018706881671
2026-04-09 00:01:33.851 | INFO     | modules.train:run_training:181 - Epoch 2 : train contrastive loss = 3.735362061666786
2026-04-09 00:01:33.852 | INFO     | modules.train:run_training:182 - Epoch 2 : train MSE loss = 0.03684742661158836
2026-04-09 00:01:33.853 | INFO     | modules.train:run_training:184 - Epoch 2 : validation total loss = 1.148390259431756
2026-04-09 00:01:33.853 | INFO     | modules.train:run_training:185 - Epoch 2 : validation contrastive loss = 3.737985937491707
2026-04-09 00:01:33.855 | INFO     | modules.train:run_training:186 - Epoch 2 : validation MSE loss = 0.03856346278410891
2026-04-09 00:01:33.880 | INFO     | modules.train:run_training:89 - Epoch 3 :
2026-04-09 00:02:44.307 | INFO     | modules.train:run_training:180 - Epoch 3 : train total loss = 1.1359279057301512
2026-04-09 00:02:44.308 | INFO     | modules.train:run_training:181 - Epoch 3 : train contrastive loss = 3.6997876429776535
2026-04-09 00:02:44.310 | INFO     | modules.train:run_training:182 - Epoch 3 : train MSE loss = 0.03713081459249925
2026-04-09 00:02:44.311 | INFO     | modules.train:run_training:184 - Epoch 3 : validation total loss = 1.1396867995676787
2026-04-09 00:02:44.313 | INFO     | modules.train:run_training:185 - Epoch 3 : validation contrastive loss = 3.7044872874798984
2026-04-09 00:02:44.314 | INFO     | modules.train:run_training:186 - Epoch 3 : validation MSE loss = 0.04048652574419975
2026-04-09 00:02:44.385 | INFO     | modules.train:run_training:89 - Epoch 4 :
2026-04-09 00:03:54.451 | INFO     | modules.train:run_training:180 - Epoch 4 : train total loss = 1.1243359331690936
2026-04-09 00:03:54.452 | INFO     | modules.train:run_training:181 - Epoch 4 : train contrastive loss = 3.658743321348768
2026-04-09 00:03:54.453 | INFO     | modules.train:run_training:182 - Epoch 4 : train MSE loss = 0.03816127938585817
2026-04-09 00:03:54.455 | INFO     | modules.train:run_training:184 - Epoch 4 : validation total loss = 1.1371555121048638
2026-04-09 00:03:54.456 | INFO     | modules.train:run_training:185 - Epoch 4 : validation contrastive loss = 3.6898778936137324
2026-04-09 00:03:54.458 | INFO     | modules.train:run_training:186 - Epoch 4 : validation MSE loss = 0.04313157239685888
2026-04-09 00:03:54.538 | INFO     | modules.train:run_training:89 - Epoch 5 :
2026-04-09 00:05:04.434 | INFO     | modules.train:run_training:180 - Epoch 5 : train total loss = 1.1116780359810645
2026-04-09 00:05:04.435 | INFO     | modules.train:run_training:181 - Epoch 5 : train contrastive loss = 3.6127650661206028
2026-04-09 00:05:04.436 | INFO     | modules.train:run_training:182 - Epoch 5 : train MSE loss = 0.03978352507559258
2026-04-09 00:05:04.436 | INFO     | modules.train:run_training:184 - Epoch 5 : validation total loss = 1.1387599551159402
2026-04-09 00:05:04.437 | INFO     | modules.train:run_training:185 - Epoch 5 : validation contrastive loss = 3.6945484306501304
2026-04-09 00:05:04.437 | INFO     | modules.train:run_training:186 - Epoch 5 : validation MSE loss = 0.04342198177524235
2026-04-09 00:05:04.465 | INFO     | modules.train:run_training:89 - Epoch 6 :
2026-04-09 00:06:14.679 | INFO     | modules.train:run_training:180 - Epoch 6 : train total loss = 1.1012052571007964
2026-04-09 00:06:14.681 | INFO     | modules.train:run_training:181 - Epoch 6 : train contrastive loss = 3.5747399209836206
2026-04-09 00:06:14.682 | INFO     | modules.train:run_training:182 - Epoch 6 : train MSE loss = 0.041118902273886246
2026-04-09 00:06:14.683 | INFO     | modules.train:run_training:184 - Epoch 6 : validation total loss = 1.140208231366199
2026-04-09 00:06:14.684 | INFO     | modules.train:run_training:185 - Epoch 6 : validation contrastive loss = 3.694168344787929
2026-04-09 00:06:14.686 | INFO     | modules.train:run_training:186 - Epoch 6 : validation MSE loss = 0.04565383870478557
2026-04-09 00:06:14.688 | WARNING  | modules.train:run_training:206 - Training stops after 6 epochs
2026/04/09 00:06:15 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/09 00:06:15 WARNING mlflow.pytorch: Saving pytorch model by Pickle or CloudPickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is to set `serialization_format` to 'pt2' to save the PyTorch model using the safe graph model format.
2026/04/09 00:06:21 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.
2026/04/09 00:06:32 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.

----------------------------------------------------------------------------------------------------

[I 2026-04-09 00:06:35,156] Trial 1 finished with value: 1.1371555121048638 and parameters: {'batch_size': 64, 'dropout': 0.05, 'projec_dropout': 0.2, 'lr': 0.00013340658743746087, 'weight_decay': 3.6677632134421984e-05, 'warmup_prop': 0.08, 'mean_mode': True}. Best is trial 0 with value: 1.1344977643178857.
2026-04-09 00:06:35.733 | INFO     | modules.optuna_function:objective:88 - Trial number 2:
2026-04-09 00:06:35.734 | INFO     | modules.optuna_function:objective:89 - batch_size:32_dropout:0,1_projec_dropout:0,2_lr:0,0005119178802555773_weight_decay:1,3386144108743617e-05_warmup_prop:0,09999999999999999_mean_mode:True_loss_temp:0,2_loss_alpha:0,3
2026-04-09 00:06:35.735 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-09 00:07:46.680 | INFO     | modules.train:run_training:180 - Epoch 0 : train total loss = 0.9828978645992498
2026-04-09 00:07:46.681 | INFO     | modules.train:run_training:181 - Epoch 0 : train contrastive loss = 3.171550656347035
2026-04-09 00:07:46.683 | INFO     | modules.train:run_training:182 - Epoch 0 : train MSE loss = 0.04490375706768281
2026-04-09 00:07:46.684 | INFO     | modules.train:run_training:184 - Epoch 0 : validation total loss = 0.9609172023752685
2026-04-09 00:07:46.685 | INFO     | modules.train:run_training:185 - Epoch 0 : validation contrastive loss = 3.1129873132192962
2026-04-09 00:07:46.686 | INFO     | modules.train:run_training:186 - Epoch 0 : validation MSE loss = 0.03860139068696768
2026-04-09 00:07:46.761 | INFO     | modules.train:run_training:89 - Epoch 1 :
2026-04-09 00:08:55.216 | INFO     | modules.train:run_training:180 - Epoch 1 : train total loss = 0.9617650443410982
2026-04-09 00:08:55.217 | INFO     | modules.train:run_training:181 - Epoch 1 : train contrastive loss = 3.120880367554025
2026-04-09 00:08:55.218 | INFO     | modules.train:run_training:182 - Epoch 1 : train MSE loss = 0.03642985751123532
2026-04-09 00:08:55.219 | INFO     | modules.train:run_training:184 - Epoch 1 : validation total loss = 0.9548499199651903
2026-04-09 00:08:55.220 | INFO     | modules.train:run_training:185 - Epoch 1 : validation contrastive loss = 3.09035797016595
2026-04-09 00:08:55.220 | INFO     | modules.train:run_training:186 - Epoch 1 : validation MSE loss = 0.03963213907654888
2026-04-09 00:08:55.291 | INFO     | modules.train:run_training:89 - Epoch 2 :
2026-04-09 00:10:03.880 | INFO     | modules.train:run_training:180 - Epoch 2 : train total loss = 0.950162014372016
2026-04-09 00:10:03.881 | INFO     | modules.train:run_training:181 - Epoch 2 : train contrastive loss = 3.0814051131634743
2026-04-09 00:10:03.882 | INFO     | modules.train:run_training:182 - Epoch 2 : train MSE loss = 0.03677206478045414
2026-04-09 00:10:03.882 | INFO     | modules.train:run_training:184 - Epoch 2 : validation total loss = 0.9477830234394279
2026-04-09 00:10:03.883 | INFO     | modules.train:run_training:185 - Epoch 2 : validation contrastive loss = 3.068796819256198
2026-04-09 00:10:03.883 | INFO     | modules.train:run_training:186 - Epoch 2 : validation MSE loss = 0.03877705725170271
2026-04-09 00:10:03.957 | INFO     | modules.train:run_training:89 - Epoch 3 :
2026-04-09 00:11:12.580 | INFO     | modules.train:run_training:180 - Epoch 3 : train total loss = 0.9354037199194971
2026-04-09 00:11:12.581 | INFO     | modules.train:run_training:181 - Epoch 3 : train contrastive loss = 3.031295378639169
2026-04-09 00:11:12.582 | INFO     | modules.train:run_training:182 - Epoch 3 : train MSE loss = 0.03716438679339991
2026-04-09 00:11:12.584 | INFO     | modules.train:run_training:184 - Epoch 3 : validation total loss = 0.9452530517373033
2026-04-09 00:11:12.585 | INFO     | modules.train:run_training:185 - Epoch 3 : validation contrastive loss = 3.055713999655939
2026-04-09 00:11:12.586 | INFO     | modules.train:run_training:186 - Epoch 3 : validation MSE loss = 0.04076973832542858
2026-04-09 00:11:12.664 | INFO     | modules.train:run_training:89 - Epoch 4 :
2026-04-09 00:12:21.261 | INFO     | modules.train:run_training:180 - Epoch 4 : train total loss = 0.9188217801687647
2026-04-09 00:12:21.262 | INFO     | modules.train:run_training:181 - Epoch 4 : train contrastive loss = 2.9750979492266065
2026-04-09 00:12:21.263 | INFO     | modules.train:run_training:182 - Epoch 4 : train MSE loss = 0.03756051130158064
2026-04-09 00:12:21.264 | INFO     | modules.train:run_training:184 - Epoch 4 : validation total loss = 0.9493747718872563
2026-04-09 00:12:21.266 | INFO     | modules.train:run_training:185 - Epoch 4 : validation contrastive loss = 3.063082935989544
2026-04-09 00:12:21.267 | INFO     | modules.train:run_training:186 - Epoch 4 : validation MSE loss = 0.04349979495890038
2026-04-09 00:12:21.294 | INFO     | modules.train:run_training:89 - Epoch 5 :
2026-04-09 00:13:29.903 | INFO     | modules.train:run_training:180 - Epoch 5 : train total loss = 0.9025832932928334
2026-04-09 00:13:29.904 | INFO     | modules.train:run_training:181 - Epoch 5 : train contrastive loss = 2.920475369459977
2026-04-09 00:13:29.906 | INFO     | modules.train:run_training:182 - Epoch 5 : train MSE loss = 0.03777235353821611
2026-04-09 00:13:29.908 | INFO     | modules.train:run_training:184 - Epoch 5 : validation total loss = 0.9616873418131182
2026-04-09 00:13:29.909 | INFO     | modules.train:run_training:185 - Epoch 5 : validation contrastive loss = 3.094533012759301
2026-04-09 00:13:29.911 | INFO     | modules.train:run_training:186 - Epoch 5 : validation MSE loss = 0.04761057234899972
2026-04-09 00:13:29.911 | WARNING  | modules.train:run_training:206 - Training stops after 5 epochs
2026/04/09 00:13:30 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/09 00:13:30 WARNING mlflow.pytorch: Saving pytorch model by Pickle or CloudPickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is to set `serialization_format` to 'pt2' to save the PyTorch model using the safe graph model format.
2026/04/09 00:13:32 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.
2026/04/09 00:13:43 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.

----------------------------------------------------------------------------------------------------

[I 2026-04-09 00:13:46,198] Trial 2 finished with value: 0.9452530517373033 and parameters: {'batch_size': 32, 'dropout': 0.1, 'projec_dropout': 0.2, 'lr': 0.0005119178802555773, 'weight_decay': 1.3386144108743617e-05, 'warmup_prop': 0.09999999999999999, 'mean_mode': True}. Best is trial 2 with value: 0.9452530517373033.
2026-04-09 00:13:46.830 | INFO     | modules.optuna_function:objective:88 - Trial number 3:
2026-04-09 00:13:46.831 | INFO     | modules.optuna_function:objective:89 - batch_size:32_dropout:0,15000000000000002_projec_dropout:0,15000000000000002_lr:0,002820576964445428_weight_decay:4,191307187757944e-05_warmup_prop:0,01_mean_mode:True_loss_temp:0,2_loss_alpha:0,3
2026-04-09 00:13:46.832 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-09 00:14:56.294 | INFO     | modules.train:run_training:180 - Epoch 0 : train total loss = 0.9790751751282122
2026-04-09 00:14:56.295 | INFO     | modules.train:run_training:181 - Epoch 0 : train contrastive loss = 3.1767318968914737
2026-04-09 00:14:56.297 | INFO     | modules.train:run_training:182 - Epoch 0 : train MSE loss = 0.03722223578962909
2026-04-09 00:14:56.298 | INFO     | modules.train:run_training:184 - Epoch 0 : validation total loss = 0.9746514751065162
2026-04-09 00:14:56.298 | INFO     | modules.train:run_training:185 - Epoch 0 : validation contrastive loss = 3.1596747111248713
2026-04-09 00:14:56.299 | INFO     | modules.train:run_training:186 - Epoch 0 : validation MSE loss = 0.03821288728185238
2026-04-09 00:14:56.359 | INFO     | modules.train:run_training:89 - Epoch 1 :
2026-04-09 00:16:04.102 | INFO     | modules.train:run_training:180 - Epoch 1 : train total loss = 0.9714806180796852
2026-04-09 00:16:04.103 | INFO     | modules.train:run_training:181 - Epoch 1 : train contrastive loss = 3.1541826926870806
2026-04-09 00:16:04.104 | INFO     | modules.train:run_training:182 - Epoch 1 : train MSE loss = 0.03603682071141029
2026-04-09 00:16:04.105 | INFO     | modules.train:run_training:184 - Epoch 1 : validation total loss = 0.9600582174075547
2026-04-09 00:16:04.107 | INFO     | modules.train:run_training:185 - Epoch 1 : validation contrastive loss = 3.1078750959006687
2026-04-09 00:16:04.108 | INFO     | modules.train:run_training:186 - Epoch 1 : validation MSE loss = 0.03956521405608103
2026-04-09 00:16:04.180 | INFO     | modules.train:run_training:89 - Epoch 2 :
2026-04-09 00:17:12.019 | INFO     | modules.train:run_training:180 - Epoch 2 : train total loss = 0.9605569439839989
2026-04-09 00:17:12.020 | INFO     | modules.train:run_training:181 - Epoch 2 : train contrastive loss = 3.11639400259581
2026-04-09 00:17:12.021 | INFO     | modules.train:run_training:182 - Epoch 2 : train MSE loss = 0.036626725875318594
2026-04-09 00:17:12.021 | INFO     | modules.train:run_training:184 - Epoch 2 : validation total loss = 0.9590685611130089
2026-04-09 00:17:12.022 | INFO     | modules.train:run_training:185 - Epoch 2 : validation contrastive loss = 3.108003106168521
2026-04-09 00:17:12.023 | INFO     | modules.train:run_training:186 - Epoch 2 : validation MSE loss = 0.03809656868738833
2026-04-09 00:17:12.095 | INFO     | modules.train:run_training:89 - Epoch 3 :
2026-04-09 00:18:20.382 | INFO     | modules.train:run_training:180 - Epoch 3 : train total loss = 0.9555391164611624
2026-04-09 00:18:20.383 | INFO     | modules.train:run_training:181 - Epoch 3 : train contrastive loss = 3.100359578972823
2026-04-09 00:18:20.385 | INFO     | modules.train:run_training:182 - Epoch 3 : train MSE loss = 0.03633029283891758
2026-04-09 00:18:20.388 | INFO     | modules.train:run_training:184 - Epoch 3 : validation total loss = 0.9561863663376019
2026-04-09 00:18:20.389 | INFO     | modules.train:run_training:185 - Epoch 3 : validation contrastive loss = 3.095604422271893
2026-04-09 00:18:20.390 | INFO     | modules.train:run_training:186 - Epoch 3 : validation MSE loss = 0.039292866774704505
2026-04-09 00:18:20.469 | INFO     | modules.train:run_training:89 - Epoch 4 :
2026-04-09 00:19:29.137 | INFO     | modules.train:run_training:180 - Epoch 4 : train total loss = 0.9483594929871897
2026-04-09 00:19:29.138 | INFO     | modules.train:run_training:181 - Epoch 4 : train contrastive loss = 3.0768070941113224
2026-04-09 00:19:29.140 | INFO     | modules.train:run_training:182 - Epoch 4 : train MSE loss = 0.03616761482369743
2026-04-09 00:19:29.141 | INFO     | modules.train:run_training:184 - Epoch 4 : validation total loss = 0.9580811864586287
2026-04-09 00:19:29.142 | INFO     | modules.train:run_training:185 - Epoch 4 : validation contrastive loss = 3.100396889512257
2026-04-09 00:19:29.144 | INFO     | modules.train:run_training:186 - Epoch 4 : validation MSE loss = 0.03994583091147805
2026-04-09 00:19:29.169 | INFO     | modules.train:run_training:89 - Epoch 5 :
2026-04-09 00:20:36.929 | INFO     | modules.train:run_training:180 - Epoch 5 : train total loss = 0.9405243028492349
2026-04-09 00:20:36.930 | INFO     | modules.train:run_training:181 - Epoch 5 : train contrastive loss = 3.051432316035919
2026-04-09 00:20:36.932 | INFO     | modules.train:run_training:182 - Epoch 5 : train MSE loss = 0.03584938779903802
2026-04-09 00:20:36.934 | INFO     | modules.train:run_training:184 - Epoch 5 : validation total loss = 0.9616649022666357
2026-04-09 00:20:36.934 | INFO     | modules.train:run_training:185 - Epoch 5 : validation contrastive loss = 3.1120229869760494
2026-04-09 00:20:36.936 | INFO     | modules.train:run_training:186 - Epoch 5 : validation MSE loss = 0.04008281440223738
2026-04-09 00:20:36.937 | WARNING  | modules.train:run_training:206 - Training stops after 5 epochs
2026/04/09 00:20:37 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/09 00:20:37 WARNING mlflow.pytorch: Saving pytorch model by Pickle or CloudPickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is to set `serialization_format` to 'pt2' to save the PyTorch model using the safe graph model format.
2026/04/09 00:20:45 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.
2026/04/09 00:20:54 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.

----------------------------------------------------------------------------------------------------

[I 2026-04-09 00:20:57,377] Trial 3 finished with value: 0.9561863663376019 and parameters: {'batch_size': 32, 'dropout': 0.15000000000000002, 'projec_dropout': 0.15000000000000002, 'lr': 0.002820576964445428, 'weight_decay': 4.191307187757944e-05, 'warmup_prop': 0.01, 'mean_mode': True}. Best is trial 2 with value: 0.9452530517373033.
2026-04-09 00:20:57.982 | INFO     | modules.optuna_function:objective:88 - Trial number 4:
2026-04-09 00:20:57.983 | INFO     | modules.optuna_function:objective:89 - batch_size:32_dropout:0,25_projec_dropout:0,05_lr:0,002180359266950528_weight_decay:0,00019546338849593442_warmup_prop:0,02_mean_mode:True_loss_temp:0,2_loss_alpha:0,3
2026-04-09 00:20:57.985 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-09 00:22:07.892 | INFO     | modules.train:run_training:180 - Epoch 0 : train total loss = 0.9805265798721488
2026-04-09 00:22:07.893 | INFO     | modules.train:run_training:181 - Epoch 0 : train contrastive loss = 3.178592433100161
2026-04-09 00:22:07.895 | INFO     | modules.train:run_training:182 - Epoch 0 : train MSE loss = 0.03849830571562052
2026-04-09 00:22:07.896 | INFO     | modules.train:run_training:184 - Epoch 0 : validation total loss = 0.9752355929343931
2026-04-09 00:22:07.897 | INFO     | modules.train:run_training:185 - Epoch 0 : validation contrastive loss = 3.160619648553992
2026-04-09 00:22:07.899 | INFO     | modules.train:run_training:186 - Epoch 0 : validation MSE loss = 0.038642377202068603
2026-04-09 00:22:07.959 | INFO     | modules.train:run_training:89 - Epoch 1 :
2026-04-09 00:23:16.527 | INFO     | modules.train:run_training:180 - Epoch 1 : train total loss = 0.9741053680806193
2026-04-09 00:23:16.528 | INFO     | modules.train:run_training:181 - Epoch 1 : train contrastive loss = 3.1636581999213527
2026-04-09 00:23:16.529 | INFO     | modules.train:run_training:182 - Epoch 1 : train MSE loss = 0.03572553254821651
2026-04-09 00:23:16.530 | INFO     | modules.train:run_training:184 - Epoch 1 : validation total loss = 0.9596917058831902
2026-04-09 00:23:16.532 | INFO     | modules.train:run_training:185 - Epoch 1 : validation contrastive loss = 3.10708353852713
2026-04-09 00:23:16.533 | INFO     | modules.train:run_training:186 - Epoch 1 : validation MSE loss = 0.03938086751487947
2026-04-09 00:23:16.616 | INFO     | modules.train:run_training:89 - Epoch 2 :
2026-04-09 00:24:25.898 | INFO     | modules.train:run_training:180 - Epoch 2 : train total loss = 0.961358160257885
2026-04-09 00:24:25.899 | INFO     | modules.train:run_training:181 - Epoch 2 : train contrastive loss = 3.118862085538816
2026-04-09 00:24:25.900 | INFO     | modules.train:run_training:182 - Epoch 2 : train MSE loss = 0.036713568622659835
2026-04-09 00:24:25.901 | INFO     | modules.train:run_training:184 - Epoch 2 : validation total loss = 0.9564141086352769
2026-04-09 00:24:25.902 | INFO     | modules.train:run_training:185 - Epoch 2 : validation contrastive loss = 3.09825982329666
2026-04-09 00:24:25.903 | INFO     | modules.train:run_training:186 - Epoch 2 : validation MSE loss = 0.03848018743077754
2026-04-09 00:24:25.972 | INFO     | modules.train:run_training:89 - Epoch 3 :
2026-04-09 00:25:34.376 | INFO     | modules.train:run_training:180 - Epoch 3 : train total loss = 0.9551974941445707
2026-04-09 00:25:34.377 | INFO     | modules.train:run_training:181 - Epoch 3 : train contrastive loss = 3.099044430992423
2026-04-09 00:25:34.378 | INFO     | modules.train:run_training:182 - Epoch 3 : train MSE loss = 0.03640589721019229
2026-04-09 00:25:34.380 | INFO     | modules.train:run_training:184 - Epoch 3 : validation total loss = 0.9563692404377845
2026-04-09 00:25:34.381 | INFO     | modules.train:run_training:185 - Epoch 3 : validation contrastive loss = 3.0958809186053533
2026-04-09 00:25:34.382 | INFO     | modules.train:run_training:186 - Epoch 3 : validation MSE loss = 0.039435606359714465
2026-04-09 00:25:34.452 | INFO     | modules.train:run_training:89 - Epoch 4 :
2026-04-09 00:26:42.961 | INFO     | modules.train:run_training:180 - Epoch 4 : train total loss = 0.9486074110736018
2026-04-09 00:26:42.961 | INFO     | modules.train:run_training:181 - Epoch 4 : train contrastive loss = 3.0773840316100305
2026-04-09 00:26:42.962 | INFO     | modules.train:run_training:182 - Epoch 4 : train MSE loss = 0.03627452491388339
2026-04-09 00:26:42.963 | INFO     | modules.train:run_training:184 - Epoch 4 : validation total loss = 0.9608713740943581
2026-04-09 00:26:42.965 | INFO     | modules.train:run_training:185 - Epoch 4 : validation contrastive loss = 3.107674798657817
2026-04-09 00:26:42.966 | INFO     | modules.train:run_training:186 - Epoch 4 : validation MSE loss = 0.040812704852351576
2026-04-09 00:26:42.967 | WARNING  | modules.train:run_training:206 - Training stops after 4 epochs
2026/04/09 00:26:43 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/09 00:26:43 WARNING mlflow.pytorch: Saving pytorch model by Pickle or CloudPickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is to set `serialization_format` to 'pt2' to save the PyTorch model using the safe graph model format.
2026/04/09 00:26:45 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.
2026/04/09 00:26:55 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.

----------------------------------------------------------------------------------------------------

[I 2026-04-09 00:26:57,704] Trial 4 finished with value: 0.9563692404377845 and parameters: {'batch_size': 32, 'dropout': 0.25, 'projec_dropout': 0.05, 'lr': 0.002180359266950528, 'weight_decay': 0.00019546338849593442, 'warmup_prop': 0.02, 'mean_mode': True}. Best is trial 2 with value: 0.9452530517373033.
2026-04-09 00:26:58.357 | INFO     | modules.optuna_function:objective:88 - Trial number 5:
2026-04-09 00:26:58.358 | INFO     | modules.optuna_function:objective:89 - batch_size:32_dropout:0,05_projec_dropout:0,15000000000000002_lr:0,0010036326863450127_weight_decay:0,00013814862105675894_warmup_prop:0,08_mean_mode:False_loss_temp:0,2_loss_alpha:0,3
2026-04-09 00:26:58.360 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-09 00:28:08.512 | INFO     | modules.train:run_training:180 - Epoch 0 : train total loss = 0.9782880004538006
2026-04-09 00:28:08.513 | INFO     | modules.train:run_training:181 - Epoch 0 : train contrastive loss = 3.1639020901250077
2026-04-09 00:28:08.515 | INFO     | modules.train:run_training:182 - Epoch 0 : train MSE loss = 0.04159619111473964
2026-04-09 00:28:08.516 | INFO     | modules.train:run_training:184 - Epoch 0 : validation total loss = 0.9624435215867976
2026-04-09 00:28:08.518 | INFO     | modules.train:run_training:185 - Epoch 0 : validation contrastive loss = 3.1170115932341544
2026-04-09 00:28:08.518 | INFO     | modules.train:run_training:186 - Epoch 0 : validation MSE loss = 0.039057157302816066
2026-04-09 00:28:08.584 | INFO     | modules.train:run_training:89 - Epoch 1 :
2026-04-09 00:29:17.172 | INFO     | modules.train:run_training:180 - Epoch 1 : train total loss = 0.9612025602185753
2026-04-09 00:29:17.173 | INFO     | modules.train:run_training:181 - Epoch 1 : train contrastive loss = 3.1188602365672726
2026-04-09 00:29:17.174 | INFO     | modules.train:run_training:182 - Epoch 1 : train MSE loss = 0.03649207432083018
2026-04-09 00:29:17.175 | INFO     | modules.train:run_training:184 - Epoch 1 : validation total loss = 0.9577190664506727
2026-04-09 00:29:17.176 | INFO     | modules.train:run_training:185 - Epoch 1 : validation contrastive loss = 3.1007802922238588
2026-04-09 00:29:17.178 | INFO     | modules.train:run_training:186 - Epoch 1 : validation MSE loss = 0.03926420452634013
2026-04-09 00:29:17.247 | INFO     | modules.train:run_training:89 - Epoch 2 :
2026-04-09 00:30:25.701 | INFO     | modules.train:run_training:180 - Epoch 2 : train total loss = 0.9546776038831104
2026-04-09 00:30:25.702 | INFO     | modules.train:run_training:181 - Epoch 2 : train contrastive loss = 3.097502845921287
2026-04-09 00:30:25.703 | INFO     | modules.train:run_training:182 - Epoch 2 : train MSE loss = 0.03632387590063928
2026-04-09 00:30:25.703 | INFO     | modules.train:run_training:184 - Epoch 2 : validation total loss = 0.9580803789118285
2026-04-09 00:30:25.704 | INFO     | modules.train:run_training:185 - Epoch 2 : validation contrastive loss = 3.103711256416895
2026-04-09 00:30:25.705 | INFO     | modules.train:run_training:186 - Epoch 2 : validation MSE loss = 0.03852423699071971
2026-04-09 00:30:25.731 | INFO     | modules.train:run_training:89 - Epoch 3 :
2026-04-09 00:31:33.949 | INFO     | modules.train:run_training:180 - Epoch 3 : train total loss = 0.9452894604178806
2026-04-09 00:31:33.950 | INFO     | modules.train:run_training:181 - Epoch 3 : train contrastive loss = 3.0661078585094392
2026-04-09 00:31:33.951 | INFO     | modules.train:run_training:182 - Epoch 3 : train MSE loss = 0.03636723801438234
2026-04-09 00:31:33.953 | INFO     | modules.train:run_training:184 - Epoch 3 : validation total loss = 0.9498907532743228
2026-04-09 00:31:33.954 | INFO     | modules.train:run_training:185 - Epoch 3 : validation contrastive loss = 3.071416690785398
2026-04-09 00:31:33.955 | INFO     | modules.train:run_training:186 - Epoch 3 : validation MSE loss = 0.04066530323677486
2026-04-09 00:31:34.027 | INFO     | modules.train:run_training:89 - Epoch 4 :
2026-04-09 00:32:42.113 | INFO     | modules.train:run_training:180 - Epoch 4 : train total loss = 0.9300991013066446
2026-04-09 00:32:42.114 | INFO     | modules.train:run_training:181 - Epoch 4 : train contrastive loss = 3.014772751784161
2026-04-09 00:32:42.116 | INFO     | modules.train:run_training:182 - Epoch 4 : train MSE loss = 0.03666748556157135
2026-04-09 00:32:42.117 | INFO     | modules.train:run_training:184 - Epoch 4 : validation total loss = 0.9522792113724575
2026-04-09 00:32:42.118 | INFO     | modules.train:run_training:185 - Epoch 4 : validation contrastive loss = 3.0786120660843386
2026-04-09 00:32:42.120 | INFO     | modules.train:run_training:186 - Epoch 4 : validation MSE loss = 0.04099365384868717
2026-04-09 00:32:42.147 | INFO     | modules.train:run_training:89 - Epoch 5 :
2026-04-09 00:33:50.323 | INFO     | modules.train:run_training:180 - Epoch 5 : train total loss = 0.9164210871646279
2026-04-09 00:33:50.324 | INFO     | modules.train:run_training:181 - Epoch 5 : train contrastive loss = 2.9705805876707867
2026-04-09 00:33:50.326 | INFO     | modules.train:run_training:182 - Epoch 5 : train MSE loss = 0.03606696240497365
2026-04-09 00:33:50.327 | INFO     | modules.train:run_training:184 - Epoch 5 : validation total loss = 0.9640277893312516
2026-04-09 00:33:50.328 | INFO     | modules.train:run_training:185 - Epoch 5 : validation contrastive loss = 3.1121532481203795
2026-04-09 00:33:50.329 | INFO     | modules.train:run_training:186 - Epoch 5 : validation MSE loss = 0.04340253387808159
2026-04-09 00:33:50.330 | WARNING  | modules.train:run_training:206 - Training stops after 5 epochs
2026/04/09 00:33:50 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/09 00:33:51 WARNING mlflow.pytorch: Saving pytorch model by Pickle or CloudPickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is to set `serialization_format` to 'pt2' to save the PyTorch model using the safe graph model format.
2026/04/09 00:33:58 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.
2026/04/09 00:34:08 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.

----------------------------------------------------------------------------------------------------

[I 2026-04-09 00:34:11,392] Trial 5 finished with value: 0.9498907532743228 and parameters: {'batch_size': 32, 'dropout': 0.05, 'projec_dropout': 0.15000000000000002, 'lr': 0.0010036326863450127, 'weight_decay': 0.00013814862105675894, 'warmup_prop': 0.08, 'mean_mode': False}. Best is trial 2 with value: 0.9452530517373033.
2026-04-09 00:34:12.007 | INFO     | modules.optuna_function:objective:88 - Trial number 6:
2026-04-09 00:34:12.008 | INFO     | modules.optuna_function:objective:89 - batch_size:32_dropout:0,1_projec_dropout:0,1_lr:0,0017263266493212528_weight_decay:0,000683227867921707_warmup_prop:0,03_mean_mode:True_loss_temp:0,2_loss_alpha:0,3
2026-04-09 00:34:12.010 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-09 00:35:21.755 | INFO     | modules.train:run_training:180 - Epoch 0 : train total loss = 0.9749773392961009
2026-04-09 00:35:21.756 | INFO     | modules.train:run_training:181 - Epoch 0 : train contrastive loss = 3.1586894907176633
2026-04-09 00:35:21.758 | INFO     | modules.train:run_training:182 - Epoch 0 : train MSE loss = 0.03910065265116655
2026-04-09 00:35:21.759 | INFO     | modules.train:run_training:184 - Epoch 0 : validation total loss = 0.9607801770651212
2026-04-09 00:35:21.760 | INFO     | modules.train:run_training:185 - Epoch 0 : validation contrastive loss = 3.1109213418858026
2026-04-09 00:35:21.760 | INFO     | modules.train:run_training:186 - Epoch 0 : validation MSE loss = 0.03929105952822713
2026-04-09 00:35:21.824 | INFO     | modules.train:run_training:89 - Epoch 1 :
2026-04-09 00:36:29.390 | INFO     | modules.train:run_training:180 - Epoch 1 : train total loss = 0.9606372411245613
2026-04-09 00:36:29.391 | INFO     | modules.train:run_training:181 - Epoch 1 : train contrastive loss = 3.1165761462065396
2026-04-09 00:36:29.393 | INFO     | modules.train:run_training:182 - Epoch 1 : train MSE loss = 0.036663376860474016
2026-04-09 00:36:29.394 | INFO     | modules.train:run_training:184 - Epoch 1 : validation total loss = 0.9548442312466201
2026-04-09 00:36:29.395 | INFO     | modules.train:run_training:185 - Epoch 1 : validation contrastive loss = 3.0910635968690277
2026-04-09 00:36:29.396 | INFO     | modules.train:run_training:186 - Epoch 1 : validation MSE loss = 0.039321590520401475
2026-04-09 00:36:29.465 | INFO     | modules.train:run_training:89 - Epoch 2 :
2026-04-09 00:37:36.695 | INFO     | modules.train:run_training:180 - Epoch 2 : train total loss = 0.9545272180908605
2026-04-09 00:37:36.696 | INFO     | modules.train:run_training:181 - Epoch 2 : train contrastive loss = 3.096373522581716
2026-04-09 00:37:36.697 | INFO     | modules.train:run_training:182 - Epoch 2 : train MSE loss = 0.03659303585233623
2026-04-09 00:37:36.697 | INFO     | modules.train:run_training:184 - Epoch 2 : validation total loss = 0.9534697628790333
2026-04-09 00:37:36.698 | INFO     | modules.train:run_training:185 - Epoch 2 : validation contrastive loss = 3.087784182640814
2026-04-09 00:37:36.699 | INFO     | modules.train:run_training:186 - Epoch 2 : validation MSE loss = 0.038763527317793776
2026-04-09 00:37:36.783 | INFO     | modules.train:run_training:89 - Epoch 3 :
2026-04-09 00:38:44.409 | INFO     | modules.train:run_training:180 - Epoch 3 : train total loss = 0.9491928282536959
2026-04-09 00:38:44.410 | INFO     | modules.train:run_training:181 - Epoch 3 : train contrastive loss = 3.0796113559801466
2026-04-09 00:38:44.412 | INFO     | modules.train:run_training:182 - Epoch 3 : train MSE loss = 0.036156265672458256
2026-04-09 00:38:44.414 | INFO     | modules.train:run_training:184 - Epoch 3 : validation total loss = 0.9566986439048603
2026-04-09 00:38:44.415 | INFO     | modules.train:run_training:185 - Epoch 3 : validation contrastive loss = 3.096778272300638
2026-04-09 00:38:44.416 | INFO     | modules.train:run_training:186 - Epoch 3 : validation MSE loss = 0.03952160600312455
2026-04-09 00:38:44.445 | INFO     | modules.train:run_training:89 - Epoch 4 :
2026-04-09 00:39:51.841 | INFO     | modules.train:run_training:180 - Epoch 4 : train total loss = 0.9417903222808576
2026-04-09 00:39:51.842 | INFO     | modules.train:run_training:181 - Epoch 4 : train contrastive loss = 3.055222773715615
2026-04-09 00:39:51.843 | INFO     | modules.train:run_training:182 - Epoch 4 : train MSE loss = 0.036033505376735254
2026-04-09 00:39:51.843 | INFO     | modules.train:run_training:184 - Epoch 4 : validation total loss = 0.9612518593829166
2026-04-09 00:39:51.844 | INFO     | modules.train:run_training:185 - Epoch 4 : validation contrastive loss = 3.1095976957710842
2026-04-09 00:39:51.845 | INFO     | modules.train:run_training:186 - Epoch 4 : validation MSE loss = 0.040532170895046446
2026-04-09 00:39:51.845 | WARNING  | modules.train:run_training:206 - Training stops after 4 epochs
2026/04/09 00:39:52 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/09 00:39:52 WARNING mlflow.pytorch: Saving pytorch model by Pickle or CloudPickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is to set `serialization_format` to 'pt2' to save the PyTorch model using the safe graph model format.
2026/04/09 00:40:00 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.
2026/04/09 00:40:11 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.

----------------------------------------------------------------------------------------------------

[I 2026-04-09 00:40:14,198] Trial 6 finished with value: 0.9534697628790333 and parameters: {'batch_size': 32, 'dropout': 0.1, 'projec_dropout': 0.1, 'lr': 0.0017263266493212528, 'weight_decay': 0.000683227867921707, 'warmup_prop': 0.03, 'mean_mode': True}. Best is trial 2 with value: 0.9452530517373033.
2026-04-09 00:40:14.801 | INFO     | modules.optuna_function:objective:88 - Trial number 7:
2026-04-09 00:40:14.802 | INFO     | modules.optuna_function:objective:89 - batch_size:32_dropout:0,1_projec_dropout:0,1_lr:0,001532223306220127_weight_decay:0,0001182983291048804_warmup_prop:0,01_mean_mode:True_loss_temp:0,2_loss_alpha:0,3
2026-04-09 00:40:14.803 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-09 00:41:25.783 | INFO     | modules.train:run_training:180 - Epoch 0 : train total loss = 0.9795371995092257
2026-04-09 00:41:25.784 | INFO     | modules.train:run_training:181 - Epoch 0 : train contrastive loss = 3.177291827016346
2026-04-09 00:41:25.785 | INFO     | modules.train:run_training:182 - Epoch 0 : train MSE loss = 0.037642305012519556
2026-04-09 00:41:25.786 | INFO     | modules.train:run_training:184 - Epoch 0 : validation total loss = 0.9748219943815662
2026-04-09 00:41:25.786 | INFO     | modules.train:run_training:185 - Epoch 0 : validation contrastive loss = 3.15994998972903
2026-04-09 00:41:25.787 | INFO     | modules.train:run_training:186 - Epoch 0 : validation MSE loss = 0.038338516979047686
[I 2026-04-09 00:41:26,295] Trial 7 pruned.
2026-04-09 00:41:26.894 | INFO     | modules.optuna_function:objective:88 - Trial number 8:
2026-04-09 00:41:26.895 | INFO     | modules.optuna_function:objective:89 - batch_size:64_dropout:0,25_projec_dropout:0,05_lr:0,002273127577304322_weight_decay:0,0002866988682737223_warmup_prop:0,05_mean_mode:True_loss_temp:0,2_loss_alpha:0,3
2026-04-09 00:41:26.896 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-09 00:42:36.710 | INFO     | modules.train:run_training:180 - Epoch 0 : train total loss = 1.1741321540753775
2026-04-09 00:42:36.712 | INFO     | modules.train:run_training:181 - Epoch 0 : train contrastive loss = 3.8147380778548916
2026-04-09 00:42:36.713 | INFO     | modules.train:run_training:182 - Epoch 0 : train MSE loss = 0.04244382923827806
2026-04-09 00:42:36.714 | INFO     | modules.train:run_training:184 - Epoch 0 : validation total loss = 1.1651494891747185
2026-04-09 00:42:36.715 | INFO     | modules.train:run_training:185 - Epoch 0 : validation contrastive loss = 3.7905325578606646
2026-04-09 00:42:36.717 | INFO     | modules.train:run_training:186 - Epoch 0 : validation MSE loss = 0.0399852593064956
[I 2026-04-09 00:42:37,280] Trial 8 pruned.
2026-04-09 00:42:37.856 | INFO     | modules.optuna_function:objective:88 - Trial number 9:
2026-04-09 00:42:37.856 | INFO     | modules.optuna_function:objective:89 - batch_size:32_dropout:0,1_projec_dropout:0,25_lr:0,006987254241678245_weight_decay:1,2335097316744706e-05_warmup_prop:0,09999999999999999_mean_mode:True_loss_temp:0,2_loss_alpha:0,3
2026-04-09 00:42:37.857 | INFO     | modules.train:run_training:89 - Epoch 0 :
2026-04-09 00:43:45.956 | INFO     | modules.train:run_training:180 - Epoch 0 : train total loss = 0.9774914323874415
2026-04-09 00:43:45.957 | INFO     | modules.train:run_training:181 - Epoch 0 : train contrastive loss = 3.165869330923399
2026-04-09 00:43:45.959 | INFO     | modules.train:run_training:182 - Epoch 0 : train MSE loss = 0.03961513405751002
2026-04-09 00:43:45.960 | INFO     | modules.train:run_training:184 - Epoch 0 : validation total loss = 0.9626225309987222
2026-04-09 00:43:45.961 | INFO     | modules.train:run_training:185 - Epoch 0 : validation contrastive loss = 3.1159576498052126
2026-04-09 00:43:45.962 | INFO     | modules.train:run_training:186 - Epoch 0 : validation MSE loss = 0.039764581097950856
2026-04-09 00:43:46.024 | INFO     | modules.train:run_training:89 - Epoch 1 :
2026-04-09 00:44:53.659 | INFO     | modules.train:run_training:180 - Epoch 1 : train total loss = 0.9631482827854375
2026-04-09 00:44:53.660 | INFO     | modules.train:run_training:181 - Epoch 1 : train contrastive loss = 3.124341773768584
2026-04-09 00:44:53.660 | INFO     | modules.train:run_training:182 - Epoch 1 : train MSE loss = 0.036922449666955584
2026-04-09 00:44:53.661 | INFO     | modules.train:run_training:184 - Epoch 1 : validation total loss = 0.957889635075805
2026-04-09 00:44:53.663 | INFO     | modules.train:run_training:185 - Epoch 1 : validation contrastive loss = 3.1007283374827397
2026-04-09 00:44:53.664 | INFO     | modules.train:run_training:186 - Epoch 1 : validation MSE loss = 0.03953014159955645
2026-04-09 00:44:53.742 | INFO     | modules.train:run_training:89 - Epoch 2 :
2026-04-09 00:46:01.564 | INFO     | modules.train:run_training:180 - Epoch 2 : train total loss = 0.957802352834348
2026-04-09 00:46:01.565 | INFO     | modules.train:run_training:181 - Epoch 2 : train contrastive loss = 3.106920147378603
2026-04-09 00:46:01.566 | INFO     | modules.train:run_training:182 - Epoch 2 : train MSE loss = 0.036751817096689676
2026-04-09 00:46:01.567 | INFO     | modules.train:run_training:184 - Epoch 2 : validation total loss = 0.9553154892818903
2026-04-09 00:46:01.569 | INFO     | modules.train:run_training:185 - Epoch 2 : validation contrastive loss = 3.0950064659118652
2026-04-09 00:46:01.570 | INFO     | modules.train:run_training:186 - Epoch 2 : validation MSE loss = 0.038305020255226925
2026-04-09 00:46:01.649 | INFO     | modules.train:run_training:89 - Epoch 3 :
2026-04-09 00:47:09.684 | INFO     | modules.train:run_training:180 - Epoch 3 : train total loss = 0.9522175614293708
2026-04-09 00:47:09.685 | INFO     | modules.train:run_training:181 - Epoch 3 : train contrastive loss = 3.088574252357745
2026-04-09 00:47:09.686 | INFO     | modules.train:run_training:182 - Epoch 3 : train MSE loss = 0.03663606843133233
2026-04-09 00:47:09.688 | INFO     | modules.train:run_training:184 - Epoch 3 : validation total loss = 0.9555235235921798
2026-04-09 00:47:09.689 | INFO     | modules.train:run_training:185 - Epoch 3 : validation contrastive loss = 3.09347774136451
2026-04-09 00:47:09.690 | INFO     | modules.train:run_training:186 - Epoch 3 : validation MSE loss = 0.03925737899838276
2026-04-09 00:47:09.717 | INFO     | modules.train:run_training:89 - Epoch 4 :
2026-04-09 00:48:17.765 | INFO     | modules.train:run_training:180 - Epoch 4 : train total loss = 0.9465655998179787
2026-04-09 00:48:17.766 | INFO     | modules.train:run_training:181 - Epoch 4 : train contrastive loss = 3.07011508177838
2026-04-09 00:48:17.767 | INFO     | modules.train:run_training:182 - Epoch 4 : train MSE loss = 0.03647291497380667
2026-04-09 00:48:17.769 | INFO     | modules.train:run_training:184 - Epoch 4 : validation total loss = 0.9589719682611445
2026-04-09 00:48:17.770 | INFO     | modules.train:run_training:185 - Epoch 4 : validation contrastive loss = 3.102950503749232
2026-04-09 00:48:17.771 | INFO     | modules.train:run_training:186 - Epoch 4 : validation MSE loss = 0.040123976907262236
2026-04-09 00:48:17.774 | WARNING  | modules.train:run_training:206 - Training stops after 4 epochs
2026/04/09 00:48:18 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/09 00:48:18 WARNING mlflow.pytorch: Saving pytorch model by Pickle or CloudPickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is to set `serialization_format` to 'pt2' to save the PyTorch model using the safe graph model format.
2026/04/09 00:48:30 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.
2026/04/09 00:48:40 WARNING mlflow.utils.requirements_utils: Found torch version (2.10.0+cu128) contains a local version label (+cu128). MLflow logged a pip requirement for this package as 'torch==2.10.0' without the local version label to make it installable from PyPI. To specify pip requirements containing local version labels, please use `conda_env` or `pip_requirements`.

----------------------------------------------------------------------------------------------------

[I 2026-04-09 00:48:43,666] Trial 9 finished with value: 0.9553154892818903 and parameters: {'batch_size': 32, 'dropout': 0.1, 'projec_dropout': 0.25, 'lr': 0.006987254241678245, 'weight_decay': 1.2335097316744706e-05, 'warmup_prop': 0.09999999999999999, 'mean_mode': True}. Best is trial 2 with value: 0.9452530517373033.

In [32]:
study_loaded=optuna.load_study(study_name="recommendation_model_study",storage="sqlite:///optuna_study.db")

In [39]:
study_best_components={
    "study_best_params":study_loaded.best_params,
    "study_best_value":study_loaded.best_value
}
torch.save(study_best_components,"./train_savings/study_best_components.pt")

In [34]:
fig=optuna.visualization.plot_param_importances(study_loaded)
fig.show()

In [35]:
fig=optuna.visualization.plot_parallel_coordinate(study_loaded)
fig.show()

In [36]:
fig=optuna.visualization.plot_optimization_history(study_loaded)
fig.show()

In [5]:
best_model_name="Best_Recommendation_model"
best_model_uri=f"runs:/45f1895105314bd4a5cb348fcfd545f1/best_model_lr_0,0003897563887501594_weight_decay_6,280785308506033e-05_dropout_0,1"
result=mlflow.register_model(best_model_uri,best_model_name)

Registered model 'Best_Recommendation_model' already exists. Creating a new version of this model...
2026/04/06 21:45:30 WARNING mlflow.tracking._model_registry.fluent: Run with id 45f1895105314bd4a5cb348fcfd545f1 has no artifacts at artifact path 'best_model_lr_0,0003897563887501594_weight_decay_6,280785308506033e-05_dropout_0,1', registering model based on models:/m-8d07540e3ee34437a09f96d1c7b68df6 instead
Created version '1' of model 'Best_Recommendation_model'.

In [7]:
best_recommendation_model=mlflow.pytorch.load_model(best_model_uri,map_location=torch.device("cpu"))

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/6 [00:00<?, ?it/s]

2026/04/06 21:59:16 WARNING mlflow.pytorch: Stored model version '2.10.0+cu128' does not match installed PyTorch version '2.8.0+cpu'

In [11]:
for param in best_recommendation_model.parameters():
    print(param)

Parameter containing:
tensor([[ 0.0217,  0.0122,  0.0136,  ...,  0.0112,  0.0078,  0.0116],
        [-0.0037,  0.0242,  0.0092,  ..., -0.0087,  0.0165, -0.0126],
        [ 0.0278,  0.0198, -0.0101,  ..., -0.0263,  0.0063,  0.0368],
        ...,
        [ 0.0264, -0.0088, -0.0193,  ..., -0.0195,  0.0297, -0.0232],
        [ 0.0205, -0.0013, -0.0059,  ..., -0.0368,  0.0208, -0.0203],
        [-0.0152, -0.0170, -0.0115,  ...,  0.0181,  0.0044, -0.0238]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0233, -0.0320, -0.0210, -0.0304, -0.0219,  0.0238,  0.0189, -0.0008,
        -0.0111,  0.0200,  0.0072,  0.0248, -0.0075, -0.0207,  0.0065,  0.0222,
        -0.0037, -0.0347, -0.0147, -0.0016,  0.0226, -0.0316, -0.0252,  0.0033,
         0.0251,  0.0166, -0.0348,  0.0034,  0.0073,  0.0114, -0.0301,  0.0092,
        -0.0051, -0.0251, -0.0001, -0.0349, -0.0116, -0.0293,  0.0181, -0.0052,
        -0.0290,  0.0200,  0.0130,  0.0205, -0.0038, -0.0281,  0.0041, -0.0332,
        -0.0170, -0.0377,  0.0144, -0.0012,  0.0063,  0.0043,  0.0096, -0.0136,
        -0.0332,  0.0285, -0.0410,  0.0082, -0.0213, -0.0243,  0.0284, -0.0288,
        -0.0176,  0.0074,  0.0076, -0.0049, -0.0156,  0.0183,  0.0173, -0.0119,
         0.0408, -0.0449, -0.0293, -0.0487,  0.0139,  0.0010,  0.0057, -0.0457,
         0.0264,  0.0043, -0.0031, -0.0050, -0.0076,  0.0314,  0.0172,  0.0143,
        -0.0100, -0.0231, -0.0308, -0.0232, -0.0392,  0.0010, -0.0014, -0.0066,
        -0.0100, -0.0270,  0.0118,  0.0328, -0.0226,  0.0232, -0.0197,  0.0150,
        -0.0074, -0.0088,  0.0258, -0.0306,  0.0030, -0.0520,  0.0115, -0.0154,
        -0.0412, -0.0171,  0.0365, -0.0272, -0.0232, -0.0281, -0.0134,  0.0299,
        -0.0210,  0.0053, -0.0265,  0.0145, -0.0082,  0.0214,  0.0166, -0.0116,
         0.0086,  0.0096,  0.0342,  0.0208,  0.0134, -0.0332, -0.0033,  0.0052,
        -0.0282,  0.0111,  0.0059, -0.0175,  0.0126,  0.0029,  0.0007,  0.0019,
        -0.0177, -0.0042, -0.0137, -0.0393, -0.0154,  0.0173, -0.0306,  0.0266,
        -0.0324, -0.0231, -0.0246, -0.0193, -0.0138,  0.0038, -0.0113,  0.0089,
         0.0077, -0.0048,  0.0160,  0.0031, -0.0282,  0.0122, -0.0288,  0.0240,
         0.0008,  0.0383, -0.0039,  0.0013, -0.0362, -0.0026,  0.0213, -0.0459,
         0.0181, -0.0314, -0.0207,  0.0102, -0.0221,  0.0214,  0.0109, -0.0280,
        -0.0009,  0.0095, -0.0018, -0.0256,  0.0390, -0.0216,  0.0307,  0.0344,
        -0.0254, -0.0347,  0.0172,  0.0258,  0.0090,  0.0144,  0.0039,  0.0162,
         0.0039, -0.0128, -0.0072,  0.0419, -0.0202, -0.0264, -0.0256, -0.0089,
         0.0243,  0.0248, -0.0314,  0.0349, -0.0135,  0.0202, -0.0017, -0.0068,
        -0.0182,  0.0068, -0.0098, -0.0275, -0.0197, -0.0040, -0.0124,  0.0264,
         0.0049, -0.0033,  0.0465,  0.0296, -0.0280,  0.0128,  0.0267, -0.0047,
        -0.0107, -0.0323,  0.0009,  0.0111, -0.0200, -0.0024, -0.0308, -0.0230,
         0.0179, -0.0164,  0.0342,  0.0306, -0.0252, -0.0465,  0.0299,  0.0283,
        -0.0104, -0.0131, -0.0210, -0.0342,  0.0107,  0.0213, -0.0475,  0.0091,
         0.0028, -0.0072, -0.0287,  0.0124,  0.0009, -0.0012,  0.0157, -0.0018,
         0.0054,  0.0208,  0.0280, -0.0357,  0.0013, -0.0212,  0.0266,  0.0276,
        -0.0166,  0.0185, -0.0031,  0.0078, -0.0138, -0.0079,  0.0089,  0.0167,
        -0.0339,  0.0109,  0.0024,  0.0157,  0.0233, -0.0042,  0.0022, -0.0156,
        -0.0409,  0.0180, -0.0232, -0.0223, -0.0277,  0.0219, -0.0146, -0.0044,
        -0.0128, -0.0010, -0.0314, -0.0215, -0.0018, -0.0238,  0.0548,  0.0247,
        -0.0034,  0.0036,  0.0194, -0.0258,  0.0016, -0.0386, -0.0158, -0.0084,
         0.0100,  0.0083,  0.0112,  0.0030,  0.0115, -0.0142,  0.0300, -0.0034,
        -0.0227,  0.0232,  0.0238, -0.0298,  0.0266,  0.0276,  0.0026,  0.0205,
        -0.0157, -0.0041, -0.0361,  0.0191,  0.0165,  0.0147, -0.0117,  0.0228,
         0.0184, -0.0133,  0.0184,  0.0016, -0.0221,  0.0295, -0.0267, -0.0182,
        -0.0173,  0.0028,  0.0204,  0.0378, -0.0081,  0.0210, -0.0013, -0.0079,
         0.0058, -0.0135,  0.0050, -0.0312, -0.0086, -0.0178, -0.0248, -0.0289,
        -0.0138,  0.0011, -0.0067,  0.0429, -0.0116,  0.0078,  0.0457,  0.0017,
         0.0179,  0.0064, -0.0200, -0.0097,  0.0226,  0.0215,  0.0250,  0.0057,
        -0.0166, -0.0295, -0.0168, -0.0002, -0.0301,  0.0028, -0.0162, -0.0236,
         0.0058, -0.0341,  0.0178,  0.0431,  0.0063, -0.0273, -0.0374, -0.0075,
         0.0014,  0.0302,  0.0162,  0.0038,  0.0470, -0.0239,  0.0152, -0.0135,
        -0.0171,  0.0194, -0.0386,  0.0078, -0.0211, -0.0123,  0.0071,  0.0121,
        -0.0286,  0.0103,  0.0296,  0.0201, -0.0231, -0.0119, -0.0181,  0.0302,
         0.0040,  0.0309, -0.0037, -0.0043,  0.0289, -0.0045, -0.0065,  0.0260,
         0.0344, -0.0316, -0.0184, -0.0332, -0.0344, -0.0148,  0.0173, -0.0090,
         0.0270, -0.0120, -0.0207,  0.0240, -0.0157, -0.0169, -0.0148, -0.0214,
        -0.0333, -0.0291,  0.0077,  0.0070, -0.0033,  0.0223, -0.0025,  0.0072,
        -0.0294, -0.0454, -0.0016,  0.0273,  0.0164,  0.0141, -0.0023, -0.0133,
        -0.0398, -0.0223,  0.0288,  0.0045,  0.0005,  0.0148,  0.0054,  0.0125,
         0.0216,  0.0288, -0.0129, -0.0140, -0.0244,  0.0183,  0.0254, -0.0196,
        -0.0233, -0.0116, -0.0123, -0.0009,  0.0432,  0.0133, -0.0263,  0.0378,
         0.0063, -0.0103, -0.0143, -0.0196,  0.0063, -0.0003, -0.0199, -0.0339,
        -0.0096,  0.0418, -0.0053,  0.0065,  0.0217, -0.0466, -0.0084,  0.0089,
        -0.0157, -0.0038, -0.0039, -0.0417, -0.0318,  0.0019,  0.0292,  0.0183,
        -0.0330,  0.0133,  0.0022,  0.0065,  0.0261,  0.0087, -0.0075,  0.0300],
       requires_grad=True)
Parameter containing:
tensor([0.9883, 0.9879, 1.0112, 1.0312, 1.0133, 0.9923, 0.9969, 0.9887, 1.0258,
        0.9801, 0.9965, 1.0460, 1.0025, 1.0028, 1.0273, 0.9888, 1.0025, 1.0196,
        0.9621, 0.9931, 0.9919, 0.9761, 0.9943, 0.9828, 1.0177, 1.0139, 1.0083,
        0.9758, 0.9877, 0.9766, 0.9880, 0.9995, 0.9640, 0.9905, 0.9941, 1.0024,
        0.9894, 0.9955, 1.0045, 1.0367, 0.9973, 1.0049, 1.0099, 1.0556, 0.9960,
        1.0064, 1.0094, 0.9933, 1.0024, 1.0127, 1.0065, 1.0128, 1.0063, 0.9841,
        0.9978, 1.0162, 1.0345, 0.9986, 1.0184, 0.9892, 0.9889, 1.0002, 0.9899,
        1.0197, 1.0016, 0.9788, 1.0264, 0.9805, 0.9794, 1.0000, 0.9943, 1.0032,
        1.0265, 1.0263, 1.0038, 1.0166, 0.9896, 0.9970, 1.0081, 1.0377, 1.0027,
        0.9930, 1.0690, 0.9842, 1.0047, 1.0086, 1.0200, 1.0210, 0.9837, 0.9948,
        0.9828, 0.9836, 0.9986, 0.9970, 0.9882, 1.0190, 1.0083, 1.0253, 1.0369,
        1.0030, 1.0070, 1.0164, 1.0039, 0.9965, 0.9975, 1.0198, 1.0187, 0.9971,
        0.9927, 1.0347, 0.9424, 0.9905, 1.0006, 0.9945, 1.0129, 0.9982, 0.9954,
        1.0350, 0.9530, 1.0280, 0.9852, 0.9981, 0.9925, 1.0034, 0.9931, 1.0031,
        0.9927, 0.9845, 0.9978, 0.9844, 1.0524, 1.0147, 1.0001, 0.9890, 0.9971,
        0.9937, 0.9586, 0.9940, 1.0037, 0.9905, 1.0360, 1.0203, 0.9954, 0.9936,
        1.0145, 0.9975, 0.9982, 1.0187, 1.0393, 0.9863, 0.9808, 0.9749, 0.9920,
        0.9911, 1.0012, 0.9953, 1.0544, 1.0093, 1.0204, 1.0025, 0.9824, 0.9469,
        0.9912, 0.9860, 0.9941, 1.0256, 1.0221, 1.0096, 0.9579, 1.0076, 0.9943,
        1.0008, 1.0163, 1.0010, 0.9900, 1.0068, 0.9903, 0.9629, 0.9921, 0.9969,
        0.9615, 0.9985, 0.9971, 0.9880, 0.9975, 1.0373, 0.9657, 0.9958, 1.0314,
        0.9896, 1.0123, 1.0193, 0.9845, 0.9937, 1.0078, 0.9928, 1.0032, 1.0130,
        1.0064, 0.9784, 1.0336, 1.0184, 0.9901, 1.0098, 1.0006, 0.9957, 0.9969,
        0.9924, 1.0144, 1.0194, 0.9934, 1.0256, 1.0155, 1.0185, 0.9829, 0.9921,
        0.9625, 0.9722, 0.9818, 0.9647, 0.9912, 0.9937, 0.9787, 0.9932, 1.0008,
        0.9831, 1.0426, 0.9945, 1.0054, 0.9914, 1.0136, 1.0016, 1.0010, 1.0024,
        1.0400, 1.0283, 1.0362, 1.0234, 0.9866, 0.9883, 0.9998, 0.9964, 1.0006,
        1.0407, 1.0377, 1.0286, 1.0481, 0.9966, 0.9984, 0.9740, 1.0001, 0.9760,
        0.9952, 0.9977, 1.0179, 1.0169, 1.0219, 1.0441, 1.0314, 0.9858, 0.9827,
        1.0261, 0.9880, 0.9879, 1.0087, 1.0056, 1.0296, 1.0008, 0.9615, 0.9816,
        1.0066, 1.0104, 0.9888, 1.0081, 0.9821, 0.9941, 1.0088, 0.9940, 0.9755,
        1.0034, 1.0008, 1.0087, 0.9941, 1.0000, 0.9881, 0.9845, 0.9978, 0.9927,
        0.9928, 1.0067, 1.0120, 0.9952, 1.0176, 0.9937, 0.9907, 1.0040, 1.0059,
        1.0109, 1.0106, 1.0546, 1.0153, 0.9413, 1.0615, 0.9987, 0.9851, 0.9932,
        0.9992, 0.9822, 0.9981, 1.0463, 0.9942, 0.9880, 1.0239, 0.9961, 1.0034,
        0.9863, 0.9306, 1.0116, 0.9940, 1.0080, 1.0279, 0.9581, 1.0179, 0.9948,
        0.9982, 0.9612, 1.0314, 0.9994, 0.9751, 0.9922, 0.9974, 1.0138, 1.0119,
        1.0062, 1.0246, 1.0245, 0.9963, 0.9898, 1.0039, 0.9897, 0.9783, 1.0253,
        1.0085, 0.9915, 0.9916, 0.9848, 0.9996, 1.0437, 0.9951, 0.9936, 0.9915,
        0.9768, 0.9862, 1.0218, 0.9841, 0.9967, 1.0094, 0.9991, 0.9974, 1.0147,
        1.0010, 1.0011, 1.0061, 1.0097, 0.9919, 0.9956, 1.0554, 0.9904, 1.0044,
        1.0008, 1.0039, 1.0142, 0.9892, 1.0231, 1.0398, 1.0600, 1.0016, 0.9977,
        1.0460, 1.0022, 0.9871, 0.9923, 1.0097, 1.0118, 0.9935, 1.0018, 1.0159,
        1.0041, 0.9890, 0.9967, 1.0159, 1.0289, 0.9970, 1.0164, 0.9938, 1.0098,
        1.0045, 0.9963, 1.0436, 1.0059, 1.0084, 1.0020, 0.9869, 1.0340, 0.9929,
        1.0249, 0.9929, 1.0004, 1.0208, 0.9973, 1.0385, 0.9975, 1.0048, 0.9870,
        0.9873, 1.0126, 0.9924, 0.9976, 0.9960, 0.9931, 1.0095, 0.9848, 1.0136,
        0.9671, 1.0658, 0.9946, 0.9920, 1.0089, 1.0119, 0.9326, 0.9884, 1.0085,
        1.0144, 0.9854, 1.0228, 0.9661, 1.0263, 0.9979, 1.0061, 1.0084, 0.9910,
        1.0134, 0.9956, 1.0034, 1.0051, 1.0161, 0.9855, 1.0226, 0.9865, 1.0111,
        0.9891, 1.0095, 1.0111, 1.0438, 0.9701, 0.9886, 1.0144, 0.9861, 0.9967,
        0.9670, 0.9979, 0.9729, 1.0574, 1.0132, 0.9995, 1.0081, 0.9830, 0.9198,
        1.0024, 0.9964, 1.0140, 0.9695, 0.9918, 1.0132, 0.9903, 0.9982, 1.0351,
        1.0179, 1.0011, 1.0362, 0.9883, 0.9853, 0.9905, 1.0065, 0.9955, 0.9991,
        1.0037, 1.0016, 1.0265, 1.0421, 1.0183, 0.9947, 0.9978, 1.0345, 0.9725,
        1.0265, 0.9990, 1.0059, 1.0044, 0.9699, 0.9843, 1.0382, 0.9927, 0.9943,
        1.0416, 1.0003, 0.9795, 0.9906, 0.9986, 0.9895, 0.9956, 1.0045],
       requires_grad=True)
Parameter containing:
tensor([ 1.1272e-02,  7.0701e-03,  1.1518e-02, -8.6920e-03, -7.2407e-04,
         6.6687e-03,  3.5718e-03,  2.8686e-03,  1.0162e-02,  1.0975e-02,
        -1.0032e-02,  1.7508e-02,  1.2663e-02,  1.3123e-02, -2.5462e-03,
         4.1762e-03,  4.4339e-03, -8.3499e-03, -2.2950e-02,  3.5248e-03,
         1.2512e-04, -1.0752e-02, -2.1642e-04,  1.2295e-03,  2.8478e-03,
         8.9354e-03, -7.3370e-03,  1.0044e-02,  9.8997e-03,  1.1793e-02,
         8.6879e-03,  3.5965e-03, -2.7104e-02, -7.0115e-04,  1.2385e-02,
         1.2713e-03,  4.3736e-03,  6.0355e-03,  1.2569e-02,  1.2141e-02,
         2.9437e-03, -2.5142e-03,  1.0455e-02,  1.5016e-02,  3.7532e-03,
        -6.0926e-03,  1.6850e-02, -3.3627e-03,  1.1285e-03, -7.8454e-03,
         1.7470e-02,  6.0619e-03,  5.2753e-03,  1.0328e-02, -8.6228e-03,
         1.1941e-02, -1.1599e-02,  5.2738e-03, -7.6161e-03,  1.7015e-02,
         9.9667e-03,  7.9909e-03,  8.8584e-03, -9.6709e-03,  1.2159e-02,
         3.4038e-03,  1.4465e-02, -1.8265e-02,  1.1753e-02,  1.0818e-02,
         1.2002e-02, -2.0672e-03,  1.2652e-02, -1.1873e-02, -7.3151e-03,
        -8.1867e-03,  8.4541e-03, -6.5359e-03,  2.4562e-03, -7.7561e-03,
         1.3173e-02,  1.2358e-02, -1.0343e-02,  6.4638e-03, -6.4577e-03,
         1.1882e-02,  6.1814e-03, -8.2854e-03,  6.5154e-04,  8.5238e-03,
        -9.4872e-04,  7.8075e-03, -4.2382e-03,  6.3709e-03,  7.9406e-03,
        -9.1289e-03,  9.3959e-03, -9.3468e-03,  5.5109e-03,  1.2076e-02,
        -7.0189e-03,  1.7230e-02, -3.1604e-03, -2.7581e-04, -3.4374e-03,
        -6.7910e-03,  1.4883e-02, -2.6639e-03,  8.1038e-03, -1.2219e-02,
        -2.5293e-02,  1.0651e-02, -6.3306e-04,  6.4150e-03,  1.4075e-02,
        -2.4465e-03,  1.6510e-03, -8.5022e-03, -2.0026e-02,  7.5621e-03,
         1.1838e-02,  2.1475e-03,  2.1925e-03, -1.9846e-03,  6.9162e-03,
         1.2137e-02,  3.8549e-05,  9.9816e-03,  6.7511e-04,  1.1229e-02,
         1.8321e-02, -1.8514e-03,  7.4340e-03, -1.7639e-02,  1.5245e-02,
         5.2833e-03, -1.9732e-02,  3.8192e-04, -4.1471e-03,  1.1353e-02,
        -8.2932e-04, -5.5739e-03,  1.3314e-02,  1.4015e-03, -2.6446e-03,
        -4.2239e-03,  1.3006e-02, -4.0356e-03, -1.1249e-02, -6.9826e-03,
         9.3424e-03,  7.8183e-03,  3.3001e-03, -4.3870e-03, -7.3421e-04,
        -3.4967e-03, -9.1192e-03,  6.0209e-03, -6.5804e-03,  9.4785e-03,
         1.8193e-03, -3.5008e-02,  7.7435e-03,  3.4065e-03,  8.2145e-03,
         1.5037e-02, -9.6978e-05,  3.4753e-03, -1.7066e-02,  1.5101e-02,
         1.2690e-02, -6.4505e-03, -5.1138e-05,  1.5888e-02,  2.6960e-03,
        -4.7785e-03,  9.0479e-03, -1.0464e-02,  1.3324e-02, -1.5842e-03,
        -2.6121e-02,  1.3655e-02,  1.2497e-02, -1.1177e-03,  1.1615e-02,
        -3.4129e-03, -1.5271e-02,  8.6058e-03,  1.3493e-02, -3.0896e-03,
         1.8068e-02,  1.5689e-02,  5.8736e-03,  8.9670e-04, -5.1936e-03,
         1.6651e-02, -5.3585e-03,  1.0086e-02, -2.8279e-03,  9.6919e-04,
         1.2668e-02,  5.4453e-04,  1.0687e-02,  1.5391e-02, -7.0225e-03,
        -3.2482e-04, -9.9079e-04,  4.3052e-03,  1.6199e-02,  1.2285e-02,
         8.6700e-03,  1.6000e-02, -6.4396e-03,  4.3767e-03, -2.8195e-03,
        -1.3933e-02, -2.5884e-02,  5.2856e-03,  8.0482e-03, -1.6928e-02,
         1.5878e-03,  1.9391e-03,  6.3473e-03,  1.4508e-02,  1.5761e-02,
         2.8517e-03,  1.6372e-02,  1.1455e-02, -2.4805e-03,  1.2483e-02,
         1.3959e-02,  1.1535e-02,  1.7525e-02, -3.6116e-03,  1.8286e-02,
         1.4622e-02, -4.6503e-03, -1.2213e-02,  1.9121e-03, -3.2909e-03,
        -1.4637e-03,  1.4167e-03,  1.4165e-02,  9.3217e-03, -1.1629e-02,
        -6.9212e-03,  1.8566e-02,  1.6253e-02,  1.7932e-02, -1.9869e-02,
        -2.6676e-03, -1.6819e-02, -4.6314e-03,  4.8273e-03, -1.0185e-02,
        -4.4173e-03,  1.5554e-02, -8.6865e-03, -6.5122e-03,  1.1098e-02,
         1.1465e-02, -2.5574e-03,  9.2289e-03,  5.4239e-03,  1.2747e-02,
         3.1658e-03,  1.4424e-02,  8.6003e-04, -2.3135e-02, -7.0909e-03,
         6.2400e-03,  1.2444e-02,  7.9038e-03,  5.6560e-03,  1.6975e-03,
         9.1714e-04, -1.3382e-03,  1.8111e-02,  5.6491e-03,  3.2018e-03,
         7.6314e-04,  1.5029e-02,  1.6034e-03,  1.7864e-02,  7.8431e-03,
         1.0415e-02,  4.6231e-03, -3.5514e-03, -9.9118e-04,  1.4401e-02,
        -6.3489e-03,  3.4241e-03,  8.1843e-03, -6.3422e-04,  6.8590e-03,
        -2.1934e-03, -2.0011e-03, -8.8270e-03, -4.4021e-03, -7.0905e-03,
         1.1271e-02, -2.6932e-02,  1.5210e-02,  6.2281e-03, -2.8401e-04,
        -2.0582e-03,  8.6461e-03,  3.5708e-03,  1.0323e-02, -7.1858e-03,
        -2.3102e-03,  7.3484e-03, -2.6556e-03,  7.1800e-03,  6.9967e-03,
        -1.6627e-02, -3.2994e-02,  2.9060e-03,  1.4684e-02, -3.7093e-03,
        -1.0305e-02, -1.8872e-02,  1.6271e-02, -1.0144e-03,  4.1347e-03,
        -2.4119e-02,  1.4437e-02,  1.1994e-02,  2.2891e-03,  1.5548e-02,
         2.5548e-03,  1.2219e-02,  1.4414e-02,  1.6830e-03, -2.9791e-03,
         7.7671e-03,  9.1130e-03,  4.1173e-03,  1.6328e-02,  4.6421e-03,
         1.3318e-02,  1.7951e-02, -3.1255e-05,  5.5406e-03,  3.0671e-03,
         6.1768e-03,  1.1971e-02,  1.2839e-02,  9.5895e-03,  9.8478e-03,
         7.6220e-03,  9.2170e-03, -1.1576e-03, -8.7768e-03, -6.8412e-03,
         4.0770e-03,  3.3893e-03,  4.7266e-03, -4.7396e-03, -7.1188e-03,
         1.7852e-02, -1.5459e-03,  1.9841e-02,  1.3581e-02, -1.9200e-03,
         7.2854e-03,  1.5743e-02,  1.2230e-02,  1.2311e-02,  4.0843e-03,
        -4.7696e-03,  1.7963e-03,  8.7540e-03,  1.7819e-02,  1.4665e-02,
         1.9058e-02, -1.8085e-05,  1.0273e-02, -1.1304e-02,  4.9242e-03,
         4.8852e-03, -7.8762e-04,  1.8791e-04, -5.7617e-03,  1.7700e-02,
         5.4064e-03,  5.3733e-03,  1.5445e-02,  1.7801e-02,  7.6193e-04,
        -3.5455e-03, -9.8804e-03, -2.4852e-03,  1.3029e-02,  4.0196e-04,
         1.9269e-04,  1.9791e-02,  7.3199e-03,  4.4813e-03, -5.2622e-03,
         1.2868e-02,  1.8055e-03, -1.0538e-02, -5.4706e-03, -6.2513e-03,
         9.8076e-03,  1.5641e-02, -5.0475e-03, -5.8302e-03,  1.3680e-02,
         4.6635e-03,  8.3696e-04, -5.3974e-04, -9.0215e-03,  6.7947e-03,
         1.4404e-02,  1.5871e-02,  7.4111e-03,  1.4726e-02, -2.4963e-03,
         3.4998e-03,  1.6706e-02, -1.0509e-02, -1.4142e-02,  1.1488e-02,
         7.9150e-03,  4.4905e-04, -1.9632e-03, -5.6566e-03, -3.7493e-02,
         9.3778e-03, -6.7981e-03,  5.5720e-03,  6.6339e-03, -8.1063e-03,
        -1.5289e-02,  1.0072e-02, -5.3585e-03, -4.3752e-03, -5.9658e-03,
         1.3533e-04, -4.8971e-03,  9.6772e-03,  7.2339e-03, -6.4406e-03,
         1.2803e-02,  1.6922e-02,  1.6538e-02,  4.0819e-03, -6.5782e-03,
         6.1359e-03,  4.1755e-03,  1.7175e-02,  1.5747e-02, -1.2137e-03,
         7.8631e-03, -6.2783e-03,  1.3181e-02,  9.6467e-03, -2.4844e-02,
         1.3276e-02, -1.3404e-02,  1.3368e-02,  1.3460e-02, -2.0224e-03,
         1.4660e-02, -4.9857e-03, -3.6092e-02,  5.9683e-03, -6.4510e-03,
         1.8346e-02, -1.6595e-02, -3.7222e-03,  1.4958e-02,  1.0136e-02,
         1.6829e-02,  1.3173e-02,  1.1300e-02,  4.1479e-04,  1.4769e-02,
         5.8062e-03,  7.4382e-03,  1.3201e-02, -8.1835e-03,  7.4716e-05,
         1.5179e-03, -7.7942e-03, -2.4515e-03, -9.3122e-03,  1.5948e-02,
         8.1360e-03,  6.3343e-04,  3.2807e-03, -5.1481e-03, -4.4892e-03,
        -5.1969e-03,  6.0763e-03,  7.4272e-03,  1.3496e-02, -2.4631e-02,
         7.8318e-03,  8.6860e-03,  1.0333e-02,  1.1232e-03, -7.1284e-03,
         1.2059e-02, -1.5758e-02,  1.3800e-02,  7.5352e-03,  2.7529e-04,
        -3.1713e-03,  1.4794e-02], requires_grad=True)
Parameter containing:
tensor([[ 0.0293, -0.0361, -0.0103,  ..., -0.0185, -0.0231,  0.0214],
        [ 0.0307,  0.0282, -0.0150,  ..., -0.0323, -0.0183,  0.0140],
        [ 0.0319, -0.0308, -0.0435,  ...,  0.0078, -0.0425,  0.0265],
        ...,
        [ 0.0184, -0.0120,  0.0140,  ...,  0.0352,  0.0153,  0.0015],
        [-0.0292, -0.0224,  0.0273,  ...,  0.0127, -0.0249,  0.0269],
        [ 0.0127,  0.0330,  0.0094,  ..., -0.0002,  0.0050,  0.0021]],
       requires_grad=True)
Parameter containing:
tensor([-0.0099,  0.0146,  0.0257,  ..., -0.0386,  0.0132,  0.0175],
       requires_grad=True)
Parameter containing:
tensor([[-0.0135, -0.0299, -0.0002,  ...,  0.0039,  0.0180,  0.0254],
        [ 0.0022, -0.0234, -0.0141,  ..., -0.0161,  0.0006, -0.0163],
        [ 0.0282,  0.0104, -0.0220,  ...,  0.0121,  0.0095, -0.0122],
        ...,
        [-0.0479, -0.0058, -0.0038,  ...,  0.0013,  0.0311,  0.0021],
        [ 0.0196,  0.0034,  0.0026,  ..., -0.0079, -0.0095, -0.0268],
        [-0.0049, -0.0102,  0.0071,  ...,  0.0294,  0.0317, -0.0058]],
       requires_grad=True)
Parameter containing:
tensor([-0.0043,  0.0298,  0.0224, -0.0212,  0.0332, -0.0086,  0.0113, -0.0149,
        -0.0037,  0.0091,  0.0069, -0.0047, -0.0112, -0.0133, -0.0135, -0.0320,
        -0.0331, -0.0264,  0.0151, -0.0167,  0.0345, -0.0216, -0.0136, -0.0040,
        -0.0130, -0.0161, -0.0352,  0.0243, -0.0087, -0.0033,  0.0041,  0.0095,
         0.0261,  0.0279,  0.0059, -0.0169,  0.0117, -0.0042,  0.0314, -0.0054,
        -0.0203,  0.0249,  0.0189,  0.0250,  0.0267,  0.0261, -0.0286, -0.0066,
         0.0091,  0.0159,  0.0161,  0.0375, -0.0168,  0.0147,  0.0249,  0.0041,
         0.0001, -0.0198, -0.0317,  0.0108, -0.0170, -0.0069,  0.0200, -0.0128,
        -0.0123,  0.0023,  0.0015,  0.0227,  0.0063, -0.0129, -0.0260,  0.0132,
        -0.0040, -0.0206, -0.0317,  0.0143,  0.0050,  0.0143, -0.0095,  0.0210,
        -0.0109,  0.0133, -0.0138, -0.0283,  0.0108,  0.0186,  0.0171,  0.0137,
         0.0245,  0.0212, -0.0160, -0.0248,  0.0166,  0.0209, -0.0101,  0.0311,
         0.0054, -0.0222,  0.0250,  0.0269,  0.0004, -0.0087,  0.0033,  0.0117,